### ISSUE TITLE
[Suggestion] More Materials Types

### ISSUE THREAD

**Issue by Ravin890** [mickelus/tetra#1]
Would it be possible to add more materials to be used for tools such as flint, copper, ect.?

**Comment by MasterEnderman** [comment]
i would like to suggest Soulforged Steel from Better With Mods as a Material as well as the basic go-to metals. (Copper, Tin, Bronze, Silver, Lead, Electrum, Invar, Constantan). Maybe even add Treatet wood for Handles to add some Compat for Immersive Engineering.

**Comment by Dragnier** [comment]
Yeah, I can't even upgrade my iron short blade to diamond which is a vanilla material.

**Comment by mickelus** [comment]
The following materials were added in 0.10.0:
**blades & heads:** copper, tin, silver, nickel, lead, bronze, electrum, steel, thaumium, ironwood, steeleaf, fierymetal, knightmetal
**hilt & handle:** oak, spruce, birch, jungle, acacia, dark_oak, maple, cherry, baobab, bronze, steel, blaze_rod, end_rod, greatwood, treated_wood, ironwood (rustic)

There's still some balancing left to do to get some decent progression paths in place.
Diamond variants of modules which do not have a vanilla counterpart will probably not be a thing, but there will be improvements which use diamonds.
