### ISSUE TITLE
Feature request: toolbelt compatibility with curios (a.k.a new baubles).

### ISSUE THREAD

**Issue by Edulml** [mickelus/tetra#100]
## Feature Request

**Feature description**
The toolbelt would be much easier to use if its inventory menu was accessible by keybind while being equipped in the belt slot (or just anywhere in the inventory). The keybind could be ctrl+v, to stay consistent with the other means of interacting with it.

**How it improves the player experience**
It would synergize with a widely used mod and make the toolbelt much more easier to use and it could open up further opportunities should the modular item system be used for new types of equipment be added.

**Comment by mickelus** [comment]
Curios support has been added for both 1.14 and 1.15.
