### ISSUE TITLE
Feature request: More toolbelt modules?

### ISSUE THREAD

**Issue by Edulml** [mickelus/tetra#101]
## Feature Request

**Feature description**
To further increase the usefulness of the toolbelt it could have a wider variety of utilities. The first few examples I could think about are:

* Totem of undying holder, to automatically use it instead of requiring it to be in a player's main hand. It could require gold and experience to make?
* Emergency potion shatterer? It could activate for splash potions when the situation is right for certain potions (low health, burning, drowning). It may be redundant with the totem of undying holder.
* Flower pouch holder for botania compatibility.
* Focus pouch when Thaumcraft gets ported.

**How it improves the player experience**
It provides even more utilities to the toolbelt.

**Tetra synergies**
It gives even more uses to an already very versatile piece of equipment, however it may add some unnecessary feature bloat (especially the potion shatterer).

**Comment by mickelus** [comment]
Closing, I don't indend to implement your suggested features. The flower pouch might become viable in the future.
