### ISSUE TITLE
tetra Pickaxes with modded heads vanish upon loading

### ISSUE THREAD

**Issue by MitztheKat** [mickelus/tetra#105]
Any pickaxe i use that A) use two different materials for the heads or B) two different parts for the heads end up vanishing from inventory.
Will update with a log if within my limits.
edit: now includes my mattock

**Comment by mickelus** [comment]
Closing. I'm unable to reproduce this and it does not follow the template for bug reports. Feel free to re-open when updated to adhere to the template.
