### ISSUE TITLE
missing texture and crash lan game

### ISSUE THREAD

**Issue by troyheady2** [mickelus/tetra#106]
## Bug Report

**Observed Behaviour**
hammer/mallet does not show texture and when placed in tetra  workbench game crashes
This is only issue for person attached to the lan game. person hosting has no issue

Crash log:  https://pastebin.com/NEWc2Wma

**Expected Behaviour**
no crashing  ;)

**Minimal setup needed to reproduce**
running mod pack: Enigmatica 4
- Forge version:  1.14.4  28.1.1.109
- Tetra version:  1.8.0
- Tetra configuration:  https://pastebin.com/RkivtgEB
 
- Other mods:  https://www.curseforge.com/minecraft/modpacks/enigmatica4/relations/dependencies

**Steps to reproduce**
connect to lan game
create hammer like normal (but no texture) 
create crafting table, hit with hammer, tuning it to workbench
placing the hammer (texture missing) in the workbench crashes game
also confirmed it does not crash with a standard pick even if you are carrying the hammer in inventory

**Comment by mickelus** [comment]
This was fixed in 1.11.0, you should be able to update tetra to the latest without breaking your enigmatica instance.
