### ISSUE TITLE
Support for Silent Gems / Gems Plus Plus

### ISSUE THREAD

**Issue by WenXin20** [mickelus/tetra#108]
## Feature Request

**Feature description**
- Support for [Silent's Gems](https://www.curseforge.com/minecraft/mc-mods/silents-gems) and [Gems Plus Plus](https://www.curseforge.com/minecraft/mc-mods/gemsplusplus) gems (Or gems in general). Both mods add a lot of gems with corresponding tools & armor.
- Gems are using the tag `#forge:gems` & 
`#forge:gems/gem_name`.
- Silent Gems also adds enchantment tokens as well as custom enchantments.
  - Weapon Enchantments:
    - Lightning Aspect II
    - Life Steal II
  - Tool Enchantments:
    - Gravity III

**How it improves the player experience**
- It would add many more tool customization options.

**Tetra synergies**
- More modded support.

**Comment by mickelus** [comment]
I need the following for each tool/weapon:
- name
- damage
- swing speed
- durability
- harvest capabilities (type, level, speed)
- effects (e.g. autosmelt or uses mana to restore durability, sweeping)
- usages (e.g. can till dirt or strip logs)

I need the following for each additional material:
- applicable modules or slots (e.g. all blades or socket or all handles or handle wraps)
- damage (fixed amount, or multiplier)
- speed (fixed, multiplier)
- durability
- integrity
- harvest capabilities (type, level, speed)
- effects (e.g. autosmelt, uses mana to restore durability, sweeping)
- usages (e.g. can till dirt or strip logs)

**Comment by WenXin20** [comment]
Wow, I'm not even sure of all the stats of the tools, but I'll see what I can do

**Comment by DoctorGoat** [comment]
I wish I'd noticed this earlier. I've wanted this for a bit. The mod supports dumping all current supported materials. Attached are my outputs for materials and parts and my modlist, in the event I'm missing some that people would want supported. 
[material_export.xlsx](https://github.com/mickelus/tetra/files/5086359/material_export.xlsx)
[part_export.xlsx](https://github.com/mickelus/tetra/files/5086360/part_export.xlsx)
[modlist.txt](https://github.com/mickelus/tetra/files/5086361/modlist.txt)

**Comment by mickelus** [comment]
wontfix
