### ISSUE TITLE
Support for Xerca Mod Enchantments

### ISSUE THREAD

**Issue by WenXin20** [mickelus/tetra#109]
## Feature Request

**Feature description**
- Support for [Xerca](https://www.curseforge.com/minecraft/mc-mods/xercamod). It adds several new enchantments.

**How it improves the player experience**
- It would add many more tool enchantment customization options.

**Tetra synergies**
- More modded enchantments support.

**Comment by WenXin20** [comment]
Weapons:
- Heavyweight
- Maiming
- Legerity
- Quake
- Uppercut

**Comment by mickelus** [comment]
For each enchantment i need the following information to implement this:

name
description
id
max level
applicable items
enchantability function (typically something like this: enchantability = base + enchantmentLevel * levelMultiplier)

**Comment by mickelus** [comment]
Closing this as the enchantments from xerca are only applicable for items from xerca.
