### ISSUE TITLE
[Suggestion] Add Baubles support for Toolbelt

### ISSUE THREAD

**Issue by Dragnier** [mickelus/tetra#11]
Would be nice to see the ability to stick the toolbelt on the belt slot of Baubles if it is present.

**Comment by mickelus** [comment]
This has been implemented in a separate branch, but the solution makes baubles a required dependency. The value this currently provides is not enough in comparison to the cost. It is possible that this could be implemented in such a way that baubles will only be an optional dependency.

**Comment by mickelus** [comment]
Managed to get it in as an optional dependency, available from 0.19.0!
