### ISSUE TITLE
Support for Ma Enchants Mod

### ISSUE THREAD

**Issue by WenXin20** [mickelus/tetra#111]
## Feature Request

**Feature description**
- Support for [Ma Enchants](https://www.curseforge.com/minecraft/mc-mods/ma-enchants). It adds several new enchantments.

**How it improves the player experience**
- It would add many more tool enchantment customization options.

**Tetra synergies**
- More modded enchantments support.

**Comment by WenXin20** [comment]
Weapons Enchantments: 
- Wisdom V
- Ice Aspect II
- Lifesteal
- Faster Attack V
- Combo
Bow/Crossbow Enchantments:
- Dentonation III
- Paralysis III
- Floating III
- Quick Draw III
- True Shot
Axe Enchantments:
- Butchering V
- Lumberjack
Pickaxe Enchantments: 
- Stone Mending III
- Reinforced Tip III
Tools Enchantments:
- Momentum
Weapons/Tool Enchantments:
- Curse of Butterfingers
- Curse of Breaking III

**Comment by mickelus** [comment]
For each enchantment i need the following information to implement this:
* name
* description
* id
* max level
* applicable items
* enchantability function (typically something like this: `enchantability = base + enchantmentLevel * levelMultiplier`)

**Comment by WenXin20** [comment]
How might I find the enchantabilith function?

**Comment by mickelus** [comment]
I found a way to generate everything so I only need the enchantment id going forward!
This is available in 2.4.0+

**Comment by WenXin20** [comment]
Awesome, thanks!
