### ISSUE TITLE
Support for Charm Enchantments

### ISSUE THREAD

**Issue by WenXin20** [mickelus/tetra#112]
## Feature Request

**Feature description**
- Support for [Charm](https://www.curseforge.com/minecraft/mc-mods/charm). It adds several new enchantments.

**How it improves the player experience**
- It would add many more tool enchantment customization options.

**Tetra synergies**
- More modded enchantments support.

**Comment by WenXin20** [comment]
All Tool/Weapon Enchantments:
- Salvage
- Curse Break

All Tool Enchantments:
- Homing
- Magnetic

**Comment by mickelus** [comment]
For each enchantment i need the following information to implement this:
* name
* description
* id
* max level
* applicable items
* enchantability function (typically something like this: `enchantability = base + enchantmentLevel * levelMultiplier`)

**Comment by mickelus** [comment]
The magnetic enchantment is the only enchantment that would work with tetra and an enchantment with the same effect is already provided by cyclic, so I'm skipping charm.

**Comment by WenXin20** [comment]
Would the magnetic enchantment still work if someone has charm installed but not cyclic?

**Comment by mickelus** [comment]
It would not :/
