### ISSUE TITLE
Support for Enchantable

### ISSUE THREAD

**Issue by WenXin20** [mickelus/tetra#113]
## Feature Request

**Feature description**
- Support for [Enchantable](https://www.curseforge.com/minecraft/mc-mods/enchantable). It adds the Replanting & Cultivator enchantments for the hoe & shovel.

**How it improves the player experience**
- It would add many more tool enchantment customization options.

**Tetra synergies**
- More modded enchantments support.

**Comment by WenXin20** [comment]
Hoe/Shovel Enchantments:
- Cultivator
Hoe Enchantments:
- Replanting

**Comment by mickelus** [comment]
For each enchantment i need the following information to implement this:
* name
* description
* id
* max level
* applicable items
* enchantability function (typically something like this: `enchantability = base + enchantmentLevel * levelMultiplier`)

**Comment by mickelus** [comment]
This is available in 2.4.0+
