### ISSUE TITLE
Support for Tombstone Enchantments

### ISSUE THREAD

**Issue by WenXin20** [mickelus/tetra#114]
## Feature Request

**Feature description**
- Support for [Tombstone](https://www.curseforge.com/minecraft/mc-mods/corail-tombstone). It adds 3 new enchantments.

**How it improves the player experience**
- It would add many more tool enchantment customization options.

**Tetra synergies**
- More modded enchantments support.

**Comment by WenXin20** [comment]
Weapon Enchantments:
- Magic Siphon V

All Tool/Weapon Enchantments:
- Tombstone Soulbound

**Comment by mickelus** [comment]
For each enchantment i need the following information to implement this:
* name
* description
* id
* max level
* applicable items
* enchantability function (typically something like this: `enchantability = base + enchantmentLevel * levelMultiplier`)

**Comment by mickelus** [comment]
Closing this as I'm unable to run data generation for corail tombstones and the author does not intend to fix that.
