### ISSUE TITLE
Support for Ice and Fire: Dragons in a whole new light!

### ISSUE THREAD

**Issue by justinwbaker** [mickelus/tetra#117]
## Feature Request

**Feature description**
Support for the [Ice and Fire: Dragons in a whole new light!](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons) mod, adding materials for the dragon bones, dragon scales, the various chitin, sea serpent scales, troll leather, shiny scales and dragon steel.

**How it improves the player experience**
more tool customization, and a fun way to get the materials

**Tetra synergies**
more mod support

**Comment by mickelus** [comment]
I need the following information for each additional material:

applicable modules or slots (e.g. all blades or socket or all handles or handle wraps)
damage (fixed amount, or multiplier)
speed (fixed, multiplier)
durability
integrity
harvest capabilities (type, level, speed)
effects (e.g. autosmelt, uses mana to restore durability, sweeping)
usages (e.g. can till dirt or strip logs)

**Comment by mickelus** [comment]
Closing this as it still has not been refined, feel free to reopen if you manage to provided the requested information.
