### ISSUE TITLE
Support for Cyclic Enchantments

### ISSUE THREAD

**Issue by WenXin20** [mickelus/tetra#119]
## Feature Request

**Feature description**
- Support for [Cyclic](https://www.curseforge.com/minecraft/mc-mods/cyclic). It adds several new enchantments.

**How it improves the player experience**
- It would add many more tool enchantment customization options.

**Tetra synergies**
- More modded enchantments support.

**Comment by WenXin20** [comment]
Weapon Enchantments: 
- Venom II
- Life Leech II
- Experience Boost III

Bow Enchantments:
- Multi-Shot

All Tool/Weapon Enchantments:
- Magnet III

Tool Enchantments:
- Excavate III

**Comment by mickelus** [comment]
For each enchantment i need the following information to implement this:
* name
* description
* id
* max level
* applicable items
* enchantability function (typically something like this: `enchantability = base + enchantmentLevel * levelMultiplier`)

**Comment by mickelus** [comment]
This is available in 2.4.0+
