### ISSUE TITLE
[Suggestion] Craft Tweaker Support OR adding Materials via config/scripts

### ISSUE THREAD

**Issue by Burgersim** [mickelus/tetra#12]
I really love this mod, and I really wish to be able to replace Tinkers Construct in my Mopdack with it, because of it's simplicity, so I thought, maybe you could add the possibility to add Materials for Parts via Craft Tweaker or Config or Scripts in general, something like, for example:

```
{ materialname: "Cold Iron":
          {
          materialcolor: #9abfff;
          materialdurability: 300;
          materialglint: ;
          materialenchantment: ;
          materialitem: "ingot:coldiron";  **[the item you need to use for changing/repairing]**
          restrictions: pommel, guard       **[what the material cannot be used for]**
          }
}
```

I hope this is a good suggestion, I just thought that would be a nice possibility to add more mod compatibility without you having to add every single material yourself ^^

**Comment by Burgersim** [comment]
Sorry for the double post, I just saw on the wiki, that such a thing is nearly possible, and so the one thing I would request is maybe better documentation on what exactly is what (I for example would not know atm how to add BiomesOPlenty Logs for recipes in e.g. Heavy Blade) and maybe it would be possible to make a book, that you can get (config true/false) when you start a new world with informations about what can be used for what part, strength, and so forth, or another way to learn about possibilities, maybe when you find materials, you can unlock their properties in the book or sthg like that, it shouldnt be too modern though, I think, so not a teblet or sthg like that xD

Thx and sorry again for everything ^^*

**Comment by mickelus** [comment]
The documentation is really lacking, I'll take a stab at it!
I have been thinking of the approach you described, adding support for oredict metals was really tedious (and adding more modules is also going to be). It would be cool if it was possible to define materials with properties such as weight, hardness, flexibility etc. and then have the stats for a module be a function of those e.g. the damage of a hammer head depends on the weight of the material and the integrity provided by a handle depends on the flexibility and hardness of the material.
The good thing with the current approach is that you can set up new types of modules just trough configuration.

**Comment by Laike-Endaril** [comment]
Material customization would be a fantastic feature (ofc. being able to customize existing materials as well, not just adding new ones).

Just fyi, it will probably be far easier to do the customization within your own config as opposed to crafttweaker. I don't see anything your mod would really gain from that integration and it's a lot of extra work (but if you feel like it!)

**Comment by mickelus** [comment]
It's already possible :). This issue is still open because the documentation for how to do the configuration is lacking, available here: [github.com/mickelus/tetra/wiki/Config-wiki](https://github.com/mickelus/tetra/wiki/Config-wiki)

**Comment by mickelus** [comment]
It only took half a year, but here's a configuration wiki! https://github.com/mickelus/tetra/wiki/Configuration

**Comment by Laike-Endaril** [comment]
Nice!  I'll have to take another look at it and maybe try customizing tetra for my modpack.  I had removed it because by default the double-headed stone axe did 15(?) damage, so if you do a jump attack... :P
