### ISSUE TITLE
Compatibility with Loot Slash Conquer

### ISSUE THREAD

**Issue by Marthuzar** [mickelus/tetra#120]
Loot Slash Conquer provides leveling system for players, world area, and enemies.  Providing them with attributes, as well as the selection of playable classes (warrior, hunter, mage).  Weapon attributes are random by quality creation (common, rare, rare, epic and legendary).  The mod provides a lot of fun, but other mods don't have much compatibility with the mod itself. provides leveling system for players, world area, and enemies.  providing them with attributes, as well as the selection of playable classes (warrior, hunter, mage).  Weapon attributes are random by quality creation (common, rare, rare, epic and legendary).  The mod provides a lot of fun, but other mods don't have much compatibility with the mod itself. the thing is it would seem nice to me that the stats could be put on in the weapons modified by Tetra mod preserving both mod attributes.

**Comment by mickelus** [comment]
Please update this to adhere to the feature request template: https://github.com/mickelus/tetra/issues/new?template=feature_request.md

**Comment by mickelus** [comment]
Closing this, feel free to re-open when you've updated it to adhere to the template.
