### ISSUE TITLE
Support for Switch-Bow Enchantments

### ISSUE THREAD

**Issue by WenXin20** [mickelus/tetra#121]
## Feature Request

**Feature description**
- Support for [Switch-Bow](https://www.curseforge.com/minecraft/mc-mods/switch-bow). It adds several new bow/crossbow enchantments.

**How it improves the player experience**
- It would add many more enchantment customization options.

**Tetra synergies**
- More modded enchantments support.

**Comment by WenXin20** [comment]
Bow Enchantments:
- Scope
- Pull-Speed III
- Reduce Cooldown V

**Comment by mickelus** [comment]
Switch-bow is not open source and is released with an all-rights-reserved clause, which makes it kinda tricky to support it :/. Closing this, if things change then we can look into this again!
