### ISSUE TITLE
Misc Enchantments Support

### ISSUE THREAD

**Issue by WenXin20** [mickelus/tetra#122]
## Feature Request

**Feature description**
- Support for [Ore Smelter](https://www.curseforge.com/minecraft/mc-mods/ore-smelter-enchantment), [Attack Speed Enchantment](https://www.curseforge.com/minecraft/mc-mods/attack-speed-enchantment), & [Nature's Aura](https://www.curseforge.com/minecraft/mc-mods/natures-aura). This is for mods that add only one or two enchantments.

**How it improves the player experience**
- It would add many more enchantment customization options.

**Tetra synergies**
- More modded enchantments support.

**Comment by WenXin20** [comment]
Ore Smelter:
- Pickaxe Enchantment:
  - Flametouch

_____

Attack Speed Enchantment:
- Weapon Enchantment:
  - Attack Speed X
______
Natura's Aura: 
- All Tools/Weapons Enchantment:
  - Nature's Mend

**Comment by mickelus** [comment]
For each enchantment i need the following information to implement this:
* name
* description
* id
* max level
* applicable items
* enchantability function (typically something like this: `enchantability = base + enchantmentLevel * levelMultiplier`)

**Comment by mickelus** [comment]
Added support for Nature's Aura, but I don't intend to add support for Ore Smelter (still just 1.14) and  Attack Speed Enchantment.
