### ISSUE TITLE
Honing progress by right-clicking

### ISSUE THREAD

**Issue by Minamikaze392** [mickelus/tetra#123]
## Bug Report

**Observed Behaviour**
Currently honing for blades/tools can be too easily done by right-clicking.

**Expected Behaviour**
It would make more sense if progress is only by hurting or breaking something.

**Minimal setup needed to reproduce**
- Forge version: 1.14.4 - 28.1.118
- Tetra version: 1.19.1
- Tetra configuration: Should be default

**Steps to reproduce**
-Equip a Tetra blade or tool.
-Look at a block.
-Holding right-click, when it should do no effect (eg. random dirt block).
-???
-Profit

**Comment by VallenFrostweaver** [comment]
Oof. Can confirm. This is a broken and major bug.
