### ISSUE TITLE
1 material at a time doesn't show Hammer level but requirement amount does

### ISSUE THREAD

**Issue by VallenFrostweaver** [mickelus/tetra#125]
## Bug Report

**Observed Behaviour**
When placing a material in (example) an axe head and you only place 1 of the material (when it requires 2) it will not show the hammer level required. Add 1 more and it still won't show the hammer level but you can craft it. If I place multiple or a stack in the material spot 

**Expected Behaviour**
If I place 1 block at a time, once I meet the material amount needed, it shows the hammer level needed.

**Minimal setup needed to reproduce**
Replace a wooden axe head with a stone axe head placing 1 stone material at a time in the Head Material.

- Forge version: 28.1.111
- Tetra version: 1.14.4-1.19.1
- Tetra configuration: n/a
- Other mods: lots but works with vanilla + tetra too for me

**Steps to reproduce**
see **Minimal setup needed to reproduce**

**Comment by ejektaflex** [comment]
This also happens to me. Placing any less than the required amount in the slot does not show the happen requirement in 1.21.0, on Forge 28.2.1. If it requires 3 materials, for example, placing 1 or 2 in the slot will not show the hammer icon. Even adding another material will not show the icon. Instead, you must place 3 or more in one go for the icon to show up.

**Comment by mickelus** [comment]
I think I've managed to fix this in 1.23.0 (although before this I've only got the issue when I shift-click items into the material slot)
