### ISSUE TITLE
[Suggestion] More Types of Weapons/Tools

### ISSUE THREAD

**Issue by Burgersim** [mickelus/tetra#13]
Just a second, relatively small suggestion. I really like the thought of being able to customize swords, tools, and being able to make different tools, like in TC the Lumberaxe, Excavator, Hammer and Cleaver, Rapier, Broad- and Longsword, so I was wondering, are there any plans to maybe add more types of Tool Heads or possibilities for changing party of Tools and Weapons?

Thanks in Advance ^^

**Comment by mickelus** [comment]
The next 10 items in the backlog are new modules :). What do you mean with "party of tools"?

**Comment by Burgersim** [comment]
Oh sorry, that was a typo, it should've said "changing parts of tools", but I realize that is already possible, as far as I know.

**Comment by mickelus** [comment]
All parts in this batch have been implemented in 0.14.0, go check em' out!
