### ISSUE TITLE
Broken/missing textures in ruins

### ISSUE THREAD

**Issue by cerrot** [mickelus/tetra#131]
## Bug Report

**Observed Behaviour**
Most of the Ancient ruins structures do not render any texture

**Expected Behaviour**
self evident

**Minimal setup needed to reproduce**
- Forge version: 1.14.4-28.1.37
- Tetra version: 1.14.4-1.21.0
- Tetra configuration: default
- Other mods: mgui
![broken textures](https://user-images.githubusercontent.com/61561853/75482522-e5006500-599c-11ea-8fb5-c3cc7c548653.png)

**Steps to reproduce**

**Comment by mickelus** [comment]
Updating to a newer forge version fixes this issue.
