### ISSUE TITLE
Incorrect reach values on iron loop

### ISSUE THREAD

**Issue by Felixnightshade** [mickelus/tetra#132]
## Bug Report

**Observed Behaviour**

My sword, when upgraded with an iron loop, only reaches blocks that are 6 blocks away. I tested on both the shortsword and the standard sword blade with the iron loop upgrade, same thing happens for both.

**Expected Behaviour**

The sword stats in the workbench say 6.5 block reach, so it should be reaching 6.5 blocks. Though, the default reach is 4.5 blocks, and the upgrade gives 1.5 extra reach, so it should be 6 blocks. So maybe it is working as intended, and just the number reported in the sword stats menu of the workbench are incorrect.

**Minimal setup needed to reproduce**

- Forge version: 28.1.109 
- Tetra version: 1.21.0 
- Tetra configuration: Default 
- Other mods: None

**Steps to reproduce**

1: Make a sword
2: Upgrade the sword with iron loop
4: Notice that the sword stats report 6.5 reach
3: Place a block and back up 6 blocks away. If you are over 6 blocks away, you will miss. If you are under, you will hit.

**Comment by mickelus** [comment]
Ouf, fixed this at some point but I forgot to close the issue!
