### ISSUE TITLE
Failure to launch server in 1.22

### ISSUE THREAD

**Issue by ejektaflex** [mickelus/tetra#133]
## Bug Report

**Observed Behaviour**

The server crashed when trying to launch.

Crash log: 
[crash-2020-03-05_17.19.49-server.txt](https://github.com/mickelus/tetra/files/4295437/crash-2020-03-05_17.19.49-server.txt)

**Expected Behaviour**
Expected not to crash! 💯 haha

**Minimal setup needed to reproduce**

- Forge version: 28.2.1
- Tetra version: 1.22.0
- Tetra configuration: default
- Other mods: tested with no other mods for sanity's sake (besides mGui)

**Steps to reproduce**
Load this on a new Forge server with it being the only mod  (besides mGui).

**Comment by mickelus** [comment]
Fixed in 1.23.0!
