### ISSUE TITLE
[1.12] Cannot craft after converting vanilla tool to Tetra tool

### ISSUE THREAD

**Issue by lieronet** [mickelus/tetra#134]
Details:
Stock install of the latest version of Tetra 1.12.2
Only installed mods are SheftiPhianASM and Tetra
Latest version of Forge - 14.23.5.2847

After I make a Tetra tool, I can no longer craft certain items - sticks and tools are what I observed. Once the behavior occurs, the world is permanently corrupted - reloading under an older version of Forge will not allow me to craft normally.

Steps to reproduce:
Create a vanilla tool
Create a Tetra workbench
Insert Vanilla tool
Exit workbench, try to craft sticks

![2020-03-05_18 35 20](https://user-images.githubusercontent.com/28401732/76035832-7a0cdc00-5f10-11ea-9915-0f3bbf1aaa2a.png)

![2020-03-05_18 35 29](https://user-images.githubusercontent.com/28401732/76035933-bd674a80-5f10-11ea-8cc4-f27f2a584cee.png)

**Comment by lieronet** [comment]
Took out ShetiPhian-ASM-1.12.0, and of course the issue doesn't reproduce. Closing this.

**Comment by scribbler957** [comment]
I can reproduce this with only Tetra and JEI (and Toast Control).
1. Start a new world (allow cheats for convenience).
2. Cheat in a oak, spruce, and stone. (I used JEI)
3. Make a crating table.
4. Make some sticks, a pick, and a log mallet.
5. Create the Tetra workbench.
6. Put the pick in and change a head to stone.
7. Attempt to make sticks with spruce planks.
8. Fail.
You can do stuff with oak. But sticks, crafting tables, etc. don't work with other woods. The recipe for crafting tables shows 2 oak planks in each spot.

**Comment by faeldray** [comment]
I've also experienced the same thing. It seems that happens is that most of the planks and logs get stripped of their ore dictionary info. I noticed it when I reloaded the save.

**Comment by scribbler957** [comment]
What I'm curious about is how people **don't** have this problem. Is there a mod or a way of making tools that skips this issue somehow? I'd love a workaround.

**Comment by faeldray** [comment]
For anyone who comes across this issue, I did some testing and when I downgraded Tetra to v0.37.0, the issue does not appear and I can craft sticks without issue. Only versions 0.38.0 and up have the problem. I don't know why more people aren't reporting this...maybe they're all using older versions of the mod for 1.12?

**Comment by Bellegas** [comment]
I've also had this issue, thanks for the info on how to avoid it. It doesn't matter what mods you use with it, pretty sure every version after v0.38.0 is borked like this. Very weird.
