### ISSUE TITLE
[Feature] Add pickaxe synergy bonuses

### ISSUE THREAD

**Issue by ejektaflex** [mickelus/tetra#135]
## Feature Request

**Feature description**
Currently, axes and hammers have synergy bonuses, but there's no reason not to combine, say, a pickaxe head with an adze head. 

**How it improves the player experience**

Synergy bonuses would encourage more individualized tools and using a larger variety of Tetra tools at a time.

**Tetra synergies**
It's meant to add synergy, making it a tradeoff - would you rather have two unique tools that do their job a tiny bit better, or a duplex tool that does both?

**Comment by mickelus** [comment]
As we talked about on discord, I'd rather that the player have several unique tools for different usecases than having a single tools that does all. It would be cool to add synergy bonuses that make something like a claw-axe behave differently than a claw-pick, or a hammer-claw different from a hammer-pick.

Closing!
