### ISSUE TITLE
[1.14] Unexpected interaction between Enchanted Tools and Grindstone

### ISSUE THREAD

**Issue by RayTrace082** [mickelus/tetra#136]
## Bug Report

**Observed Behaviour**
Tetra modular tools which are enchanted, if passed through the [Grindstone](https://minecraft.gamepedia.com/Grindstone) grant some XP, but lose the effects of their enchantments while the enchantments remain displayed in the Tooltip

The resulting tool can be mostly used as normal

**Expected Behaviour**
Either:
a) Modular Tools can not be stripped of enchantments with the Grindstone, as it is redundant
b) Modular Tools lose their enchantments completely (like with the "Cleanse" option) if they are used on the Grindstone, yielding some XP in the process

**Minimal setup needed to reproduce**
- Forge: 1.14.4 - 28.1.115
-Tetra: 1.25.1 (Experimental features have been enabled in the Config)
-mGui: 1.2.0

**Steps to reproduce**
(in Creative mode)
-Create modular Sword, any material will do
-Apply any enchantment to the tool (Fire Aspect and Mending have been tested, as they can be taken from the Combat tab and have very obvious effects)
-Clone the Tool with middle Mouse Button
-Place one copy through the Grindstone
-Compare the performance of both tools

**Comment by mickelus** [comment]
Ouf, I overlooked that. This one will be tricky to solve.

**Comment by mickelus** [comment]
Fixed in 2.17.0!
