### ISSUE TITLE
Repairing Bug - different material 

### ISSUE THREAD

**Issue by Themitheus** [mickelus/tetra#139]
## Bug Report

**Observed Behaviour**
While repairing tool upgraded from wooden to cobblestone, elder prismarine (from quark) is required to repair that part

**Expected Behaviour**
Cobblestone is required to repair a part made of cobblestone

**Minimal setup needed to reproduce**

- Forge version: 28.1.106
- Tetra version: 1.14.4 - 1.1.0
- Tetra configuration:  default
- Other mods: Quark

**Steps to reproduce**
1. Craft any non-cobblestone tool
2. Upgrade it with Tetra workbench to have cobblestone part
3. Use up the durability
4. Try to repair it

**Comment by mickelus** [comment]
You can use anything that's tagged as stone to repair stone tools, the UI didn't represent this properly until 1.15.0.

Update tetra, you're two months behind :P

**Comment by Themitheus** [comment]
yeah, i got the mod from a modpack, guess it is time to update haha


wt., 24 mar 2020 o 11:49 Mikael E. Wikner <notifications@github.com>
napisał(a):
