### ISSUE TITLE
[Bug] Not able to change the blade of a sword

### ISSUE THREAD

**Issue by Burgersim** [mickelus/tetra#14]
![image](https://user-images.githubusercontent.com/26793150/42806388-a6c1f7dc-89ae-11e8-9eb9-c4c77ed67f20.png)

Maybe I'm doing sthg wrong, but it doesn't seem possible to change my iron sword to a diamond sword. Am I missing sthg or is this a bug? 

Side Question: How exactly do you improve integrity? And what exactly does the "**!1**" mean next to the Craft Button?

**Comment by mickelus** [comment]
You need a tier 1 hammer!
The hilt provides integrity, using planks or iron instead of the stick is a
good start!

**Comment by Burgersim** [comment]
Ah okay, so you always need a Hammer in your Inventory to upgrade tools? ^^

Then maybe another suggestion, just in case, that would be easy and possible, I have the mod [Improved Backpacks](https://minecraft.curseforge.com/projects/improvedbackpacks?gameCategorySlug=mc-mods&projectID=270457) installed, and was wondering if it would be possible to check the backpack inventory too for the Hammers, since I mostly carry them around like that.


Also, big thanks for this mod, and for your quick answers and help ^^

**Comment by mickelus** [comment]
Sort of, some variants or parts requires an axe (and leather/cloth will probably require cutting tools soon). Supporting tools in backbacks is a good idea, I've been meaning to add support for using tools in the toolbelt as well. I've created a separate issue for the backbacks https://github.com/mickelus/tetra/issues/16, so I'll be closing this one.
