### ISSUE TITLE
Repair function not working

### ISSUE THREAD

**Issue by MonkChampion** [mickelus/tetra#142]
## Bug Report

**Observed Behaviour**
Upon clicking the **Repair** icon in a tetra workbench with a tool placed inside, the repair icon disappears, leaving behind a barely noticeable slot to put items in and an un-repaired tool.

(Note that before clicking the repair button it also says Tier 0 hammer needed, Tier 0 available. Even though I have a Tier 2 hammer in my inventory)

**Expected Behaviour**
Clicking the repair icon should open a small text box explaining the repair mechanic, alongside the slot to put an item in and a **Craft** button to initiate repairing once the materials are inserted. (I think, I haven't seen a successful repair myself yet)

**Minimal setup needed to reproduce**
- Forge version: 28.2.3
- Tetra version: 1.24.0
- Tetra configuration: https://pastebin.com/d6Hb2404
- Other mods:
(Playing using the **Minecolonies Getting Started** Modpack on the twitch launcher with the attached mod list apart from Tetra):

https://pastebin.com/5HLkmmRm

**Steps to reproduce**
1. Place a crafting table
2. Craft a Log Mallet
3. Craft a stone sword and use it to damage it
3. Right click crafting table with mallet to create Tetra workbench
4. Right click workbench and place stone sword inside
5. Click Repair

**Comment by mickelus** [comment]
This was fixed in 1.25.1 :)
