### ISSUE TITLE
Support for Apotheosis Enchants

### ISSUE THREAD

**Issue by NillerMedDild** [mickelus/tetra#145]
## Feature Request

**Feature description**
Support for [Apotheosis](https://www.curseforge.com/minecraft/mc-mods/apotheosis) enchants.

**How it improves the player experience**
It would add many more tool enchantment customization options.

**Tetra synergies**
More modded enchantment support.

You can find the code for these enchantments [here](https://github.com/Shadows-of-Fire/Apotheosis/tree/1.15/src/main/java/shadows/apotheosis/ench/enchantments).

| Name                     | Id                          | Description                                            | Max Level | Applicable Items         | Enchantability Function |
| ------------------------ | --------------------------- | ------------------------------------------------------ | --------- | ------------------------ | ----------------------- |
| Hell Infusion            | apotheosis:hell_infusion    | Deals extra magic damage in the Nether.                | 10        | Weapons                  |                         |
| Mounted Strike           | apotheosis:mounted_strike   | Deals extra damage when on a horse.                    | 6         | Weapons                  |                         |
| Miner's Fervor           | apotheosis:depth_miner      | Adjusts mining speed based on Y-level.                 | 7         | Tools                    |                         |
| Stable Footing           | apotheosis:stable_footing   | Negates the mining speed penalty for flying.           | 1         | Boots                    |                         |
| Scavenger                | apotheosis:scavenger        | Mobs killed may roll their loot tables twice.          | 3         | Swords                   |                         |
| Life-Mending (Curse)     | apotheosis:life_mending     | Converts health into durability.                       | 3         | Any item with durability |                         |
| Icy Thorns               | apotheosis:icy_thorns       | Slows attackers.                                       | 3         | Armor                    |                         |
| Temptation               | apotheosis:tempting         | Entices nearby farm animals.                           | 1         | Hoe                      |                         |
| Berserker's Fury (Curse) | apotheosis:berserk          | Become enraged when taking damage.                     | 4         | Armor                    |                         |
| Knowledge of the Ages    | apotheosis:knowledge        | Enemy drops are directly converted to experience.      | 3         | Sword                    |                         |
| Nature's Blessing        | apotheosis:natures_blessing | Hoes may be used to bone-meal crops.                   | 3         | Hoe                      |                         |
| Rebounding               | apotheosis:rebounding       | Melee attackers may find themselves much further away. | 3         | Armor                    |                         |
| Occult Aversion          | apotheosis:magic_protection | Magic damage dealt by and to the user is reduced.      | 4         | Armor                    |                         |
| Capturing                | apotheosis:capturing        | Makes mobs have a chance to drop their spawn egg.      | 5         | Sword                    |                         |
| Endless Quiver           | apotheosis:true_infinity    | Makes all arrows infinite.                             | 1         | Bow                      |                         |

**Weapons = Swords & Axes**

**Tools = Pickaxes, Axes & Shovels**

**Armor = Helm, Chestplate, Leggings & Boots** 

Other Apotheosis enchants that Tetra should not support, due to their target item being unrelated to Tetra:
| Name                | Id   | Description                                                  | Max Level | Applicable Items |
| ------------------- | ---- | ------------------------------------------------------------ | --------- | ---------------- |
| Splitting           |      | Allows anvils to split multiple enchantments from books they fall upon. | 5         | Anvil            |
| Shield Bash         |      | Empowers damage done by shields.                             | 5         | Shield           |
| Reflective Defenses |      | Blocked attacks may harm the attacker.                       | 5         | Shield           |

**Comment by mickelus** [comment]
Yes! This is super!

**Comment by mickelus** [comment]
Added support for everything that has applicable items in 2.4.0!
