### ISSUE TITLE
View model bug

### ISSUE THREAD

**Issue by ElChinooo** [mickelus/tetra#148]
**I'd like to point out that there's an issue regarding with the view model of a tetra-converted tool that it's not in a proper position. "Axe, hoe and pickaxe" are affected.**

![2020-04-12_22 34 18](https://user-images.githubusercontent.com/63174098/79088625-2496cc80-7d11-11ea-8b22-27b607f2091a.png)

**Also with the tetra-converted trident. First person view model is off and as for the third person view model, it seems like the spearhead isn't facing the right way.** 

![2020-04-12_23 18 12](https://user-images.githubusercontent.com/63174098/79089815-822d1800-7d15-11ea-8153-073b1fe0baca.png)

![2020-04-12_23 18 19](https://user-images.githubusercontent.com/63174098/79089928-fc5d9c80-7d15-11ea-85f3-f74e0f279160.png)

**Comment by mickelus** [comment]
Please update this issue to use the template for bug reports.

**Comment by mickelus** [comment]
Closing, feel free to reopen after updating to adhere to the template for bug reports.
