### ISSUE TITLE
Disappearing Tools from Tetra update (2.0.1 to 2.3.0)

### ISSUE THREAD

**Issue by rckymtnrfc** [mickelus/tetra#150]
## Bug Report

**Observed Behaviour**
Updating from Tetra 2.0.1 to Tetra 2.3.0 and some tools have disappeared from the player inventory.

**Expected Behaviour**
Tool not to disappear.

**Minimal setup needed to reproduce**
- Forge version: 31.1.44
- Tetra version: 2.0.1 then 2.3.0
- mGUI version: 2.0.1 then 2.1.1
- Tetra configuration: https://pastebin.com/iJcpWQCy
- Other mods: JEI 6.0.0.3

**Steps to reproduce**
Created single player world, added iron pickaxe to one side of a vanilla stone pickaxe.  Then updated to Tetra 2.3.0 and mGUI 2.1.1  (was Tetra 2.0.1 and mGUI 2.0.1).  Upon loading single player world, tool is missing from player inventory.

**Comment by mickelus** [comment]
2.0.1 was an alpha build, wait until release if you want something stable.
