### ISSUE TITLE
Request for Datapacks: Modules can change display properties of their item.

### ISSUE THREAD

**Issue by FirebladeProduction** [mickelus/tetra#153]
## Feature Request

**Modules can change display properties of their item.**
Datapacks should have the ability to change the display properties of Items they are part of, for example if a datapack adds greatsword blades, they should be able to use a different texture size (for example 24x24 instead of 16x16) and be displayed with an offset and scaling, can also rescale the main item to be the accurate size in hand and inventory.

**How it improves the player experience**
Less improvment for players exept immersion but a great tool for datapack creators to make more and more interesting tools and weapons that are more unique.

**Tetra synergies**
just more tools for datapack creators and greater potential for Tetra.

**Comment by mickelus** [comment]
Forgot about this one...

I need examples on how this could be used, and suggestions for json formats and/or structures to support this.
