### ISSUE TITLE
[1.14.4] Replacing a piece with available honing does not clear honing

### ISSUE THREAD

**Issue by noobanidus** [mickelus/tetra#154]
Instead, you're able to replace it, and then hone the replacement part. (Specifically tool handle/simple hilt of a blade)

**Comment by mickelus** [comment]
As I mentioned on discord I've tried resetting honing progress (and reducing it) when you replace a part and even if that makes it more immersive it stops you from wanting to experiment with different modules and upgrades, and that's the opposite of what I want to achieve!

**Comment by noobanidus** [comment]
I misunderstood and yay it works awesomely
