### ISSUE TITLE
Feature Request: Forge Ruins Maps

### ISSUE THREAD

**Issue by pogo152** [mickelus/tetra#156]
**Feature description:**
I was thinking that maps could be added that helped the player find the forge ruins, much like those for woodland mansions, ocean monuments, and buried treasure. They could be bought from cartographer villagers of a certain level, or maybe obtained in some other way (crafting, dungeons, etc.)

**How it improves the player experience:**
Currently, these ruins are required for progression in Tetra. While I like that exploration is necessary to advance, the biome-specific generation and rareness might make it frustrating. Adding maps would still require players to go out and explore, without making them strip-mine through cold biomes hoping to stumble across some ruins. You could still stumble upon them by accident, but it would be easier to find them if you really needed to.

**Tetra Synergies:**
Keeps exploration intact while making progression more straightforward and less luck-based.

**Comment by mickelus** [comment]
I want to add those as well, but I need to figure out how to do proper structure generation first (they're just regular terrain features as of now).

Update your issue to use the feature request template.

**Comment by Nightcaste** [comment]
I would like to offer a format for how a locator system might work, other than just a map.

The holosphere could have a function like the Meteoric Compass from Applied Energistics, where it starts 'doing stuff' as you get closer.  The particular 'stuff' it might do is open-ended.  The model could start glowing, or changing colors, or shaking, or making noise (only if it's in your hand please).

The scrambled text on some of the pages could start to be more clear as you get closer too.

**Comment by hron84** [comment]
I rather stay with maps, especially because structure compass is nonexistent in vanilla and vanilla-ish mods. E.g. Apotheosis also offers structure maps through wandering trader and I think it's an awesome idea, it's much closer to vanilla experience.

**Comment by Spongman** [comment]
yeah, the holosphere scanner is pretty much useless for rinding ruins. after giving up on my server, i just fired up a new world and flew around in spectator trying to find a ruins. i worked out that it would have taken me about 3 months IRL of caving before i found it.

imagine if the vanilla eye-of-ender didn't do anything unless you were within 80 blocks of a stronghold... do you think mojang would have shipping it like that expecting anyone to find one without cheating?

**Comment by kohlth** [comment]
if structures spawned with a consistent y level you could have the scanner scan that y level for the ruin blocks and highlight them with a sorta glowing effect?

**Comment by mickelus** [comment]
Added in 5.3.0.
