### ISSUE TITLE
Compatibility with SwordBlocking Combat 1.14.4~1.15.2

### ISSUE THREAD

**Issue by MakcSan** [mickelus/tetra#161]
## Feature Request

**Feature description**
simply putting "tetra:sword_modular" or "tetra:modular_sword" in config doesnt work (or my format is wrong at all)
https://github.com/Fuzss/swordblockingcombat/issues/7
Issue related 
i don't know which mod is causing issue so i posted both mods

**How it improves the player experience**
Bring Backs Old Combat Mechanics Doesn't it feel good blocking arrows or attacks(damage reduce ratio can customize in Swordblockingcombat mod, Also has a options to reject projectiles) with Custom Swords made with tetra?

**Tetra synergies**
Pretty much what i said in before

**Comment by Fuzss** [comment]
Was an issue on my side; it's fixed now. You can close this.
