### ISSUE TITLE
Crafting Table won't transform

### ISSUE THREAD

**Issue by sapientiana** [mickelus/tetra#162]
## Bug Report

**Observed Behaviour**
https://youtu.be/QMUz_A_pBh8

Title

**Expected Behaviour**
Crafting table to transform into tetra's crafting table

**Minimal setup needed to reproduce**

- Forge version: forge 31.1.0
- Tetra version: 1.15.2-2.0.1 and 2.5.0
- Tetra configuration: default
- Other mods: FastLeafDecay, Inventory Tweaks, JEI, mgui, MouseTweaks, NetherPortalFix, Tetra (But the bug occurred even without the other mods present [except tetra and mgui])

**Steps to reproduce**
1. Make new world
2. Make mallet + crafting table
3. Place crafting table and right click with mallet

**Comment by sapientiana** [comment]
Thank you so much for your hard work!

**Comment by mickelus** [comment]
Updating forge seems to resolve this issue, it happened somewhere between 31.1.0 and 31.1.41 so update to something after that (preferrably the latest ;))

**Comment by sapientiana** [comment]
updating fixed it. thank you so much
