### ISSUE TITLE
Compatibility Requests

### ISSUE THREAD

**Issue by Gantros** [mickelus/tetra#163]
## Feature Request

**Feature description**
Would like to see SimpleOres support, which covers most ores you support except for Mithril, Adamantite, and Onyx. Also some Quark support, specifically for the redesigned enchantment table and a handful of additional enchantments from a companion mod, V-Tweaks. Also Nether+ adds the 1.16 content to 1.15 (sort of), so support for that would be nice if feasible. Forgot to mention this one, too, Loyalty enchantment support for the Javelin from your mod.

https://www.curseforge.com/minecraft/mc-mods/simpleores
https://quark.vazkii.net/ (See under Features/Oddities for Matrix Enchanting Table info)
https://www.curseforge.com/minecraft/mc-mods/v-tweaks (See video on page for description of Lumbering Enchantment)
https://www.curseforge.com/minecraft/mc-mods/netherplus

**How it improves the player experience**
Not sure if I could say anything here other than Quark is a very popular mod, SimpleOres covers most of the ores you already support except the 3 mentioned above, V-Tweaks gives a tree felling enchantment which I feel is better earned than another mod that simply gives it to you by default. Nether+ is just a means to include Netherite and Nether woods to your mod in 1.15. Allowing the Loyalty Enchantment for your Javelin spear just makes sense, but the other Trident enchantments like Channeling and Riptide seem OP to anything other than the Trident, sso just Loyalty seems sufficient.

**Tetra synergies**
See above

**Comment by mickelus** [comment]
When I replied with "If you're able to better express what you're looking for" on your comment on curseforge I did not mean that you should straight up copypaste your comment over here.

Split this into one issue per mod, describe the applicable modules and stats of the materials and provide the enchantment IDs for the enchantments.
It's not possible to hook into the behaviour of the enchanting table, so you can't enchant tetra items in an enchanting table.
You can already enchant the javelin with loyalty.
