### ISSUE TITLE
Feature Request: Various Mod Compatibility (SimpleOres/Quark/V-Tweaks/Nether+)

### ISSUE THREAD

**Issue by Gantros** [mickelus/tetra#165]
## Feature Request

**Feature description**
Would like to see SimpleOres support, which covers most ores you support except for Mithril, Adamantite, and Onyx. Also some Quark support, specifically for the redesigned enchantment table and a handful of additional enchantments from a companion mod, V-Tweaks. Also Nether+ adds the 1.16 content to 1.15 (sort of), so support for that would be nice if feasible. Forgot to mention this one, too, Loyalty enchantment support for the Javelin from your mod. Other miscellaneous ideas is to allow the Loyalty enchantment to be applied to the Javelin from your mod. Other Trident enchantments don't apply in my opinion. 

https://www.curseforge.com/minecraft/mc-mods/simpleores
https://quark.vazkii.net/ (See under Features/Oddities)
https://www.curseforge.com/minecraft/mc-mods/v-tweaks
https://www.curseforge.com/minecraft/mc-mods/netherplus
**How it improves the player experience**
Most of these mods don't impart an unfair advantage, but the interaction of Tetra tools and the changes these mods make a workaround needed to use them fully. For example, Quark revamps the enchantment table by changing the application of enchantments using a matrix grid, basically assigning shapes randomly to the enchantments and you have to arrange them on the grid so they fit. SimpleOres would simply add Mithril, Adamantite, and Onyx to your tool material options. V-Tweaks adds a couple enchantments, the one I'm focused on is called Lumbering, which adds a tree felling ability to an axe. I feel this is more fair than most felling mods which give it to you at the start. Nether+ simply adds 1.16 nether content to 1.15, and the netherite materials being applied to Tetra tools would be nice.

**Tetra synergies**
Explained above

**Comment by mickelus** [comment]
This still applies:

> Split this into one issue per mod, describe the applicable modules and stats of the materials and provide the enchantment IDs for the enchantments.
> It's not possible to hook into the behaviour of the enchanting table, so you can't enchant tetra items in an enchanting table.
> You can already enchant the javelin with loyalty.

Follow those points and don't repost the same thing again.
