### ISSUE TITLE
V-Tweak Enchantment Support

### ISSUE THREAD

**Issue by Gantros** [mickelus/tetra#166]
## Feature Request
Would like support for enchantments introduced in the mod V-Tweaks
**Feature description**
There are two mods in V-Tweaks, Imperishable and Lumbering. Imperishable is a kind of super Mending and not what I am interested in. My interest is in the Lumbering Enchantment, which gives a tree felling ability to axes. Here are the mod IDs.

vtweaks:imperishable
vtweaks:lumbering

**How it improves the player experience**
Imperishable is too OP and is only included for the sake of completeness. Lumbering I feel is a way to balance the ability to gather wood quickly as a reward for struggling through the early game. Other tree felling mods usually give this ability by default, which in my opinion degrades the feeling of accomplishment in the early game.

**Tetra synergies**
Tree Felling mods are very common, and since Tetra is supposed to enrich the survival experience, having it so this ability has to be earned makes sense to me.

**Comment by mickelus** [comment]
Fixed in 4.3.0.
