### ISSUE TITLE
SimpleOres Support

### ISSUE THREAD

**Issue by Gantros** [mickelus/tetra#167]
SimpleOres Support

**Feature description**
Support for the ores in this mod, specifically Mythril, Adamantite, and Onyx.

**How it improves the player experience**
Most of the ores in this mod are already supported by Tetra, aside from the aforementioned. These Ores are diamond equivalent with the exception of Onyx and probably should only be used with the ancient technology in Tetra. Perhaps added/differing bonuses could be applied to differentiate them. For example, Adamantite and Mythril are equivalent to Diamond in a Pickaxe with a durabiliy rating of 5 and an Attack of 1.2, but Onyx has durability of 7 but the same Attack of 1.2.

Ore IDs
simpleores:adamantium_ore
simpleores:copper_ore
simpleores:mythril_ore
simpleores:onyx_ore
simpleores:tin_ore

**Tetra synergies**
With the technology found in cold biomes, there is somewhat of a lack of diamond equivalent materials available, unless you include mods that might add other technologies. SimpleOres could offer additional materials without the added technologies that often use them.

**Comment by mickelus** [comment]
wontfix
