### ISSUE TITLE
Diamond Shortblade and "arrested" stones? (Bug) 1.15.2

### ISSUE THREAD

**Issue by ZR-00** [mickelus/tetra#169]
## Bug Report

**Observed Behaviour**

when making some weapon i happen to try lotts of things, and this is what i came up with. some bugs.
when i tried crafting shortblade it turns into regular sized, and wen giving a stone variant (granite diorite andersite) it is "arrested", even tho it should be able to settle

![2020-04-29_15 12 02](https://user-images.githubusercontent.com/64331654/81490521-a4cb3600-92ad-11ea-960b-43db5490f4d4.png)
![2020-05-09_23 11 13](https://user-images.githubusercontent.com/64331654/81490523-a8f75380-92ad-11ea-96e9-4e6896be2b4b.png)

**Comment by mickelus** [comment]
Closing this as it does not adhere to the template for bug reports, feel free to reopen when you've added the missing fields.
