### ISSUE TITLE
No Class Defined on Server

### ISSUE THREAD

**Issue by kreezxil** [mickelus/tetra#17]
Issue:  1.12.2-0.12.0 crashes dedicated server Forge 1.12.2 build 2745

Notes:
     no class defined

crash report:
https://gist.github.com/6210fef3502436af151e244f9cabc6d9

fml server latest:
https://gist.github.com/5cb5531d66a2b2a8a0b3f1476e31b24d

Ditto for 0.11.1

**Comment by mickelus** [comment]
This is fixed in 1.12.1. Graphics for upcoming stuff snuck with, no sneakpeaks please.
