### ISSUE TITLE
Shovel Heads don't truly exist

### ISSUE THREAD

**Issue by Ravin890** [mickelus/tetra#170]
## Bug Report

**Observed Behaviour**
Most of the heads are classified as wooden heads for the shovel.

**Expected Behaviour**
The heads of the shovel to exist

**Minimal setup needed to reproduce**
- Forge version: 1.15.2 forge 31.1.78
- Tetra version: 2.5.0
- Tetra configuration: default
- Other mods: mGui version 2.1.1

**Steps to reproduce**
Check either guide or worktable with shovel head.

![image](https://user-images.githubusercontent.com/13302573/81525661-68d2b800-9323-11ea-9941-a3351a63148c.png)

**Comment by PokeMaserJ** [comment]
I'll add to this. Shovel Heads are being considered tool rods. Since materials like Bone are popping up. And their magic capacity is a tad bit high... Bone has 90
![2020-05-13_22 03 49](https://user-images.githubusercontent.com/11018346/81887943-e6860600-9565-11ea-9693-5c1b8fdf13e0.png)
