### ISSUE TITLE
Craftable/replacement holosphere

### ISSUE THREAD

**Issue by withalwhere** [mickelus/tetra#171]
## Feature Request

**Feature description**
It should be possible to replace your original holosphere if it gets lost or destroyed.

**How it improves the player experience**
It's easy to lose individual items in Minecraft, whether that's from dying somewhere inconvenient or just having terrible item storage. Since the holosphere is only available through crafting your first mallet, it's basically irreplaceable without cheating a new one in.

**Tetra synergies**
Without another in- or out-of-game reference, engaging with Tetra without the holosphere is much less convenient.

**Comment by Edulml** [comment]
In newer versions of Tetra it's already craftable by surrounding a redstone lamp with 4 scraps from the structures. You should close this issue yourself and before you ask no, mod developers don't like to backport when they're already working on newer versions.

**Comment by withalwhere** [comment]
I'm glad that they added a recipe, presumably some time in the several months that this issue has been open. No offense, but that's kind of a rude way of asking for an issue to be closed.
