### ISSUE TITLE
Prevented from repairing  - Module Null

### ISSUE THREAD

**Issue by Zeeham** [mickelus/tetra#175]
## Bug Report

**Observed Behaviour**

![null](https://user-images.githubusercontent.com/65502799/82154312-2d0b8700-982a-11ea-8816-8781fdbbeb5a.PNG)

**Minimal setup needed to reproduce**

- Forge version: 1.14.4 - 28.2.3
- Enignmatica 4 modpack - 0.4.10

Was working fine for multiple play sessions, then occurred for one player but not others, is now spreading to other players.

Thanks much.

**Comment by mickelus** [comment]
Update to a newer version of tetra
