### ISSUE TITLE
Compatability Suggestion: Quark Coloured Runes

### ISSUE THREAD

**Issue by thisisACat5** [mickelus/tetra#176]
**Feature description**
Compatability with Quark's Coloured Runes.

**How it improves the player experience**
It'll make enchanted tools look nicer.

**Tetra synergies**
As this would be purely cosmetic I dont think it would change much or really "synergise" with anything. *(I am unsure what I am supposed to write here tbh)*

**Comment by mickelus** [comment]
Please update this to adhere to the template for feature requests.

**Comment by thisisACat5** [comment]
is that better? i really didnt know what to write there.

**Comment by mickelus** [comment]
From what I've seen this should work now!
