### ISSUE TITLE
Prismarine dagger texture has stray pixel

### ISSUE THREAD

**Issue by Terravolt14** [mickelus/tetra#178]
![2020-05-24_19 06 45](https://user-images.githubusercontent.com/47836751/82766983-ba824480-9df1-11ea-9b02-e57a98498731.png)

**Comment by Terravolt14** [comment]
one pixel above the hilt

**Comment by mickelus** [comment]
Closing this as it does not adhere to the template for bug reports, feel free to reopen after updating the issue.
