### ISSUE TITLE
Odd error messages during worldgen, possibly linked to Tetra

### ISSUE THREAD

**Issue by NillerMedDild** [mickelus/tetra#179]
## Bug Report

**Observed Behaviour**
A player was flying, generating new terrain.

**Expected Behaviour**
No mysterious logged errors mentioning Tetra items :P

**Minimal setup needed to reproduce**
- Forge version: 1.15.2-32.2.0
- Tetra version: 2.7.2
- Tetra configuration: 
- Other mods: A ton, Enigmatica 5 v0.4.13

**Steps to reproduce**
Not entirely sure to be honest, haven't tested myself.

**Comment by mickelus** [comment]
Can you hook me up with the log? Perhaps I can find something!

**Comment by NillerMedDild** [comment]
Heh woops, forgot the most important part :P I even made the gist. https://gist.github.com/NillerMedDild/d661383104074158b4ec8cdff1ea183c

**Comment by mickelus** [comment]
Are you sure it's from tetra? It looks like it ran out of memory while loading advancements
```
[06:48:46] [Sound engine/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.OutOfMemoryError: Java heap space
```

**Comment by NillerMedDild** [comment]
No that part isn't Tetra, but that part isn't what this issue is about :)
Lines 6700 to about 7000 are the odd error messages this bug report is about.

**Comment by mickelus** [comment]
Ah, yes! I think we talked about those before! I've got no idea why they pop up though :D
