### ISSUE TITLE
Unhandled Exception: right-click behavior for hoe tools [0.13.0]

### ISSUE THREAD

**Issue by xentaros** [mickelus/tetra#18]
Not sure if you are already aware of this but there is an issue with right-clicking blocks with a hoe that leads to a shutdown. Here is a crash report. 

https://paste.ee/p/gbM0C

**Comment by mickelus** [comment]
Thank you for the crash report! This has been fixed and will be part of the next release :)

**Comment by mickelus** [comment]
Fixed in 0.14.0
