### ISSUE TITLE
Broken Rendering When Using Bow with 0 Draw Speed

### ISSUE THREAD

**Issue by Ikeath** [mickelus/tetra#180]
## Bug Report

**Observed Behaviour**
When firing a bow with a draw time of 0, rendering for everything but the player's hand breaks. This persists through loading other saves. I could only fix this by restarting my game.

**Expected Behaviour**
For it not to break rendering.

**Minimal setup needed to reproduce**
- Forge version: 31.2.0
- Tetra version: 2.7.2
- Tetra configuration: Default
- Other mods: None

**Steps to reproduce**
A bow with a draw speed of 0. I did this with a membrane string, a spruce recurve, and a limb adjuster set all the way to the left.

**Comment by mickelus** [comment]
Fixed this in 2.17.0!
