### ISSUE TITLE
Quick Latch auto-tool select fails on certain blocks, works on others.

### ISSUE THREAD

**Issue by darloth** [mickelus/tetra#181]
## Bug Report

**Observed Behaviour**
Toolbelt quick slots upgraded with Quick Latch does not always select correct tool type for terrain when you press the toolbelt hotkey.  Whether it works depends on the specific block you're looking at - For example some dirt blocks work fine, and some don't, with no obvious difference in the block type.

**Expected Behaviour**
Toolbelt quick latch auto-tool select should be consistent across all blocks of the same type.

**Minimal setup needed to reproduce**
Reproduced in new modpack via Twitch client containing only Tetra, mGui, and JEI.
- Minecraft Version: 1.15.2
- Forge version: forge-31.2.5
- Tetra version: tetra-1.15.2-2.7.2.jar

- Tetra configuration: Fresh/Default
- Other mods: JEI was present but is not believed to be involved.

**Steps to reproduce**

Create and upgrade a toolbelt with some quick latch upgraded quickslots. (reproduced with Leather Belt with a single 2 Iron Loops slotted and upgraded with Quick Latch).
Fill the belt with two different tools (reproduced with vanilla Iron Shovel and Iron Pickaxe, though initially noticed with Tetra modular tools).
Dig down a bit until you have an area with both dirt and stone showing.
Experiment with pressing toolbelt hotkey (default V, unchanged in reproduction case) when looking at various blocks.  Some will work (the tool will swap out) and some will not.  These blocks will stay consistent in that the failing blocks will always fail, and the successful blocks will always cause the tool to swap.  Minecraft F3 debug shows no observable difference between the blocks, and they are not crossing chunk boundaries.

**Comment by mickelus** [comment]
Which are the blocks you've obseved this fail and suceed for?

**Comment by darloth** [comment]
So far I've only tested on dirt and stone.

**Comment by Derpyherpman234** [comment]
I've had the same problem on stone, and with a cutter mattock (I think that's what it's called) but dirt seems to work fine with a shovel.

**Comment by mickelus** [comment]
This seems to have been related to which side of the block the player was looking at, fixed in 1.16. There are currently no plans to backport that though :P
