### ISSUE TITLE
Compatibility Request: Materials from "Create" mod

### ISSUE THREAD

**Issue by erisdev** [mickelus/tetra#184]
## Feature Request

**Feature description**
Support the handful of [metals added by Create](https://github.com/Creators-of-Create/Create/wiki/Create%27s-Materials), particularly the "ordinary" metals — zinc and brass. 

**How it improves the player experience**
Consistency — other common modded metals like copper and steel are already supported. If copper works, brass should too; if emerald, why not rose quartz?

Variety — look, who doesn't love having more choices? If more metals are supported, there are that many more opportunities for experimentation.

Beauty — just look at polished rose quartz?? I'd love to make a custom sword out of that, or slot it into a gem socket. Or what about shadow steel... totally badass.

**Tetra synergies**
I'm not sure what to write here? What _are_ the goals of Tetra?

**Comment by mickelus** [comment]
It's rather unclear which materials you're suggesting support for, but crafting weapons and tools from zinc and brass don't make sense.

I need the following information for each additional material:

applicable modules or slots (e.g. all blades or socket or all handles or handle wraps)
damage (fixed amount, or multiplier)
speed (fixed, multiplier)
durability
integrity
harvest capabilities (type, level, speed)
effects (e.g. autosmelt, uses mana to restore durability, sweeping)
usages (e.g. can till dirt or strip logs)

**Comment by erisdev** [comment]
do you have a specific system you use to decide each module's durability, speed, etc. for a given material, or are all the values just what you think makes sense? i was trying to crunch the numbers for the vanilla materials and i can't discern a pattern in e.g. the durability values of diamond vs iron vs gold modules relative to the vanilla tool durability and it's leaving me kinda stumped as to how i'm supposed to decide.

to be more specific, i can't figure out why a `simple_pickaxe/diamond` has ~6.70 times the durability of a `simple_pickaxe/iron`, but a `simple_axe/diamond` has only ~5.14 times the durability of a `simple_axe/iron`. am i overthinking this?

**Comment by mickelus** [comment]
I've based it on the stats for their vanilla (or modded) counterparts.

Historically (from what I've read) copper and bronze have been used for making tools, but brass and zinc has not. I would have skipped tin as well but the mods I used for references when adding most metals also added tools made from tin.

**Comment by hron84** [comment]
Shadow steel could be added too. Back in the days, Metallurgy has this material as a tool/armor material, also TerrafirmaCraft tinkering with numerous different steels. For stat-wise, I think it could be relative to steel but a bit stronger.

**Comment by Themitheus** [comment]
Taking the approach create devs took, currently Create features only one tool - Deforester. 
**Deforester** is an axe made from refined radiance. 
My suggestion towards create compat would be allowing to tweak deforester- treating it as an axe with refined radiance head and tool butt, obsidian / repurposed beam handle and with a tetra's **cogwheel socket.** 
Cogwheel socket could grant other double - headed type tools deforester's ability - veinmining tool's intended block (fex. ore for pickaxes, logs with axes).

Another compat feature might consists of allowing usage of create's mechanical press as a tier 3 hammer, when placed above tool forge.

**Comment by mickelus** [comment]
Closing as this has been in need of refinement for a long time with no progress. Feel free to update & comment on the issue and I'll reopen it.
