### ISSUE TITLE
Crafting EX crafting table doesn't work for conversion

### ISSUE THREAD

**Issue by SupGamerNL** [mickelus/tetra#185]
## Bug Report

**Observed Behaviour**
When I right-click the crafting table while I play modded Minecraft with the mod Crafting EX and Tetra, the mallet won't convert the normal crafting table into Tetra's own workbench.

**Expected Behaviour**
I actually expected that Tetra would've converted the crafting table even though Crafting EX is also installed besides Tetra itself

**Minimal setup needed to reproduce**
Installed mods: Crafting EX & Tetra, configs stays as default.
- Forge version: 1.12.2 - 14.23.5.2854
- Tetra version: 0.39.1
- Tetra configuration: all default
- Other mods: Crafting EX

**Steps to reproduce**
1. Create a new world in survival.
2. Craft 2 crafting table.
3. Craft the mallet of Tetra.
4. Right-click 1 of the crafting tables with the mallet.

**Comment by mickelus** [comment]
I've not played with Crafting EX, does it remove the vanilla crafting table?

**Comment by SupGamerNL** [comment]
No it doesn't remove the vanilla crafting table, it changes it's functionality so that if you have duplicated recipes you can toggle between them by using two new buttons in the GUI if you are using a recipe that can have multiple outcomes from other mods, like for example; wooden gears from Buildcraft and Ender IO have the same recipe, then you can toggle between the both wooden gears.

**Comment by mickelus** [comment]
Many mods add their own crafting tables, support for converting them into tetra workbenches does not fit with upcoming features.
