### ISSUE TITLE
Crash when attempting to craft hammer (Optifine)

### ISSUE THREAD

**Issue by Kwikxilver** [mickelus/tetra#186]
## Bug Report

**Observed Behaviour**

Attempted to get started with Tetra in 1.15.2, using Optifine with Shaders. Couldn't find the recipes for the hammer in JEI, when I attempted to create the hammer in a crafting table my game crashed as soon as it tried to render the hammer item. Similar crash occurs when viewing Tetra's creative mode tab.

Crash log: [https://pastebin.com/8KEYhZds](https://pastebin.com/8KEYhZds)

**Expected Behaviour**

I expected the hammer to be craftable and that it wouldn't have any issues rendering it. I was wrong.

**Minimal setup needed to reproduce**

- Forge version:  forge-31.2.9
- Tetra version: tetra-1.15.2-2.8.1.jar
- Tetra configuration: default
- Other mods: JEI, Optifine w/ shaders

**Steps to reproduce**

1. Install mods and launch game.
2. Enable shaders.
3. Attempt to craft a hammer.

**Comment by mickelus** [comment]
Does this still persist? I've seen several people use tetra with shaders without problem.

**Comment by IMaFishEatshark** [comment]
I have the same problem not using optifine but using some mods doesn't happen in singleplayer only in multiplayer, when i craft a hammer for the first time it goes dark gray and gets kicked out of the server and can't join tghe server again until the player data is erased.


> curent modlist
Bookshelf (by DarkhaxDev)
Just Enough Items (JEI) (by mezz)
Default Options (by BlayTheNinth)
Mekanism Additions (by bradyaidanc)
Enchantment Descriptions (by DarkhaxDev)
Refined Storage Addons (by raoulvdberge)
Light Overlay (Rift/Forge/Fabric) (by shedaniel)
Flat Bedrock (by Sunekaer)
Ars Nouveau (by baileyholl2)
Ender Storage 1.8.+ (by covers1624)
JEITweaker (by Jaredlll08)
ReAuth (by TechnicianLP)
Storage Drawers (by Texelsaur)
Bad Wither No Cookie - Reloaded (by Kreezxil)
AppleSkin (by squeek502)
Architectury (Forge) (by shedaniel)
FTB GUI Library (by FTB)
GraveStone Mod (by henkelmax)
Cloth Config API (Forge) (by shedaniel)
Waystones (by BlayTheNinth)
🥝 Kiwi (by Snownee_)
The One Probe (by McJty)
Better Ping Display (by Quintinity)
Simple Storage Network (by Lothrazar)
☃ Snow! Real Magic! (by Snownee_)
Dungeons Mobs (by the_infamous_1)
GeckoLib (by ThanosGecko)
FastFurnace (by Shadows_of_Fire)
Flux Networks (by sonar_sonic)
Crafting Tweaks (by BlayTheNinth)
Create (by simibubi)
Mystical World (by EpicSquid315)
mGui (by mickelus)
TrashSlot (by BlayTheNinth)
Apotheosis (by Shadows_of_Fire)
Patchouli (by Vazkii)
Building Gadgets (by Direwolf20)
Ranged Pumps (by raoulvdberge)
Step (by ModdingLegacy)
Morpheus (by Quetzi)
CraftTweaker (by Jaredlll08)
Mekanism (by bradyaidanc)
Refined Storage (by raoulvdberge)
Guns, Rockets and Atomic Explosions (by songxia23)
YUNG's Better Caves (Forge) (by YUNGNICKYOUNG)
Dungeons Gear (by the_infamous_1)
Neat (by Vazkii)
Mekanism Generators (by bradyaidanc)
Dash (by ModdingLegacy)
Miner's Helmet (by ModdingLegacy)
Overloaded Armor Bar (by tfarecnim)
Botania (by Vazkii)
Chunk-Pregenerator (by Speiger)
CodeChicken Lib 1.8.+ (by covers1624)
NetherPortalFix (by BlayTheNinth)
Forbidden and Arcanus (by cesar_zorak)
Astral Sorcery (by HellFirePvP)
AttributeFix (by DarkhaxDev)
Quark (by Vazkii)
Just Enough Resources (JER) (by way2muchnoise)
The Weirding Gadget (by AtomicBlom)
Aquaculture 2 (by Shadowclaimer)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Scuba Gear (by ModdingLegacy)
Clumps (by Jaredlll08)
Leap (by ModdingLegacy)
ObserverLib (by HellFirePvP)
Nature's Compass (by Chaosyr)
Quark Oddities (by Vazkii)
ContentTweaker (by Jaredlll08)
Iron Chests (by ProgWML6)
FTB Backups (by FTB)
AutoRegLib (by Vazkii)
FTB Chunks (by FTB)
Mining Gadgets (by Direwolf20)
Curios API (Forge) (by TheIllusiveC4)
Buddycards (by wildcard_gamer)
Tetra (by mickelus)
FPS Reducer (by bre2el)
FastWorkbench (by Shadows_of_Fire)
Waddles (by Girafi)
Armor Toughness Bar (by tfarecnim)
Mouse Tweaks (by YaLTeR)
Ding (by ohaiiChun)
Ping (by Girafi)
Controlling (by Jaredlll08)
Placebo (by Shadows_of_Fire)
JEI Integration (by SnowShock35)

**Comment by Sandcake-Dev** [comment]
I also have this issue. It only occurs in multiplayer. There server is running mohist build 255 (Its a forge/spigot hybrid). When a payer tries to craft the hammer, the game crashes.
In the server console it says this after the player is disconnected: 

> Sandcake_ lost connection: Internal Exception: java.lang.StackOverflowError

Here is a link to the crash report: [https://pastebin.com/6T5vPMzk](url)

**Comment by mickelus** [comment]
Closing this, comments are not related to optifine.
