### ISSUE TITLE
Psi compatibility

### ISSUE THREAD

**Issue by SaikoChan1** [mickelus/tetra#187]
I would like Psi to be compatible with Tetra, this means any tool or weapon from Psi could become modular and Psimetal (possibly of all types, meaning Ebony and Ivory ingots as well) and possibly even Psigems could become a material to be used in other modular items

This would make the game more fun for people like me who love Psi just based on the premise of being able to modify your Psi tools and min max them fully, it could add an extra layer of depth with all of the possible new item combinations and generally being able to modify all the types of weapons or tools from Psi or other mods would be intuitive and immersive in of itself

Maybe you could socket a Psigem into a modular tool/weapon and it would give it special properties like being able to have spell bullets loaded and it would repair with your Psi energy? Or just if you have a tool or weapon made with Psimetal it would have the same properties. And also just generally make it so you can modify Psi tools and weapons

That's mostly stuff kind of copied and pasted from my Curseforge comment so, sorry, just kinda tired rn and honestly don't feel like writing that much. Anywways, I've made a lot of the 1.15 textures for Psi, and I feel like I'm pretty decent at making weapon and tool textures, so if you would like I could do some things and stuff with textures. okay, bai bai sayonara ^^

**Comment by mickelus** [comment]
This issue does not adhere to the template for feature requests.
I've not played with psi so I have no idea what you're suggesting, please provide more details on what you're looking for.

**Comment by mickelus** [comment]
Closing this, feel free to reopen when you've updated it to adhere to the template and provided more information about what this would entail.
