### ISSUE TITLE
[1.15.2] Randomly generated stone blocks

### ISSUE THREAD

**Issue by TheUntamed** [mickelus/tetra#188]
MC 1.15.2
Forge: 31.2.9
Tetra: 2.10.0

Tetra seems to randomly generate single stone blocks that are not from minecraft but from this mod. If broken they drop Geodes.
The problem is, when played with TerraForged strate generation those single stone blocks generate inside other stone variants layer destroying the optic.

![Screenshot_1](https://user-images.githubusercontent.com/48363903/85071047-2ec4c380-b1b7-11ea-824c-da8dc80f6dfd.jpg)

I'm not 100% sure but it might be that it only replaces vanilla stone variants (andesite granite, diorite and normal stone ofc.). If that's the case it could be enough to change the filler block from "NATURAL_STONE" to stone.

**Comment by mickelus** [comment]
You can disable geodes in the config if you've got something that drastically changes worldgen.
