### ISSUE TITLE
[Suggestion] Rift Compatibility

### ISSUE THREAD

**Issue by Burgersim** [mickelus/tetra#19]
Hi there, still really love the mod and seeing how it is coming along, so I wanted to pose the question, would it be possible to implement this mod in 1.13 with the Rift Mod loader? Just wanted to ask politely, because I'm making a mod for it myself, adding some materials, and I would've still loved to have this mod in our pack. Of course I do understand that that may be too much to ask.

**Comment by mickelus** [comment]
I'm not sure how to do that and still keep things maintainable. I just had a quick look at the documentation, but is it not possible to run rift and forge in parallel?

**Comment by Burgersim** [comment]
It is planned to be possible, as far as I know, we wanted to trya and stay "more lightweight" with our new server though

**Comment by mickelus** [comment]
I'm sorry but I do not know how to support both api:s while still maintaining a reasonable development speed. If someone has figured out a way feel free reopen and provide suggestions.
