### ISSUE TITLE
Player gets stuck in place if machete attack button is held before targeting plant block

### ISSUE THREAD

**Issue by WrongWeekend** [mickelus/tetra#190]
## Bug Report

**Observed Behaviour**
If, while holding a machete, you hold down the break block/attack button before actually targeting a plant/leaf block (which machetes are intended to be good at breaking) the player gets mostly stuck in position and the block is not broken. However, particles are generated from the block. This persists as long as the attack/break block button is held down. This makes it very difficult to cut paths through vegetation and limits the usefulness of the tool.

**Expected Behaviour**
The machete would break the plant block with no issues or at least wait for an attack cooldown to finish.

**Minimal setup needed to reproduce**

- Forge version: 1.15.2 - 31.2.29
- Tetra version: tetra-1.15.2-2.12.0
- Tetra configuration: Default config settings
- Other mods: 

Bookshelf-1.15.2-5.6.40
culinaryconstruct-FORGE-1.15.2-2.0
forgemod_VoxelMap-1.9.20_for_1.15.2
Hwyla-forge-1.10.8-B72_1.15.2
invtweaks-1.15.2-2.0.7
jei-1.15.2-6.0.0.4
mgui-1.15.2-2.1.1
SimpleStorageNetwork-1.15.2-1.0.1
TerraForged-1.15.2-0.1.0-BETA-2
WailaHarvestability-mc1.15.2-1.1.12
WAWLA-1.15.2-3.0.2

**Steps to reproduce**
Equip a machete type blade, hold down the attack/break block button, then while still holding that button, target a plant/leaf block.

**Comment by mickelus** [comment]
It's the same with all items that have the sweeping strike effect, I can't find a way to fix that without changing the mechanic.
