### ISSUE TITLE
Problems with the GUI and a few other things

### ISSUE THREAD

**Issue by DapperCore** [mickelus/tetra#191]
Want to preface this by saying that I absolutely adore the mod, seeing something so innovative and unique really resparked my love for modded minecraft!

One of my only complaints with Tetra is that the GUI is rather clustered and hard to comprehend. Here are a few examples of where I struggled to understand what exactly I was looking at:

1.
![image](https://user-images.githubusercontent.com/55637354/86302586-2ae16a00-bbd7-11ea-8e0e-db83ce419ad6.png)

When the user first opens their new crafting menu, they're greeted by a black diamond and absolutely nothing else. Unless you've done research as to what Tetra is meant to be, it's rather intimidating. A solution to this would be to add an outline of a tool such as a pickaxe. Ideally reverting from a diamond shape back to a square and staying away from the white on black color scheme would also dramatically improve legibility across the entire mod as it would remove the pixelated diagonal line effect. Here's an example of both solutions:
![image](https://user-images.githubusercontent.com/55637354/86304829-105ebf00-bbde-11ea-912c-45ec7a49faf1.png)

2.
![image](https://user-images.githubusercontent.com/55637354/86304927-5fa4ef80-bbde-11ea-8341-307a8af9add9.png)
After placing a tool inside, you're once again greeted with a ton of information that can be difficult to understand. Following the previous idea of swapping from a diamond shape to a square, it would be much easier to organize the words, as can be seen here:
![image](https://user-images.githubusercontent.com/55637354/86307507-eceb4280-bbe4-11ea-81ca-a73113a97b8f.png)

3.
Modifying parts of your tool feels rather awkward, especially since the 'Enchant' Option is mixed together with the various other parts. Here's an idea for a more legible version(Clicking on the hammer in the previous Icon would bring up this menu)
![image](https://user-images.githubusercontent.com/55637354/86308734-f6c27500-bbe7-11ea-8bdb-f96682ce8e1d.png)

4.
That's most of the issues with the GUI, the final concern I'd have is that it's rather strange to have to use a hammer to swap a vanilla crafting bench over to something new. Whenever you break the crafting table, it even reverts back to its original state. Having a unique block that could be crafted by placing a log hammer on top of a vanilla crafting bench would be a simple QoL improvement.

Thanks for reading all this, your mod is amazing and I'm really looking forward to seeing what it turns into in the future!

**Comment by mickelus** [comment]
This does not adhere to the template for feature requests. I don't get what you're trying to say as you've focused more on presenting your solutions rather than the problem.

I've also seen people struggle with understanding that they need to place an item in the diamond, but everyone figures it out pretty fast. That shape is a recurring theme in the mod, I don't intend to change that to solve that problem.

Not sure what you're trying to suggest with the two other mockups, they don't fit how the mod works :s

**Comment by mickelus** [comment]
Closing this, feel free to reopen if you're able to clarify what you're trying to suggest.
