### ISSUE TITLE
[Shield] Bosses

### ISSUE THREAD

**Issue by vaningaard** [mickelus/tetra#193]
## Bug Report

**Observed Behaviour**
When going to bash, nothing happens. Tested on multiple entities in both creative + survival. (https://youtu.be/KS-8HGGqFR0)

**Expected Behaviour**
Expected the bash to deal low damage + stun them.

**Minimal setup needed to reproduce**
- Forge version: 31.2.0
- Tetra version: 2.13.0
- Tetra configuration: 
(all defaults, except)
shield = true
- Other mods:
===Unsure if they matter, adding because it's a small list and for clarity===
+ JEI 1.15.2-6.0.2.12 (https://www.curseforge.com/minecraft/mc-mods/jei)
+ HWYLA Forge 1.10.8-B72_1.15.2 (https://www.curseforge.com/minecraft/mc-mods/hwyla)
+ JER 1.15.2-0.10.1.77 (https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
+ mGui 1.15.2-2.1.1 (https://www.curseforge.com/minecraft/mc-mods/mgui)
+ OptiFine Preview 1.15.2 HDU G1 Pre30 (https://optifine.net/downloads , preview versions)

**Steps to reproduce**
Take shield, throw into workbench, give boss, right click.

**Comment by mickelus** [comment]
Blocking has priority over bashing, you need to hold down shift to bash if the shield can block.
