### ISSUE TITLE
Missing texture when pickaxe breaks

### ISSUE THREAD

**Issue by hjpoe** [mickelus/tetra#195]
## Bug Report

**Observed Behaviour**
When my (iron) pickaxe breaks, the particles that come off of it is that purple and black missing texture block. 
**Expected Behaviour**
I would expect a to see a texture.

**Minimal setup needed to reproduce**

- Forge version: 31.2.30
- Tetra version: 2.16.0 (I saw it in 2.15.0 as well)
- Tetra configuration: I'm not sure what this is? I haven't changed anything.
- Other mods: I can reproduce it with just Tetra. 

**Steps to reproduce**
1. Make Tetra iron pickaxe. 
2. Use it until it breaks.

**Comment by mickelus** [comment]
Fixed in 3.3.0
