### ISSUE TITLE
Bugged interaction between Tool Racks and Geodes

### ISSUE THREAD

**Issue by RayTrace082** [mickelus/tetra#197]
## Bug Report

**Observed Behaviour**
Trying to crack open a Geode, with a Hammer from a nearby Tool Rack does not work properly. 

Clicking "Break Open" will not break open the Geode and no sound is triggered, but the Hammer will still be granted XP as normal, this allows generating infinite hammer XP from one single Geode

**Expected Behaviour**
Geode disappearing, and granting some loot in the process

**Minimal setup needed to reproduce**
- Forge version: 1.15.2 - 31.2.31 
- Tetra version: 1.15.2 - 2.16.1 (latest)
- Tetra configuration: Untouched configuration

**Steps to reproduce**
- Get Geode
- Try to crack open Geode from a Hammer stored in a Tool Rack (no Hammer should be in the inventory)
- Profit

**Comment by mickelus** [comment]
Fixed this in 2.17.0!
