### ISSUE TITLE
Tool Racks are reversed when placed facing east/west

### ISSUE THREAD

**Issue by Coffe-e** [mickelus/tetra#198]
## Bug Report

**Observed Behaviour**
If you place a tool rack facing east or west, you will end up putting tools on the left slot when you aim for the right, and vice versa

**Expected Behaviour**
it places the item into the tool rack on the side you were looking at

**Minimal setup needed to reproduce**

- Forge version: 1.15.2 - 31.2.19
- Tetra version:  1.15.2 - 2.16.1
- Tetra configuration: Default Config
- Other mods:

**Steps to reproduce**
Make a tool rack
place it while facing east or west
place something into the tool rack on the right side, and it will place it on the left if I didn't mess something up lol

**Comment by mickelus** [comment]
I'm unable to reproduce this :/, do you have any other mods present in your minecraft instance?

**Comment by Coffe-e** [comment]
I have, quite a lot actually. I had assumed because it was a very minute issue that it'd be the mod with the bug, but it seems my assumption was wrong.

![image](https://user-images.githubusercontent.com/65330012/88638696-b502de00-d070-11ea-88b5-849b0b3a06bf.png)
![image](https://user-images.githubusercontent.com/65330012/88638786-d1067f80-d070-11ea-8eeb-51bf912ea11a.png)

There's the picture of my mod list. I ran quite a few of these with the tool racks before, so I assumed a few more couldn't hurt, but I guess something went wrong. I'll do some testing of my own for a bit to see if I can't find it

**Comment by Coffe-e** [comment]
it appears quark is one of the problems, though i'm going to be checking w/ all the other mods installed to see if the issue still persists

**Comment by mickelus** [comment]
I think I figured it out, it appears to only happen in server environments for me.

**Comment by Coffe-e** [comment]
Ah, I see.
This thing was driving me insane tbh, cause I tested it with a few mods, then decided "hey let's see if it happens if i only have tetra installed" and the first time i did it, it didn't do it, but then the second time i did it, it did, and that was just confusing lol

**Comment by mickelus** [comment]
Fixed this in 2.17.0!
