### ISSUE TITLE
Shovel head texture is 1 pixel too far to the right

### ISSUE THREAD

**Issue by MobiusFlip** [mickelus/tetra#199]
When applying a shovel head to a single-head Tetra tool, the shovel head is one pixel off compared to vanilla tools.

**Tetra shovel:** 
![tetrashovel](https://user-images.githubusercontent.com/25667711/88960796-0ded9480-d272-11ea-9e62-e825a8fdbba5.png)

**Vanilla shovel:**
![vanillashovel](https://user-images.githubusercontent.com/25667711/88960814-134adf00-d272-11ea-9ce8-ae5448f229be.png)

**Comment by mickelus** [comment]
Thought I had fixed this already 😅, actual fix in 2.18.0
