### ISSUE TITLE
[0.14.0] Certain duplex-tool combinations have (potentially) unintended behavior

### ISSUE THREAD

**Issue by xentaros** [mickelus/tetra#20]
I haven't check all permutations to know the extent of affected tools but I'll describe the noticed behaviors. Full Iron Pickaxe appears to be a good example. When breaking blocks, it does so instantly but cannot break another block until the combat cooldown bar is finished. It seems like all sickles are also affected. If there are other examples, I haven't uncovered them yet. Nothing appears in logfiles to assist with debugging.

**Comment by mickelus** [comment]
That behavior is intended for the sickle. The iron pickaxe should not work like that, it seems like some test config slipped through.

**Comment by mickelus** [comment]
Fixed in [0.14.2](https://minecraft.curseforge.com/projects/tetra/files/2613205)
