### ISSUE TITLE
Suggestion: Hone command

### ISSUE THREAD

**Issue by MobiusFlip** [mickelus/tetra#200]
## Feature Request

**Feature description**
I think a command (probably in the form /hone <player>) which immediately advances a Tetra tool held in your main hand to the next "Honing Available" milestone would be useful for testing.

**How it improves the player experience**
This command would make testing tool combinations in creative mode much easier, so players could know exactly what they want to work towards in their survival worlds. Currently, the only way I know of to test potential honing options in creative mode is to drop into survival and set up something to quickly use the tool as normal, but a command would make this process unnecessary and allow for quick and easy testing.

**Tetra synergies**
Not entirely sure what this means, but I think the goal of any modular tool system like this should be for players to craft the tools that best suit their needs, and allowing them to quickly test a large variety of potential tools to find the best one supports this.

**Comment by mickelus** [comment]
+1

Until then you can set honing limit config values really low!

**Comment by mickelus** [comment]
Ooof, this was added in 5.4.0!
