### ISSUE TITLE
Racks crash the game when placed on bottom/top of block

### ISSUE THREAD

**Issue by MobiusFlip** [mickelus/tetra#201]
## Bug Report

**Observed Behaviour**
When trying to place a rack on the bottom or top side of a block, regardless of whether or not there are other blocks with sides bordering the rack's space, the game crashes.

Crash log: [here](https://pastebin.com/5PvBD72v)

**Expected Behaviour**
Expected to right-click with no result, like when trying to place a torch on the bottom of a block. I also expected that potentially if there was a block nearby that a rack *could* be placed on the side of in the same space (so, occupying the same position, but in an allowed orientation) it might just be placed there, like how ladders will attach to a wall if you try to place them on the ground or ceiling.

**Minimal setup needed to reproduce**
- Forge version: 1.15.2 - 31.2.33
- Tetra version: 1.15.2 - 2.18.0

**Steps to reproduce**
Try to place a rack on the bottom or top of a block.

**Comment by mickelus** [comment]
Fixed in 2.18.1!
