### ISSUE TITLE
Crash when using grindstone

### ISSUE THREAD

**Issue by Roonas** [mickelus/tetra#202]
## Bug Report

**Observed Behaviour**
Server crashes when interacting with a grindstone.

Crash log: Attached.
[crash-2020-08-03_18.25.17-server.txt](https://github.com/mickelus/tetra/files/5024789/crash-2020-08-03_18.25.17-server.txt)

**Expected Behaviour**
Normal interaction with a grindstone.

**Minimal setup needed to reproduce**
On a *server* interact with a grindstone.
- Forge version: 31.2.31
- Tetra version: 1.15-2.17.0
- Tetra configuration: Default
- Other mods: See crash report.

**Steps to reproduce**
Right click a grindstone on a server.

**Comment by mickelus** [comment]
This was fixed in 2.18.0
