### ISSUE TITLE
Mod Integration with Project MMO

### ISSUE THREAD

**Issue by Tyrius1** [mickelus/tetra#203]
I'd like to request mod integration with Project MMO

**Material Based Level Restrictions**
The ability to set a level requirement on individual material parts using Project MMO's level restriction mechanics

**How it improves the player experience**
Adding integration would allow players to feel rewarded from leveling up in Project MMO by using Tetra's design. Rather than just using level restrictions based on the item_id of the tool as a whole. For instance if say diamond pick-axe is set to mining level 50 but a pick-axe from tetra is only restricted using the item_id of the tool then people with 1 mining could technically use and wield level 50+ equipment

(default values could be added and be able to be configured via Project MMO's config)

**Tetra synergies**
It allows Project MMO to compliment and coexist with Tetra's natural progression

**Comment by mickelus** [comment]
I've not played Project MMO so I need some more information to be able to work on this. Does the mod lock items behind some sort of level?

If so, would it not be enough to lock hammers/axes/blades behind certain levels and balance tetra crafting recipes to require fitting tools for the level?

**Comment by Tyrius1** [comment]
It does indeed lock behind levels introduced by project mmo. It adds skills such as mining, woodcutting, excavation, farming etc. 

I could indeed lock the items behind the tag. I’ve done so with silents gear the same way. However, that approach undersells your mod. As it does the same with silent gear. 

If I could say diamond material parts however were locked behind a level it would truly be able to compliment your mod. Allowing the tools themselves to have custom levels based on the highest level material inserted into the tool.

**Comment by lilmrmagoo** [comment]
I think the best way to implement it is to have each tool requirement when making a module would gain a stat requirement along with it. so for say to use a  tier 3 hammer you need level 30 smithing etc. other things like repairing items is better if you have a higher smithing and crafting skill. then maybe a small part in the config where you can enable and disable support as well as change the levels of skills required.

**Comment by mickelus** [comment]
Not interested in adding compat for project MMO to tetracelium. If someone wants to make a dedicated compat mod I'd gladly help out.
