### ISSUE TITLE
Emerald socket crit can break immersive engineering crates

### ISSUE THREAD

**Issue by eggyplantsu** [mickelus/tetra#204]
The Emerald effect has a weird effects on immersive crates, if you crit a storage crate, its content is deleted and the crate doesn't drop itself.
I am playing on enigmatica 5 modpack
ImmersiveEngineering-0.15-105
tetra-1.15.2-2.16.1
*If playing with these versions be careful not to break your crates with any emerald socketed tools YOU WILL LOSE ITEMS*
*edit: I forgot about this again and smacked a spare crate and lost a mining trip worth of ores*

**Comment by mickelus** [comment]
Should be fixed in 3.4.0!
