### ISSUE TITLE
Potions Disappearing in Toolbelt

### ISSUE THREAD

**Issue by StoneMasons4106** [mickelus/tetra#205]
Got this message from someone in my server:

I had 6 regular strength potions and 6 splash strength potions. When i was inserting them into the belt, it combined the regular and splash into one slot and converted them all into regular potions. seems like a bug since it means i wasted gunpowder on making them the splash variant.

To note, Minecraft tags them both as minecraft:potion, possibly related to the issue.

**Comment by mickelus** [comment]
I think I've managed to fix this in 3.4.0!
