### ISSUE TITLE
File path displaying during honing wrapped handle

### ISSUE THREAD

**Issue by MWM92** [mickelus/tetra#206]
Hey, I love your mod to bits, brilliant job! Can't wait to see how it develops.

Anyway - I encountered this little bug while honing my spear. When I honed for speed, the bugged option disappeared.
![tetrabug1](https://user-images.githubusercontent.com/62249640/89588680-6d383f80-d844-11ea-8dc4-bb2a8619621d.png)
![tetrabug2](https://user-images.githubusercontent.com/62249640/89588682-6f9a9980-d844-11ea-9f76-6140f7444f2b.png)

**Comment by mickelus** [comment]
Fixed this at some point, can't remember in which version :P
