### ISSUE TITLE
Source out of date? (only goes to 2.13.0)

### ISSUE THREAD

**Issue by PieKing1215** [mickelus/tetra#208]
## Bug Report

**Observed Behaviour**
The source code here on the GitHub is out of date, and only goes up to 2.13.0.
I'm doing some testing for #207 but since the source is out of date I can't use my temporary solution.

**Expected Behaviour**
I would expect the source to be up to date with the releases (2.18.1)

**Comment by mickelus** [comment]
It is indeed out of date, and will probably continue to be so for some time.
