### ISSUE TITLE
CTD at world load

### ISSUE THREAD

**Issue by j3ssential** [mickelus/tetra#211]
## Bug Report

**Observed Behaviour**
Crash to desktop upon world load and sometimes on launch

Crash log: [crash-2020-08-26_04.40.50-server.txt](https://github.com/mickelus/tetra/files/5128743/crash-2020-08-26_04.40.50-server.txt)

**Expected Behaviour**
The game to load.

**Minimal setup needed to reproduce**

- Forge version: forge-31.2.30
- Tetra version: tetra-1.15.2-2.18.1
- Tetra configuration: https://gist.github.com/j3ssential/6ab435efac367643f7b49573d7a4b259
- Other mods: see crashlog

**Steps to reproduce**
Open minecraft and try to load in a world

**Comment by mickelus** [comment]
You've got a faulty datapack installed, I need the full log to be able to tell where the issue is. This is not a bug, hop onto discord if you want help with you datapacks.
