### ISSUE TITLE
Source code doesn't seem to reflect latest version of Tetra

### ISSUE THREAD

**Issue by IceDragon200** [mickelus/tetra#214]
## Bug Report

**Observed Behaviour**

This more of an issue with the repository itself, I can't seem to find the Rack block, like at all, another issue is the latest version is 2.18 yet the source is stuck at 2.13

Crash log: none, this is a source issue

**Expected Behaviour**
Source reflects current uploaded version on curseforge and includes all latest source changes

**Minimal setup needed to reproduce**

- Forge version: Same as master
- Tetra version: Master
- Tetra configuration: Master
- Other mods: None, this was all off the master branch

**Steps to reproduce**
* Clone latest version of the master branch (2d8518a383427a395beea639d48ab4d6c3206132)
* `./gradlew build runClient`
* Create a new world and then check creative inventory, no rack
* Also check the `gradle.properties` and notice that tetra is `2.13.0`

**Comment by mickelus** [comment]
Had some issues with harassment related to the source and I can't afford to deal with that. I'll start pushing to the public repository once I feel I can deal with that again, or if the community changed significantly I guess ;).

Closing the issue, watch the repo if you want a notification.
