### ISSUE TITLE
ConcurrentModificationException when browsing holo gui

### ISSUE THREAD

**Issue by viveleroi** [mickelus/tetra#215]
## Bug Report

**Observed Behaviour**
Game crashed. `java.util.ConcurrentModificationException: null`

Crash log: https://pastebin.com/ZCjCbTgv

**Expected Behaviour**
No crash.

**Minimal setup needed to reproduce**
- Forge version: 1.15.2 forge-31.2.44
- Tetra version: tetra-1.15.2-2.18.1.jar
- Tetra configuration: default
- Other mods: (see full list in crash logs)

**Steps to reproduce**
Not sure, was browsing the holo gui under "Blades" category. May have clicked too quickly, not sure.

**Comment by mickelus** [comment]
This should have been fixed in >3
