### ISSUE TITLE
[1.16.3] Duplication Bug in Workbench

### ISSUE THREAD

**Issue by KaySchus** [mickelus/tetra#217]
## Bug Report

**Observed Behaviour**
When using a sorting mod with the workbench open various items that can fit inside of it will duplicate if you sort your inventory.

**Expected Behaviour**
Ideally if I sort my inventory with this UI open I would prefer it not to see them as valid spaces to be sorted into.  Unsure how feasible that is on your end, but at least the items shouldn't duplicate.

**Minimal setup needed to reproduce**
- Forge version: 1.16.3 - 34.1.17
- Tetra version: 3.0.0
- Tetra configuration: Default Configuration
- Other mods: Inventory Tweaks Renewed

- Other Configurations:  I have been able to replicate this exact behavior on 1.15.2 as well (Tetra - 2.18.1) as that is the version I play on my current server with friends.  Checked on the current latest version to see if it was still present and found that it was.

**Steps to reproduce**
Open a Workbench UI with more than 1 item that can socket inside the workbench then proceed to use your inventory sorting hotkey from Inventory Tweaks.  Items will begin spewing out of the workbench as they are duplicated.

**Comment by mickelus** [comment]
#243 duplicates this, that issue is more detailed so closing this in favor of that.
