### ISSUE TITLE
[1.16.3] Honing Damage Upgrades & Holt Wraps do not add damage

### ISSUE THREAD

**Issue by Shiarbme** [mickelus/tetra#218]
## Bug Report

**Observed Behaviour**
Using a Honing upgrade to add damage.....adds nothing.  All hilt wraps also add no damage.  This is reflected in the modified stats before applying both, and after the upgrade when testing on mobs.

**Expected Behaviour**
Honing damage upgrade and hilt wraps adding damage.

**Minimal setup needed to reproduce**
- Forge version: 1.16.3 - 34.1.17
- Tetra version: tetra-1.16.3-3.0.0
- Tetra configuration: Default config
- Other mods: N/A

**Steps to reproduce**
Increase weapon/tool honing to add damage modifier, or wrap the hilt.

**Comment by saneandsad** [comment]
Same with bow drawspeed and weapon attack speed.

**Comment by mickelus** [comment]
Fixed in 3.3.1
