### ISSUE TITLE
[1.16.3] Long handled shovels wrapped with string have missing texture

### ISSUE THREAD

**Issue by hjpoe** [mickelus/tetra#222]
## Bug Report

**Observed Behaviour**
When you make a shovel with a long handle and wrap it in string, it has the missing texture black and purple thing with the shovel head overlayed. Leather wrap seems to display a similar missing texture. 

**Expected Behaviour**
I expect there to be a texture. 

**Minimal setup needed to reproduce**

- Forge version: forge-34.1.25
- Tetra version: tetra-1.16.3-3.3.0
- Tetra configuration: 
- Other mods: mgui-1.16.3-3.1.2

**Steps to reproduce**
Make a shovel with a long handle. Wrap the handle with string. I have tested all vanilla shovel varieties with all handle types I can think of with string wraps: all overworld and nether wood types, blaze rods, iron, gold, netherite, repurposed beam and end rods.

**Comment by WrongWeekend** [comment]
This texture bug happens with leather wraps on shovel handles as well.

**Comment by mickelus** [comment]
Fixed in 3.3.1
