### ISSUE TITLE
Bow Issue

### ISSUE THREAD

**Issue by ShabotleCreamer** [mickelus/tetra#223]
## Bug Report

**Observed Behaviour**

A really low bow draw time with a quick latch gets rid of your surroundings. The effect happens when the draw speed is 0.20 or below I could be mistaken but ik for sure it happens at 0.15 and below. is like all your chunks unloaded permanently. This effect also happens when your bow is broken and you try to pull the string back. This issue cannot be fixed by just leaving the game, but you have to restart your game completely.

**Expected Behaviour**

I Expected me to be able to just shoot normally without having to restart the game every time I use a broken bow or a quick bow with a release latch
![Proof 2](https://user-images.githubusercontent.com/73693475/97737071-e695a600-1ab2-11eb-9cbf-d87a81e56e56.png)

**Minimal setup needed to reproduce**
![Proof 1](https://user-images.githubusercontent.com/73693475/97736937-bea64280-1ab2-11eb-8057-311fbbc781d0.png)

Minecraft/Forge version 1.16.3 
The effect happens when the draw speed is 0.20 or below I could be mistaken but ik for sure it happens at 0.15 and below.

**Steps to reproduce**

Minecraft/Forge version 1.16.3 
The effect happens when the draw speed is 0.20 or below I could be mistaken but ik for sure it happens at 0.15 and below with a quick latch.

**Comment by mickelus** [comment]
Fixed in 3.4.0!
