### ISSUE TITLE
[1.16.3] Ensorcelled Compatibility (1 enchant)

### ISSUE THREAD

**Issue by NillerMedDild** [mickelus/tetra#225]
## Feature Request

**Feature description**
Support for [Ensorcelled](https://www.curseforge.com/minecraft/mc-mods/ensorcelled) enchant (it has 1).

**How it improves the player experience**
It would add AoE mining capabilities to Pickaxes, at a very large durability cost

**Tetra synergies**
An AoE mining tool with consistent AoE

You can find the code for these enchantments [here](https://github.com/Mowmaster/Ensorcelled/tree/main/src/main/java/com/mowmaster/ensorcelled/enchantments).

| Name                     | Id                          | Description                                            | Max Level | Applicable Items         | Enchantability Function |
| ------------------------ | --------------------------- | ------------------------------------------------------ | --------- | ------------------------ | ----------------------- |
| AOE Miner            | ensorcelled:enchantmentminer | Applies area of effect to Pickaxe mining - Goes up by 2x2 per level, starting from 3x3.                | 10        | Pickaxes                  |                         |

**Comment by mickelus** [comment]
Fixed in 4.3.0.
