### ISSUE TITLE
support for limiting materials to only certain modules

### ISSUE THREAD

**Issue by lilmrmagoo** [mickelus/tetra#228]
## Feature Request

**Feature description**
I think certain materials wouldn't be able to be made into say a greatsword because maybe they are too brittle or maybe to small but they could be made into say a short sword for example a talon could be sharpened into a dagger but not melded with other talons to make a bigger sword.

**How it improves the player experience**
adds some realism and uniqueness to certain materials making them better for certain jobs and unusable for others. you could also use this to make it so you can't make a blade or tool out of something but you can make a pommel or guard out of it,

**Tetra synergies**
adds support for more creativity and logic when it comes to making tools and weapons

**Comment by mickelus** [comment]
You can either add one-off module variants for the modules that you'd want to be craftable from this "material" or place your material in the misc folder and reference that for the applicable modules. Perhaps I misunderstand what you're suggesting but from what I can see you're already able to do what you are suggesting.

From what I've seen people get confused or frustrated when I've tried to apply rules like that ("why can't I craft a diamond heavy blade!?"), but you're free to do what you want there in a datapack or an addon :P.

Closing, feel free to reopen if there's something I've missed.

**Comment by lilmrmagoo** [comment]
I didn't mean for it to apply to vanilla things but to give the option for datapack makers. And making another module would feel redundant if there is already a small blade. 
It is good to know that the way the misc category works is like that, but if that thing already falls under one of the other categories then i feel like it would be weird to have them under misc. 

But it's up to you since it's your mod.

**Comment by mickelus** [comment]
You don't need to make another module, you can add variants to a module without a material, everything was set up like that before 1.16 (e.g. https://github.com/mickelus/tetra/blob/master/src/main/resources/data/tetra/modules/sword/basic_blade.json)

Module variants reference folders when determining which materials to create variants (e.g. basic blades reference "tetra:wood/", "tetra:stone/", "tetra:metal/", "tetra:gem/", "tetra:bone/"). The category field for a material does not have to be the same as the name of the folder that the material sits in, i.e. you can have a material in the misc folder that has the category "metal".
