### ISSUE TITLE
ability to have sub color materials.

### ISSUE THREAD

**Issue by lilmrmagoo** [mickelus/tetra#229]
## Feature Request

**Feature description**
it would be nice if for organization and time if we could have a way to have one material then another below it that has a different item and different tint but the same stats like allowing for different coloured wool to actually show up as a different colour maybe it would be something like this at the end of a material file 
	"colors": {
	[577E7B,Minecraft:cyan_wool], []
	}
not sure what the syntax would be but something like this would work well.
**How it improves the player experience**
more options so your weapon can still look cool and have nice stats, as well as differentiate between 2 peoples tools and such

**Tetra synergies**
more customization and options for datapack makers.

**Comment by mickelus** [comment]
Will probably implement this as "hidden" materials, i.e. a material can exist but it does not show up in the holosphere. You'd create one material for each wool and hide all but the undyed one.

**Comment by lilmrmagoo** [comment]
Would that require you to make a whole diffrent material for each? In which case the only diffrence for that is that it doesn't appear in the holosphere. It would also make datapacks larger with all the diffrent colored versions files. Still hidden is a good idea for other things.

**Comment by mickelus** [comment]
Fixed in 3.16.0.
