### ISSUE TITLE
effects ideas for data pack makers and future materials

### ISSUE THREAD

**Issue by lilmrmagoo** [mickelus/tetra#231]
## Feature Request

**Feature description**
just a bunch of effects datapack makers can use 
| effect name | short description | data inputs |
| ------------- | --------------- | --------------- |
| potions | applying potions to a target | potion id, duration, strength, target, chance, effect name |
| freezing | chance to freeze target | duration, chance, target |
| heavy | chance to stun target | chance, target, duration |
| electrified | chance to strike target with lighting | chance, target  |
| exp boost | gives % more exp (normal mc exp) | % |
| command | chance to execute a command | chance, command, effect name |

ones like potion and command with effect name would be since they're so versatile the creator of the datapack should be able to name the effect so it fits the material. some of this might be far stretched but the amount of versatility is endless with potions and commands.  
**How it improves the player experience**
adds more ways to make fancier materials with datapacks

**Tetra synergies**
Customizability!

**Comment by mickelus** [comment]
I'd much rather add effects that are used by default, but there are some plans to add ways of defining potion effects, command "effects" and faking the effects of other items using json configuration.

If you want to add your own effects that's easily done by other mods in 1.16+ :)
