### ISSUE TITLE
[1.16.3] All tools are pickaxes

### ISSUE THREAD

**Issue by Vixlia** [mickelus/tetra#232]
## Bug Report

**Observed Behaviour**
When checking for silverfish, I noticed I was able to break stone bricks with my sword. I was also able to break stone bricks with my adze, and my hammer. I believe that all tools are acting as pickaxes, possibly that all tetra tools are simply acting as each other.
I could not break normal stone, but I noticed normal stone has a minimum pickaxe level of wood. I could also break normal bricks.
Even went to test outside of the modpack I was playing in to see if it was strange behavior caused by something else and found the same thing.

**Expected Behaviour**
Not being able to break bricks with my sword or my hoe.

**Minimal setup needed to reproduce**
- Forge version: (1.16.3) 34.1.42
- Tetra version: 3.3.0
- Tetra configuration: Default, but just in case: https://pastebin.com/gF6grvD5
- Other mods: None required

**Steps to reproduce**
Install Forge, Tetra, and mGui
Upgrade a non-pickaxe tool (like an iron sword) in a Tetra workbench
Place down a brick block or a stone brick block
Break the bricks with the not-pickaxe

**Comment by Edulml** [comment]
What are you talking about? It is standard vanilla behavior to be able to break everything that's not bedrock. You can even break obsidian with your fists if you are patient enough. What would be unexpected behavior is being able to harvest the blocks without the appropriate tools but I just tested it to be sure and no, breaking stone with a Tetra sword takes as much time as breaking it with an empty hand.

**Comment by mickelus** [comment]
As Edulml noted this is vanilla behaviour, closing.

**Comment by Vixlia** [comment]
Sorry, I didn't get to check my email yesterday!

I do mean being able to **harvest** these blocks, and as I said stone was for some reason not affected. But going back to test with vanilla tools, I was not able to harvest bricks with a vanilla sword, and was able to harvest bricks with a Tetra sword.

I'm sorry for the confusion! For the sake of clarity, here's a screenshot proving that I'm not crazy: https://i.imgur.com/7Om274U.png
