### ISSUE TITLE
[1.15.2] some small questions and suggestions.

### ISSUE THREAD

**Issue by 012phuong** [mickelus/tetra#233]
## Feature Request

**Feature description**
<add the ability to make 3d model resource packs.>

**How it improves the player experience**
<Modpack developers can use it to change the model of the mod to fit their desired themes >

**Tetra synergies**
<it's doesn't relate much to the current goals of Tetra, it just a small suggestion to make the mod better.>

**Comment by mickelus** [comment]
I'll consider it if you provide decent a suggestion on the format

**Comment by mickelus** [comment]
Please update the title to match the described request.

**Comment by lilmrmagoo** [comment]
Not sure if this is possible or how the current modular textures work but I would think it would be similar to how the current textures work where you have a base model of different types of materials then apply the tints to the model's texture. Whether that is possible i don't know.

**Comment by mickelus** [comment]
Closing this as it's yet to be updated. Feel free to re-open if you manage to update it.
