### ISSUE TITLE
Bugged spears

### ISSUE THREAD

**Issue by redalpha00** [mickelus/tetra#234]
## Bug Report

**Observed Behaviour**
it is a missing texture

**Minimal setup needed to reproduce**
![2020-11-06_02 07 44](https://user-images.githubusercontent.com/74044453/98344164-78804000-1fd8-11eb-97b9-9518d827e3a9.png)

- Forge version: 34.1.0
- Tetra version: 3.3.0
- Tetra configuration: base config
- Other mods:
<img width="901" alt="mods" src="https://user-images.githubusercontent.com/74044453/98344524-fd6b5980-1fd8-11eb-8c5d-b2ab13419bd6.PNG">

**Steps to reproduce**
make a crimson long handle with a black stone spear head and string wrap.
![2020-11-06_02 07 44](https://user-images.githubusercontent.com/74044453/98344634-2390f980-1fd9-11eb-819e-0daa1b9881c7.png)

**Comment by hjpoe** [comment]
This might be related to #222.

**Comment by redalpha00** [comment]
It has a missing texture with or without that string, but it slaps the string on top of the missing texture.

**Comment by mickelus** [comment]
Fixed in 3.3.1
