### ISSUE TITLE
Toolbelt quick access item to main hand swallows the toolbelt if holding the toolbelt in main hand

### ISSUE THREAD

**Issue by JamesYeoman** [mickelus/tetra#235]
## Bug Report

**Observed Behaviour**
So by using the quick-access keybind while the toolbelt was in my main hand, I assigned an item to my main hand, and the toolbelt was replaced with the item, essentially casting the toolbelt to the void

**Expected Behaviour**

**Minimal setup needed to reproduce**

- Forge version: 1.16.3 - 34.1.42
- Tetra version: 3,3,0
- Tetra configuration: https://gist.github.com/JamesYeoman/807116fa7b9f17b1c39b7cdae14413ba
- Other mods:
Playing Valhelsia 3 pre4-3.1.0, but the issue doesn't feel like it's the cause of the other mods, it just feels like a mishandled edge case

**Steps to reproduce**
1. craft a belt with at least 1 belt loop
2. right-click while the belt is in your main hand
3. add an item to the belt's inventory
4. while the belt is in your main hand, use the quick access key, and assign the item to your main hand
~~5. cry because you haven't set up a cow farm yet in your survival world~~

**Comment by illmatix** [comment]
Yup. I ran into this as well on Valhelsia 1.16.4

**Comment by kstufflebam** [comment]
Also ran into this.

Also note: any items in the belt that you didn't select during the quick access get evaporated as well. So many hone bonuses gone :(

**Comment by dustinswede** [comment]
Yup. This is happening to me too (using version 3.3.1).

**Comment by mickelus** [comment]
Fixed in 3.4.0!
