### ISSUE TITLE
Enchatment Color

### ISSUE THREAD

**Issue by Rarket-glitch** [mickelus/tetra#236]
## Feature Request

**Feature description**
Currently, the enchantments on a forged/ edited item are this bright pink, could you make it the default purple

**How it improves the player experience**
This would be nicer as it wont be as distracting, and would allow you to better see the tool itself, and what modifications you have made to it.

**Tetra synergies**

**Comment by mickelus** [comment]
It's the default texture. For items with several textures the enchantment overlay renders several times, which makes it more intense and bright. I've added a config option for disabling the enchantment glint in 3.4.0.
