### ISSUE TITLE
[Feature Request] Make steel hammers an alternative to blackstone hammers.

### ISSUE THREAD

**Issue by Edulml** [mickelus/tetra#238]
**Feature description**
Allow steel hammers to become a tier 4 hammer just like blackstone can, to have a bit of variety for those that don't like the look of the blackstone hammer. Since in most cases steel can be acquired before entering the nether, making it require a tier 4 hammer to be crafted may be the way to keep the gating of that hammer before entering the nether (or finding a forged workshop + hammer).

**Comment by mickelus** [comment]
Closing, does not adhere to the template for feature requests.
