### ISSUE TITLE
Tetra crashes the game when interacting with slabs.

### ISSUE THREAD

**Issue by felipedeoliveirarios** [mickelus/tetra#241]
## Bug Report

**Observed Behaviour**
Minecraft crashed on placing a stone slab. It seems to be a compatibility issue with [Double Slabs Mod](https://www.curseforge.com/minecraft/mc-mods/double-slabs).

Crash log: [crash-2020-11-14_13.02.03-client.txt](https://github.com/mickelus/tetra/files/5541276/crash-2020-11-14_13.02.03-client.txt)

**Expected Behaviour**
Place a slab.

**Minimal setup needed to reproduce**

- Forge version: 1.16.3 - 34.1.42
- Tetra version: 3.3.0
- Tetra configuration: default.
- Other mods: [Double Slabs Mod](https://www.curseforge.com/minecraft/mc-mods/double-slabs).

**Steps to reproduce**
1. Place a vertical slab.
2. Interact with it using a Tetra tool.
3. Open the crash folder and collect your crash report.

**Comment by mickelus** [comment]
This should have been fixed in 3.4.0!
