### ISSUE TITLE
Surrounding blocks adding to a workstation

### ISSUE THREAD

**Issue by lilmrmagoo** [mickelus/tetra#242]
## Feature Request

**Feature description**
I'm not the first one to come up with this but thought I would make a GitHub post and add some more ideas to the fray. basically, if you had certain blocks around your work table they would allow or give benefits to your tools. For example like a grindstone allowing you to sharpen an item for a small boost in damage for limited uses or, a smithing table giving you a boost to tools made of metal, fletcher's table giving a boost to bows, leather and string, maybe a furnace or blast furnace gives another type of boost to metals. 
well, I realized what if for modpack makers and datapack devs we could have materials or modules have limitations based on what's around them like how tools work. like having just a small part next to the tools where you put a block id and boom you now require a blast furnace to make a tool with steel.

**How it improves the player experience**
it rewards those who put the time into making an actual forge and makes it feel like you're using all the things you would in a real smithy instead of just a crafting table

**Tetra synergies**
expansion min-maxing creativity with building and customizability.

**Comment by mickelus** [comment]
This is rather vague.

**Comment by lilmrmagoo** [comment]
hmm well, it was kinda supposed to because it was an idea and I'm not exactly sure what boosts would be. damage, durability, tier all of these would make sense as buffs but having all three would be op. and I'm not exactly sure what would fit right for the gameplay.

**Comment by mickelus** [comment]
Closing, this feature request cannot be completed.
