### ISSUE TITLE
[1.16.3] Duplicating inside the workbench.

### ISSUE THREAD

**Issue by PawSolaire752** [mickelus/tetra#243]
## Bug Report

**Observed Behaviour**

Using the invtweaks mod and clicking scroll wheel throws almost every item in my inventory into the workstation and if I click the scroll wheel again it will duplicate any item that was added into the workbench.
Ex: 1 sword, 1 pickaxe, 1 axe, 1 bow, 37 diamonds, 6 iron blocks, 3 stacks of birch planks, 64 torches, 64 steak, 1 crafting table, and 3 potions of regeneration. Clicking Scroll wheel will send almost all the items into the workbench and clicking it again will make the workbench spit out the items as if duplicating and if I break the workbench I would get as a result: 1 sword, 2 pickaxes, 1 axe, 1 bow, 72 diamonds, 12 iron blocks, 6 stacks of birch planks, 2 stacks of torches, 2 stacks of steak, 2 crafting tables, and 3 potions of regeneration.

**Expected Behaviour**

Nothing.

**Minimal setup needed to reproduce**

- Forge version: 34.1.41
- Tetra version: 3.3.1
- Tetra configuration: 
- Other mods: Inventory Tweaks Renewed

**Steps to reproduce**
1) Have Inventory Tweaks Renewed
2) Click scroll wheel inside workbench
3) Most items will be transferred into workbench
4) Click scroll wheel again
5) Duplicate items will pop out of the top of the workbench
6) Break workbench to get items that were transferred inside

**Comment by mickelus** [comment]
I'd suggest you to report this in the issuetracker for Inventory Tweaks Renewed as well

**Comment by PawSolaire752** [comment]
Reported it on there as well now.

**Comment by NillerMedDild** [comment]
This can be fixed by inserting this in the invtweaks config, under Custom settings per GUI:

```toml
[[sorting.containerOverrides]]
	containerClass = "se.mickelus.tetra.blocks.workbench.WorkbenchContainer"
	sortRange = ""
```
