### ISSUE TITLE
Shulker box deleting all it's contents...

### ISSUE THREAD

**Issue by SwanX1** [mickelus/tetra#245]
## Bug Report

**Observed Behaviour**
When a shulker box gets broken by a pickaxe with an emerald in its socket, and the socket behaviour is observed on a shulker box (instant break), an empty shulker box gets dropped.

**Expected Behaviour**
Shulker box drops with all its contents.

**Minimal setup needed to reproduce**
Only mod needed is Tetra.

- Forge version: 1.16.3 - 34.1.42
- Tetra version: 3.3.1
- Tetra configuration: Default config, Valhelsia 3.
- Other mods: Every mod in Valhelsia 3 + Optifine (optifine didn't influence the result, as the bug was on a server)

**Steps to reproduce**
1. Get a pickaxe with emerald socket
2. Place a shulker box with items inside
3. Break shulker box and repeat step 2, if tool's socket doesn't activate
4. ???
5. Don't profit because you lost all your stuff in the shulker box

**Comment by mickelus** [comment]
Fixed in 3.4.0!
