### ISSUE TITLE
Modular Pickarang (from Quark mod)

### ISSUE THREAD

**Issue by TBiscuit1** [mickelus/tetra#249]
## Feature Request

**Feature description**
Add a new category of tool, the Pickarang (from Quark mod)
The Pickarang is a pickaxe, shovel, axe and weapon that can be thrown to blocks, items or mobs
Basicly, it's a ranged tool and weapon

**How it improves the player experience**
First, I feel like the Pickarang (and it's netherite counterpart, the Flamerang) is a really interesting item that sadly doesn't get enough love because it get overpowered by other tools, so, making it more usable with other mods will actually make the pickarang valuable end game.
Second, the tool is really good but you need to get an Heart of Diamond from a Stoneling from Quark, since these small thing are rare and it's not a 100% drop, it is balanced and it won't be broken if you compare to the other tools and weapons

**Tetra synergies**
So first, here is how the pickarang work in Quark mod
The tool break most blocks that it can mine and that is not too slow to mine (like obsidian or ancient debris) in one hit
It has a cooldown after you pick it up to avoid spamming
The tool lose durability when you BREAK a block or HIT a mob, just hitting a block because it's too strong DOESN'T break the tool
If the tool is thrown to an item or if the block is broken or if a mob die, it will pick it up the itme and then give it to the player when picked up back

Enchantements
Efficiency : +Speed, +Range
Fortune, Silk Touch : Works the same as a normal tool
Sharpness, Bane of Athropods and Smite : Works the same as a normal weapon
Piercing : Works the same as a crossbow
Unbreaking : Works the same as normally
Curses and Mending : Works the same as normally

Now the Tetra specific I'm thinking right now
The tool stats would be :
Tool Durability : The durability of the pickarang
Tool Harvest Level : The harvest level of the pickarang
Tool Cooldown : The cooldown between each use of the pickarang
Tool Speed : The speed of the pickarang when thrown (duh)
Tool Range : The range of the pickarang (bigger range = longer distance)
Tool Damage : The damage of the pickarang on hit
Tool Strengh : The strengh of the pickarang on block hit (the bigger the strengh, the more powerful blocks that can be broken)
Tool Type : Is a Pickaxe, an Axe, a Shovel or a Sword depending of the module

The tool modules :
- Category :
**Middle Part** - The middle of the tool that combine both side of the pickarang
Socket - Add a gem to the tool to boost it
Binding - Add a binding to make it stronger
**Head Part** - The side part of the tool, it makes the type of the tool and the strengh of it
Axe Head - Cut wood and do insane damage, make the tool cooldown slower
Pickaxe Head - Mine stone and do medium amount of damage, make the tool faster
Shovel Head - Dig soft material and do small amount of damage, make the tool slower (because it unbalance the tool?)
Hoe Head - Turn dirt to farmland, destroy leaves, hay bal and nether wart block and do small amount of damage, make the tool cooldown faster and the tool faster
Sword Head - Cut web and wool and do high amount of damage, make the tool cooldown faster
Dagger Head - Cut web and wool and do small amount of damage, make the tool cooldown way faster and add a piercing effect (combine with the piercing enchant)
_Enchantements_ - Apply Enchantements to the tool head
Efficiency : More strengh and less cooldown
X - Piercing
Fortune : More drops from blocks (Vanilla Behavior)
X - Silk Touch
Silk Touch : Blocks drop them self instead of their normal drop (Vanilla Behavior)
X - Fortune
Unbreaking : More durability (Vanilla Behavior)
Mending : Exp to durability (Vanilla Behavior)
Sharpness : More damage (Vanilla Behavior)
X - Smite, Bane of Athropods
Smite : More damage to undeads (Vanilla Behavior)
X - Sharpness, Bane of Athropods
Bane of Athropods : More damage to athropods (Vanilla Behavior)
X - Sharpness, Smite
Piercing : Pierce threw mobs and blocks
X - Efficiency

Sorry for Text Wall but it's a quite complicated tool with multiple uses so it makes sense

Edit : Of course, the tool would only be obtainable when Quark mod is on

**Comment by lilmrmagoo** [comment]
hmm, I think a way of implementing this could be a boomerang/throwing weapon category of weapon and putting an earthpiecer on it would make it break blocks. this could also allow for stuff like chakrams and shurikens 
  -boomerang being long-range and the ability to have tool heads and also boomerang back.
  -chakrams being short mid ranged with some mele damage that returns when thrown.
  -and shurikens being durability based where throwing it consumes durability like ammo
for the components of it having a core wich determines what type it is (chakram, boomerang or shuriken) then 
  -a trim  which determines the outer edge of a chakram the sides of a boomerang and the blade of a shuriken
  -option for a wrap. wich would wrap the center of the boomerang and shuriken then part of a chakram
you could also have some options like jagged edges which could add a bleed or something.

**Comment by mickelus** [comment]
This would have to be implemented on quarks side, or as a separate addon mod.

**Comment by mickelus** [comment]
But I really appreciate the work you put into this issue! If anyone takes on adding this to quark or as a separate addon feel free to poke me for pointers on how to set it up!
