### ISSUE TITLE
Tetra tools don't show enchantments.

### ISSUE THREAD

**Issue by Deshiba** [mickelus/tetra#25]
Unlike the vanilla tools, Tetra enchantments aren't shown on the item.
![vanilla](https://user-images.githubusercontent.com/10565800/45687277-a4b57a00-bb4e-11e8-995e-7414038c7329.png)
![tetra](https://user-images.githubusercontent.com/10565800/45687282-a54e1080-bb4e-11e8-9541-b778b3498c7a.png)
![tetra pickaxe](https://user-images.githubusercontent.com/10565800/45687320-c3b40c00-bb4e-11e8-92e9-813b6aead1bb.png)

**Comment by mickelus** [comment]
Added enchantment display in 0.17.0, holding shift should also display all modules and improvements!
