### ISSUE TITLE
Compatiblity with XercaMod

### ISSUE THREAD

**Issue by Themitheus** [mickelus/tetra#250]
**Feature description**
Adding features to two existing tool types in tetra, the hammer and the shortblade from Xercamod's warhammer and knife.

**Hammer** would get some niche combat use as a knock-back heavy weapon, which hits must be charged similarly to trident to deal maximum damage / knock-back. 
Also featuring enchantments:
Heavyweight: Increases the maximum pull time, but also adds more damage and knock-back.
Legerity: The opposite of Heavyweight, lets you pull the hammer faster while having the same power. These two enchantments cannot be applied on the same item.
Maim: Cripples your opponent on hit, applying a Slow effect on them. Especially useful when your knocked back opponent is trying to run away!
Uppercut: Adds a “knock up” component to the hammer. A way to use fall damage to your advantage or an unorthodox method of vertical transportation.
Quake: Allows you to target the ground. When you hit the ground, all enemies around the target point are damaged according to their proximity and knocked back from that point. 

**Short blade** receiving additional use in combat, allowing off-hand usage and providing additional damage when attacking while sneaking and facing back of the enemy. Also additional enchantment and possible blade - improvement:
Silent Killer: Increases the bonus damage applied on sneak back stabs.
Venomous: Applies poison effect to the target on hit. Be careful, as the poison effect is not lethal - originally being an enchantment, might be a module to apply to any blade type. 
The changes would apply while having xercamod installed and this would disable original items

**How it improves the player experience**
It would improve some aspects of tools usually used mainly for crafting purposes, opening new play styles with the back stab mechanic.

**Tetra synergies**
It fits current weapons, further expanding their usage.

**Comment by mickelus** [comment]
I won't add this to tetra, but perhaps it is something they could add on their side.
