### ISSUE TITLE
Long bow multishot easily produce 100 damage seems broken?

### ISSUE THREAD

**Issue by No3371** [mickelus/tetra#252]
A crimson long bow has +16.5 draw strength, and it's triple shots. Immediate releasing the bow can damage the target 18, full draw can damage 100, any boss can be terminated in seconds.

With Infinity, this breaks the balance even worse...

Do you have anything in mind that we can tweak this?

**Comment by No3371** [comment]
A crimson recurse bow with multishot 4 damage 80 in one shooting.

This could make all other weapons useless.

**Comment by mickelus** [comment]
It doesn't work like that, read the description ingame.

**Comment by No3371** [comment]
I read the description but the behaviour is confusing me. Now you remind me, I'd like to inform you that the mod could be incompatible with [BetterHurtTimer](https://www.curseforge.com/minecraft/mc-mods/better-hurt-timer) gameplay-wise. (it stacks arrow damage)
