### ISSUE TITLE
Crossbow support

### ISSUE THREAD

**Issue by hjpoe** [mickelus/tetra#254]
## Feature Request

**Feature description**
Be able to modify and improve vanilla crossbows with Tetra. This might include things like different bow material types (such as different wood types or metal), different string types (such as basic string, leather, or phantom membrane), improved draw time, extended rest, or a sight.

**How it improves the player experience**
This would make the crossbow more useful and customizable.

**Tetra synergies**
 It would make sense to add crossbows, as they are a vanilla weapon, and most if not all of the other vanilla tools are supported by Tetra. This would make Tetra more immersive.

**Comment by mickelus** [comment]
Marking this as done since it's rather unspecific, basic crossbow support is available in 3.4.0.
