### ISSUE TITLE
Unregistered ConfiguredFeatures found in Tetra

### ISSUE THREAD

**Issue by TelepathicGrunt** [mickelus/tetra#255]
Hello! I was test running my mod called Blame with a bunch of mods and it seemed to have found that Tetra does not register several ConfiguredFeatures. This can be an issue for mod compatibility as under certain conditions, unregistered ConfiguredFeatures can basically prevent other mod's registered ConfiguredFeatures from spawning if in the same generation stage.

By that I mean, if mod A adds an unregistered CF to the ore generation stage and the biome's codec reaches it first, it will choke and basically nuke mob B's registered CFs afterwards. Here's a case where BetterCaves forgot to register their CF and caused several CFs from Oh The Biomes You'll Go to stop spawning in the world: yungnickyoung/YUNGs-Better-Caves#75

Here's a more detailed explanation of why this happens in the biome's codec:
![image](https://user-images.githubusercontent.com/40846040/95459000-ff41ee80-0940-11eb-8569-52a2be15cc4d.png)

Specifically, when you call .withConfiguration on a Feature, you create a ConfiguredFeature. This is what should be registered to the WorldgenRegisties at mod init (you can do it in FMLCommonSetupEvent so you have your config ready too if it is needed). 

Anyway here's an example from my mod RepurposedStructures of me registering all my ConfiguredFeatures.
https://github.com/TelepathicGrunt/RepurposedStructures/blob/584433a0745338802c84e9f498dc063c1f5505f8/src/main/java/com/telepathicgrunt/repurposedstructures/modinit/RSConfiguredStructures.java#L72-L74

I hope this helps!

From the log with Blame
-----------------------------------------------------------------------
****************** Blame Report 1.7.3 ******************

 This is an experimental report. It is suppose to automatically read
 the JSON of all the unregistered ConfiguredFeatures, ConfiguredStructures,
 and ConfiguredCarvers. Then does its best to collect the terms that seem to
 state whose mod the unregistered stuff belongs to.

Possible mods responsible for unregistered stuff:

tetra:block_geode
tetra:feature

Log that possibly has more info:
[latest.log](https://github.com/mickelus/tetra/files/5630290/latest.log)

**Comment by mickelus** [comment]
Thanks a bunch, I missed that you had to register the configured feature as well!

**Comment by Baxi2** [comment]
This issue is still on going.
Is there any progress? There are no labels telling something

**Comment by mickelus** [comment]
Fixed in 3.4.0!
