### ISSUE TITLE
Reverb modifier has no lang key

### ISSUE THREAD

**Issue by aaronhowser1** [mickelus/tetra#258]
## Bug Report

**Observed Behaviour**
![image](https://user-images.githubusercontent.com/15698722/101239588-379a4a80-36ae-11eb-889d-29c6d927c916.png)

**Minimal setup needed to reproduce**

- Forge version: 35.1.7
- Tetra version: 1.16.4-3.3.1

**Comment by mickelus** [comment]
Ow, fixed this in 3.5.0!
