### ISSUE TITLE
Conflicting enchantments on a single tool

### ISSUE THREAD

**Issue by Deshiba** [mickelus/tetra#26]
You can put both fortune and silk touch on a tetra pickaxe. When doing this the tool will apply the last enchantment put in.
![silk touch](https://user-images.githubusercontent.com/10565800/45687568-784e2d80-bb4f-11e8-9fad-fa0f2065ec22.png)
![fortune](https://user-images.githubusercontent.com/10565800/45687570-7be1b480-bb4f-11e8-9041-85b6c95375c2.png)

When you first put fortune and then silk touch on a Tetra tool, mining redstone or coal ore will give XP with silk touch.
![silk touch xp](https://user-images.githubusercontent.com/10565800/45687801-f7dbfc80-bb4f-11e8-8991-65ab17646493.png)

**Comment by mickelus** [comment]
If a tool has both silktouch and fortune then silktouch goes first if it's possible to silktouch the block. So in most cases it makes no sense for a player to apply both. But I still like the idea of players being able to apply them both.
The silk touch still dropping xp is a big issue, I've completely missed that and I'm not sure how to fix it yet :/.

**Comment by mickelus** [comment]
Figured it out. Fixed in 24fb62e007f44ecda9893ba81bf15127126cd77a, available once 0.17.1 gets approved.
