### ISSUE TITLE
Allow Hammers to modify themselves

### ISSUE THREAD

**Issue by aaronhowser1** [mickelus/tetra#260]
## Feature Request

**Feature description**
To make an Iron Hammer, you have to make two Wooden Mallets, use one to turn the other into a Stone Hammer (using SPECIFICALLY Diorite, no other type of stone, for some reason), then use the Stone Hammer to turn the other into an Iron Hammer

**Comment by mickelus** [comment]
There are related changes in 3.4.0, but I won't implement this suggestion.
