### ISSUE TITLE
Quiver auto latch doesn't work with tetra bows

### ISSUE THREAD

**Issue by TheZenNinja** [mickelus/tetra#262]
## Bug Report

**Observed Behaviour**
Having a belt with a quiver with the quick latch upgrade (both in tool belt slot and inventory) doesn't work with a tetra bow (gave a normal bow a leather string), it will draw the bow back but not fire anything on release and the UI that shows the arrow doesn't appear either. It works with a normal bow however. 

**Minimal setup needed to reproduce**
- Forge version: 1.16.4 - 35.1.7
- Tetra version: 3.3.1
- Tetra configuration: no change 
- Other mods:
Mgui - 3.1.3
Curios api - 1.16.4 - 4.0.2.1

**Steps to reproduce**
Equip a tool belt with a quiver and quick latch and use a modified tetra bow

**Comment by mickelus** [comment]
Fixed in 3.4.0!
