### ISSUE TITLE
Add all max tier tools to creative menu

### ISSUE THREAD

**Issue by aaronhowser1** [mickelus/tetra#264]
## Feature Request

**Feature description**
![image](https://user-images.githubusercontent.com/15698722/101463812-842a9380-3903-11eb-8e13-0ab3c63d096f.png)
This is amazing. But having to make a tier whatever cutting tool every time you're doing something in creative mode is annoying. It would be super nice if the max version of the other tools also was in the creative menu.

**Comment by mickelus** [comment]
Won't fix.
