### ISSUE TITLE
Add support for the /locate command

### ISSUE THREAD

**Issue by aaronhowser1** [mickelus/tetra#265]
## Feature Request

**Feature description**
Very useful tool for modpack developers, so we can make sure they work if some other mod might change world gen. 

**How it improves the player experience**
It would help modpack developers make sure they work if some other mod might world gen.

**Tetra synergies**
Makes it easier to find Tetra structures, so we can make sure they spawn.

**Comment by aaronhowser1** [comment]
Er, `/locate`, not `/locatebiome`

**Comment by mickelus** [comment]
This issue does not adhere to the template for feature requests.

**Comment by aaronhowser1** [comment]
The other two categories didn't really feel like they would apply, but I added them back

**Comment by mickelus** [comment]
I don't see the issue, you can quickly assert that they're generating by going into spectator mode.

**Comment by RedMoikle** [comment]
I can't tell if I am just unlucky and can't find any, or if another mod is preventing them from generating.
