### ISSUE TITLE
Claws can't break crafting tables.

### ISSUE THREAD

**Issue by Edulml** [mickelus/tetra#267]
## Bug Report

**Observed Behaviour**
When shift clicking a crafting table with a claw tool nothing happens.
 
**Expected Behaviour**
The claw will be able to pry the crafting table, the same way to can be done with the workstation and other wooden blocks.

**Minimal setup needed to reproduce**
- Forge version: 1.16.4   35.1.7
- Tetra version: 3.3.1
- Tetra configuration: Default

**Steps to reproduce**
Shift right click a crafting table with any claw tool.

**Comment by mickelus** [comment]
Fixed in 3.5.0!
