### ISSUE TITLE
Add astral sorcery enchant compat

### ISSUE THREAD

**Issue by torterra2234** [mickelus/tetra#268]
## Feature Request

**Feature description**
Add the ability to use astral sorcery enchants on tools, currently they are simply ignored when putting on a new enchanted book

**How it improves the player experience**
Allows for use of tetra tools with more enchantments, making them even more useful (and thereby desirable)

**Tetra synergies**
This is expected behaviour for most players

**Comment by mickelus** [comment]
I need id, name, description and which items it can be used on, for each enchantment.

**Comment by torterra2234** [comment]
Scorching Heat
key "astralsorcery:scorching_heat"
applied to shovels, picks, axes, hoes (techically anything that digs)

night vision (armour, for future reference owing to pinned issue)
key "astralsorcery:night_vision"
applied to helmets

i think that's right, not *perfectly* sure how to get the ID

**Comment by mickelus** [comment]
Fixed in 4.3.0.
