### ISSUE TITLE
The wiki on here for 1.16, no permission

### ISSUE THREAD

**Issue by Crayder** [mickelus/tetra#269]
i.e. getting "you do not have permission to update this wiki" at the following page when trying to view it:

https://github.com/mickelus/tetra/wiki/1.16-Configuration

**Comment by mickelus** [comment]
I don't understand what you're trying to get to with this issue. Do you want to help with documentation on how to configure tetra?

**Comment by Crayder** [comment]
It's all the 1.16 wiki articles, they just aren't accessible. Is this because they are under construction?

**Comment by Crayder** [comment]
If that's all this can be closed.
