### ISSUE TITLE
Enchanted Tetra tools can enchanted vanilla style

### ISSUE THREAD

**Issue by Deshiba** [mickelus/tetra#27]
An already enchanted Tetra tool can still be enchanted vanilla style even when the effect is already on there.

![tetra enchant](https://user-images.githubusercontent.com/10565800/45688062-ac761e00-bb50-11e8-9da5-242a08178278.png)

**Comment by mickelus** [comment]
When you're in creative mode it seems as if you can apply enchants to everything. As tetra enchantments aren't stored the same way as the vanilla ones they would probably stack as well. As it's only available in creative mode I'll keep it until we find something that actually breaks.

**Comment by Deshiba** [comment]
Makes sense. Serves me right not testing in survival.
