### ISSUE TITLE
arrow visual bug when shot by tetra bows

### ISSUE THREAD

**Issue by brandonmaster590** [mickelus/tetra#270]
## Bug Report

**Observed Behaviour**
when you fire a fully changed tetra bow the arrow some time fly to the side but it doesn't affect where it's gonna land like it still hit the target but the arrow flew to the side

**Expected Behaviour**
i expected it to flew straight like a normal arrow shot by a bow do
**Minimal setup needed to reproduce**

- Forge version: 1.16.3 - 34.1.42
- Tetra version: 3.3.1
- Tetra configuration: Default

**Steps to reproduce**
get a bow and put it into the tetra worktable then change the bow types to a longbow or any other, then get a target block or mobs then go around in a circle and keep shooting them with a fully changed tetra bow (I haven't tested it with the bowstring only, so I don't know if it affected it the same way as the bow types do)

**Comment by mickelus** [comment]
This happens for bows with high draw strength. I've looked at the projectile code but I can't figure out why it's happening.
 I spawn particles for the stabilizer based on the arrow trajectory which goes in the expected direction but the arrow still does not, so perhaps it's just rendering rather than it being incorrectly positioned on the client.

**Comment by hjpoe** [comment]
Hello! 

I was reporting an issue for another mod when I happened to see [this](https://github.com/noriokun4649/TorchBowMod/issues/6#issue-703934956) issue with a fix regarding item animation and bows. I don't know if the fix will help you, but I thought I would link it here for you in case it does.

:)

**Comment by Kool-Whipp** [comment]
Has there been any headway on this issue?

**Comment by mickelus** [comment]
Fixed in 3.9.0
