### ISSUE TITLE
Prying a banner with a claw resets it to a white banner.

### ISSUE THREAD

**Issue by Edulml** [mickelus/tetra#271]
**Observed Behaviour**
Prying a banner resets it to a white banner.

**Expected Behaviour**
Prying a banner should preserve all of it's NBT data.

**Minimal setup needed to reproduce**

- Forge version: 1.16.4 35.1.13
- Tetra version: 3.3.1
- Tetra configuration: Default

**Steps to reproduce**
Use a claw on a banner.

**Comment by mickelus** [comment]
Fixed in 3.4.0!
