### ISSUE TITLE
Axe instead of hammer?

### ISSUE THREAD

**Issue by Khorp** [mickelus/tetra#273]
So i dont know if this is a bug or just a weird feature but for the axe i need a axe instead of a hammer to upgrade or repair the axe.
i just seems werid when the other tools dont. just want to bring it up, please tell me if it is a intended feature or a bug, 
![billede](https://user-images.githubusercontent.com/71438210/102803499-9eab4500-43b8-11eb-86bf-08c062966c8d.png)

**Comment by superbrias** [comment]
do you think that, when working with wood, one would use a hammer? the tool feature takes into account the material type, and thus requires axes for wood-like, cutting(swords/daggers) for fabric-likes, and hammers for stone and metals. Hope this helps you wrap your head around it more.

**Comment by Khorp** [comment]
Just went in to test what you said. you are correct, when you work with wood it wants to an axe, and with stone its the hammer. Thank you for helping. 👍
