### ISSUE TITLE
Stonecutter can cut bedrock

### ISSUE THREAD

**Issue by reggiekage** [mickelus/tetra#274]
## Bug Report

**Observed Behaviour**
Stonecutter destroyed bedrock blocks

**Expected Behaviour**

Bedrock to be left behind when stonecutter destroys other blocks

**Minimal setup needed to reproduce**

- Forge version: 35.1.13
- Tetra version: 3.3.1
- Tetra configuration: base config of pack
- Other mods: Direwolf20 1.16.4 modpack V1.1.2

**Steps to reproduce**
Stand near bedrock and use stonecutter so the bedrock is in the path.

**Comment by mickelus** [comment]
Fixed in 3.4.0!
