### ISSUE TITLE
The Holosphere materials list goes off the screen if in certain GUI modes.

### ISSUE THREAD

**Issue by VallenFrostweaver** [mickelus/tetra#275]
Forge: 35.1.7
Minecraft: 1.16.4
Tetra: 3.3.1
Video GUI Scale setting on 3 or 4
The Holosphere materials list goes off the screen if in certain GUI modes.
![image](https://user-images.githubusercontent.com/13642054/102996288-bf8bab80-451a-11eb-8cc5-0d3c8d69ba5e.png)

**Comment by toruPuchuu** [comment]
On a 1920x1200 monitor this happens in Video GUI Scale setting 2-4

**Comment by Miner239** [comment]
You can scroll the list.

**Comment by mickelus** [comment]
I'm closing this, I've seen a few people miss that it's scrollable so there'll probably be some sort of visual indicator that it's possible in the future!
