### ISSUE TITLE
[Question] Ruins generation dependency

### ISSUE THREAD

**Issue by No3371** [mickelus/tetra#277]
In my modpack I can not find any ruins now, and I suspect it's BetterCaves changed the underground terrain so the ruins failed to spawn, so I'd like to know the condition for the ruin to spawn so maybe I can tweak it.

BTW, ruins are not listed in /locate, not sure if that's normal.

**Comment by No3371** [comment]
I configured the config of BetterCaves increase the spawn rate of vanilla cave (by default it set to 0), ruins are generated.
The issue will be left open just to let you know about this.

**Comment by No3371** [comment]
Ah, however the spawn rate still seems off, would like to know if there's something about the generation that you are willing to share 😅

**Comment by mickelus** [comment]
It's better if you post your questions on discord.

There's an issue that causes incorrectly registered worldgen features to disable worldgen features from other mods, it may be that another mod is causing them to not generate. It's probably not due to BetterCaves underground terrain.
