### ISSUE TITLE
DUPE BUG USING FTB ULTIMINE!!!

### ISSUE THREAD

**Issue by YTMrSnipa** [mickelus/tetra#280]
(I have reported this to the FTB Ultimine devs as well)
(https://github.com/FTBTeam/FTB-Ultimine/issues/41)

Watch how he's doing it:
https://drive.google.com/file/d/14nc96aGlfYcyIAJP6XxN_KWTH1H9geBK/view?usp=sharing

(He is spamming the "`" key which is the default for the FTB ultimine thing)

**Comment by mickelus** [comment]
Closing, this does not adhere to the template for a bug report (I assue that's what you're trying to do). Feel free to reopen the issue once it's updated.
