### ISSUE TITLE
Belt disappears if you try to grab something in it while holding it

### ISSUE THREAD

**Issue by serp-nt** [mickelus/tetra#282]
I was holding my work belt which had my hammer, shield, and I think shears in it. I also pressed b on accident while holding it, hovered over my shield to take it out and then it switched into the belt slot making my belt and its contents disappear.

I think making it so players can't press b and also shift+b while holding a belt should fix it, or maybe just not being a dunce like myself.

**Comment by mickelus** [comment]
Use the provided templates when creating issues.

This was fixed in 3.4.0.
