### ISSUE TITLE
Crossbow does not have loading animation

### ISSUE THREAD

**Issue by hjpoe** [mickelus/tetra#283]
## Bug Report

**Observed Behaviour**
When I draw my Tetra modified crossbow, it does not play the loading animation. 

The sounds also seem to be "off" compared to a vanilla unmodified crossbow, like one of the loading sounds isn't playing, and it might be quieter than the vanilla crossbow.

**Expected Behaviour**
I expect there to be a loading animation for my crossbow.

**Minimal setup needed to reproduce**
I could reproduce it with no other mods.
-Minecraft version: 1.16.3
- Forge version: 34.1.42
- Tetra version: 3.4.0
- Tetra configuration: I don't think I have one? I don't change anything.
- Other mods: mGui

**Steps to reproduce**
Make a Tetra modified crossbow and some arrows. Load the crossbow.

**Comment by mickelus** [comment]
Created a new issue for gathering bugs/suggestions/whatever for the crossbow while it's in "work in progress". Added your issue with the animation to that list. The changes to the sound volume is intended.
