### ISSUE TITLE
Botania compat request 

### ISSUE THREAD

**Issue by kohlth** [mickelus/tetra#284]
## Feature Request
Adding botania materials to tetra
**Feature description**
note: all botania metals/gems should have mana repairability, no clue on having the sockets give mana repair functionality too but sounds like a good enough bonus

manasteel (metal):
durability: 300
efficiency: 6.2
flex: 3.2
magi: 90
density: 3.9
hardness: 5.2
integ: 5:2
hammer lvl: 2
tlvl: 4
note: possible hammer material equal to iron level?
special effects: mana repair 

elementium (metal):
durability: 900
efficiency: 6.2
flex: 3.4
magi: 100
density: 4
hardness: 5.4
integ: 5:2
hammer lvl: 2
tlvl: 4
special effects: mana repair. (botania tool effects: pickaxe/shovel delete mined stone types and dirt and gravel, axe has behading chance, sword summons botania fairy/ increases its power)

terrasteel (metal):
durability: 2300
efficiency: 9
flex: 4
magi: 110
density: 2.9
hardness: 6
integ: 8:2
hammer lvl: 4
tlvl: 5
note: possible hammer material equal to netherite level
special effects: mana repair. (botania pickaxe and axe are special and cost runes and have very powerful effects, sword shoots a mana blast/beam when swung from a full swing)

**How it improves the player experience**
as botania is a mod used in my observation at minimum 50% of packs, having integration with this mod would greatly improve the player experience and in general modded synergy/play 

**Tetra synergies**
as botania is a mod with a more vanilla style of balance the materials while having some powerful or daresay op aspects (cheap repair with mana) most of the later game materials are balanced in a fashion that makes them almost or as hard to get than netherite but not as chance-based making it more fun and generally gives a better time spent for x reward than netherite

better summary: vanilla style balance mod could be used as an alternative way to invest time than jus the vanilla tetra path to netherite or better their tools with good bonuses  (the main synergy is alternative to netherite that won't flush your time and energy down the drain)

note: not yet done with botania materials but posting now as it's very late and I also want to know if I need to add any other info 

thank you for this wonder full mod (tetra) and have a good night!

**Comment by mickelus** [comment]
I've addes support for those materials (plus some more) in 3.5.0.

Not sure how to do the rest of the effects, those aren't in the API. Perhaps you can ask the botania team to add support for that! :)
