### ISSUE TITLE
[1.16.4] Thermal Cell Desync

### ISSUE THREAD

**Issue by ocram9** [mickelus/tetra#285]
## Bug Report

**Observed Behaviour**
When playing in multiplayer on a server (haven't tested LAN), the thermal cell placement desyncs on a forge hammer. We only tested this on the forge hammer, this might also affect other machines/interactions. This might also be related to #213 

**Expected Behaviour**
For all players to be able to see the thermal cell when placed.

**Minimal setup needed to reproduce**
- Forge version: 35.1.28
- Tetra version: 3.4.0
- Tetra configuration: https://gist.github.com/ocram9/e6b2cd48c7ea216cc991c563e369a695

**Steps to reproduce**
1. Player 1 puts a thermal cell in the forge hammer
2. Player 2 looks at the forge hammer (which looks empty) and right clicks
3. Player 2 gets the cell but player 1 still sees it in the forge hammer
4. Player 1 tries to take the thermal cell out and gets a ghost item

**Comment by mickelus** [comment]
Fixed in 3.5.0!
