### ISSUE TITLE
Item duplication with workbench

### ISSUE THREAD

**Issue by Jastyo** [mickelus/tetra#286]
## Bug Report

**Observed Behaviour**
It can duplicate any item or stacks.

**Expected Behaviour**
No duplication ;)

**Minimal setup needed to reproduce**

- Forge version: 35.1.13
- Tetra version: 3.3.1
- Other mods: TNP Limitless 3 Modpack version 1.8.2
- Seems like this is an issue with Tetra & Inventory Tweaks Renewed.

**Steps to reproduce**
- Create the Tetra workbench.
- Place an item into the slot.
- Press the grave key and it will duplicate item/items from your inventory.

**Comment by Gbergz** [comment]
I fixed this by blacklisting the Tetra workbench GUI, but yes it is an issue with the InvTweaks mod.

**Comment by mickelus** [comment]
Won't fix for now as invtweaks seem to provide a blacklist option.
