### ISSUE TITLE
Shift+clicking an item out of the belt stops the game from responding.

### ISSUE THREAD

**Issue by sorathenobody** [mickelus/tetra#29]
You can Shift+click items from the inventory into the belt just fine, but when you Shift+click on items that are already in the belt the game will freeze then stop responding. This happens with any belt slot/upgrade.
I only had JEI and Optifine installed along with Tetra.
Sadly, since the game isn't responding, it doesn't give me a crash report.

**Comment by mickelus** [comment]
It gets stuck in an infinite loop when there's no potion bag attached, fix will be available in 0.20.0. To fix this until then either put a potion bag in all of your toolbelts or poke me on discord and I'll pass you a half finished 0.20.0 jar.
