### ISSUE TITLE
Support for material from own mod

### ISSUE THREAD

**Issue by HarmanU** [mickelus/tetra#290]
Hi,

Is there a way i could add support for a material in my own mod?

Can I add a json file on my end and have that automatically picked up by this mod as a compatible material?

Thanks!

**Comment by mickelus** [comment]
Yep!

Here's an example on how to add custom effects https://github.com/mickelus/tetra-effect-example.
If you don't have any special effects for your materials then you only need some data, there are some examples on how to do that on discord and in some modpacks (like e6: https://github.com/NillerMedDild/Enigmatica6/tree/master/kubejs/data). I've started documentation for materials over here: https://gist.github.com/mickelus/6a290340b0cb59fa55725ab43b4fef05#materials.

Closing this, hop onto discord if you want some more help!

**Comment by HarmanU** [comment]
cool, thank you!
