### ISSUE TITLE
Quiver interchanges Regular & Spectral arrows on restock

### ISSUE THREAD

**Issue by KindarConrath** [mickelus/tetra#291]
## Bug Report

Possibly related to #289 

**Observed Behaviour**
Spectral Arrows & Vanilla arrows interchange in quiver when pressing "restock" hotkey

**Expected Behaviour**
with partial stack of arrows in quiver, after pressing restock key, arrows should fill their own stack. Should not interact with other itemstacks.

**Minimal setup needed to reproduce**

- Forge version: 35.1.29
- Tetra version: 3.4.0
- Tetra configuration: default
- Other mods: FTB GUI Library, FTB Essentials, Just Enough Items, mgui

**Steps to reproduce**
Craft belt with quiver
place 1 spectral arrow in quiver
shift-b to restock 64x regular arrows
end up with 64 spectral arrows & 1 regular arrow
(works reverse as well, turning spectral arrows in to regular arrows)

**Comment by mickelus** [comment]
Fixed in 3.5.0!
