### ISSUE TITLE
[1.16.4] - v3.5.0 causes a "Rendering Overlay" crash when Thatched is present

### ISSUE THREAD

**Issue by clootas** [mickelus/tetra#295]
## Bug Report

Crash log: https://pastebin.com/DSxPkE6m
latest.log: https://pastebin.com/V7Dhufs3

**Minimal setup needed to reproduce**
List the minimal set of mods and configuration changes required for the observed behaviour to occur:
- Forge version: 1.16.4 - 35.1.28
- Tetra version: v3.5.0
- Thatched v0.3

**Steps to reproduce**
Having [thatched](https://www.curseforge.com/minecraft/mc-mods/thatched/files/3157301) v0.3 installed causes a rendering crash after a long time in the loading screen. Doesn't happen when Thatched is disabled, and instead I get a mod loading error, same one that others have posted

**Comment by mickelus** [comment]
I'm unable to reproduce this with just tetra and thatched (+ mgui & decorative blocks, as those are required dependencies). Judging by the log you've got far more than those mods installed, perhaps there's some issue between thached and one of those. You should report this to the thatched issue tracker, as far as I can see tetra is not involved in the crash in any way.
