### ISSUE TITLE
[1.16.4] Internal server error

### ISSUE THREAD

**Issue by ocram9** [mickelus/tetra#296]
## Bug Report

**Observed Behaviour**
When I try to join my server I get kicked out with an "internal server error." Downgrading to tetra 3.4.0 fixes it.
Crash log (technically not a crash but the log is important): https://gist.github.com/ocram9/336016753365a47d6cf88814481ea007

**Expected Behaviour**
Being able to join my server.

**Minimal setup needed to reproduce**
- Forge version: 35.1.29
- Tetra version: 3.5.1
- Tetra configuration: https://gist.github.com/ocram9/179ac651a880dc9998a92f7ae120f2c6

**Steps to reproduce**
1. Start server with tetra 3.5.1
2. EDIT: Join a server
3. Take a Tetra item (like a hammer)
4. Get kicked with an "internal server error"

**Comment by mickelus** [comment]
Should be fixed for real in 3.5.2!
