### ISSUE TITLE
[1.16.4]client crash

### ISSUE THREAD

**Issue by EnterFor** [mickelus/tetra#297]
details：https://github.com/BloCamLimb/ModernUI/issues/36
debug.log:https://gist.github.com/EnterFor/71cbef596353d8d032f57dace29d089b

- Forge version: <35.1.28>
- Tetra version: <3.5.1>

**Comment by mickelus** [comment]
Closing this as the issue does not adhere to the template for bug reports, and the log you've provided does not include a crash. Feel free to reopen when you've updated the issue to adhere to the template and when you've dug up the correct log ;)

**Comment by EnterFor** [comment]
The crash report is in the details, I just didn't put it here...
