### ISSUE TITLE
Error in localization file? (Variable names showing of statistics on Tetra tools.)

### ISSUE THREAD

**Issue by Rainemakerx** [mickelus/tetra#299]
## Bug Report

**Observed Behaviour**
Titles of various statistics are bugged, showing the name of the variable rather than the actual string.

IE: "tetra.stats.draw_strength" instead of "Draw Strength"

Crash log: 

**Expected Behaviour**
The variable should be nicely hidden behind its string value.

**Minimal setup needed to reproduce**

- Forge version: 1.16.4-35.1.13
- Tetra version: 1.16.4-3.5.2
- Tetra configuration: Stock
- Other mods: Too many to list here, but the behavior was not present before the only change of upgrading to 3.5.2

**Steps to reproduce**
Place any item on a forged workbench, or a tetra worktable and view the stats.

**Additional info**
I'm gonna try upgrading to forge 35.1.28 just in case it's a forge issue somehow, I'll keep you posted if that fixes the issue.
There's no error in the client or server logs when the issue takes place.

Please don't tear your hair out over this one Mickelus, I really appreciate the hard work you do, and would love to donate to a patreon if you have one!

**Comment by Rainemakerx** [comment]
Double posting because I couldn't find an edit button, but there's no crash associated with this issue.

**Comment by Rainemakerx** [comment]
Upgrading to Forge 35.1.28 yielded no fix.

**Comment by mickelus** [comment]
No idea what's going on here 😅 

![image](https://user-images.githubusercontent.com/224698/103578726-625b0700-4ed7-11eb-8414-2021a4b4ac4c.png)
You mean the stats over here, right?

Does it fix itself if you downgrade to your previous version?

I've got a patreon over here: https://www.patreon.com/mickelus! I would happily accept your support! ^^

**Comment by Rainemakerx** [comment]
Yeah, it was working fine in the previous version 3.4.0. Here's what I get 
![2021-01-04_16 50 44](https://user-images.githubusercontent.com/1348431/103583091-214dfd00-4ead-11eb-8073-785b0daaa2ff.png)

**Comment by mickelus** [comment]
Found it! Should be fixed in 3.5.3!
