### ISSUE TITLE
[SMP Glitch] Table not usable

### ISSUE THREAD

**Issue by Burgersim** [mickelus/tetra#3]
Hi there, I tried your mod before in a Single Player world with other mods and it seemed to work just fine, but now I installed in on my Server too and when I try to put sthg into thhe upgrade table it seems to appear and reappear, if i shift click it, I can put it inside, and shhift click the material to upgrade, it even shows the new tool, but then when you want to take it out, it just is the old tool again (I tried it with a wooden sword). Also when I try to destroy the table by hand it goes away for a split second then reappears again, except if I do it in creative mode. And it seems that if I made a table at some position and place a normal crafting table there again, it transforms into the upgrade table again.

Update: every block I try to place where the table was before transforms into the table xD

Sorry for the lots of text, I really like your mod and the idea behind it and the simplicity, and especially the design ^^*

Another maybe interesting thing, I was able to put a Pickaxe made from Base Metals Materials into the upgrade table, it identified it as a wooden pick, but I thought i'd mention it because maybe it helps for compatibility ^^*

**Comment by mickelus** [comment]
That's really bad! I've forgotten to test the last few releases in SMP and I've made some changes to how the table applies upgrades.

Happy to hear that you like it!

Regarding the base metals pickaxe, it probably extends the vanilla pickaxe so tetra picks it up but cannot recognize the material so it uses wood as a fall back material :)

**Comment by mickelus** [comment]
This should be fixed in 0.7.1, feel free to reopen the issue if the problem persists!
