### ISSUE TITLE
[0.19.1] Not compatible with quark enchants

### ISSUE THREAD

**Issue by Alaberti** [mickelus/tetra#30]
I had a player on my server try to use a Quark enchant (specifically an unbreaking 4 book) and it didn't apply to the weapon and he lost the book. Could you either add compatibility with quark enchants or prevent them from being consumed if they don't work? Thank you.

**Comment by Alaberti** [comment]
That'll tide us over, thanks!

**Comment by mickelus** [comment]
Added additional levels and fixed invalid material consumption issue in 0.20.1!
