### ISSUE TITLE
Which mods do work with this mod?

### ISSUE THREAD

**Issue by Begnom** [mickelus/tetra#300]
i saw on the main page on curseforge, that the mod supports:
"maple
cherry
baobab
greatwood
treated wood
ironwood
tin
silver
nickel
lead
bronze
electrum
steel
ironwood
amber"

these tags. Im not a "proffesional" mod pack maker so i don't know if any mod that adds these types of ores work with Tetra fine or not.

**Comment by Rainemakerx** [comment]
So I think I can field this one, those are item tags, any item with those tags will be usable with the mod from my understanding. 

    Basically if a mod adds bronze as an available ingot, as long as it has the proper forge tag in its code you can use a bronze ingot from said mod with Tetra. Most of those tags that I see are from different mods, the lead alone is from about 3 different mods off the top of my head in 1.16.4, who knows how many from 1.12.2. 


     The crucial thing is that Tetra itself is what determines the value of these materials for balancing in the tools from Tetra. So just because Immersive Engineering adds a material, doesn't mean that the same material from Tinker's Construct (Using 1.12.2 as an example here) would have different stats in Tetra.

**Comment by Begnom** [comment]
Thanks for the help! I'll try to find some mods that add these kind of ores. Just a quick question, if i for example find a mod that adds nickel but the tag isn't nickel but for example nickel1 or anything like that, can i change it to something else so the mod counts it as a ore that i can use?

**Comment by Rainemakerx** [comment]
Erm, the easiest way to do that would be to convert that metal to another metal which does use the tag, for example if you have IceAndFire silver, (which doesn't use the silver forge tag), you'd want to use craft tweaker to make a recipe which converts that silver to silver from another mod which DOES use the forge tag. Alternatively you could use datapacks but that assumes you're on 1.16.4 or some other version which supports those.

**Comment by mickelus** [comment]
I've updated the list on curseforge, here's all modded materials that have support out of the box:

bone
* dragon_bone 
* wither_bone 

fibre
* hemp 
* mana_string 

gem
* agate 
* amethyst 
* certus_quartz 
* citrine 
* ruby 
* sapphire 
* serendibite 

metal
* bronze 
* copper 
* electrum 
* elementium 
* infused_iron 
* lead 
* manasteel 
* nickel 
* osmium 
* silver 
* sky 
* steel 
* terrasteel 
* tin 

wood
* ancient_wood 
* baobab 
* cherry 
* dreamwood 
* livingwood 
* maple 
* treated_wood 

You can also use datapacks to add more materials :)
Closing!
