### ISSUE TITLE
Gui bug

### ISSUE THREAD

**Issue by castilio20** [mickelus/tetra#301]
![2021-01-04_22 52 44](https://user-images.githubusercontent.com/76228548/103578866-29497500-4e8c-11eb-97c6-6ec62dd69c2c.png)
i dont think i need to say more
overlapping

**Comment by mickelus** [comment]
You still need to use the template for bug reports. Duplicate of #229, closing.

**Comment by castilio20** [comment]
sorry about that  but will you fix the bug?
