### ISSUE TITLE
Im not able to Modify my tools

### ISSUE THREAD

**Issue by Begnom** [mickelus/tetra#302]
I have a stone Greataxe, and i wanted to upgreade it to Iron greataxe, but i can't. I have a tier 2 hammer and the hammer icon is green so i should be able to craft it, but the "Craft" button is grayed out. I can turn the Greataxe into anything from stone but not iron. I tried to make a new Iron Axe and then modifying it but it also doesn't work. Is there something that im missing?

**Comment by mickelus** [comment]
Use discord to ask for help, github issues is for feature requests and bug reports.
