### ISSUE TITLE
New Socket Item: Amalgam (or Stasis?) Crystal? Focus?

### ISSUE THREAD

**Issue by Deightine** [mickelus/tetra#303]
## Feature Request

**Feature description**
Introduce a new ultra rare Tetra component found in complexes that can be Socketed into a tool. It could be gemstone, crystal, or something more technological. It is able to be socketed like a gem (diamond, emerald, pristines, etc), and its effect is to allow carrying honing benefits and enchantments from one tier of material to the next. But in the process, it should be destroyed. Right now some tools and weapons don't have sockets, but it seems like the most appropriate component slot for it.

Ex. You have an Iron Pickaxe, you have honed it heavily and want to keep its traits/enchantments, but you want to upgrade the material to diamond or mana steel (if you have it). But doing so throws away all of the past honing (which it should, it's sensible). So you override your current binding/socket with [new component]. The next time you change out a head, component, etc, on the tetra tool, the honing and enchantments survive the transition but the socket is now empty. There should probably be a sound effect like a crystal shattering or a hot hissing noise, to give feedback that it worked.

Caveat: It needs to be able to survive repairs, but not the upgrades, in case its used before its understood. The socket items tend to be kind of mysterious right now anyway, so trial and error may be the best way to understand this one as well.

**How it improves the player experience**
Players intuitively feel the pinch of loss in anything they have 'built up'. It's an effect of 'sunk cost'... "Aw, man, but I put so much [X] into that, and I lost it... Now I have to start over." I think this is actually a good element in Tetra normally. However, no side-effect should be a punishment, if it can be an obstacle to overcome instead.

A player would hoard this new component once they knew how it worked and it would further drive their urge to seek out new underground complexes, forcing them to explore. This extends the life of their play while using Tetra.

**Tetra synergies**
- It appears to integrate with Tetra's current vision (foraging ancient ruins for components) and exists entirely within the envelope of how the items are already being created.
- Induces prolonged play using Tetra, keeping the player base active for longer.
- Will help when integrating content from other mods (like Botania), because it gives players a sense of continuity.

**Comment by mickelus** [comment]
I want to add some mechanic for keeping enchantments on an item as you replace parts, but I'd like that to be something external than having it be a part of the item. Considered adding a scroll for this in the schematics/scroll update but it required too many technical changes to make the cut, so I pushed it for the future. Would like it to be some block that you place on, or near, the workbench, probably with a high chance of causing destabilization effects that can be countered by placing other items (like skulls or 1.17 candles) in symmetrical patterns around the workbench.

Keeping honing progressions will be added with the insight system (there's some info about that on discord), but it won't stay on the item when you replace part.

Closing this as it's rather different from the plan, you'll have to keep track of release notes to see when it's added :P
