### ISSUE TITLE
Integrate Immersive Engineering Materials Fully

### ISSUE THREAD

**Issue by Deightine** [mickelus/tetra#304]
## Feature Request

**Feature description**
Right now, Tetra incorporates Copper, Electrum, Nickel, Silver, and Steel by virtue of the Ore Dictionary, but Immersive Engineering has a number of other materials which could also be helpful. I suggest incorporating the remainder, rounding out the 'all tech' side of mod compatibility to pair up with the recent Botania materials additions.

**New Materials:**

1. Aluminum (processed ore)
- Information: Used as a thermal insulator in IE. Aluminum reflects heat and insulates areas around high voltage, which is why IE uses Aluminum in its HV Wire relays, which are integrated into transformers.
- Idea: Aluminum could lower rate of durability loss, rather than increasing durability numerically. Something like a 0.8x durability consumption rate. It makes for a 'stronger' tool without necessarily making it sharper or harder.
2. Uranium (processed ore)
- Information: Used as a source of radioactive heat in IE (for thermal generation).
- Idea: Uranium ingots would make a good inlay material for sword and shield components and it could do something like add a short burn and lingering poison affect on attacks.
3. Constantin (alloy of copper and nickel)
- Information: Used as a heat conductor in IE. It allows for thermo generation, adds the oomph to the armor piercing bullets, and is sourced for the railgun heatsink.
- Idea: This is a strong candidate for a Burn material effect, but rather than 'adds burning', it would be better if it added 'weakness to fire' when it hit an enemy (as a sword), and soak up fire when the wielder is burned (on shield). If you were willing to integrate IE slightly more, it could also generate small amounts of Flux (which would transfer to baubles/curios in the inventory).
4. HOP Graphite (compressed coal coke dust <- coal coke <- coal ore)
- Information: HOP (Highly oriented pyrolytic graphite) Graphite is a 'man made' graphite, and upgrade from 'flint' essentially. It requires significant processing and is used in IE to make graphite rods for the Arc Furnace. But along the way, it becomes an Ingot.
- Idea: This is an incredibly sharp but brittle substance and makes a good candidate for a 'second tier' version of the Flint material. It should have innate penetration, high damage, but have a low-middle base durability, with the Arrested Mod.

**How it improves the player experience**
This would add more opportunities for fun mix and match of materials and create more synergy between mods. Immersive Engineering is a great 'technological throwback' from Tetra (implying Tetra's culture collapsed and then new attempts to recover the same old ground happen in IE).

**Tetra synergies**
Tetra can always use more materials, provided they add something tangible and clearly beneficial, rather than rechewing old mod ideas. These materials are essentially out there in the open waiting to be integrated and they're a chance to add more spice to Tetra.

**Comment by mickelus** [comment]
I appreciate the work you've put into this, but I don't think it makes sense to craft tool heads out of any those materials. Perhaps you could convince the authors of tetranomicon or tetrapak (syric or noobulus) to hook you up with something like this!
