### ISSUE TITLE
Removing Enchantments with Evilcraft

### ISSUE THREAD

**Issue by rxwsh** [mickelus/tetra#305]
## Bug Report

**Observed Behaviour**
When putting tools with enchantments on the modules in the purifier from Evilcraft to remove the enchantments the enchantment is simply copied and the tool still has the enchantment.

**Expected Behaviour**
The tool should lose the enchantments that get put onto the book bei the purifier.

**Minimal setup needed to reproduce**
- Forge version: 1.16.4 - 35.1.28
- Tetra version: 3.5.1
- Tetra configuration: no configs changed after creating and entering the world
- Other mods: Evilcraft 1.16.3-1.0.4

**Steps to reproduce**
Put enchantment on tool module
place enchanted tool into the purifier
place a blook into the purifier
put 3 buckets of blood(with the blood extractor) in the purifier
When the process is finished the blook turns into an enchanted book and the blood got used up.
take both the book and the tool out of the purifier.

You said this was on the Evilcraft dev to fix, and they came to this conclusion:
https://github.com/CyclopsMC/EvilCraft/issues/826#issuecomment-755582646

**Comment by mickelus** [comment]
> You said this was on the Evilcraft dev to fix
I said it has to be fixed on their side, as I can't hook into how they remove enchantments. There's a few ways this could be done, but completely blacklisting tetra items is probably the easiest. 

Blocking you here as well as I want nothing to do with you.

**Comment by rubensworks** [comment]
EvilCraft developer here;
Can we have a collaborative attempt to resolve this issue?
No need to start blocking people 😉

Clearly there's some cross-mod conflict going on somewhere, as each mod works fine on their own.
[This is our class](https://github.com/CyclopsMC/EvilCraft/blob/172cc5cd07a753af252d0b93df58b1fdefa62814/src/main/java/org/cyclops/evilcraft/tileentity/tickaction/purifier/DisenchantPurifyAction.java) taking care of echantment handling. Perhaps you can identify parts in here that may be incompatible with this mod?

**Comment by mickelus** [comment]
Sure! What do you propose?

I store information about which enchantments a modular item has per slot, and then I rebuild the enchantments nbt list when modules or modifiers change for an item.

You remove items from the enchantments nbt list, which I then re-populate when a player modifies the item, at which point the enchantment is back on the item.

**Comment by rubensworks** [comment]
Oh, now I fully understand the problem. So the tools of this mod are not really enchanted through vanilla mechanisms.
In this case, it makes sense to blacklist all tools from this mod in EvilCraft's purifier, I'll look into that.
Thanks for the clarification! :-)
