### ISSUE TITLE
Regarding Reach

### ISSUE THREAD

**Issue by Fokson** [mickelus/tetra#307]
I've read a couple of issues on here regarding reach, but they don't fit my particular issue so I'll write a quick one of my own.

I've made two weapons; a sword with a grip loop and heavy blade and a spear with a long handle.  Both of them say they have a reach of 6.5 blocks.

First, I'd like to start with a note of the numbers being inaccurate.  The table stats the basic reach of a weapon is 5 meters, which is wrong - it's 3.5.  When a grip loop is added, it says it'll increase the reach by 1.5 meters ( to 6.5 ), but it instead increases it from 3.5 -> ~10, which is an insane 6.5 meter boost!

Now, the sword.  The reach mechanic partially works.  The raytrace doesn't reach the mob ( the attack indicator doesn't light up ) but the cleave/sweep mechanic still affects them, and I'm of the opinion that it's obscenely busted!  You swing the sword and it hits everything within _ten_ meters of you, regardless of you even looked at an enemy, _sometimes even hitting things behind you_.  I did bother to measure the length to be 10 blocks, and this becomes a huge problem when playing cooperatively with a friend.  It was a great laugh for us the first couple of times, but it started to get upsetting that we kept accidentally hitting each other.  I think that the reach could be extended by less for the grip loop in particular, and the cleave certainly shouldn't be hitting everything in a 10 meter radius from it ( especially not behind the user ).

As for the spear?  No effect.  The long handle doesn't seem to work for mobs, though blocks can still be targeted behind a mob you're looking at ( you can't hit them though, presumably since the raytrace is intercepted by the mob ).  I would argue that a spear's reach should be a lot longer than a sword with a grip loop, so assuming all of the provided numbers were accurate, I'd personally have a grip loop increase range by 1 meter ( 3.5 -> 4.5 ), and a spear by default have a 0.5 meter reach bonus with a long handle add 1.5 more to that ( 3.5 -> 4 -> 5.5 ), perhaps even allowing the spear to hit multiple targets in a line.  As it is now, even without the bugs, spears are useless in favor of a grip-looped sword.

If at all possible, I'd also suggest a visible cone on the ground acting as a sort of indication of what's in range of your heavy blade's sweep attack, so as to help a user stay their hand if an allied player is in the way.  This would also be useful for a spear, if you chose to implement the previous suggestion.

Anyway, that's all I have to report.  Thanks for your work on this mod, it's been very fun so far =)

**Comment by mickelus** [comment]
Don't know if this is supposed to be a feature request or a bug report, but it's use the template for neither of them. If it's neither it doesn't belong in the issue tracker.

Minecraft caps reach at 3 blocks when hitting entities.

**Comment by Fokson** [comment]
It shouldn't be too difficult to understand that it's a bug report from the context of the message, even despite the addition of a couple of suggestions on how it could be fixed.  If you refuse to acknowledge the issue unless it's formatted to your liking, then here you go.  Since I've already detailed the issue fully above, I'll give a more concise version here.

## Bug Report

**Observed Behaviour**
Inaccurate ranges on tools and weapons, especially where the heavy blade is concerned.

**Expected Behaviour**
Accurate ranges on tools and weapons, especially where the heavy blade is concerned.

**Minimal setup needed to reproduce**
1. Create a tool such as a heavy blade with a grip loop, 
2. Observe the range that the table states it will have,
3. Attempt to use it,
4. See that it does not perform as stated.

- Forge version: 
- Tetra version: 
- Tetra configuration: 
- Other mods: 

**Steps to reproduce**
As above.

.

There ya go. Now "it's use" the template for one of them.
