### ISSUE TITLE
navigation bar in holosphere disappearing

### ISSUE THREAD

**Issue by janDigeser** [mickelus/tetra#308]
## Bug Report

**Observed Behaviour**
The navigation bar in the holosphere disappears when clicking on "Materials" on the material overview, making it impossible to navigate to the other sections. This bug is global until game client is restarted. 

**Expected Behaviour**
No change of the bar. (The other sections in the craft menu don't produce this bug)

**Minimal setup needed to reproduce**

- Forge version: 1.16.4-forge-35.1.15
- Tetra version: 1.16.4-3.4.0
- Tetra configuration: default

**Steps to reproduce**

1. Open Holosphere
2. Goto "Craft > Materials"
3. Click on "*Materials*" in nav bar

https://user-images.githubusercontent.com/22981726/103947689-cdefdf00-5138-11eb-914f-d4cc0200c9a2.mp4

**Comment by cranphin** [comment]
Ran into the same issue here,  stuck now, help :D

**Comment by Daovala** [comment]
Current work around I found until this gets fixed after having the issue myself; pressing **Q** allows you to go back a menu

**Comment by mickelus** [comment]
Ah, fixed this a long time ago :D
