### ISSUE TITLE
Manasteel and Elementium Harvest levels are too low.

### ISSUE THREAD

**Issue by The-Arcanian** [mickelus/tetra#309]
## Bug Report

**Observed Behaviour**
Terta pickaxes with either Double-headed Manasteel or double-headed Elementium have a harvest level of 2 while Botania's Manasteel and Elementium pickaxes have harvest levels of 3.

**Expected Behaviour**
Tetra pickaxes to have the same harvest level as their non-tetra equivalents.

**Minimal setup needed to reproduce**
- Forge version: 35.1.36
- Tetra version: 3.5.3
- Other mods: Botania 1.16.4-410

**Steps to reproduce**
1. Create a world.
2. Spawn in a harvest level 3 block (IE. obsidian).
3. Create a tetra pickaxe with Double-headed Manasteel or double-headed Elementium. (Easy way is to add a binding to a Botania Pick in a workbench.)
4. Try to break harvest level 3 block in survival.

**Comment by mickelus** [comment]
Closing as this issues does not adhere to the template for bug reports, feel free to reopen once it's updated to fit the template.

**Comment by The-Arcanian** [comment]
Updated. Sorry, the template somehow did not show up when I was submitting the report.

**Comment by The-Arcanian** [comment]
@mickelus Because you closed this issue I am unable to reopen it.

**Comment by mickelus** [comment]
Nice!

**Comment by mickelus** [comment]
Fixed this in 3.6.0!
