### ISSUE TITLE
Duplicating Some Blocks

### ISSUE THREAD

**Issue by TickingTimebomb1** [mickelus/tetra#31]
Breaking a Embers Rekindled Mixer or Centrifuge gives you two instead of the normal 1. I noticed this with Abyssalcraft too but Abyssal items keep stored data and it seems the pick doesnt like meta data? It creates one with the stored data and one without thus creating 2 of the item.

**Comment by mickelus** [comment]
Can you provide more information about the tool you're using? (hover the item while holding shift and taking a screenshot would suffice)

**Comment by TickingTimebomb1** [comment]
![2018-11-27_12 19 19](https://user-images.githubusercontent.com/45340797/49099232-ec3b3f00-f23e-11e8-8947-4391d4825825.png)

**Comment by mickelus** [comment]
This was a bit tricky to figure out, but it's fixed! This fix will also be released with 0.20.0, I should really step up my branching game...
It's the fortune effect that cause this issue for some modded blocks which handle drops on their own.
