### ISSUE TITLE
Repairing a tool with mana resets the block break progress

### ISSUE THREAD

**Issue by LeoBeliik** [mickelus/tetra#310]
## Bug Report

**Observed Behaviour**
When a tool is repaired with mana whilst breaking a block, the breaking progress gets restarted.

**Expected Behaviour**
Tools shouldn't reset the block break progress when being repaired.

**Minimal setup needed to reproduce**

- Forge version: 1.16.4-35.1.28
- Tetra version: 3.5.3
- Tetra configuration: default
- Other mods:
- Botania version: 410

**Steps to reproduce**
- Make a pickaxe with botania components
- Have a mana tablet with mana in your inventory
- Mine a few blocks

I use obsidian as the example because is easy to show the problem, but this happens with any block
https://imgur.com/1f7g26Y

**Comment by mickelus** [comment]
Fixed in 5.3.1.
