### ISSUE TITLE
Request: The Ability to Rename Items

### ISSUE THREAD

**Issue by Crazydude323** [mickelus/tetra#311]
## Feature Request

**Feature description**
A way to name items you've made using the workbench, either in the workbench itself, or through another block.

**How it improves the player experience**
Some people, myself included, get rather attached to their tools. I've had my pickaxe for a very long time, constantly upgrading it rather than making a new one. It'd be nice to give it a name. Alternatively, some people forge really, really powerful weapons through a combination of Tetra and enchanting. Such powerful weapons deserve names, in some people's eyes.

Yes, you can rename it through a name tag, but those aren't always the easiest to come by, and some people have LOTS of tools they want to name.

**Tetra synergies**
Tetra is all about customization. You can customize practically anything about your weapon. ...except for the name, it seems. It would complement the customization already present, without dramatically changing anything.

**Comment by mickelus** [comment]
You can rename your items in an anvil without a tag.

**Comment by Crazydude323** [comment]
Well, now I feel incredibly dumb. Sorry about that!
