### ISSUE TITLE
Diamond levels seems like they could use adjusting?

### ISSUE THREAD

**Issue by JustJinxed** [mickelus/tetra#312]
## Feature Request

**Feature description**
For some odd reason, the damage for diamond is set at 6, whereas vanilla Minecraft is set at 7, and settling doesn't seem to raise the damage enough to make it to 7 even with a basic sword. What purpose does the mod serve when it comes to weapons when the damage scale is lower than vanilla when creating a "basic blade"? Might I suggest making this 7 like vanilla at least? 

**How it improves the player experience**
Other modifications make up for that damage loss by having sweeping, serated or utility effect on plans/vines/webs. But the Basic blade is a detriment. Boosting this to vanilla level would at least encourage people to utilize the weapons from this mod more often.

**Tetra synergies**
It's not really for me to say what aligns with your ultimate goals for mod. It's quite possible I'm missing something here, and there's some way to get more damage out of these weapons short of enchanting them?

**Comment by mickelus** [comment]
Tetra diamond swords already do 7 damage per hit.
