### ISSUE TITLE
Add more material options for hammers from other mods

### ISSUE THREAD

**Issue by kohlth** [mickelus/tetra#313]
## Feature Request

**Feature description**
The addition of more hammer matrials from other mots like botania to take advantage of material traits and allow more options than the netherite grind for materials like terrasteel

**How it improves the player experience**
Allows more modded synergy and allows alternative paths to teir 6 hammers

**Tetra synergies**
Adds upon a already existing feature and with some limitations of hammer materials can still be balanced in terms of tetra / its vanilla style

**Comment by mickelus** [comment]
If you can provide specific suggestions that provide interesting progression paths I can take it into consideration

**Comment by mickelus** [comment]
Closing since this has been in need of an update for a couple of months.
