### ISSUE TITLE
Add metal scrap as a material for bolt repairing

### ISSUE THREAD

**Issue by UzielSilva** [mickelus/tetra#315]
## Feature Request

**Feature description**
I think it would be great to use metal scraps when due to the repair cycle you need to replace a bolt.

**How it improves the player experience**
It's kinda rare to find enough bolts to be repairing them every time the repair cycle of a tool goes to the bolt, but after raiding some forges, you have a lot of metal scraps to use. Maybe you can add them in order to repair the bolt. (Sorry if my english is not so good).

**Tetra synergies**
Actually the earthpiercer work in that way, you can repair it with metal scraps, so I think it could be intuitive to also repair bolts with that.

**Comment by mickelus** [comment]
Thought I had added that already, but it seems like it's only for the bow modules 😅 . Will fix!

**Comment by mickelus** [comment]
Fixed in 3.7.0.
