### ISSUE TITLE
[Request] Option of repair scaling

### ISSUE THREAD

**Issue by No3371** [mickelus/tetra#317]
## Feature Request

**Feature description**
I'd like to have a way to balance the maintenance cost of tetra equipments in modpacks.
It seems like the current repairing is fixed to full repair with module-predefined cost. I suggest a int multiplier value of repair cost or a float multiplier value of repair result value.

**How it improves the player experience**
Balance for modpacks.
Tetra weapons are essentially better and customizable non-tetra weapons, but it's cheaper to repair. In my modpack repair cost is modified to be rather expensive, players have to concentrate their resource to really valuable equipments (which could be overwhelming powerful thanks to a lot of enchantments addition and higher level cap).
The repair cost inconsistency is there and there's no way to balance it atm.

**Tetra synergies**
A customizable scale provides no synergy, it just provide at least one way to directly balance tetra in all kinds of modpacks.

**Comment by mickelus** [comment]
Not sure if I follow, does "repair cost" refer to how many items are required to repair the item?

**Comment by No3371** [comment]
Yes, I read that the cost is taken from modules, so I thought the easiest solution is multiplying the value.

**Comment by mickelus** [comment]
I don't think it makes sense that it would require less materials to craft the module than to repair it. Magic capacity affects the xp cost of a repair, yes.

Still don't understand what you're requesting :)

**Comment by No3371** [comment]
> I don't think it makes sense that it would require less materials to craft the module than to repair it.
Conceptually and for material-based design of Tetra, no.

But for gameplay, in modded games, Tetra allows repairing very op equipments with unscaling cost, while we can balance it with mods that control repairng cost used by anvils, there's no way to control Tetra repairing cost.

I'd rather to fork it myself like I always do with up-to-date opensource mods, because I can see it could be conflicting with how you'd like to present Tetra. Any way, It's just a request for a config (or anyway) to adjust how costly to maintain/have a tetra equipment., if possible.

**Comment by mickelus** [comment]
I still don't see the problem. Closing.
