### ISSUE TITLE
[1.16.4] Crash when placing Forge Hammer next to another Forge Hammer

### ISSUE THREAD

**Issue by NillerMedDild** [mickelus/tetra#318]
## Bug Report

Original issue: https://github.com/NillerMedDild/Enigmatica6/issues/916

**Observed Behaviour**
 Placing a Tetra Forge Hammer on another Forge Hammer crashes/freezes the game.

[Log](https://gitlab.com/-/snippets/2062024)

**Expected Behaviour**
For the block to be placed, and then.. nothing I guess?

**Minimal setup needed to reproduce**

- Forge version: 1.16.4-35.1.36
- Tetra version: 1.16.4-3.5.3
- Tetra configuration: Shouldn't really matter, will link if asked :)
- Other mods:

**Steps to reproduce**
- Place Forge Hammer
- Place Forge Hammer next to it

**Comment by mickelus** [comment]
Fixed this in 3.6.0!
