### ISSUE TITLE
[1.16.4] Hammers can't harvest forged blocks

### ISSUE THREAD

**Issue by SonOfDiablo** [mickelus/tetra#319]
## Bug Report

**Observed Behaviour**

The Tetra hammers doesn't seem to be able to harvest the forged blocks (Forged Wall, Platform, Pillar, etc).
No items are returned when harvested.

According to TOP (The One Probe) the blocks are to be harvested with a hammer.
![image](https://user-images.githubusercontent.com/9123250/104853728-0a72c600-5903-11eb-8ded-92594f6c0754.png)

I have tried an Iron Hammer (two Hammer heads) and an Iron Claw Hammer (one hammer head and a claw head).

And I'm playing the modpack [Enigmatica 6](https://www.curseforge.com/minecraft/modpacks/enigmatica6)

**Expected Behaviour**
Expect the hammer to be able to harvest these blocks. (as in return an item)

**Minimal setup needed to reproduce**

- Forge version: 35.1.37
- Tetra version: 3.5.3
- Tetra configuration: 
- Other mods: [Enigmatica 6 Mod list](https://www.curseforge.com/minecraft/modpacks/enigmatica6/relations/dependencies)

**Steps to reproduce**
Try to break a Forged block with a hammer.

**Comment by Karthas077** [comment]
Supposedly you need a double netherite hammer to harvest forge blocks.

**Comment by mickelus** [comment]
You do indeed need a double headed netherite hammer. Closing.
