### ISSUE TITLE
The Insight enchant from Ensorcellation shouldn't be able to apply to handles or hilts from Tetra.

### ISSUE THREAD

**Issue by Vaelzan** [mickelus/tetra#322]
## Bug Report

**Observed Behaviour**
The Insight enchantment from the Ensorcellation mod can be applied to Tetra tool handles, while normally it can only be applied as a helmet enchant.

**Expected Behaviour**
The Insight enchantment shouldn't apply to anything in Tetra at all, unless Tetra adds modular armour in the future. :)

**Minimal setup needed to reproduce**
- Forge version: 1.16.4-35.1.37
- Tetra version: 1.16.4-3.5.3
- Tetra configuration: Default config files, custom data pack (found here: https://github.com/ValhelsiaTeam/Valhelsia/tree/1.16/openloader/data/Valhelsia%203%20-%20Tetra%20%5Bdata%5D)
- Other mods: Ensorcellation + CoFH Core are the minimum required to reproduce, but this was in Valhelsia 3 3.1.5.

**Steps to reproduce**
Obtain an Insight Enchanted Book from Ensorcellation, and a few experience levels.
Apply to Tetra Handle or Hilt via the Workbench.

**Comment by mickelus** [comment]
Fixed this in 3.6.0!
