### ISSUE TITLE
Compatibility/Integration with Spartan Weapons/Spartan Shields?

### ISSUE THREAD

**Issue by Corvus20** [mickelus/tetra#324]
## Feature Request

**Feature description**
Integration with Spartan Weapons (for example: different rapier guards, greatsword blade types, mace spikes, etc.) and spartan shields (additional shield types, such as bucklers, heaters, kite shields, etc.)

**How it improves the player experience**
The ability to add tetra's deep customization/upgrade system to the extensive selection spartan weapons and shields could double the depth of this mod from olympic swimming pool to mariana trench in terms of things you could tweak/customize.

**Tetra synergies**
Tetra already expands on customizing vanilla weapons, and adds more depth to them, so adding this mechanic to spartan weapons and shields would only allow for players to customize and create their ideal weapons to a far greater extent.

**Comment by mickelus** [comment]
That's a lot of work which I'd rather do on something else. Perhaps you could ask the developers of spartan weapons/shields, if they're interested I can show them how.
