### ISSUE TITLE
[Feature Request] Improving Accuracy and Optimizing the Holosphere + Tetra's Starting Achievements

### ISSUE THREAD

**Issue by Pattable** [mickelus/tetra#326]
## Feature Request

**Feature description**

1.
When you first get the Holosphere and use it, a screen that looks like a crafting window appears, however that is not the case. It is an in-game encyclopedia for Tetra but that is not clear until you look around the Holosphere's menus for a bit. Adding a line in the item's description clarifying this would save the player's time.

![image](https://user-images.githubusercontent.com/77807709/105429804-685b2280-5c0f-11eb-81ea-df6d3f4b2dd1.png)

---

2.
**[Outlined in Yellow]** For regular wooden items, crimson/warped planks appear in the cycling wood planks icon (the one that changes every few seconds). 

**[Outlined in Green]** Crimson/warped have distinct stats from each other and are also different from regular wood, so they should not be appearing in the cycling icon of normal wooden items, but rather remain as their own icons like they already are.

**[Outlined in Red]** All other regular wood icons are also redundant because of the cycling icon. They could be removed to save space. 

![image](https://user-images.githubusercontent.com/77807709/105430026-d6074e80-5c0f-11eb-89dc-c4ae29d24359.png)

Menus in the Holosphere where crimson/warped planks appear in the cycling icons of regular wooden items:

Craft>Bows>Stave>(All)
Craft>Bows>Riser>(Sights / Extended rest / Stabilizer)

Craft>Single headed>(Head / Handle)>(All)

Craft>Blades>(Fuller / Pommel / Blade / Hilt)>(All)
Craft>Blades>Guard>(Forefinger ring / Wide guard)

Craft>Double headed>(Head [Left,Right] / Handle)

Craft>Shields>Plate>(All)
Craft>Shields>Grip>Basic grip

Craft>Materials

---

3.
Organize the toolbelt slots to be more intuitive.

![image](https://user-images.githubusercontent.com/77807709/105430502-e23fdb80-5c10-11eb-89f4-dd6a1030170a.png)

---

4.
Organize sockets and change pristine gem icons to be more intuitive.
Example image: Diamond, Diamond+, Emerald, Emerald+, Lapis, Lapis+

![image](https://user-images.githubusercontent.com/77807709/105430799-9ccfde00-5c11-11eb-8231-6b9e77a12942.png)

---

5.
Granite, Diorite, Andesite could have a cycling icon, just like regular wood planks, because they are equivalent materials.

![image](https://user-images.githubusercontent.com/77807709/105430949-ef10ff00-5c11-11eb-900e-7ca74b64b05f.png)

---

6. Stone, Granite, Diorite, and Andesite hammers should not be craftable in a crafting table because the first achievement only works if you craft a wooden hammer, not stone. Also, the second achievement only works if you upgrade a hammer to stone in the Tetra workbench, not crafting it in the crafting table.

![image](https://user-images.githubusercontent.com/77807709/105431887-c12cba00-5c13-11eb-9d3b-1edc11c892c5.png)

---

**How it improves the player experience**

- [ ] 1. Players will not feel frustrated when clicking all the buttons in the Holosphere without anything happening.
- [ ] 2. So it doesn't say that you can craft regular wooden parts with crimson/warped planks, also reduces screen clutter.
- [ ] 3. Making menus more intuitive.
- [ ] 4. Same as 3.
- [ ] 5. Reducing screen clutter.
- [ ] 6. Making sure that the achievements work correctly.

---

**Tetra synergies**
Tetra's aesthetic is very sleek and modern. These suggestions, in my opinion, will make Tetra more optimized, clean up some screen clutter, and give an overall better user experience.

**Comment by mickelus** [comment]
To me this appears as seemingly random changes that would not make things easier to understand but would cause signficant technical debt. Closing.
