### ISSUE TITLE
Shield boss upgrade doesn't knock back players.

### ISSUE THREAD

**Issue by Crazydude323** [mickelus/tetra#327]
## Bug Report

**Observed Behaviour**
When using the boss upgrade of the shield by shift+r-clicking, it doesn't knock back players. It applies slowness fine, but doesn't knock them back. Tested on players with nothing equipped.

**Expected Behaviour**
I expected that, as with other mobs, it would knock the player back and then stop them from moving for a second.

**Minimal setup needed to reproduce**

- Forge version: 
- Tetra version: 
- Tetra configuration: 

**Steps to reproduce**
Make a tetra shield with the "boss" upgrade.
Use the shield bash on another player.

**Comment by mickelus** [comment]
Fixed this in 3.6.0!
