### ISSUE TITLE
[1.16.4] Fire Aspect enchantment not working with shortblade Jab

### ISSUE THREAD

**Issue by HongBo-contact** [mickelus/tetra#328]
## Bug Report

**Observed Behaviour**
During testing of how various enchantments show up on UI and how they potentially scale with Tetra, I noticed that shortblade jab does not apply fire effect on jab, despite being enchanted with fire aspect. Mainhand attacks work as intended.

**Expected Behaviour**
Jab attacks with Fire Aspect setting enemies on fire when used in offhand.

**Minimal setup needed to reproduce**
- Forge version: 1.16.4 - 35.1.37
- Tetra version: Tetra v. 3.5.3
- Tetra configuration: Default
- Other mods: Was reproduced on a clean slate with Tetra only.

**Steps to reproduce**
- Make a Tetra shortblade with Fire Aspect enchantment.
- Equip in offhand
- Use Jab ability of the shortblade on an enemy

**Comment by mickelus** [comment]
Fixed this in 3.6.0!
