### ISSUE TITLE
tetra.stats.integrity lang key missing

### ISSUE THREAD

**Issue by aaronhowser1** [mickelus/tetra#329]
## Bug Report

**Observed Behaviour**
![image](https://user-images.githubusercontent.com/15698722/105575360-b287f500-5d30-11eb-8f6e-e66897511a93.png)

**Minimal setup needed to reproduce**

- Forge version: 36.0.1
- Tetra version: tetra-1.16.4-3.5.3

**Comment by mickelus** [comment]
Unable to reproduce this, difficult to say why as you've left out several fields.
