### ISSUE TITLE
Hammer level validity is not updated when one enters the inventory

### ISSUE THREAD

**Issue by ejektaflex** [mickelus/tetra#33]
Or any tool condition validity, for that matter. If I am switching out a counterweight on a wooden sword, it will tell me (in red) that I need a level 1 hammer in order to do so. Adding one to my inventory via JEI does not update the UI to show that it is now valid, even though I now have the materials necessary. 

This seems a little bit inconsistent because the inventory *does* update when items are moved, highlighting valid materials for the given modification (e.g. cobblestone for the counterweight has an outline around it.)

**Comment by mickelus** [comment]
Fixed in 0.20.4!
