### ISSUE TITLE
Holospheres are too difficult to make for what they are

### ISSUE THREAD

**Issue by aaronhowser1** [mickelus/tetra#330]
## Feature Request

**Feature description**
If you lose your Holosphere early on, there's essentially nothing you can do about it. You'll have to wait until the mod's endgame to make another. The recipe should be made cheaper, using materials you can find earlier in the game.

**How it improves the player experience**
If a player loses their *guide to the mod*, and there's no way for them to make a new one, they simply won't use the mod.

**Comment by mickelus** [comment]
It's a temporary solution until the origin of the holosphere is implemented, won't fix.
