### ISSUE TITLE
Add more config options for modpack creators

### ISSUE THREAD

**Issue by hamOverlord** [mickelus/tetra#332]
## Feature Request

**Feature description**
It would be nice to add more options for the config so modpack creators can balance the game.

- Blacklisting/whitelisting what ores the Cthonic Extractor generates
- Blacklisting/whitelisting what items are obtained via salvaging
- Being able to change what level tool is required to do a certain task. For instance, making the Cthonic Extractor require a higher or lower tier hammer

**How it improves the player experience**
I feel like blacklisting/whitelisting is the most important config item this mod needs, as modpack creators will often turn off the generation of certain ores for balance and convenience (removing the many types of copper ores). It would be nice if the Chthonic Extractor's generation could therefore be tweaked (especially if modpack creators wanted to make certain ores only obtainable through the extractor)

The tool level changes would be incredibly helpful for balancing modpacks and making the mod work well in the context of other mods that do similar things.

**Tetra synergies**
This feature allows other mods to better synergise with tetra and vice versa, by, as previously stated, allowing modpacks to better control with how tetra interacts with other mods

**Comment by mickelus** [comment]
You can already change the loot tables which determines which ores the extractor generates. How many tiers covers too many systems, I will not make that configurable.

The resource location for the loot table for the first "tier" is "tetra/loot_tables/extractor/tier1.json" (replace 1 with 2-4 for the other tiers), check the example data that's provided on discord for more info.
