### ISSUE TITLE
Cyclic Disenchanted duplicates enchantments when placing an enchanted Tetra Tool within

### ISSUE THREAD

**Issue by Lansy22** [mickelus/tetra#334]
## Bug Report

**Observed Behaviour**
I put an enchanted sword from Tetra in the Disenchanter from Cyclic, and it produced a book with the enchantments, but the enchantments were not removed from the tool.

**Expected Behaviour**
Honestly, I didn't expect it to work at all. I expected the tool to go into the machine and do nothing because they are enchanted differently from normal tools.

**Minimal setup needed to reproduce**
- Forge version: 35.1.36
- Tetra version: 3.5.3
- Tetra configuration: As far as I know, the configs are the default. The modpack is the Direwolf20 1.16 modpack.
- Other mods: Cyclic version 1.1.4

**Steps to reproduce**
1. Create a Tetra Tool
2. Enchant the Tetra Tool
3. Place the Tetra Tool within the Cyclic Disenchanter.

**Comment by mickelus** [comment]
There's nothing to be done about that on tetra's side, cyclic probably provides a blacklist option for the disenchanter which has to be configured in the modpack.
