### ISSUE TITLE
Netherite prices too high

### ISSUE THREAD

**Issue by ProfessorBustanut** [mickelus/tetra#336]
in vanilla it cost one netherite ingot to upgrade any diamond item
in Tetra it can cost two or more, based on how rare this material is it can cause making a full netherite sword cost up to 24 debris
Perhaps you can lower the price for all netherite or add netherite nuggets to use for upgrading from diamond

**Comment by mickelus** [comment]
I don't intend to lower the cost. Use the provide templates for future issues.
