### ISSUE TITLE
[Proposal] Shortblade Potion Coatings

### ISSUE THREAD

**Issue by HongBo-contact** [mickelus/tetra#337]
## Feature Request

**Feature description**
An additional modification for Tetra Shortblades, on par with tempering and serrating, adding various potion coatings to the blade, allowing to add potion effects on strike, similar to the [Tipped Arrow](https://minecraft.gamepedia.com/Arrow#Tipped_arrows) mechanic of Vanilla Minecraft.
Coatings would not be stackable for a single blade, each coating replacing the previous one, and, similar to the Tipped Arrow recipe, would require player to use a [Lingering Potion](https://minecraft.gamepedia.com/Lingering_Potion) of an appropriate type.
Effect durations, most likely, would be similar to the coressponding Tipped Arrows, but similarly to the Serrated and Tempered modifications, an option of honing (either to increase potion effect, or lengthen it) could also be added, using either glow-/redstone powder or the same potion that was used to make the coating in the first place.

**How it improves the player experience**
Adding Coatings to the shortblades would expand on availiable options for the weapons and provide an alternative for non-messy application of potion effects that is not reliant on using ranged weapons. Additionally, with proposed recipe it would be intuitive and immersive for any player that used Tipped Arrows before, as it is reliant on the same logic.

**Tetra synergies**
Coatings would synergize very well with Shortblade's Jab being a reliable way to apply on-hit effects, potentially making it stronger and more diverse as a support weapon.

**Comment by HongBo-contact** [comment]
# Additional notes
This proposal is partially based on [0th Law's Suggestion](https://github.com/mickelus/tetra/issues/141#issuecomment-762968900) in Modular armor thread.

## Balancing
As it was brought up in discussion on discord, the coatings might be a bit overpowered if you consider the fact that they could be used as an infinite version of Tipped Arrow of any type.

I also have two proposals on ways to balance this:
### Non-permanent coatings
Any coating applied to a shortblade would slowly dissipate after being used (aka on attack), with amount of uses being at least 8 (as per Tipped Arrows being crafted in batches of 8). That would, of course, take away the possibility of honing the coating on the shortblade.

### Permanent coatings
Any coating applied to a shortblade is slightly weaker than it's coressponding Tipped arrow, but with honing it could become way stronger than it originally was, possibly allowing for stronger effects than the Vanilla potions have.

**Comment by silhouettedDoomsday** [comment]
A good way of doing the longer lasting effect could be a socket that would make the blade into that of an alchemist dagger have it use up a certain amount per hit. The balance for this could be making the part is hard since you'd need a new tool to even work glass but also it takes up a slot on the blade already.
