### ISSUE TITLE
The Abyss: Chapter II mod breaks Tetra completely

### ISSUE THREAD

**Issue by sirben99** [mickelus/tetra#338]
Bug Report

Observed Behaviour
I downloaded The Abyss: Chapter 2 and noticed that Tetra mod is completely broken

Expected Behaviour
The Abyss: Chapter 2 and Tetra work together

Minimal setup needed to reproduce
- Forge version: 1.16.5, 36.0.10
- Tetra version: 1.16.4 3.5.3
- The Abyss: Chapter 2 version: 1.0.4-1.0.5
Steps to reproduce
1. Download and install Tetra and The Abyss: Chapter 2
2. Start the game and go to server/singeplayer
3. Go to any Tetra block/items/achievment and see it be complete broken.

Heres the link with the screenshots: https://imgur.com/a/ElB2U1V
(The first one is not related. It got there by accident)

**Comment by Y3Z0N** [comment]
as we already wrote in the Tetra Discord and Abyss Discord the issue is now closed :)
there was no way to reproduce the issue and it works fine on 1.16.4 / 1.16.5 - forge 35.1.35 - 37.
