### ISSUE TITLE
StackOverflowError when entering world

### ISSUE THREAD

**Issue by Spectre96** [mickelus/tetra#340]
## Bug Report

**Observed Behaviour**
Immediately disconnected with a StackOverflowError when connecting to a personal server, with no message in either log. Strangely, installing Optifine and Optiforge allows the client to connect, but causes a large number of StackOverflowErrors relating to Tetra to be printed to the client log (attached below).

[debug.log](https://github.com/mickelus/tetra/files/5901043/debug.log)

Issue presents itself when connecting to a personal server, but does not present on other worlds or on the official server of the modpack being used.

**Expected Behaviour**
The server should be able to be connected to without Optifine and Optiforge installed on the client.

**Minimal setup needed to reproduce**
- Forge version: 1.16.5 - 36.0.13
- Tetra version: Issue presents on both 3.5.3 and 3.6.0
- Other mods: TNP Limitless 3 Modpack, version 1.9.3, run via GDLauncher

**Steps to reproduce**
Attempting to load the world in TNP Limitless 3 v1.9.3 without Optifine and OptiForge causes an immediate disconnect with a StackOverflowError message. Installing Optifine and OptiForge allows connection, but displays a StackOverflowError in the log related to Tetra. Removing only Tetra from the modpack also remedies the issue. The world conditions that cause the issue are unclear.

**Comment by mickelus** [comment]
I'm guessing that you've used the /give command to give yourself a modular item? Please try starting up a different world on your server

**Comment by mickelus** [comment]
This should have been fixed in 3.7.0.
