### ISSUE TITLE
More World Gen Settings to Config File

### ISSUE THREAD

**Issue by rtbittaker** [mickelus/tetra#344]
## Feature Request
Add World Gen Settings to the player side config file

**Feature description**
Better implementation of World Gen adjustment. There is no working wiki page for Tetra 1.16 configuration (Wiki might be broken as well). The Tetra Configuration file only allows World Gen to be turned on/off. 
![image](https://user-images.githubusercontent.com/9347865/106980673-73d14200-6715-11eb-9b32-5255b98cff97.png)
 I would like to be able to adjust the frequencies up/down. 

**How it improves the player experience**
Better control over World Gen allows players to properly align the world with how they want to play. I currently am trying to set up a floating Island playthrough. However, Tetra structures are generated way too common for the empty space and I'd like to reduce their numbers by half or more. 
![2021-02-03_19 03 02](https://user-images.githubusercontent.com/9347865/106980586-4edccf00-6715-11eb-874a-bd4ca2dd3a60.png)

**Comment by mickelus** [comment]
You can already do this using datapacks.

**Comment by Sandriell** [comment]
How since none of it is documented?
