### ISSUE TITLE
Missing Apotheosis Endless Quiver enchantment support

### ISSUE THREAD

**Issue by wogns3623** [mickelus/tetra#346]
## Bug Report

**Observed Behaviour**
Looking at #145, I thought that it supports all the enchantments in Apotheosis mod.
But I don't know why, but the support for the endless quiver enchantment doesn't seem to apply.

**Expected Behaviour**
Apply Endless quiver enchantment to my fancy bow and enjoy the combination of tetra & apotheosis

**Minimal setup needed to reproduce**

- Forge version: 1.16.4 - 35.1.36
- Tetra version: Mine is 3.6.0, but I think all version after 2.4.0 has same problem
- Tetra configuration: 
- Other mods: Apotheosis version 4.4.1

**Steps to reproduce**
Creates a single player world and try to apply an endless quiver enchant to the tetra bow.

**Comment by mickelus** [comment]
Bows were not implemented when I added support for apotheosis :)
