### ISSUE TITLE
missing/not working apotheosis enchants

### ISSUE THREAD

**Issue by najlitarvan** [mickelus/tetra#349]
## Bug Report

**Observed Behaviour**
some apotheosis enchants were not working
was messing with the game and i found that:
bane of illagers is not in the compat file
endless quiver/true infinity is not in the compat file
sea infusion is not in the compat file
and reflective defenses seem to not work with the shield

**Expected Behaviour**
all of the enchants properly detected and applicable where, they would be placed in vanilla

**Minimal setup needed to reproduce**
shouldn't need any, just install apotheosis and tetra and try to use these specific enchants

- Forge version:  1.16.4 - 35.1.28 
- Tetra version:  tetra-1.16.4-3.6.0.jar
- Tetra configuration: nothing has been changed except for 3. the total magic cap
- Other mods: Apotheosis-1.16.3-4.4.1.jar

**Steps to reproduce**
put the enchants into inventory and try to use them on tetra tools in the workbench.

**Comment by mickelus** [comment]
Please update the issue so that it adheres to the template for bug reports.

**Comment by najlitarvan** [comment]
hope this is better

**Comment by mickelus** [comment]
I need the enchantment id's of the requested enchantments.

**Comment by mickelus** [comment]
Closing this as the requested information has still not been provided.
