### ISSUE TITLE
[Compat Bug] Axe breaking with Dynamic Trees

### ISSUE THREAD

**Issue by Deshiba** [mickelus/tetra#35]
Within Dynamic Trees there is an option to enable tree volume making up the damage the tool makes. When this is enabled the axe from tetra breaks completely, probably because the threshold is exceeded. 

I imagine the same would happen with vein miner or similar mods.

**Comment by mickelus** [comment]
I think I managed to squash it, fix in 0.21.1! Thank you for all the reports!
