### ISSUE TITLE
Only one Hammer shows in JEI, even though there are 10 craftable ones

### ISSUE THREAD

**Issue by aaronhowser1** [mickelus/tetra#351]
## Bug Report

**Observed Behaviour**
![image](https://user-images.githubusercontent.com/15698722/107133840-00186c00-68b2-11eb-9d08-29832a854b81.png)

**Expected Behaviour**
For you to see all 10

**Minimal setup needed to reproduce**

- Forge version: 1.16.5 36.0.13
- Tetra version: tetra-1.16.4-3.6.0
- Tetra configuration: https://pastebin.com/nqam0K3i
- Other mods: https://pastebin.com/dQTzLXj3

Additionally, you can only bookmark one at a time. That could lead to this being a JEI issue?

**Comment by mickelus** [comment]
Which hammers are available is determined by datapacks, that information is not available when creative tabs are set up.
