### ISSUE TITLE
Dupe Bug

### ISSUE THREAD

**Issue by Delvious** [mickelus/tetra#352]
## Bug Report

**Observed Behaviour**
Middle clicking while in the Tetra workbench GUI will take items from inventory and duplicate them. 

Crash log: 

**Expected Behaviour**
For items not to be duplicated. 

**Minimal setup needed to reproduce**
No additional mods and no changes made to configs. 
- Forge version: 36.0.14
- Tetra version: 1.16.4-3.1.3
- Tetra configuration: [tetra.txt](https://github.com/mickelus/tetra/files/5939815/tetra.txt) (obviously saved as a .tmol file)
- Other mods: No mods other than dependencies. 

**Steps to reproduce**
place an item in the workbench, then middle click it to duplicate a stack of the item.

**Comment by mickelus** [comment]
That works for any stack in any inventory when you are in creative mode
