### ISSUE TITLE
Tetra server crash.

### ISSUE THREAD

**Issue by SirOMGitsYOU** [mickelus/tetra#354]
## Bug Report

**Observed Behaviour**

Player said they were making a hammer and during the crafting process it crashed the server

Crash log: 
[crash-2021-02-09_12.31.42-server.txt](https://github.com/mickelus/tetra/files/5951398/crash-2021-02-09_12.31.42-server.txt)

**Expected Behaviour**

**Minimal setup needed to reproduce**

- Forge version: 36.0.14
- Tetra version: 3.3.1
- Tetra configuration: https://paste.ubuntu.com/p/wRPsmFRdk7/
- Other mods:
- a lot - https://i.imgur.com/khv0Slp.png

**Steps to reproduce**

1. Start making a tetra hammer
2. Crash when trying to take it out?

**Comment by mickelus** [comment]
Can you be more specific on how to reproduce this?

**Comment by mickelus** [comment]
Can you update to 3.6.1 and see if this persists? And if it does, please provide me with the log :)

**Comment by mhostilis** [comment]
Hi! I'm having a similar issue on my server, I'm not getting a full server crash, but I will get kicked whenever I try to add a hammer to my inventory through the creative menu. I am using 3.6.1, and here is the server kick message:

`14.02 04:36:16 [Disconnect] User MHostilis has disconnected, reason: Internal Exception: io.netty.handler.codec.DecoderException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Recursive load of: INVALID-tetra:modular_double`

**Comment by copygirl** [comment]
Oddly enough, for me it is crashing when the game is just starting up.
[crash-2021-02-16_15.16.52-client.txt](https://github.com/mickelus/tetra/files/5989212/crash-2021-02-16_15.16.52-client.txt)

### Versions
- Minecraft `1.16.5`
- Forge `36.0.42`
- Tetra `3.6.1`
- mGui `3.1.3`

No other mods. Fresh MultiMC instance, so no configuration either.
(By the way, this version of mGui is not marked to work with 1.16.5.)

**Comment by SirOMGitsYOU** [comment]
> Can you update to 3.6.1 and see if this persists? And if it does, please provide me with the log :)

I haven't had any future reports about this but looks like @mhostilis is having the potentially same issue i had reported to me
