### ISSUE TITLE
1.16.5 Hammer not working properly 

### ISSUE THREAD

**Issue by Jimberys** [mickelus/tetra#355]
## Bug Report

**Observed Behaviour**
Crafted and upgraded a hammer to Iron hammer and enchanted silk touch on it, it will not allow me to pick up any forged walls, pillars, slabs or anything it just destroys them I noticed on the tooltip it says it requires a hammer with a red X when i have a hammer in my main hand 

**Expected Behaviour**
to pick up block when mined with hammer with silk touch applied to it 

**Minimal setup needed to reproduce**

- Forge version: 36.0.0
- Tetra version: 3.6.0
- Tetra configuration: I dont mess with configs
- Other mods:

**Steps to reproduce**
Made a wood hammer in crafting station
upgraded both sides of the hammer to stone then Iron through the Forged workbench 
Then upgraded the hammer enchant with silk touch on the forged workbench

Any help with this will be greatly appreciated

![2021-02-09_20 27 15](https://user-images.githubusercontent.com/77068605/107451459-51746580-6b15-11eb-8d43-33d9ed2b4f9c.png)

![2021-02-09_20 27 01](https://user-images.githubusercontent.com/77068605/107451446-48839400-6b15-11eb-8123-ada1a8779a72.png)

**Comment by mickelus** [comment]
You need a netherite hammer to break the forged blocks, check the advancements.
