### ISSUE TITLE
Forged vent visuals don't match up to block's hitbox properly

### ISSUE THREAD

**Issue by NovaLynxie** [mickelus/tetra#358]
## Bug Report

**Observed Behaviour**
The forged vents block model does not properly orientate themselves to their hitboxes in north/south directions.
![2021-02-14_15 05 25](https://user-images.githubusercontent.com/21307676/107880360-22277500-6ed6-11eb-9e98-96d44349ac30.png)
This occurs with forged vents placed in creative and generated in the world.

**Expected Behaviour**
The rendered block to properly face correct direction, in this case it should render the block texture following the block's hitbox like it does when facing east/west.

**Minimal setup needed to reproduce**

- Forge version: 35.1.37
- Tetra version: 1.16.4-3.6.0
- Tetra configuration: Default configuration used.
- Other mods:

**Steps to reproduce**
Try to place forged vent block so it would be facing north/south.

**Comment by NovaLynxie** [comment]
I can confirm this also occurs in versions 3.5.3 and 3.6.1 as well.

**Comment by mickelus** [comment]
I can't reproduce this. Can you press f3 and take a screenshot while looking at one of the vents?

**Comment by NovaLynxie** [comment]
Got them. I have both orientations placed with F3 data included.
First orientation (working)
![2021-03-08_08 07 23](https://user-images.githubusercontent.com/21307676/110292571-5bd73180-7fe5-11eb-918b-813c32f64e95.png)
Second orientation (broken - using same model of above, yet hitbox says otherwise)
![2021-03-08_08 07 27](https://user-images.githubusercontent.com/21307676/110292574-5d085e80-7fe5-11eb-81bd-28ebdc9ea072.png)

**Comment by mickelus** [comment]
Cheers! Did you place those by hand?

**Comment by NovaLynxie** [comment]
Yes, both of those in the screenshots are placed by hand. The second screenshot showing the one on the right also occurs in structures that try to spawn in that orientation. I can try and find ones where they spawn naturally if needed.

**Comment by NovaLynxie** [comment]
Just in case it is needed, I have found one in the underground structures. f3 data is included in the screenshot.
![2021-03-09_18 41 20](https://user-images.githubusercontent.com/21307676/110521496-b668ae80-8107-11eb-92f5-3a6c7697d56b.png)

**Comment by RGFTheCoder** [comment]
I have this same issue; but I have already broken the vents.

**Comment by mickelus** [comment]
Ah, this was fixed a while back!
