### ISSUE TITLE
[Compat bug]Geodes visible with UBC

### ISSUE THREAD

**Issue by Deshiba** [mickelus/tetra#36]
When Underground Biomes Construct is present its painfully obvious where the geodes actually are. This is presumably because the stones used aren't minecraft ones.
![2019-01-08_17 35 43](https://user-images.githubusercontent.com/10565800/50845366-f5a2e580-136c-11e9-9db6-1433276e5396.png)
![2019-01-08_17 35 58](https://user-images.githubusercontent.com/10565800/50845367-f5a2e580-136c-11e9-92ab-bc8e35d24a7b.png)

**Comment by mickelus** [comment]
Fixed this by making it only generate in vanilla stone (before it used an oregen method on blocks which allowed the block to decide if the generation was to be allowed). The goal would be to make it possible for it to generate in any rock and (and not be visible), I've got a setup planned.

**Comment by Deshiba** [comment]
So, fixed this bug. Full compatibility with Mods like UBC and Earthworks incoming. Correct?

**Comment by mickelus** [comment]
It will be fully configurable, e.g. you could make nether rack between y level 99 and 137 drop a different type of geode which only yield blaze powder or coal when broken or you could make igneous stone from UBC between y level 5 and 25 drop the regular geode. I can take a stab at adding support for UCB out of the box.

**Comment by Deshiba** [comment]
Personally I'd be fine with a system that supports vanilla out of the box but can be extended to support modded blocks trough something like json files. If you document that part it'd be more scalable for other mods too.

Thank you for all efforts taken.

**Comment by mickelus** [comment]
I tried to put in some support by default but the resource manager logged some confusing messages so I skipped it. But here's an example which add geode generation to black granite, rhyolite & basalt: https://github.com/mickelus/tetra-config-example/tree/master/geode-variants
