### ISSUE TITLE
Hoe / Shovel Combination won't work

### ISSUE THREAD

**Issue by Alec153** [mickelus/tetra#360]
## Bug Report

**Observed Behaviour**
By combining a sickle head and an adze head right clicking dirt would only make path blocks. Further testing revealed that a hoe and shovel head does the same. Even with a sickle and an axe path blocks are still made on dirt, vanilla hoes do not do this. 
Edit: a diamond in the binding makes the game see it as all tools according to waila, so removing the diamond will make the axe/sickle combination work.

**Expected Behaviour**
I feel that tilling the ground should be preferred over creating path blocks.

**Minimal setup needed to reproduce**
- Forge version: 1.16.5-36.0.14
- Tetra version: 3.6.0
- Other mods: too many to list, I was using steel from mekanism if that makes a difference

**Steps to reproduce**
create a two headed tool with a sickle and an adze head then try to till the dirt.

**Comment by hjpoe** [comment]
I've had this issue as well. I was just using iron.

It is actually even worse if you have Quark. Quark has a feature where if you right click on a path block with a shovel, it turns into this block called shallow dirt, which is  a 14px high variant of dirt that can be waterlogged.

**Comment by mickelus** [comment]
Fixed in 3.8.0.
