### ISSUE TITLE
Allow non-Tetra modified tools to break. 

### ISSUE THREAD

**Issue by zacbritton** [mickelus/tetra#361]
Basically what the title says. I understand the the whole point of the mod is to allow you to modify your tools and upgrade them, but if I make a wooden tool I'm not going to want it again after it breaks. Plus in modpacks some people may not want to delve into Tetra and all the broken tools just end up wasting space.

Maybe adding a way on the players end to toggle if certain tools break could help fix this.

**Comment by mickelus** [comment]
Closing, does not adhere to the template for feature requests.
