### ISSUE TITLE
Vein Mining Enchantment compat

### ISSUE THREAD

**Issue by Mundayne** [mickelus/tetra#362]
## Feature Request

**Feature description**

It'd be nice if the Vein Mining enchantment from the mod "Vein Mining" could be added to Tetra tools, even if this is via Vanilla mechanics rather than Tetra's enchanting.

**How it improves the player experience**

In general, vein mining mods are a great quality of life enhancement for Minecraft.

**Tetra synergies**

Tetra on its own enriches the Minecraft experience by allowing your tools to continuously get stronger over time. By the time you're able to make really strong tools in Tetra, you probably have reached the stage where mining ores by hand is pointless without something like vein miner to assist you. Vein Mining gates it behind a fairly rare enchantment (more rare than Mending if I'm not mistaken), which falls about in line with the time at which you need it. Overall I think it fits the theme of enhancing the Vanilla experience and getting stronger over time rather than cheap instant power.

**Comment by mickelus** [comment]
Fixed in 4.3.0.
