### ISSUE TITLE
Twilight Forest materials missing

### ISSUE THREAD

**Issue by 0x6273** [mickelus/tetra#366]
## Bug Report

**Observed Behaviour**
Twilight Forest tools can't be modified, and Twilight Forest materials can't be used to modify Tetra tools.

**Expected Behaviour**
It used to work in 1.12

**Minimal setup needed to reproduce**

- Forge version: 1.16.5 - 36.0.40
- Tetra version: 3.6.1
- Tetra configuration: default
- Other mods: Twilight Forest 4.0.355

**Steps to reproduce**
- Get TF "experimental build" from [`here`](https://artprodcus3.artifacts.visualstudio.com/Abaabfa6c-deea-4587-ba05-c308c2597b7a/1ef09d39-06cf-41fa-ad98-7258b70c2a72/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3RlYW10d2lsaWdodC9wcm9qZWN0SWQvMWVmMDlkMzktMDZjZi00MWZhLWFkOTgtNzI1OGI3MGMyYTcyL2J1aWxkSWQvNDI5L2FydGlmYWN0TmFtZS9SZWxlYXNl0/content?format=file&subPath=%2Ftwilightforest-1.16.5-4.0.355-universal.jar).
- Put a TF tool, such as the Knightmetal Axe, in a Tetra workbench. Tetra doesn't recognize it.
- Try to modify a Tetra tool with a material from TF, such as Knightmetal Ingot. Tetra doesn't recognize the material.

When looking at `master` branch source (which I think is 1.15 only? I could not find 1.16 tree), there are references like `forge:ingots/knightmetal` in the json files, but the ingot only seems to have `twilightforest:ingots/knightmetal` tag. Maybe a change from TF 1.12 -> 1.16.

**Comment by mickelus** [comment]
Removed tf support in 1.16. Will re-add it once tf is released :P
