### ISSUE TITLE
[Server] WARN Failed to load datapacks, cant proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode

### ISSUE THREAD

**Issue by Sitherious** [mickelus/tetra#367]
## Bug Report

**Observed Behaviour**
Server locks up and fails to load

Crash log: there is no crashlog that is made from this error

**Expected Behaviour**
it to work! without errors

**Minimal setup needed to reproduce**

- Forge version: works fine on forge but i use mohist
- Mohist version: mohist-1.16.5-376-server.jar
- Tetra version: tetra-1.16.4-3.6.0
- Tetra configuration: default
- Other mods:
- direwolf20 1.16.5 modpack

on mohist github they say this mod is causing the error, if i remove tetra server loads with no issue. i want to use tetra as its part of the direwolf20 modpack and i want to use mohist as i run  a few bukkit plugins.
i hope this is a small issue that could get fixed.

https://github.com/Mohist-Community/Mohist/issues/975

**Comment by mickelus** [comment]
Closing, missing log & forge version.

**Comment by Sitherious** [comment]
there is no crash log to put up because the server fails to load, there is no forge version because i am not using forge.

**Comment by mickelus** [comment]
There's always a log in logs/ even if it did not crash. Tetra won't load without forge as it's a forge mod. So either mohist is built on forge and you need to dig up which version that is, or tetra will never load since there's no forge involved.

**Comment by Sitherious** [comment]
when i look at the github i think its built off of Forge 36.0.43

**Comment by mickelus** [comment]
Tetra doesn't work for forge past 36.0.40, get a mohist version that's based on  36.0.40 or earlier.

**Comment by Sitherious** [comment]
will there be an updated build for tetra for the new forge or does forge have to fix it so tetra could work?
