### ISSUE TITLE
Crash when crafting a hammer/Hammer unavailable in JEI

### ISSUE THREAD

**Issue by bryinabrt** [mickelus/tetra#368]
## Bug Report

**Observed Behaviour**
Started a new world, wanted to make a workbench but I forgot the recipe and for some reason it wasn't showing up in JEI. Tried to do it from memory, it was correct, however, when I placed the last ingredient it crashed

Crash log: https://pastebin.com/aVn348Nn

**Expected Behaviour**
Well, I expected a hammer, not a crash

**Minimal setup needed to reproduce**
- Forge version: 1.16.4 - 35.1.37
- Tetra version: 3.6.1
- Tetra configuration: Default
- Other mods: Too many to write, they are listed in the crash log at line 182, although I did use Optifine with shaders.

**Steps to reproduce**
Load a new world, use a crafting table and try to craft a hammer.

**Comment by mickelus** [comment]
Unable to reproduce this. Could possibly be some datapack that cause data to fail to load. I need a full log.

**Comment by mickelus** [comment]
Can you update to 3.8.0 and see if this persists?

**Comment by bryinabrt** [comment]
> Can you update to 3.8.0 and see if this persists?

The issue has been fixed, thank you.
