### ISSUE TITLE
Have geode-bearing stones blend better into other types of stone

### ISSUE THREAD

**Issue by brckts** [mickelus/tetra#369]
## Feature Request

**Feature description**
It would be nice if stone containing geodes would take the texture and name of adjacent blocks if those blocks are in the forge:stones tag, as it would prevent picture related from happening with some terrain generation mods/datapacks.

(screenshot taken in enigmatica 6, which uses terraforged with different stone layers depending on depth)
![210304-0855-53](https://user-images.githubusercontent.com/51674867/109930752-e9521300-7cbf-11eb-81a8-e1d3e8f5c504.png)

**How it improves the player experience**
Makes geodes less easy to spot, allowing for more immersion and a more "random loot" feel for them.

**Tetra synergies**

**Comment by mickelus** [comment]
Used to work like that but it's not worth it, I suggest you disable geode generation if you are using another mod that changes underground stone.
