### ISSUE TITLE
[Bug] Silk touch complete destroys geodes

### ISSUE THREAD

**Issue by Deshiba** [mickelus/tetra#37]
When using silk touch of any kind, modded or vanilla, the geodes are completely broken without returning anything. Not returning the block seems fair, but it doesn't return geodes either.

The second GIF below shows nothing enters the inventory. Tried several geodes with vanilla silk touch too.
![geode](https://user-images.githubusercontent.com/10565800/50845770-f9833780-136d-11e9-9101-c947cdfd1291.gif)
![geode2](https://user-images.githubusercontent.com/10565800/50845776-fab46480-136d-11e9-8bf6-77708ee711f3.gif)

**Comment by mickelus** [comment]
Fixed in 0.20.2, now drops the stone block if silktouch is used.
