### ISSUE TITLE
Allow hiding of materials in the Holosphere

### ISSUE THREAD

**Issue by anIceyGirl** [mickelus/tetra#370]
## Feature Request

**Feature description**
The ability to hide certain materials in the holosphere via a single boolean toggle in the material's .json file.
By default, tool materials without an associated item, or with an empty item tag, shouldn't show up in the holosphere.

**How it improves the player experience**
For players, it would lead to less clutter in the holosphere, since, if the player doesn't have a mod that adds in silver or copper, there's not much purpose to having silver and copper show up in the materials listing.

**Tetra synergies**
If one of the goals of Tetra is "beauty in simplicity," I think this would make a pretty fine addition. Having a bunch of unused materials taking up the materials list doesn't exactly help that goal.

**Comment by mickelus** [comment]
That's already how it works unless you've turned on development mode.

**Comment by anIceyGirl** [comment]
Well I'm dumb. That was exactly my problem.
