### ISSUE TITLE
Modular items appear identically in advancements tab/JEI

### ISSUE THREAD

**Issue by anIceyGirl** [mickelus/tetra#372]
## Bug Report

**Observed Behaviour**
Every tool type (modular_single, modular_double) each appears identically in advancement tabs. I'm not sure how to explain, so, here's some images.
![image](https://user-images.githubusercontent.com/35877888/109982839-4786f200-7cd0-11eb-97b1-efc0162c1db2.png)
![image](https://user-images.githubusercontent.com/35877888/109984713-0db6eb00-7cd2-11eb-93e5-392c69215d18.png)

**Expected Behaviour**
In previous versions of the mod, tools in advancement tabs did appear as they should, with each icon respecting the NBT tags passed into them.

**Minimal setup needed to reproduce**
- Forge version: 1.16.5 - 36.0.45
- Tetra version: 3.7.0
- Tetra configuration: Default configuration
- Other mods: 
- I did have [Ears](https://www.curseforge.com/minecraft/mc-mods/ears) and Optifine installed at the time, but I don't think that should make much of a difference, since this seems to be moreso an issue with the models displaying incorrectly. 
- JEI also somewhat counts, since viewing the crafting recipes for hammers in JEI will display a similar issue.

**Steps to reproduce**

1.  Create a new world with cheats enabled and unlock all advancements via `/advancement grant @s everything`
2.  Go into the advancements menu.
3.  Click on the "Basic Tinkering" tab.

**Comment by mickelus** [comment]
Can you get me a screenshot of how it looks in jei?

**Comment by anIceyGirl** [comment]
In this context, I am using a custom datapack to add more crafting recipes for tetra's modular items, but it behaves pretty much the same.
![image](https://user-images.githubusercontent.com/35877888/109988631-ba469c00-7cd5-11eb-8f4f-d4c6cfcc6caf.png)

**Comment by 0x6273** [comment]
I have the same issue after upgrading to 3.7.0. It did not happen with 3.6.1. I'm using Forge 36.0.40.

**Comment by mickelus** [comment]
Fixed in 3.8.0.
