### ISSUE TITLE
Enchantment Compat for Charm and Inspirations

### ISSUE THREAD

**Issue by dromedar17** [mickelus/tetra#375]
It would be nice to have support for the enchantment stuff from Charm (https://www.curseforge.com/minecraft/mc-mods/charm)
and Inspirations (https://www.curseforge.com/minecraft/mc-mods/inspirations). Charm adds ~~3~~ 2 enchantments; Inspirations lets some vanilla enchants apply to shields and axes. The descriptions of the enchantments are taken from their respective websites/wikis.

Charm enchantments:
Acquisition (charm:acquisition)
Any tool that mines blocks.
A tool with the Acquisition enchantment adds block drops straight to your inventory.

Tinted (charm:tinted)
Any tool/weapon
A tool with the Tinted enchantment may be combined with a dye on the anvil to change the enchantment glint color.
This one is only cosmetic, so less relevant than the other ones.

Inspirations lets additional enchantments apply to axes and shields
Axe combat enchantments do the same thing as in vanilla (with swords)
- minecraft:fire_aspect cannot be used alongside efficency
- minecraft:looting cannot be used alongside fortune or silk touch
- minecraft:knockback cannot be used alongside efficency

Shield enchants
- minecraft:mending
- minecraft:unbreaking
- minecraft:thorns may randomly damage attackers hitting your shield. Cannot be used alongside fire aspect
- minecraft:fire_aspect lights attackers hitting your shield on fire. Cannot be used alongside thorns
- minecraft:knockback increases knockback dealt to attackers hitting your shield
- minecraft:protection decrease damage taken when blocking. Mainly useful if the attack misses your shield
- minecraft:fire_protection decrease damage taken when blocking. Mainly useful if the attack misses your shield
- minecraft:blast_protection decrease damage taken when blocking. Mainly useful if the attack misses your shield
- minecraft:projectile_protection decrease damage taken when blocking. Mainly useful if the attack misses your shield

**How it improves the player experience**
You wouldn't have to choose between using the enchantments and using a Tetra tool.

**Tetra synergies**
It would make the experience more seamless

**Comment by mickelus** [comment]
Unfortunately I can't load data differently based on which mods are loaded.
