### ISSUE TITLE
(visual bug)Arrows fired from tetra bows not visually hitting target

### ISSUE THREAD

**Issue by Direbat** [mickelus/tetra#376]
**Description:**
When you create a longbow in the tetra mod and fire arrows the arrow hits the target but the visual model of the arrow goes in a different direction. This isn't a problem most of the time but it is really annoying when you are trying to snipe with a longbow.  

**Expected behaviour**
arrow model to travel in the direction it is shot

**Minimal setup needed to reproduce**
- open Minecraft
- create a tetra longbow with any material(it becomes easier to see if there is an extender)
- Forge version: 1.16.5 - 36.0.43
- Tetra version: 3.7.0
- Tetra configuration: no changes done to config
- Other mods: mgui version 3.1.3

**Steps to reproduce**
charge up tetra longbow to the max or beyond the max charge and

 fire an arrow at a block or entity from a long distance
the target will take damage but the visual model of the arrow will travel in a different direction and the gap will increase the further it travels

![2021-03-06_09 14 33](https://user-images.githubusercontent.com/74643395/110193856-80ec6880-7e5c-11eb-82c2-5d903deeef31.png)

![2021-03-06_09 18 00](https://user-images.githubusercontent.com/74643395/110194219-754d7180-7e5d-11eb-9cb3-e6a2c4b28d67.png)
with the extender you can see that the leftmost arrow is taking the place of the middle arrow

**Comment by Direbat** [comment]
I forgot to write that I made no changes to the config files

**Comment by Quinteger** [comment]
Unfortunately, it is a vanilla bug with projectiles travelling at really high speeds. Not related to Tetra.

**Comment by Direbat** [comment]
ok thanks for telling me
