### ISSUE TITLE
Items Dissapearing when placed in repair slot/material slot

### ISSUE THREAD

**Issue by AffectSnake** [mickelus/tetra#378]
## Bug Report

**Observed Behaviour**
repair Item Dissapered When taking out tool from Workbench

**Expected Behaviour**
item placed in the repair slot to go in to inventory or be dropped

**Minimal setup needed to reproduce**

- Forge version: 1.16.5 - forge-36.0.13
- Tetra version: 3.5.3
- Tetra configuration: 
- Other mods:

**Steps to reproduce**
place tool in workbench,
place item in repair slot,
take tool out of workbench.

**Comment by mickelus** [comment]
It plops out the next time you do anything in the workbench
