### ISSUE TITLE
Tools with mana repair do not trigger Botania's mana overlay.

### ISSUE THREAD

**Issue by The-Arcanian** [mickelus/tetra#379]
## Bug Report

**Observed Behaviour**
Tetra tools with mana repair do not trigger Botania's mana overlay to start showing.

**Expected Behaviour**
As expressed [here](https://github.com/Vazkii/Botania/issues/3096) Botania's mana overlay should start showing once the player has an item that uses mana.

**Minimal setup needed to reproduce**

- Forge version: 1.16.5 - 36.0.21
- Tetra version: 3.6.1
- Tetra configuration: Default
- Other mods: Botania-1.16.4-411, Patchouli-1.16.4-50, curios-forge-1.16.5-4.0.4.0

**Steps to reproduce**
Use a tool with mana repair while there is at least a partly full mana tablet in the player's inventory and no other mana using items.

**Comment by mickelus** [comment]
No idea what this means

**Comment by The-Arcanian** [comment]
Botania has items that store mana (Mana Tablet, Ring of Mana, Greater Ring of Mana). When a player has a mana storage item in their inventory there is an overlay on the experience bar that shows how much mana they have compared to how much they can store. According to the issue I linked, the overlay does not display until an item that uses mana actually uses some mana (the player uses a Botania gadget, or a Botania item repairing itself). But Tetra tools with the Mana Repair attribute do not trigger the mana overlay to start showing when they repair themselves.

**Comment by mickelus** [comment]
From what I can see the only way of making tetra items considered mana items is to make botania a hard dependency and that's not feasible :c
