### ISSUE TITLE
Crash On Game Load

### ISSUE THREAD

**Issue by WenXin20** [mickelus/tetra#38]
Forge v14.23.5.2796-1.12.2
Tetra v0.21.2
I get a crash while loading the game up.
**[Crash Log](https://paste.dimdev.org/atisinukux.mccrash)**

**Comment by mickelus** [comment]
I'm unable to reproduce this.
It seems as if some mod is creating tetra items with invalid itemstacks, I've patched up the possibility for crashes due to that in 0.21.3.
If this problem persists, please provide a minimal set of mods which can be used to reproduce this and reopen the issue.

**Comment by WenXin20** [comment]
I got this crash again. [Crash Report](https://paste.dimdev.org/ojokiyicun.mccrash)
I will let you know if I find the mod that causes it to crash.

**Comment by mickelus** [comment]
I'm sorry, 0.21.4 did not include the changes introduced in 0.21.3 for some reason. Please try again with 0.21.5.

**Comment by WenXin20** [comment]
Ok, thanks!
