### ISSUE TITLE
Unable to make aerodynamic trim,trim edge and studded plate modifications to shields

### ISSUE THREAD

**Issue by Direbat** [mickelus/tetra#381]
## Bug Report

**Observed Behaviour**
when entering the menu it is asking for materials suitable for the modifications however when materials are supplied the action cannot be done regardless of hammer tier

**Expected Behaviour**
To be able to make the shield modifications without suppling materials

**Minimal setup needed to reproduce**
- Open minecraft
- get shield 
- get workbench
-get hammer
- Forge version: 36.0.43
- Tetra version: 3.7.0
- Tetra configuration: no changes done to config file
- Other mods: mgui vrsion 3.1.3

**Steps to reproduce**
place shield in workbench
attempt to add one of the mentioned modifications that should not require materials
materials will be asked for
place desired material in gui slot
the craft option will become red and say that you are unable to make the modification as you cannot use the selected material for the schematic
![2021-03-07_11 59 36](https://user-images.githubusercontent.com/74643395/110231274-b1a3cf00-7f3c-11eb-9237-3f80e6a50765.png)

**Comment by 0x6273** [comment]
Wood doesn't work, you need to use a metal such as iron or gold.
