### ISSUE TITLE
Excavating, while can be applied, doesn't work

### ISSUE THREAD

**Issue by Quinteger** [mickelus/tetra#384]
## Bug Report

**Observed Behaviour**
Tools with Excavating highlight and mine a single block, as if Excavating is not present.

**Expected Behaviour**
Tools with Excavating should highlight and mine an area according to their Excavation tier.

**Minimal setup needed to reproduce**
- Forge version: 36.0.46
- Tetra version: 3.8.0
- Mgui 3.1.3
- Ensorcellation 1.1.2
- Cofh_core 1.1.6

**Steps to reproduce**

Make a basic tetra pickaxe or shovel with Excavating and try mining appropriate blocks.

![image](https://user-images.githubusercontent.com/7419124/110507860-7c9ca580-8111-11eb-86fa-16f81cad973f.png)
![image](https://user-images.githubusercontent.com/7419124/110507910-8920fe00-8111-11eb-9c7c-626ccaa081f5.png)
![image](https://user-images.githubusercontent.com/7419124/110507934-8de5b200-8111-11eb-837f-4456f5e3c4b5.png)

![image](https://user-images.githubusercontent.com/7419124/110507973-9807b080-8111-11eb-8eb3-33481d55f83c.png)
![image](https://user-images.githubusercontent.com/7419124/110507996-9ccc6480-8111-11eb-8970-f7aa3f313354.png)
![image](https://user-images.githubusercontent.com/7419124/110508008-9fc75500-8111-11eb-8a5c-594df546d24e.png)

**Comment by mickelus** [comment]
There are a few of the ensorcellation enchantments that don't work with tetra items.

I'm not sure how to approach that, not allowing the enchantment to be applied would confuse players as they can apply other enchantments from that mod, but there's no indication as to why they can't apply those that don't work. Allowing the enchantment and using the description to explain that it doesn't work would probably be overlooked by most players, and they'd then become frustrated when it didn't work and they've wasted their hard earned enchanted book.

What to do?

**Comment by mc-ganduron** [comment]
Whenever I'm confused about a Tetra item, I try placing it on the Workbench. Could the Workbench be made to display some useful details about an enchanted book when one is placed on it? E.g., whether the enchantment is supported generally, and if so, which modules support it. I think this would help the information gap even with supported enchantments. Sometimes it's not obvious to me what goes where, and the Workbench itself could explain that with this approach.

**Comment by wizzbangwa** [comment]
Same problem here.  Lost excavation enchant when changing from iron pickaxe heads to diamond on a vanilla pickaxe, which was expected  Placed an excavate book on one of the diamond heads.  Excavate doesn't work.  

Not being able to apply the book in the Tetra workbench would be obvious enough the enchant isn't compatible.

Mod pack: Direwolf20 1.16 1.11.0

Forge version: 36.2.2
Tetra version: 3.17.0
Mgui 3.3.0
Ensorcellation 1.3.1
Cofh_core 1.3.1

**Comment by mickelus** [comment]
Won't fix.
