### ISSUE TITLE
Inventory Tweaks Item Duplication

### ISSUE THREAD

**Issue by Mondrethos** [mickelus/tetra#385]
## Bug Report

**Observed Behaviour**
When you are in the Tetra workbench and you have Inventory Tweaks Renewed https://www.curseforge.com/minecraft/mc-mods/inventory-tweaks-renewed installed and you hit the hotkey for "Sort External Inventory", you can have infinite item duplication every time you hit the key.

**Expected Behaviour**
For items to not duplicate.

**Minimal setup needed to reproduce**

- Other mods:
-https://www.curseforge.com/minecraft/mc-mods/inventory-tweaks-renewed

**Steps to reproduce**
Enter the Tetra Workbench and hit the hotkey for Sort External Inventory in the inventory tweaks renewed mod.

**Comment by mickelus** [comment]
You need to blacklist the workbench.
