### ISSUE TITLE
Quick Draw tool belt quiver doesn't seem to work. (Direwolf20 1.16)

### ISSUE THREAD

**Issue by Soverilus** [mickelus/tetra#386]
Applying a Quick Latch onto the quiver and giving it an ample supply of arrows doesn't seem to work.
Additionally, Tetra's toolbelt seems wholly inaccessible in the Botania/Curios 'bauble' system.

I added the "Direwofl20 1.16" version in the title as I'm about 50/50 on whether this is a Tetra issue or a Direwolf issue, but it's worth looking into at least.

**Comment by mickelus** [comment]
Needs to be updated to use the template for bug reports.

**Comment by AudibleWallpaper** [comment]
Just for clarifications sake, did you have an item in your offhand when trying to use the bow & quicklatch belt quiver? And if so, have you tried it without an offhand item?

**Comment by mickelus** [comment]
Closing since this has been in need of an update for over a month.
