### ISSUE TITLE
Magmatic Press Channel doesn't match description

### ISSUE THREAD

**Issue by RGFTheCoder** [mickelus/tetra#388]
## Bug Report

**Observed Behaviour**
When I use a honed Blackstone hammer to make a tool out of obsidian (requires tier 5 which is blackstone + hone) I get the Magmatic Press Channel with the description "Use a forge hammer..." even though I haven't found one yet.

**Expected Behaviour**
The Magmatic Press Channel advancement should only be granted if using a forge hammer, rather than the item hammer.

**Minimal setup needed to reproduce**

- Forge version: 1.16.5 - 36.1.0
- Tetra version: 3.8.0
- Tetra configuration: Default?
- Other mods: mgui 3.1.3

**Steps to reproduce**
Get a blackstone hammer
Hone durability until the Hammer Tier hone appears
Use new Level 5 Hammer to create obsidian tools.

**Comment by mickelus** [comment]
Won't fix
