### ISSUE TITLE
Compatability Suggestion: Quark Ancient Tome

### ISSUE THREAD

**Issue by DereC4** [mickelus/tetra#389]
## Feature Request

**Feature description**
Allow quark ancient tomes (pretty much enchanted books) to be added as well

**How it improves the player experience**
Allows for more mod compatibility because ancient tomes are similar to enchanted books in both application and obtainment 

**Tetra synergies**
No new game breaking changes are made; rather, it just makes it easier to enchant your tool especially since this is a very compatible mod already

**Comment by mickelus** [comment]
Ancient tomes need to be combined with a regular enchanted book before it can be used to enchant an item.

**Comment by DereC4** [comment]
Ah ok
