### ISSUE TITLE
Incorrect enchantment

### ISSUE THREAD

**Issue by ignatferum** [mickelus/tetra#39]
This mod allows to make:
- Double/tripple enchantments of mending/unbreaking (It's funny, but axe/pickaxe with 3xUnbreaking III doesn't break almost absolutely. 1 unit per 30 blocks+)
- Enchant sword on Sharpness + Smite + Bane of Arthropods, and also axe/pickaxe on Silk Touch + Fortune
- Enchant Axe on Fire Aspect
- Not to spend levels to enchanting
But does not allow enchant axe on Bane of Arthropods and Smite
![wow](https://user-images.githubusercontent.com/29925031/50955993-85739b80-14f5-11e9-87a8-0cf6817dc069.png)
Is that even legal?=)

**Comment by mickelus** [comment]
It's unclear what you are trying to say, please rephrase.

**Comment by ignatferum** [comment]
1. Tetra's workbench allow to enchant any tools on Unbreaking III twice. 1xUnbreaking III on left head and 1xUnbreaking III on right head. Effect of enchants summing up.
Also using the anvil you can add Unbreaking III on any tool. 
In this case, I think so, the overall unbreaking effect of the tool = (Unbreaking III + Unbreaking III) * Unbreaking III. 
![3xu](https://user-images.githubusercontent.com/29925031/50961017-b22db000-1501-11e9-9569-395cf2b554a5.png) Such a tool is practically unbreakable.
2. Tetra's workbench allow to enchant sword on 3 incompatible enchantments at the same time:
- Sharpness V
- Smite V
- Bane of Arthropods V
![incen s](https://user-images.githubusercontent.com/29925031/50961425-ae4e5d80-1502-11e9-9921-a95914338588.png)
3. Tetra's workbench allow to enchant axe on Fire Aspect II, although they incopatible.
![fiaxe](https://user-images.githubusercontent.com/29925031/50961663-42202980-1503-11e9-8113-2a79f3ee3de6.png)
4. When enchanting on Tetra's workbench, experience are not spend.
Let's say we have 30 levels of experience. We added enchanted book on tool. We have to give some levels of experience for this, but enchantment is free. We still have 30 levels of experience. Enchanting tools should not be free.
5. Tetra's workbench does not allow to enchant axe on Smite and Bane of Arthropods.
![c tenaxe](https://user-images.githubusercontent.com/29925031/50962604-962c0d80-1505-11e9-8254-0e3a13067ea8.png)

**Comment by Deshiba** [comment]
Quick question. Did you try this in creative or in survival?
I'm asking because I had similar issues before, see #27 for reference.

**Comment by ignatferum** [comment]
This sword was completely enchanted in survival mode, with the of books from the creative mode and experience from command. I can add Unbreaking enchantment, but cannot add other books even in creative mode.
![sweis](https://user-images.githubusercontent.com/29925031/50973886-f8e0d180-1524-11e9-837a-a50977964a8b.png)

**Comment by mickelus** [comment]
2, 3 & 4 is intended behaviour. It's unbalanced, this will change in the future.
Applying unbreaking in the anvil, and smite + bane not being applicable for the axe is not intended, fix will be available in 0.21.4.
