### ISSUE TITLE
Holosphere Akashic Tome integration

### ISSUE THREAD

**Issue by JonasHri** [mickelus/tetra#392]
## Feature Request

**Feature description**
Option to craft Holosphere into [Akashic Tome](https://www.curseforge.com/minecraft/mc-mods/akashic-tome "Curseforge Page")

**How it improves the player experience**
Lessens Inventory Clutter

**Tetra synergies**
It does not synergize

**Comment by mickelus** [comment]
The holosphere provides more functionality than just being a guide book
