### ISSUE TITLE
Item duplication glitch with Tetra's workbench

### ISSUE THREAD

**Issue by DrZomgaming** [mickelus/tetra#393]
## Bug Report

**Observed Behaviour**
Items in my inventory were doubled when I pressed the sort key.

**Expected Behaviour**

Duplication was certainly not supposed to happen, the player's inventory was only supposed to be sorted into alphabetical order.

**Minimal setup needed to reproduce**

- Forge version: 1.16.5. - 36.0.46
- Tetra version: 1.16.5 - 3.7.0
- Tetra configuration: none (Skyopolis 4 Modpack)
- Other mods: invtweaks-1.16.2 - 1.0.0
**Steps to reproduce**

1. Place an item in the workbench's slot
2. Sort your inventory with the middle click key

**Comment by mickelus** [comment]
This is a known issue with Inventory Tweaks Renewed, you (or the pack author) need to blacklist the tetra workbench from being sorted.
