### ISSUE TITLE
[1.16.5] tetra.stats.integrity lang key incompatibility with Botania

### ISSUE THREAD

**Issue by ocram9** [mickelus/tetra#395]
## Bug Report

**Observed Behaviour**
This issue has been reported before (#329) but without much information so I decided to start testing what is causing it ('cause I have this issue too). I figured out that it's somehow related to Botania. Removing that mod restores the Integrity text back to normal.

**Minimal setup needed to reproduce**
- Forge version: 36.1.4
- Tetra version: 3.8.0
- Tetra configuration: https://gist.github.com/ocram9/4d75a4a1eb1a98ceb6e9438d9e062269
- Other mods: Botania 1.16.5-415

**Steps to reproduce**
- Install Tetra and Botania
- Create or join a world and grab the holosphere
- Go to any material and you'll see "tetra.stats.integrity" instead of "Integrity"

**Comment by mickelus** [comment]
Fixed in 3.9.0
