### ISSUE TITLE
Picking up a schematic while on a server kicks the player

### ISSUE THREAD

**Issue by belathus** [mickelus/tetra#403]
## Bug Report

**Observed Behaviour**
I was exploring the nether when I found a nether fortress. Found a bunch of the Gild I schematics. No problem pulling them from the chests, though. Decided to try tossing all the items on the ground instead of putting them in my inventory because my inventory was full. The moment I picked up the schematic from the ground, I got booted from the server. From here, I couldn't reconnect to the server until I teleported myself away from the schematic on the ground.

Not sure what exactly happened, I later tried to put the schematics near my worktable. Being a Gild schematic, the first place I put it did nothing, so I had to break it and move it, which caused me to be kicked again. From there, it was easy to realize this problem was from the schematic.

The player's log file doesn't give me much, but the server log file gives a fake crash report.

Crash log: (it doesn't crash, but this is from the server log) https://gist.github.com/belathus/899f1475df059fe3acb29f2a0b0238ff

**Expected Behaviour**
Stay connected to the server when picking up items.

**Minimal setup needed to reproduce**
- Forge version: 36.1.16
- Tetra version: 3.9.2
- Tetra configuration: Unmodified
- Other mods: gonna guess that this crash is Tetra-only, but here is the mod list: https://gist.github.com/belathus/3e4ba6725f4955b3738673bb0d2a75e0

**Steps to reproduce**

Pick up schematic that has been thrown on the ground while playing on a headless server.

**Comment by mickelus** [comment]
What happens if you remove Mahou Tsukai?

**Comment by mickelus** [comment]
Please update to 3.10.0 and see if this issue persists

**Comment by belathus** [comment]
Will do. Do you still want me to try it without Mahou Tsukai?

**Comment by mickelus** [comment]
Try with just the updated tetra first!

**Comment by jinks** [comment]
For what it's worth, here's a basically identical crash log from my personal server: https://gist.github.com/jinks/0a8d1f46dcae9d6d6bf3134866ca3e54

By the looks of it it tries to load a client-side i18n function on the server. Are the scrolls designed to display something fancy while in item form, like they do when hanging on a wall?

Tetra version is 3.9.1, pack is TNP Limitless 3 v 1.10.2a.

**Comment by belathus** [comment]
Seems to work fine on the new version.
