### ISSUE TITLE
Player kicked from server when picking up a Tetra tool using a Sophisticated Backpack with a magnet upgrade

### ISSUE THREAD

**Issue by belathus** [mickelus/tetra#406]
## Bug Report

**Observed Behaviour**
Player with a Sophisticated Backpack with a magnet upgrade accidentally dropped a Tetra tool and got kicked from the server. I went ahead and repeated the error myself. No crash without the backpack and the magnet upgrade.

Crash log: (not actually a crash) https://gist.github.com/belathus/f5e70824691814dcd98926eac7a9a112

**Expected Behaviour**
Not crash.

This is similar to the last report I sent, #403.

**Minimal setup needed to reproduce**

- Forge version: 1.16.5 - 36.1.16
- Tetra version: 3.10.0
- Tetra configuration: 
- Other mods: Sophisticated Backpacks version 2.4.0.259

**Steps to reproduce**
1. Equip sophisticated backpack with magnet upgrade
2. drop Tetra tool on the ground.

**Comment by DreiPixel** [comment]
I have a similar Crash on my server but somewhat different.
Player on my server trade with piglin and got a tetra:scroll_rolled and that caused him to disconnect/crash

https://gist.github.com/DreiPixel/ae7450c40e6e98aa595a2c77b356e62e

**Comment by mickelus** [comment]
It would also help if I had the full log!

**Comment by Darkere** [comment]
Had someone report this to us with a much more detailed explanation: https://github.com/NillerMedDild/Enigmatica6/issues/2323#issuecomment-851936729

**Comment by mickelus** [comment]
Fixed in 3.12.0.
