### ISSUE TITLE
Add Zinc and Brass

### ISSUE THREAD

**Issue by LapizGaming7751** [mickelus/tetra#408]
## Feature Request

**Feature description**
Add in Zinc and Brass as a metal type. Brass is a mix-up of copper and zinc and thus would be a big miss if they aren't added.

**How it improves the player experience**
More items and resources means more stuff to work with (And to Create players, a purpose to put Tetra and Create together)

**Tetra synergies**
Adds to the mod compability list

**Comment by mickelus** [comment]
Should we add dirt tools while we're at it?

**Comment by LapizGaming7751** [comment]
sorry
