### ISSUE TITLE
[Feature Request] 3x3 digging 

### ISSUE THREAD

**Issue by Kiyaku** [mickelus/tetra#41]
## Feature Request

**Feature description**
A 3x3 dig version of some tools (pickaxe, adze). Probably at the cost of speed. 

**How it improves the player experience**
Lots of tool mods, such as tinkers construct, have some form of 3x3 digging. It helps clearing out large amounts of lands relatively quickly.

**Tetra synergies**
It could act as an additional module for the 2nd tool slot (similar to the tool butt).

**Comment by mickelus** [comment]
I've been playing around with AOE mining/digging, I would like to have something different than a simple 3x3 as this is already done by several other mods. Currently leaning towards something similar to how the sickle AOE works, but with the sweep tilted based on pointer movement.

**Comment by NightmareTwilight** [comment]
Maybe 3x1? Make it its own tool? There _is_ a reason why AOE mining is done in so many mods.

**Comment by scribbler957** [comment]
I wonder if Tetra could be configured to work with Spark's Hammers. I'm guessing not.

**Comment by mickelus** [comment]
I'm kinda happy with how aoe mining currently works, so I'm closing this.
@scribbler957 You need to sort out your attitude dude

**Comment by scribbler957** [comment]
@mickelus What attitude? It was an honest curiosity.

**Comment by Gerdathlete** [comment]
> @mickelus What attitude? It was an honest curiosity.

Ikr wtf I just ran into this while looking into tetra. rude

**Comment by arrowflightmain** [comment]
i have not idea what you guys are talking about with the attitude thing, they asked a question about to mods working together from the single sentence he wrote? so where's the attitude from? is it the "im guessing not" part? I was looking for tetra help and found this lol. great look for the mod author.
