### ISSUE TITLE
You should be able to put ghast tears in sockets

### ISSUE THREAD

**Issue by LapizGaming7751** [mickelus/tetra#412]
## Feature Request

**Feature description**
You should be able to put ghast tears in sockets. Since they are quite rare and would need you to traverse the nether (Such as how pristine gem types are rare), it should be a choice. A ghast tear in a socket would provide the wielder passive healing that ignores saturation, and can be upgraded with an eye of ender to buff its effects. A modular item with a socketed ghast tear must be upgraded with a glass pane in order for it to be picked up, else it becomes an empty socket (since you know, tears are liquid). Modular items with a buffed socketed ghast tear explodes when it's destroyed by any means, be it burning, pricking or despawning.

**How it improves the player experience**
Socketed ghast tears would provide passive healing that ignores your saturation therefore not interfering with your hunger. A player with such weapon would be a tough opponent to fight against and likewise for the player wielding it would be able to fend off a zombie heist.

**Tetra synergies**
Tetra contains some magic elements, being the sockets and resources from forges. Adding in ghast tears would be a small but good addition to the mod

**Comment by mickelus** [comment]
Minor modules (like sockets) are typically not upgraded (i.e. you can't improve it with a glass pane or an eye of ender), and it doesn't seem like the choice matters anyway? I.e. you'd always upgrade it with a glass pane. I don't see what the explosion mechanic would add. Passive healing is a strong effect, for me it doesn't make sense that this would be provided by an handheld item?

I appreciate the effort but I'm gonna have to close this.
