### ISSUE TITLE
Breaking slime blocks does not consume durability or hone tools when on a Create contraption

### ISSUE THREAD

**Issue by TheGreatCatAdorer** [mickelus/tetra#413]
## Bug Report

**Observed Behaviour**
Four deployers were mounted on a mechanical bearing which was rotated at 32, 64, and 256 RPM.  Two of the deployers were placing slime blocks and the other two were holding Tetra tools and breaking slime blocks.  The tools neither lost durability nor gained honing progress.

Crash log: 

**Expected Behaviour**

I expected the tools to lose durability and gain honing progress quickly.

**Minimal setup needed to reproduce**

- Forge version: 1.16.5 - 36.1.16
- Tetra version: 1.16.5 - 3.10.0
- Tetra configuration: Default
- Other mods:
- Create version: 1.16.5 - 0.3.1c
**Steps to reproduce**
1. Enter a world.
2. Place a mechanical bearing with the sticky face on the top.
3. Place a radial chassis along the y-axis on the sticky face.
4. Cover each face of the radial chassis in slime using a slimeball.
5. Place deployers with their hands facing upwards horizontally adjacent to the radial chassis.
6. Place barrels diagonally adjacent to the radial chassis.
7. Get two stacks of slime blocks.  Filter a pair of opposite deployers to only using slime blocks and place a stack of slime blocks in the inventory of each.
8. Using a wrench, right-click on the hands of the other pair of deployers to put them into punch mode.
9. Get a pair of Tetra tools.  For each one, select one of the deployers you just set in punch mode, filter it to the tool, and give it the tool.
10. Power the mechanical bearing with Create's rotational force.
11. Right-click on the mechanical bearing with an empty hand to activate it.  The deployers should now be spinning, placing and punching out slime blocks along their path.
12. Wait several seconds, then right-click the mechanical bearing with an empty hand to deactivate it.
13. Right-click on the hand of one of the deployers in punch mode with an empty hand to retrieve its tool.
14. Inspect the durability and honing progress of the tool.  It will not have changed.

**Comment by mickelus** [comment]
Wouldn't this be a better fit for the create issue tracker? Tetra doesn't have any control over the deployers.

**Comment by mickelus** [comment]
Would a vanilla pickaxe take durability damage?

**Comment by mickelus** [comment]
Closing as this has still not been clarified.
