### ISSUE TITLE
Sweep attack in modular swords

### ISSUE THREAD

**Issue by jahirtrap** [mickelus/tetra#414]
**Observed Behaviour**
If the player is in the air the modular swords perform a sweeping attack, in the same way when the player makes a knockback attack and also on the subject of swords, these shouldn't break blocks in creative mode (but it's not very relevant).

**Expected Behaviour**
It's assumed that if "entityPlayer.isOnGround () = false" or the "entity.player.attack.knockback" events occurs, the sweep attack event should not occur, but modular swords perform this action, for example when performing a critical attack or a knockback attack (Sprinting).

**Minimal setup needed to reproduce**
- Forge version: 1.16.5 - 36.1.16
- Tetra version: 3.10.0
- Tetra configuration: default config
- Other mods: Only Tetra mod and dependencies

**Steps to reproduce**
Use any modular sword, perform a critical attack or a knockback attack and compare it with the behavior of vanilla swords.

**Comment by mickelus** [comment]
fixed in 3.11.0.
