### ISSUE TITLE
Infinity not working for special arrows.

### ISSUE THREAD

**Issue by PerfyNormal** [mickelus/tetra#417]
## Bug Report

**Observed Behaviour**
Infinity enchant on bow cord doesn't work for special arrows.

**Expected Behaviour**
No arrow used by a bow with infinity enchant should consumed when released.

**Minimal setup needed to reproduce**
- Forge version:  36.1.13
- Tetra version: 3.9.1
- Tetra configuration: Default settings, no changes.
- Other mods: Abnormals core 3.1.1 , Adorn 1.13.1 , Antique Atlas 5.4.4 , AI Improvements 0.3.0 , Apotheosis 4.5.1 , Aquaculture 2.1.18 , Architectury 1.12.145 , Bedspread 5.1.0.2 , Better Caves 1.1.1 , Better Mineshafts 2.0.3 , Bookshelf 10.0.7 , Bountiful Baubles 0.0.2 , Bountiful 3.3.1 , Byg 1.2 , Citadel 1.6.2 , Cloth Config 4.11.19 , Corpse 1.0.1 , Croptopia 1.3.1 , Curious 4.0.5.1 , Desolation 1.0.5b , Enchantment Descriptions 7.0.8 , End Remastered R36 , Extra Boats 2.1.0 , Fairy Lights 4.0.5 , Falling Tree 2.11.3 , Geckolib 3.0.32 , Good Night Sleep 1.2.14 , Guard Villagers 1.2.4 , Iron Chest 11.2.10 , Jei 7.6.4.87 , Kotlin 1.11.1 , Little Critters 0.0.1 , MCW Bridges 1.05 , MCW Fences 1.0.0 , MCW Furniture 2.0.1 , MCW Roofs 2.0.1 , MCW Windows 1.0.3 , More Vanilla lib 1.4.0 ,  Mythic World 0.3.1.10 , Omni 1.2.2 , Outer End 0.5.5 , Paraglider 1.3.1.0 , Patchouli 1.16.4-50 , Placebo 4.4.2 , Prefab 1.6.5.2 , Rats 7.1.1 , Relics 0.1.11 , Repurposed Structures 2.6.5 , Swing through grass 1.5.3 , The Abyss 2 The Beginning 1.0.9 , The Undergarden 0.5.1 , The Abyss 2 1.9.7 , Towers of the wild 2.0.1 , Tumble Weed 0.4.9 , Two Players One Horse 2.0.2 , Untitled Duck Mod 0.1.2 , Vanilla Excavators 2.2.1 , Vanilla Hammers 2.2.0 , Wall Jump 1.3.7 ,  Waystones 7.4.0 , YungsAPI 1.16.4-6

**Steps to reproduce**
 1 Convert a bow to the Tetra version to allow for changing the cord.
 2 Apply a leather cord on the bow. (may not have to be a leather cord, but it is what I've got)
 3 Apply infinity enchant on the cord.
 4 Fire an explosive arrow, slow arrow or similar.
 5 The fired arrow gets consumed.

**Comment by mickelus** [comment]
Should infinity work for those arrows? Doesn't work for the special arrows in vanilla.

**Comment by PerfyNormal** [comment]
Oh, I wasn't aware. I assumed it did due to that the Apotheosis enchant "Endless Quiver" allows it. It may very well just be my bad. Sorry for post and thanks for reply.
