### ISSUE TITLE
Javelin related crash (ArmorPenetrationEffect)

### ISSUE THREAD

**Issue by ivan-petrovic-soprex** [mickelus/tetra#418]
**Observed Behaviour**
I made a tempered javelin in creative mode, i put down a target dummy from MmmMmmMmmMmm mod.
When javelin hit the training dummy, game crashed.

Crash log:
https://paste.ee/p/rrCB8

**Expected Behaviour**
lack of crash

**Minimal setup needed to reproduce**
- Tetra version: 3.10.0 for 1.16.5
- Forge version: 36.1.3
- Tetra configuration: factory defaults
- Other mods: farmer's delight registers some asm stuff for its knives. others (listed in crash log) shouldn't matter

**Steps to reproduce**
Make a javelin in creative mode. Have the head **tempered**. 
Tempering it causes the crash. I remade the spearhead on the same tool and it doesn't crash if i do not upgrade the spearhead.

**Comment by mickelus** [comment]
This needs to be updated to include all fields in the bug report template

**Comment by ivan-petrovic-soprex** [comment]
updated.

**Comment by mickelus** [comment]
Good job 👍 

> Tempering it causes the crash.
Is it when you temper it that it crashes? Or is it when you hit a target dummy as you described before? Does this only occur for the target dummies in your instance, or does it happen regardless of what you're hitting?

**Comment by ivan-petrovic-soprex** [comment]
double checked. it's just a target dummy. 
maybe it's on their end...

**Comment by mickelus** [comment]
They might be calling some stuff that they shouldn't but I should also fix the application of the penetration effect on my side so this can't happen 😅

**Comment by mickelus** [comment]
Fixed in 3.12.0.
