### ISSUE TITLE
Allow potions of other mods in the potion bag.

### ISSUE THREAD

**Issue by Deshiba** [mickelus/tetra#42]
I'd like a way to add potions from other mods to the potion bags.

This improves the player experience by making Tetra more compatible with other mods. It also allows Tetra to integrate with modpacks more fluently. It would suffice to just have the option and allow integration trough config so we'd have to add stuff to it.

**Comment by mickelus** [comment]
Fixed this in 0.25.0. I don't have time to write about it in the docs. The setup is similar to how you configure modules and schemas but in a different subfolder, poke me on discord and I can give you some directions.
