### ISSUE TITLE
Alex's Mobs Falcon Crash

### ISSUE THREAD

**Issue by LordOfDaVoid** [mickelus/tetra#422]
## Bug Report

**Observed Behaviour**
I attempted to control a Bald Eagle from Alex's Mobs with a Falconry Glove while the Eagle was equipped with a Falcronry Hood. Instant crash. 
Crash log: 
[crash-2021-05-15_23.18.24-client.txt](https://github.com/mickelus/tetra/files/6488697/crash-2021-05-15_23.18.24-client.txt)

Note: Calls an unexpected error on the RevengeGui.

**Expected Behaviour**
Enter the falcon flight perspective

**Minimal setup needed to reproduce**

- Forge version: 1.16 36.1.0
- Tetra version: 1.16-3.0.8
- Tetra configuration: Default
- Other mods: Alex's Mobs

**Steps to reproduce**
Tame a Bald Eagle with Fish Oil
Equip it with a Falconry Hood with rclick
Hold falconry glove
Right click Eagle
Punch to crash

Sorry was editing title and fatfingered the enter key

**Comment by mickelus** [comment]
Probably fixed in 3.11.0.
