### ISSUE TITLE
Tetra Enchanting with Quark Oddities Matrix Enchanting Bug

### ISSUE THREAD

**Issue by Drakoflame** [mickelus/tetra#424]
## Bug Report

**Observed Behaviour**
Enchantments don't show up, don't take magic cap, but still "work"

**Expected Behaviour**
Enchantments show up

**Minimal setup needed to reproduce**
Using the modpack "Engineers Life 2"
Forge: 36.1.0
Quark: 2.4-311
Quark Oddities: 1.16.3
Tetra: 3.10.0

**Steps to reproduce**
Insert Tetra tool into enchanting table. Use Quark Oddities Matrix Enchanting to get, then apply enchantments. Enchantments do not appear on the tetra tool, but do effect it (Unbreaking gave a shield more durability.) I'm not sure what the mods were, but additional enchantments on the shield were "Bullwark" and "Phalanx". Bullwark will randomly teleport attackers, and Phalanx will increase weilder's speed when blocking. Both of these effects worked (greatly, my friend got teleported 20 blocks away and you can do heck'n zoomies with the shield out), the only "issue" is that the enchantments don't show up on the shield (neither glint nor on parts), and don't take away from magic capacity, as expected.

**Comment by Drakoflame** [comment]
Update to this issue:
Enchantments are lost if you modifty any part of the tool.

**Comment by LTCatt** [comment]
This happens in my modpack too. Using Quark Oddities Matrix Enchanting also.

**Comment by Potato6969git** [comment]
its not just with quark- a similar thing happens with eidolon soul enchanter (a thing that can enchant already enchanted items, starting from only level 1's). you put an already enchanted tetra sword and apply an enchantment- no change shows up in the tooltip thing, but the effect is still there.
to reproduce, enchant a tetra sword with something random (e.g. mending), put it in the soul enchanter from the Eidolon mod, apply an enchantment, it works but doesnt show up

**Comment by mickelus** [comment]
This should have been fixed in 4.3.0, although the enchantments won't show up on parts until you do something with the item in a workbench.
