### ISSUE TITLE
The enchanting table sense my pick as a sword.

### ISSUE THREAD

**Issue by Winemaker88** [mickelus/tetra#427]
## Bug Report

**Observed Behaviour**
I made a lead pick, put an iron handle on it, and put in a lapis lazuli. When I put it on the enchanting table, he sensed my pick to the sword and wanted to put a smite IV on it.
Crash log: ---

**Expected Behaviour**
Enchanting table didn't perceive my lead pickaxe as a pick, but as a sword.

**Minimal setup needed to reproduce**
I play with the latest versions of Valhelsia 3.
- Forge version: Forge 36.1.23
- Tetra version: tetra-1.16.5-3.10.0
- Tetra configuration:
- Other mods:

>

**Comment by mickelus** [comment]
> Expected Behaviour
> Enchanting table didn't perceive my lead pickaxe as a pick, but as a sword.

And that is what you expected?

**Comment by Winemaker88** [comment]
> > Expected Behaviour
> > Enchanting table didn't perceive my lead pickaxe as a pick, but as a sword.
> 
> And that is what you expected?

 No, I'm sorry I misinterpreted the question. I was expecting to pick pick enchants at the enchanting table.

**Comment by LTCatt** [comment]
Anyway, how strange is it to attach a smite enchantment to a pick...
In the expected state, if I have an axe/pick tool, it should be able to accept axe and pick enchantments, but not sword.
A better approach might be to check the two heads of the tool separately and have it accept enchantments for both head types. I think.

**Comment by Winemaker88** [comment]
> > Expected Behaviour
> > Enchanting table didn't perceive my lead pickaxe as a pick, but as a sword.
> 
> And that is what you expected?

No, I'm sorry I misunderstood the question. I can not speak English well. I was expecting the enchanting table to offer me enchants that could be put on a pickaxe.

**Comment by mickelus** [comment]
> Anyway, how strange is it to attach a smite enchantment to a pick...
This won't be constructive, closing!
