### ISSUE TITLE
Crash report - punching grass

### ISSUE THREAD

**Issue by Tobanyi** [mickelus/tetra#428]
## Bug Report

**Observed Behaviour**
Game crash when punching grass

Crash log: 
https://pastebin.com/NyVSnei1

**Expected Behaviour**
No game crash

**Minimal setup needed to reproduce**
- Forge version: 36.1.0
- Tetra version: 3.11.0
- Tetra configuration: Default
- Other mods: See crash log

**Steps to reproduce**
Install mods, punch grass.

**Comment by mickelus** [comment]
fixed in 3.11.1.
