### ISSUE TITLE
Use arrows from quiver

### ISSUE THREAD

**Issue by Deshiba** [mickelus/tetra#43]
## Feature Request
I'd love the ability to use arrows in the quiver, with a quick select option to choose which one

**How it improves the player experience**
It would help to not need to open the tool belt or quick select bar and first move the arrows to inventory before firing.

**Tetra synergies**
It would make the bow instantly usable and would increase the value of the quiver.

**Comment by mickelus** [comment]
I thought that this had been implemented already, but it's seem like that is not the case. I'll use the order in which the arrows are placed in the quiver inventory to decide which arrow will be used, then the player can rearrange the inventory to choose which stack will be used.

**Comment by Deshiba** [comment]
Sure, that works. Set up the arrows before hand when out hunting.

**Comment by mickelus** [comment]
Implemented in https://github.com/mickelus/tetra/commit/90aed69f13e6acafae87d393971be189deaba21f, will ship with 0.23.0
