### ISSUE TITLE
Disable tetra villager trades

### ISSUE THREAD

**Issue by jahirtrap** [mickelus/tetra#430]
## Feature Request

**Feature description**
Add an option to disable villager trades

**How it improves the player experience**
Tetra objects occupy many spaces in the villagers and avoid obtaining more variety in the trades, it would be nice to be able to disable them through the config file.

(I needed a name tag -.-)
![2021-05-24_04 48 08](https://user-images.githubusercontent.com/75038202/119329933-51731e00-bc4b-11eb-8043-3ea08b54e69f.png)

**Comment by Ictoan42** [comment]
I'd second this, toolsmiths often have multiple duplicate trades, like this guy with 3 Metal Expertise scrolls and 2 Hammer efficiency scrolls 
![image](https://user-images.githubusercontent.com/62564272/121562852-c5fed880-ca11-11eb-99e1-466d90f21137.png)
