### ISSUE TITLE
Support for Unique Enchantments

### ISSUE THREAD

**Issue by Crazydude323** [mickelus/tetra#435]
## Feature Request

**Feature description**
Support for the enchantments added by Unique Enchantments.

**How it improves the player experience**
The enchantments from Unique Enchantments are rather interesting, with many being conditional and some in particular support focusing on different stats when customizing tools.

**Tetra synergies**
Two of the enchantments, Swift Speed and Focused Impact, increase damage depending on how high or low your attack speed is. This encourages you to prioritize attack speed, raising it as high as you can, or quite differently, tanking it hard. This puts the focus on a different aspect of tool customization; Focused Impact particularly encourages you to do something you'd normally never consider.

On the tool side of things, the Momentum enchant makes you mine faster the longer you keep going, naturally encouraging you to raise Durability as high as you can, even at the expense of mining speed (which is normally a high priority).

I elected to make this ticket after seeing you were open to the idea of modded enchant compatibility in #79

**Comment by mickelus** [comment]
I need the ID's of all of the enchantments.

**Comment by Crazydude323** [comment]
Can do; I'll have them here tomorrow.

**Comment by Crazydude323** [comment]
In order to avoid a long post, I posted the info to a pastebin: https://pastebin.com/VwnKmxXi

I included the name and ID of each enchantment, separated by a |, as well as categories for Weapon (swords and axes by default), Bow, Tool, and Curse enchants. The Tool enchants have info for exactly what tools they're able to go on, and Curse enchants can go on anything normally.

Enchantments with multiple applicable items (such as enchants that could go on a tool or a weapon) are listed in each category they could apply to. I also marked down the enchants that affect durability, and the singular enchant that affects tool use range, in case you need that information. All of the durability affecting enchants just restore durability, they don't add to it or do anything else strange.

If you need any more info, or if I missed something, feel free to let me know!

**Comment by WilliamBlaze** [comment]
considering there's also now two "add-on mods" for Unique Enchantments, (and that I too have a vested interest in requesting this) I'm going to drop in here with those two mods and the enchantments/curses added by them.

IDs From Unique Enchantments Battle:
Ares Fragment
Celestial Blessing
Lunatic Despair

IDs From Unique Enchantments Utilities:
Famine's Odium
Phanes Regret
Poseidon's Soul
Sleipnir's Grace
Thick Pick
_____
There were other IDs included in the listings for UE.Util, but either they were for Armor or Elytra enchantments.

**Comment by mickelus** [comment]
Fixed in 4.3.0.
