### ISSUE TITLE
Ex Nihilo Compatiblity

### ISSUE THREAD

**Issue by Angular-Angel** [mickelus/tetra#436]
## Feature Request

Ex Nihilo is another minecraft mod focused on adding more ways to generate vanilla resources from other vanilla resources, particularly in a skyblock environment. Of note, it adds a pair of new tools, the Hammer and the Crook. Hammers are used to break blocks and give you a different kind of block back - they turn stone into cobble, cobble into gravel, gravel into sand, sand into dust, etc. Crooks are used to break leaves and obtain more saplings than normal, and to pull animals towards you. Both of these tools are fairly useful, in my opinion, but they are not compatible with Tetra - the hammers from the two mods have conflicting recipes, and tools from Ex Nihilo cannot be repaired, upgraded, or customized via Tetra. I have also created a counterpart to this issue for the Ex Nihilo github page: https://github.com/NovaMachina-Mods/ExNihiloSequentia/issues/213

**Feature description**
Remove the ex nihilo hammer when Tetra is present, and add it's functionality to the Tetra hammer. Add a Tetra crook with all the usual tetra functionality, and allow ex nihilo crooks to be upgraded to match. The crook should probably belong to the same class of tools as shovels and spears.

**How it improves the player experience**
This would help synergize the experience of playing these two mods next to each other, and

**Tetra synergies** 
This would also expand the shovel class of tools, which is currently a little barren.

**Comment by mickelus** [comment]
Please rewrite this so it's understandable for someone who doesn't know what Ex Nihilo is.

**Comment by TacocaTYT** [comment]
this would also enocurage modpack authors to use tetra over tinkers

**Comment by Angular-Angel** [comment]
Is the current write-up good? I can add more if you need it.

**Comment by mickelus** [comment]
It's good! 

Tetra hammers can't break things that pickaxes typically can and I can't change content dynamically and removing item from another mod is rather obtrusive, so it's not something I'm going to implement in tetra.

You can however do most of this with a datapack by:
* using the loot modifiers from ex nihilo together with modular item predicates from tetra
* adding the pickaxe tool type to hammer heads in tetra
* adding crafting recipes for crafting all hammers directly (if you don't want to go trough the typical progression)

You'd probably need cubeJS or some other mod for removing the ex nihilo hammers.

Hop onto discord if you need help with the datapack and we'll give you a hand.
