### ISSUE TITLE
Warforged weapons don't have access to the same enchants as swords

### ISSUE THREAD

**Issue by NillerMedDild** [mickelus/tetra#439]
## Bug Report

**Observed Behaviour**
Warforged weapons don't have access to the same enchants as swords.
This was tested with the enchants Knowledge of the Ages (Apotheosis) and Ender Disruption (Ensorcellation)

**Expected Behaviour**
For Warforged weapons to accept the same enchants as swords

**Minimal setup needed to reproduce**

- Forge version: 1.16.5-36.1.16
- Tetra version: 1.16.5-3.10.0
- Tetra configuration: Enigmatica 6 v0.4.14, so a lot 😄 
- Other mods: Apotheosis

**Steps to reproduce**
See video in original issue: https://github.com/NillerMedDild/Enigmatica6/issues/2329

**Comment by mickelus** [comment]
Need to figure out a better way to organize all of the enchantments. I've added some sword enchantments for the double headed tools but that's also causing issues (#427), so they should probably not be considered applicable when enchanting tools in an enchanting table.

**Comment by mickelus** [comment]
Fixed in 4.3.0.
