### ISSUE TITLE
Silk Touch compat bug.

### ISSUE THREAD

**Issue by Deshiba** [mickelus/tetra#44]
## Bug Report

**Observed Behaviour**
When mining an ore from Underground Biomes with a silk touch tool, it completely destroys the block.

**Expected Behaviour**
When mining an ore from Underground Biomes with a silk touch tool, to get the ore block.

**Minimal setup needed to reproduce**
- Forge version: 14.23.5.2768
- Tetra version: 0.21.5
- Other mods: Underground Biomes 1.3.1 (previously underground biome construct
- Tetra configuration: https://pastebin.com/Ejhu8qqH

**Steps to reproduce**
1. Load the above mods
2. Obtain a pickaxe with silk touch
3. Mine an ore in the world

**Console spam**
When mining happens I get this console spam on server: https://pastebin.com/vJHtTHEz

**Screenshots/Videos**
![silk touch](https://user-images.githubusercontent.com/10565800/51477441-c6d33900-1d88-11e9-8679-3963abe8700c.gif)

**Comment by Deshiba** [comment]
After further testing, the same thing happens with Tinker's Construct ores

**Comment by mickelus** [comment]
Fix will be available in 0.23.0!
