### ISSUE TITLE
Sweeping Edge IX cannot be applied to Tetra Swords.

### ISSUE THREAD

**Issue by The-Arcanian** [mickelus/tetra#440]
## Bug Report

**Observed Behaviour**
Sweeping Edge IX cannot be applied to Tetra Swords.

**Expected Behaviour**
Sweeping Edge IX to be appliable to Tetra Swords.

**Minimal setup needed to reproduce**

- Forge version: 36.1.2
- Tetra version: 3.8.0
- Other mods: Apotheosis 4.6.0, Quark r2.4-312

**Steps to reproduce**
1. Create Tetra Sword.
2. Combine a Sweeping Edge VIII book, available because of Apotheosis, with a Sweeping Edge VIII Ancient Tomb from Quark to create a Sweeping Edge IX book.
3. Open the enchantment window for the Tetra Sword's blade and see that the Sweeping Edge IX book is not a valid input.

**Comment by mickelus** [comment]
Won't fix.
