### ISSUE TITLE
Unbreaking IX cannot be applied to Tetra Tools.

### ISSUE THREAD

**Issue by The-Arcanian** [mickelus/tetra#441]
## Bug Report

**Observed Behaviour**
Unbreaking IX cannot be applied to Tetra Tools.

**Expected Behaviour**
Unbreaking IX to be appliable to Tetra Tools.

**Minimal setup needed to reproduce**

- Forge version: 36.1.2
- Tetra version: 3.8.0
- Other mods: Apotheosis 4.6.0, Quark r2.4-312

**Steps to reproduce**
1. Create Tetra Tool.
2. Combine an Unbreaking VIII book, available because of Apotheosis, with an Unbreaking VIII Ancient Tomb from Quark to create an Unbreaking IX book.
3. Open the enchantment window for the Tetra Tools's handle and see that the Unbreaking IX book is not a valid input.

**Comment by mickelus** [comment]
Won't fix.
