### ISSUE TITLE
Hide is worse than leather despite being harder to obtain

### ISSUE THREAD

**Issue by TacocaTYT** [mickelus/tetra#442]
## Feature Request

**Feature description**
Hide potion punches for example have less slots than leather despite being a harder resource to obtain. an improvement would be swap leather and hide extra a lot counts so it gives more for hide than leather .

**How it improves the player experience**
it gives a reason to hunt down rabbits to upgrade your leather stuff 

**Tetra synergies**
Since tetra is about upgrading tools sort of this would give a better sense of progression

**Comment by mickelus** [comment]
The goal is not for one to be better than the other.

**Comment by TacocaTYT** [comment]
than what is the point considering one is drastically better? even making the hide pouch hood two potions would make more sense
