### ISSUE TITLE
behidn the scenes support for ove 36 pouch slots

### ISSUE THREAD

**Issue by TacocaTYT** [mickelus/tetra#444]
## Feature Request

**Feature description**
Behind the scenes removal of the hardcap of pouch slots, preferably with either a really large UI (Unwieldly and awkward) or using the forged container UI style, with tabs on the left you can click on.

**How it improves the player experience**
It enables datapacks to add better puch materials, especially when dealing wiht modded gameplay where sometimes it would be nice to have, say, 72 slots instead of 32
**Tetra synergies**
Allegedly it hard crashes if your belt has over 36 pouch slots, which is annoying and limiting when amkign a datapack.

**Comment by mickelus** [comment]
Won't fix.

**Comment by TacocaTYT** [comment]
if you wont fix it for qhatever reason could you at least point me in teh direction of whatever code opens this gui, so i can hoepfully implement a workaround such as binding it to a differetn gui/inventory?
