### ISSUE TITLE
Toolbelt Crash

### ISSUE THREAD

**Issue by Deshiba** [mickelus/tetra#45]
## Bug Report

**Observed Behaviour**
A crash occurs while holding the toolbelt in your main hand, you hotswap while holding down V and then swap your mainhand and off hand item.   

**Expected Behaviour**
I expect this crash to occur because you are basically trying to insert the toolbelt into itself.

**Steps to reproduce**
- Have a toolbelt in the main hand and an item in the off hand. 
- Hold V to hotswap.
- Press F to alternate main and off hand.
- Select any item from the quickmenu and release.

**Comment by mickelus** [comment]
Fixed in 0.24.2!
