### ISSUE TITLE
Support for "Random Enchants" Mod's enchantments

### ISSUE THREAD

**Issue by WilliamBlaze** [mickelus/tetra#450]
The [mod](https://www.curseforge.com/minecraft/mc-mods/random-enchants)'s source is found [here](https://github.com/Tfarcenim/RandomEnchantments)

The following list is the IDs for both enchantments and curses from the mod:

Solar
Eternal
Resistant 
Magnetic 
Global Traveler
Back To the Chamber
Exploding
Harvesting
Homing 
Phasing
Piercing 
Quick Draw
Ricochet 
Shattering
True Shot
Torches
Transposition 
Teleportation 
Cursed Jumping
Disarm
Floating
Lightning
Paralysis
Swiftness
True Lifesteal
Combo
Equal Mine
Momentum
Obsidian Buster
Stonebound
Stonelover
Lumberjack
Snatching
Grappling
Breaking
Butterfingers
Fumbling
Shadows
______

There are several others IDs missing from the current list that have been newly added to the mod; but these are the only IDs I can remember off the top of my head. Armor only enchantments have been excluded from the listed IDs above as currently there seems to be no means of making armor with Tetra anyways.

**Comment by mickelus** [comment]
Those are not the enchantment IDs, e.g. the enchantment ID for Global Traveler is probably something along the lines of "randomenchantments:global_traveler". The second part of the ID can be found here https://github.com/Tfarcenim/RandomEnchantments/blob/master/src/main/java/com/tfar/randomenchants/ench/enchantment/EnchantmentGlobalTraveler.java#L41, I made a guess on the namespace.

**Comment by mickelus** [comment]
Fixed in 4.3.0.
