### ISSUE TITLE
Ticking Entity crash

### ISSUE THREAD

**Issue by Dryelo** [mickelus/tetra#451]
## Bug Report
I had two server crashes while fighting an armored zombie from Dungeons Mobs.

The dev there told me to let you know... so here I go

**Observed Behaviour**
Server crashes while fighting an armored zombie.

Crash log: [crash-2021-06-16_18.44.26-server.txt](https://github.com/mickelus/tetra/files/6680511/crash-2021-06-16_18.44.26-server.txt)

**Minimal setup needed to reproduce**

- Forge version: <1.16.5 v36.1.16>
- Tetra version: <tetra-1.16.5-3.10.0>
- Tetra configuration: 
- Other mods: Enigmatica 6 pack plus some other mods

link to my original post:
https://github.com/Thelnfamous1/Dungeons-Mobs/issues/26

**Comment by mickelus** [comment]
This has been fixed, you need to update to latest :)

Closing!
