### ISSUE TITLE
Enchantment on Extractor removed after placing

### ISSUE THREAD

**Issue by AlmightyAnubis** [mickelus/tetra#452]
## Bug Report

**Observed Behaviour**
After placing and breaking the Cythonic Extractor, it lost its mending enchantment. I am not sure if this is intended, but this might be a bug.

**Expected Behaviour**
Keeping the enchantment.

**Minimal setup needed to reproduce**

- Forge version: 1.16.5 - 36.1.23
- Tetra version: tetra-1.16.5-3.11.1
- Tetra configuration: 
[tetra_config.txt](https://github.com/mickelus/tetra/files/6682942/tetra_config.txt)
- Other mods: Minecolonies Modpack (current version 20.06.2021)

**Steps to reproduce**
 1. Get Extractor
 2. Apply Mending with anvil
 3. Place extractor
 4. break Extractor
 5. Mending is gone

**Comment by mickelus** [comment]
The extractor isn't enchantable (unless you're in creative) so it's not supposed to retain enchantments either :c

Closing!
