### ISSUE TITLE
Thrown shields deal no damage

### ISSUE THREAD

**Issue by beninjamin99** [mickelus/tetra#455]
## Bug Report

**Observed Behaviour**
Shields with the aerodynamic trim ability don't seem to do any damage when thrown. I tested using a very basic shield (default Minecraft with trim) on a chicken, and after a dozen throws, the chicken was fine. The damage value reads 7.50, however, and should easily one-shot the chicken at 4 HP. Simply put, are thrown shields supposed to do damage, or is it just a cool thing to do?

The shield:
![image](https://user-images.githubusercontent.com/47581431/122769039-7023ff00-d261-11eb-8dc5-634155cf9549.png)

**Expected Behaviour**
Thrown shields should do at least some damage, otherwise the ability seems rather useless. Even if it's only half, it ought to do something to the target rather than just giving them invulnerability frames.

**Minimal setup needed to reproduce**
- Forge version: 36.0.1
- Tetra version: 3.12.0
- Tetra configuration: Unmodified, but double check: https://gist.github.com/beninjamin99/36af678dfc9e8661de843f151691b07c
- Other mods: Just Enough Items

**Steps to reproduce**
I guess throw a shield at stuff. Chickens are good for low HP.

**Comment by mickelus** [comment]
Fixed in 3.13.0.

**Comment by beninjamin99** [comment]
Thanks a bunch! You may not see this since it got closed, but I really appreciate the hard work you put into this mod! Keep it up!
