### ISSUE TITLE
Scroll Missing Localization

### ISSUE THREAD

**Issue by WenXin20** [mickelus/tetra#456]
## Bug Report

**Observed Behaviour**

- When the scroll item is placed on the ground, it displays as `item.tetra.scroll.unknown.name` when looked at with Hwyla or The One Probe.

**Expected Behaviour**

- It should display as "Scroll".

**Minimal setup needed to reproduce**

- Forge version: v36.1.32
- Tetra version: v3.12.0

**Steps to reproduce**

1. Place a scroll
2. Use hwyla/theoneprobe to observe.

**Comment by mickelus** [comment]
Fixed in 3.13.0.
