### ISSUE TITLE
/give tetra:holo gives an invisible holosphere and cause crash in Valhelsia 3

### ISSUE THREAD

**Issue by milibucket** [mickelus/tetra#457]
## Bug Report

**Observed Behaviour**
Running the command < /give (playername) tetra:holo >  caused a crash in Valhelsia and continues to crash when trying to re-enter. 
When attempting to run the same command on an empty instance with only tetra, an invisible holosphere is given. 
The crash may be due to the modpack

Crash log:  on valhelsia 3
[crash-2021-06-23_17.56.33-client.txt](https://github.com/mickelus/tetra/files/6701140/crash-2021-06-23_17.56.33-client.txt)

**Expected Behaviour**
/give tetra:holo should give a normal holosphere for normal use without going into creative mode.

**Minimal setup needed to reproduce**
This is for the empty instance, have yet to do more testing with valhelsia 3
- Forge version:  1.16.5 - forge - 36.1.25
- Tetra version:  1.16.5-3.12.0
- Tetra configuration:  default
- Other mods:  mgui-1.16.5-3.2.0

**Steps to reproduce**
type < /give (playername) tetra:holo >

**Comment by mickelus** [comment]
It crashes because you're using tetra-1.16.5-3.11.1 in the modpack, that crash was fixed in 3.12.0.

> /give tetra:holo should give a normal holosphere for normal use without going into creative mode.
You're giving yourself a modular item without modules, which is not "normal".

Closing!
