### ISSUE TITLE
Tetra won't load without curios update when curios is already updated

### ISSUE THREAD

**Issue by VallenFrostweaver** [mickelus/tetra#458]
Minecraft 1.16.5
Forge 36.1.32
Tetra 3.8.0
Curios 4.0.5.2

I think this is self explanatory. xD
![image](https://user-images.githubusercontent.com/13642054/123303862-2c0d5480-d516-11eb-9995-f84c0e45ad46.png)

**Comment by mickelus** [comment]
I fixed this at some point, does it persist if you update to latest tetra?

**Comment by VallenFrostweaver** [comment]
Aw poo. The launcher said it was the latest version but when I look on Curseforge I can see it isn't. I'll update. Sorry for the bogus report.
