### ISSUE TITLE
Missing localization strings

### ISSUE THREAD

**Issue by mkaito** [mickelus/tetra#459]
## Bug Report

**Observed Behaviour**

![image](https://user-images.githubusercontent.com/20434/123346600-993ddb80-d550-11eb-9c67-4f1ea165efe6.png)

**Expected Behaviour**

Property names should be displayed

**Minimal setup needed to reproduce**

- Forge version: 36.1.25 
- Tetra version: 3.12.0 
- Tetra configuration: Stock
- Other mods: Too many to list, using Stacia Expert 1.11.4

**Steps to reproduce**
* Put tool in workbench

**Comment by mickelus** [comment]
Fixed in 3.13.0.
