### ISSUE TITLE
No damage on Tetra swords? (DireWolf20 1.10.1/MC Ver 1.16)

### ISSUE THREAD

**Issue by Arensbak** [mickelus/tetra#460]
## Bug Report

When making swords with Tetra in Direwolf20 1.10.1 using modded materials (Bronze) for the blade material type, the weapon does less than base damage and has no sweeping effect. The details on the item read that it should do 9dmg but does ~4 and has none of the detailed effects. I have tried with a Lead machete and a Bronze greatsword.

**Comment by mickelus** [comment]
Closing this as it's missing all the required fields of a bug report :)
