### ISSUE TITLE
Reword Hone: Gild instruction or rework placement requirements

### ISSUE THREAD

**Issue by Shadowex3** [mickelus/tetra#461]
## Feature Request

**Feature description**
The instructions for the "Hone: Gild ##" scrolls state "Has to be placed directly on top of a workbench to function". Even as a native level speaker of English I thought this meant the scroll needs to literally be placed on the top of the workbench block itself. Since that's not physically possible I'm taking it to mean this must be placed on a block  that is 1 Y-level above the workbench and immediately adjacent to the workbench's block.

I suggest one of the following:

1. Reword the scroll so it's clear the workbench must be directly against a wall, and the scroll has to go on the wall tile one Y-level above the workbench.
2. Alter the scroll placement requirements to a 3x3x1 cuboid exactly 1 y-level above the workbench. This can even be gated behind another block if necessary, such as hammer-clicking a cartographer's table to turn it into a "blueprint table" or something.

**How it improves the player experience**
1. This option makes the placement of both the scroll and workbench explicitly clear.
2. This option allows players more flexibility in base design. Workbenches won't be forced to be placed with one cardinal side directly against a wall. This allows for in-floor or center-of-room workbenches.

<img src="https://user-images.githubusercontent.com/57022604/123499062-a1734500-d63c-11eb-8800-1462fbdde394.png" width=50% height=50%>

**Tetra synergies**
This is a simple QoL change that keeps the feel of closely studying an "intricate schematic" while allowing some more flexibility in base design. Players will still be required to take care in scroll placement, but will be able to have a workbench that isn't directly abutting a wall.

**Comment by mickelus** [comment]
As with all blocks you need to hold down shift to place it against a block that has right-click behaviour. Closing.

**Comment by Shadowex3** [comment]
Well apparently I'm just an idiot who hasn't played minecraft in too many years, sorry about that.
