### ISSUE TITLE
[Bug] Right Clicking Forged Container with T4 Hammer causes crash

### ISSUE THREAD

**Issue by NillerMedDild** [mickelus/tetra#462]
### Observed behaviour

Using a tier 4 hammer from Tetra and right clicking on a Forged Container to open it causes a crash to the launcher to occur. 

### Expected behaviour

No crashing.

### Steps to reproduce

1. Right-click Forged Container with T4 Hammer.
2. Crash

### Crashlog

https://pastebin.pl/view/cdc90883

### Tetra version

1.16.5-3.14.1

### mGui version

1.16.5-3.2.0

### Forge version

1.16.5-36.1.31

### Other mods

Many! Enigmatica 6 v0.5.4

Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2649

**Comment by mickelus** [comment]
Is this in a ruin in a quark cave?

**Comment by NillerMedDild** [comment]
Not a Quark Cave no, but it was in an underground dungeon. Reply from the reporter:

> It was in a Rogue Like Dungeon. When I found another ruin, I found that the crate actually generated with only half of it, and caused a crash when trying to open it.

**Comment by mickelus** [comment]
This should have been fixed in 3.20/4.1.0.
