### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by LuvPuma** [mickelus/tetra#463]
### Observed behaviour

When I open Minecraft it tell me to get curios 4 but I already have curios API

### Expected behaviour

Well I thought it would work with the Curios api

### Steps to reproduce

I opened minecraft 
Says i need Curios 4

### Crashlog

https://gist.github.com/LuvPuma/174b0c3baf9213a7ea82e78cd570a141

### Tetra version

3.14.1

### mGui version

3.2.0

### Forge version

1.16.5-31.1.32

**Comment by mickelus** [comment]
You're on 3.7.0 and you need to update.

**Comment by LuvPuma** [comment]
thanks
