### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Maplefox0527** [mickelus/tetra#467]
### Observed behaviour

In the Modpack-Valhelsia 3 ,player can not use the tier7 hammer with [the forge hammer(which have put on two combustion chamber on it)]to build the bow with aeternium ingot (which need the tier9 hammer.The combustion chamber's features(level up the hammer) did not work on it:( 
I have spent almost 2 hours on this problem , I really hope this good mod can give me the most powerful bow in Valhelsia 3.

Thanks you
![did not working](https://user-images.githubusercontent.com/87497891/125846930-a3788335-a094-4a32-aee6-32b17e0266d8.jpg)
![hammer level](https://user-images.githubusercontent.com/87497891/125846946-e3a0daa6-b550-46d0-95fc-dca80d3a084b.JPG)
![the bow which need the T9 hammer](https://user-images.githubusercontent.com/87497891/125846953-9aafa61a-8e16-47e8-b436-1a0a0b0ea603.jpg)
![the forge hammer(which have put on two combustion chamber on it)](https://user-images.githubusercontent.com/87497891/125846961-421004a8-242f-4b0a-9fc4-84353e691575.png)

### Expected behaviour

I can use T9 hammer:)

### Steps to reproduce

![did not working](https://user-images.githubusercontent.com/87497891/125847113-7eeeb9e5-7649-42db-a7ff-f629b4fabc46.jpg)
![hammer level](https://user-images.githubusercontent.com/87497891/125847127-512d1196-b545-478f-9771-c1ea899b03c7.JPG)
![the bow which need the T9 hammer](https://user-images.githubusercontent.com/87497891/125847134-18920b3b-230d-4448-8ef3-59e9fa8ca166.jpg)
![the forge hammer(which have put on two combustion chamber on it)](https://user-images.githubusercontent.com/87497891/125847142-359efa7f-1b8a-4e51-8cfe-8d0796d58e79.png)

### Tetra version

3.14.1

### mGui version

3.2.0

### Forge version

36.1.32

### Other mods

Modpack Valhelsia3-1.16

**Comment by StrangerSon71** [comment]
The base tier of a forge hammer is 5, 2 combustion chambers provide +2, or 7 total, hammer level. I experienced the same thing with Dragonsteel crossbow, I recommend taking it up with the tetranomicon dev, as he is the person adding these materials.

**Comment by mickelus** [comment]
Thanks for clarifying @StrangerSon71! Closing.
