### ISSUE TITLE
[Bug] Tetra datapack's lang files are not recognized when using OpenLoader

### ISSUE THREAD

**Issue by egshels** [mickelus/tetra#468]
### Observed behaviour

While using Openloader, I made a datapack for some new Tetra tool materials but all their names weren't working, even though the lang files were in place and properly formatted. Moving the resource pack to my game's resourcepacks folder and enabling it had it work normally.

### Expected behaviour

Lang files work normally when used through Openloader

### Steps to reproduce

1. Create a normal datapack using Openloader
2. Witness

### Tetra version

3.14.1

### mGui version

3.2.0

### Forge version

1.16.5 - 36.1.32

### Other mods

OpenLoader 9.0.3

**Comment by mickelus** [comment]
Lang files are not loaded from datapacks.

**Comment by egshels** [comment]
Apologies, that was a typo. I meant using OpenLoader to load a resource pack that contained a lang file

**Comment by mickelus** [comment]
I'm unable to reproduce this. Minecraft handles localization, so it's unlikely that this is related to tetra. Can you provide more details about what you're doing?

**Comment by egshels** [comment]
..Updating OpenLoader seemed to have fixed the issue. Apologies for wasting your time :P
