### ISSUE TITLE
[Bug] crash if battleadze dropped before lunge hits

### ISSUE THREAD

**Issue by BradFeng02** [mickelus/tetra#471]
### Observed behaviour

I was curious so I used the battleadze lunge (with the hammer momentum thing) and dropped my adze before landing on a mob and the game crashed
(This was valhesia 3 with a launcher so I'll be honest idk the versions of anything, but it shouldn't matter unless this issue was already patched)

### Expected behaviour

Not crash

### Steps to reproduce

Battleforge adze
Lunge
Drop adze while in the air
Land on mob

### Tetra version

3

### mGui version

2?

### Forge version

1.16.5?

### Other mods

Valhesia 3.3.1

**Comment by mickelus** [comment]
Can you provide me with the crash log?

**Comment by BradFeng02** [comment]
[crash-2021-07-26_03.40.25-server.txt](https://github.com/mickelus/tetra/files/6881811/crash-2021-07-26_03.40.25-server.txt)

sorry i wrote the issue in bed, here's the crash report

**Comment by mickelus** [comment]
Fixed in 4.2.1.
