### ISSUE TITLE
More Apotheosis Enchantments

### ISSUE THREAD

**Issue by SmolFloof** [mickelus/tetra#473]
### Feature description

Apotheosis enchantments and the improved vanilla enchantments. The improved Looting VII enchantment is working, but none of the other ones like Unbreaking V or any of the enchantments from Apotheosis like Instigation. 

### How it improves the player experience

This will improve player experience by allowing even greater customizations and optimization of the player's tools. 

### Tetra synergies

Some of the enchantments already work as is, but excluding some of them removes from the full customization of tools that Tetra allows and promotes.

**Comment by mickelus** [comment]
Fixed in 4.3.0.
