### ISSUE TITLE
Add support for Charm's enchantments

### ISSUE THREAD

**Issue by QueenPM** [mickelus/tetra#474]
### Feature description

Add compatibility for Charm's enchantments
IDs:

charm:acquisition
charm:aerial_affinity
charm:tinted

### How it improves the player experience

Charm adds vanilla-esc enchantments that would improve the player experience such as tinted that would help players replace enchantment tints with dyed colours, improving the visual look of the tool.

### Tetra synergies

It gives the player more customizability for their tools and compatibility for more mods. Charm being a popular vanilla plus mod inspired by Quark, both of which are often featured in modpacks

**Comment by mickelus** [comment]
How does `charm:tinted` work?

**Comment by mickelus** [comment]
Should be fixed in 4.3.0.
