### ISSUE TITLE
[Bug] You can stack potions in your toolbelt

### ISSUE THREAD

**Issue by EpicPuppy613** [mickelus/tetra#476]
### Observed behaviour

After creating a toolbelt with a potion bag, using shift + b to quick store potions will stack the potion if there is already a potion of the same type in the potion bag.

### Expected behaviour

Quick storing a potion will first attempt to put it in an empty potion bag slot, then the storage pouch if the potion bag is full.

### Steps to reproduce

1. Craft a rope toolbelt
2. Put the toolbelt into a workbench and give it a potion bag
3. Use a brewing stand to brew 3 potions of any type
4. Manually put 1 of the potions into the potion bag, then use shift+b to store the rest
5. Opening the toolbelt will show that the potions have stacked

### Tetra version

3.14.1

### mGui version

3.2.0

### Forge version

1.16.5 - 36.2.0

### Other mods

A modpack of about 50 mods, stacking potions using your cursor doesn't work

**Comment by mickelus** [comment]
Nice, working as intended then!
