### ISSUE TITLE
Feature Request: compatibility for more enchantments?

### ISSUE THREAD

**Issue by Birgliss** [mickelus/tetra#48]
## Feature Request

This could be considered a duplicate issue, given #7 exists, but I thought I'd make a new one with some more specific requests.

**Feature description**
Currently, as far as I know, Tetra's enchantment system only supports vanilla. I don't know if this is subject to change in the future, or if I can do anything to fix it myself as a packdev, but I'd like to request specific enchantments from a couple of mods be given support. 
Specifically, I'd like to request that the Soul Stealer enchant from [Soul Shards Reborn](https://minecraft.curseforge.com/projects/soul-shards-respawn) be compatible with weapons, and for [Living Enchant](https://minecraft.curseforge.com/projects/living-enchantment) to be compatible with weapons and tools.

**How it improves the player experience**
Adding these two enchants helps transparently bridge the gap between vanilla tools and Tetra's. By adding more support to enchantments, you give people more of a reason to use Tetra's tools over vanilla.
Personally, I'd love to do a playthrough only ever using Tetra's tools, but sometimes an enchantment I want isn't compatible and it takes me out of the experience.
(As well, having Living Enchantment support allows you to have an alternative to Tinkers' Tool Leveling, which is all too important in the current modded climate.)

**Tetra synergies**
Unless you have a more-dynamic enchantment system planned in the future, I honestly think this is just fleshing out a feature you already currently have. _I_ personally don't see any reason not to add them, but I understand I might not be seeing the whole picture.

**Comment by mickelus** [comment]
Enchantments in tetra do not make use of the vanilla enchantment system, so enchantments from other mods do not work out of the box and it is difficult to add support for some of them. I have a plan for how to rewrite it, but there's alot of other fun stuff I want to squeeze in first :). 

Adding the soul stealer enchant seems straightforward, I'll take a stab at it!

I've got progression planned after this chunk of features (adventure/salvage), but living enchantment seems like a cool mod and I wouldn't mind if we could get that work work as well. I looked a bit at the code but I could not find a way to add the functionality to the item without the "real" enchantment. I'll check with clownvin if it's possible.

**Comment by mickelus** [comment]
Adding new enchantments is significantly easier after 1.1.0. Unfortunately soul shards seem to have switched to fabric and living enchantment is being rewritten, so I cannot add support for them.

Closing this, if there are enchantments from other mods feel free to create a new issue (or message me on discord if that feels clunky).
