### ISSUE TITLE
[Feature Request] Skip 1.17

### ISSUE THREAD

**Issue by StrangerSon71** [mickelus/tetra#480]
### Feature description

Please don’t spend your energy on porting to 1.17, except possibly as a stepping stone to 1.18.

### How it improves the player experience

People wouldn’t see a new feature and then realize that it’s for 1.17.

### Tetra synergies

More content on a more relevant version.

**Comment by mickelus** [comment]
Don't worry mate, I spend all of my energy dealing with issues like this.

Don't abuse the issue tracker.

**Comment by StrangerSon71** [comment]
How is this abuse?

**Comment by mickelus** [comment]
> How is this abuse?

It's neither a feature request or a bug report.

**Comment by StrangerSon71** [comment]
It’s clearly a feature request. Or the opposite of a feature request if you want to get technical about it. I don’t have discord, so there’s no where else to request this. I don’t require a response to this comment, but I hope you at least consider doing this despite this request apparently being ineligible.
