### ISSUE TITLE
[Bug] Incompatible enchantments can be applied to a tool by enchanting multiple times

### ISSUE THREAD

**Issue by Febilian** [mickelus/tetra#484]
### Observed behaviour

It's very possible to put enchantments which directly conflict with each other like Infinity/Mending or Fortune/Silk Touch to be applied to a single tool, which seems... odd.

### Expected behaviour

I would expect that enchantments which are inherently "impossible" or incompatible with one another should be checked across the entire tool's capabilities and disallow enchanting with an incompatible book if said incompatible enchant already exists on the tool.

I don't know if this is an intended quirk of Tetra or not, but I think it could cause some particularly problematic behavior when considering modded enchantments(and support for them) which are inherently incompatible with the function of another. I'd really recommend putting some kind of check in place to prevent incompatible enchantments from being applied to a single tool.

### Steps to reproduce

1. Put a vanilla bow in a Tetra workbench
2. Select the bowstring
3. Select enchant
4. Add a mending book to the tool
5. Add an infinity book to the tool
6. Congrats your bow now has both infinity and mending on it, which is impossible in vanilla

### Tetra version

3.14.1

### mGui version

3.2.0

### Forge version

36.2.2

**Comment by mickelus** [comment]
But it's possible in tetra, great!
