### ISSUE TITLE
Compatibility with Dungeons Gear's enchantments

### ISSUE THREAD

**Issue by xieve** [mickelus/tetra#485]
### Feature description

Dungeons Gear provides some very interesting enchantments ported from Minecraft Dungeons. Sadly, those can't be applied to Tetra tools as of now. I would like to see them compatible.

### How it improves the player experience

The enchantments provide refreshing new mechanics, adding to the diversity of vanilla's while not breaking balance or destroying immersion.

### Tetra synergies

Enchantments from other mods have been made compatible, and more interesting options for your weapons and tools is exactly why I love Tetra.

**Comment by mickelus** [comment]
Fixed in 4.3.0.
