### ISSUE TITLE
[Bug] Item duplication with tool belt on dedicated server

### ISSUE THREAD

**Issue by yuesha-yc** [mickelus/tetra#486]
### Observed behaviour

When you use toolbelt, you can open the gui and throw the toolbelt out of the player inventory. Then you put the items in toolbelt inventory back to your player inventory. Pick up the thrown toolbelt. The items are still inside the toolbelt. 

Using latest tetra 1.16.5, forge 36.2.0

### Expected behaviour

Fix the duplication issue.

### Steps to reproduce

When you use toolbelt, you can open the gui 

and throw the toolbelt out of the player inventory. 

Then you put the items in toolbelt inventory back to your player inventory. 

Pick up the thrown toolbelt. 

Open gui. The items are still inside the toolbelt. 

### Tetra version

3.11.1

### mGui version

3.2.0

### Forge version

1.16.5 - 36.2.0

**Comment by yuesha-yc** [comment]
Video: 
https://user-images.githubusercontent.com/52098789/130309879-c1601342-a051-4963-aa3f-451a7f6f797d.mp4

**Comment by yuesha-yc** [comment]
Also is there source for 1.16 version of the mod? I can help with debug this issue.

**Comment by mickelus** [comment]
> I can help with debug this issue.

You can start by providing a proper list of steps on how to reproduce this, as I'm unable to do so.

**Comment by yuesha-yc** [comment]
Updating to 3.14 fixes this.
