### ISSUE TITLE
Modular Magic

### ISSUE THREAD

**Issue by CoolDemon96** [mickelus/tetra#487]
### Feature description

This theme for the tetra mod will be related to magical items, devices and their upgrades.

### How it improves the player experience

Magic in the tetra fashion will help to give an extraordinary experience of interacting with magic.

### Tetra synergies

Filling the tetra mod with magic may seem like a bad idea, but magic is just a highly developed technology.

**Comment by mickelus** [comment]
This is too abstract for a feature request, feel free to create a new request if you're able to come up with concrete suggestions.
