### ISSUE TITLE
[Bug][compat] Deadlock/Timeout during nether chunk generation

### ISSUE THREAD

**Issue by theCalcaholic** [mickelus/tetra#488]
### Observed behaviour

When a specific combination of mods is installed, generating nether chunks may result in a deadlock, eventually crashing the game/server (due to reaching maximum tick duration).

### Expected behaviour

The game shouldn't lock up :)

### Steps to reproduce

1. Setup a minecraft server, following my configuration:
  * Minecraft version: 1.16.5
  * Forge version: 1.16.5-36.2.2
2. Install the following mods (these are the versions I have installed):
  - Tetra (v3.14.1)
    - mgui (v3.2.0)
  - The Abyss 2 (v1.9.7)
  - Ratlantis (v1.0.0)
    - Rats (v7.2.0)
    - Citadel (v1.8.1)
  - Forbidden and Arcanus (v16.2.0-beta-4)
    - Valhelsia Core (v16.0.10)
3. Start the server (with `nogui` parameter, obviously)
4. Once you have reached the server console, execute the command `forge generate 0 0 0 500 minecraft:the_nether`
5. Watch the server lock up and, eventually, crash :)

### Crashlog

https://gist.github.com/theCalcaholic/ce26ccca4921edc01b77253dc5279fb1

### Tetra version

3.14.1

### mGui version

3.2.0

### Forge version

1.16.5 - 36.2.2

### Other mods

Tetra (v3.14.1)
mgui (v3.2.0)
The Abyss 2 (v1.9.7)
Ratlantis (v1.0.0)
Rats (v7.2.0)
Citadel (v1.8.1)
Forbidden and Arcanus (v16.2.0-beta-4)
Valhelsia Core (v16.0.10)

**Comment by theCalcaholic** [comment]
Looks, like Forbidden and Arcanus is the culprit here. If I disable all of the other mods, nether generation still locks up, however it happens only after 1200 chunks

See also 

https://github.com/stal111/Forbidden-Arcanus/issues/186
https://github.com/stal111/Forbidden-Arcanus/issues/184

**Comment by mickelus** [comment]
Ok, closing then!
