### ISSUE TITLE
Crashing while loading my modpack

### ISSUE THREAD

**Issue by GQJIMU** [mickelus/tetra#489]
### Observed behaviour

I was started playing the modpack then it crashed

### Expected behaviour

I expected the modpack to palce

### Steps to reproduce

1. I created the modpack first
2. Then i started it up
3. Then it froze for a bit
4. Then it crashed

### Crashlog

There is none just says error code zero

### Tetra version

3.14.1

### mGui version

3.2.0

### Forge version

1.16.5 - 36.2.0

### Other mods

Kotlin for Forge
thedarkcolour
kotlinforforge-1.14.0-obf.jar

Abnormals Core
TeamAbnormals
abnormals_core-1.16.5-3.2.0.jar

Alex's Mobs
alex_khaan
alexsmobs-1.12.0.jar

Antique Atlas
Hunternif
antiqueatlas-6.0.1-forge-mc1.16.5.jar

Apotheosis
Shadows_of_Fire
Apotheosis-1.16.5-4.7.1.jar

Aquaculture 2
Shadowclaimer
Aquaculture-1.16.5-2.1.20.jar

Areas
Serilum
areas_1.16.5-2.8.jar

AutoRegLib
Vazkii
AutoRegLib-1.6-49.jar

Better Foliage
octarine_noise
BetterFoliage-2.7.1-Forge-1.16.5.jar

Better Third Person
Socolio
BetterThirdPerson-Forge-1.16.4-1.5.1.jar

Better Weather - Seasons, Blizzards, and more!
Corgi_Taco
betterweather-2.0.1.jar

BetterEnd (Forge)
Beethoven92
betterendforge-1.16.4-1.6.0.jar

Bountiful (Forge)
ejektaflex
Bountiful-1.16.4-3.3.1.jar

Caelus API (Forge)
TheIllusiveC4
caelus-forge-1.16.5-2.1.3.1.jar

Champions
TheIllusiveC4
champions-forge-1.16.5-2.0.1.7.jar

Citadel
alex_khaan
citadel-1.8.1-1.16.5.jar

Cloth Config API (Forge)
shedaniel
cloth-config-4.11.26-forge.jar

Clumps
Jaredlll08
Clumps-6.0.0.25.jar

Collective
Serilum
collective-1.16.5-2.60.jar

Colytra (Forge)
TheIllusiveC4
colytra-forge-1.16.5-5.1.1.1.jar

Comforts (Forge)
TheIllusiveC4
comforts-forge-1.16.5-4.0.1.3.jar

Curios API (Forge)
TheIllusiveC4
curios-forge-1.16.5-4.0.5.2.jar

Desolation (Forge)
y4z0n
Desolation 1.1.0-1 1.16.5.jar

Doggy Talents
percivalalb
DoggyTalents-1.16.5-2.1.0.0.jar

Dungeon Crawl
xiroc_
DungeonCrawl-1.16.5-2.3.2.jar

Dungeons Plus
ModdingLegacy
dungeons_plus-1.16.5-1.1.5.jar

Dynamic Surroundings
OreCruncher
DynamicSurroundings-1.16.4-4.0.4.2.jar

Dynamic Trees
ferreusveritas
DynamicTrees-1.16.5-0.10.0-Beta24.jar

Eidolon
elucent_
eidolon-0.2.7.jar

Entity Culling
meldexun
EntityCulling-1.16.5-2.1.6.jar

Epic Fight
maninthe_home
EpicFightMod-1.16.5-5.0.4.jar

Farmer's Delight
vectorwing
FarmersDelight-1.16.5-0.4.6.jar

FPS Reducer
bre2el
FpsReducer-forge-1.23-mc1.16.5.jar

GeckoLib
ThanosGecko
geckolib-forge-1.16.5-3.0.46.jar

Goblin Traders
MrCrayfish
goblintraders-1.6.0-1.16.3.jar

Guard Villagers
almightytallestred
guardvillagers-1.16.5.1.2.5.jar

Happy Trails
MacTso
HappyTrails-1.16.5-1.36.0.8.jar

Healing Campfire
Serilum
healingcampfire_1.16.5-3.3.jar

Hwyla
TehNut
Hwyla-forge-1.10.11-B78_1.16.2.jar

Illagers+
LiteWolf101
illagers_plus-1.16.4v1.5.jar

Improved Mobs
flemmli97
improvedmobs-1.16.5-1.7.9.jar

InsaneLib
Insane96MCP
InsaneLib-1.2.1-mc1.16.5.jar

Just Enough Items (JEI)
mezz
jei-1.16.5-7.7.1.121.jar

Lazy DataFixerUpper(LazyDFU) [FORGE]
Corgi_Taco
lazydfu-0.1.3.jar

Loot Beams
shiroroku
lootbeams-1.16.5-release-aug2021.jar

Mantle
mDiyo
Mantle-1.16.5-1.6.123.jar

mGui
mickelus
mgui-1.16.5-3.2.0.jar

Mo' Structures (Forge)
ffrannny
mostructures-forge-1.2.0-1.16.5.jar

Mouse Tweaks
YaLTeR
MouseTweaks-2.14-mc1.16.2.jar

Mowzie's Mobs
bobmowzie
mowziesmobs-1.5.19.jar

Off Hand Combat
aya_shamelessmaru
OffHandCombat-1.16.3-3.2.0.3.jar

Oh The Biomes You'll Go
AOCAWOL
byg-1.3.4.jar

Outvoted
HowBoutNo
outvoted-1.16.5-1.2.4.jar

Pam's HarvestCraft 2 - Crops
pamharvestcraft
pamhc2crops-1.16.3-1.0.2.jar

Pam's HarvestCraft 2 - Food Core
pamharvestcraft
pamhc2foodcore-1.16.3-1.0.2.jar

Pam's HarvestCraft 2 - Food Extended
pamharvestcraft
pamhc2foodextended-1.16.3-1.0.4.jar

Pam's HarvestCraft 2 - Trees
pamharvestcraft
pamhc2trees-1.16.3-1.0.1.jar

Placebo
Shadows_of_Fire
Placebo-1.16.5-4.6.0.jar

PlayerEx
clevernucleus
playerex-1.1.8-1.16.5.jar

Progressive Bosses
Insane96MCP
ProgressiveBosses-3.3.2-mc1.16.5.jar

Project: Vibrant Journeys
OrderedChaosDev
projectvibrantjourneys-1.16.5-3.2.9.jar

Quark
Vazkii
Quark-r2.4-316.jar

Random Loot Mod
milomaz1
randomloot-1.16.5-2.3.9.jar

Random Village Names
Serilum
randomvillagenames_1.16.5-1.3.jar

Rare Ice (Forge/Fabric)
shedaniel
rare-ice-0.2.2.jar

Regrowth
MacTso
Regrowth-1.16.4-1.16.5-1.35.0.22.jar

Repurposed Structures (Forge)
telepathicgrunt
repurposed_structures_forge-3.2.4+1.16.5.jar

RPG Backpacks
D12MX
rpgbackpacks-1.16.5-1.1.7.jar

RpgZ
Globox_Z
rpgz-0.4.5-forge.jar

Save Your Pets
MacTso
SaveYourPets-1.16.2-1.0.0.5.jar

Schools of Magic: Second Semester
pale_imitations
SchoolsOfMagic1.16.5-2.1.02.jar

Serene Seasons
TheAdubbz
SereneSeasons-1.16.5-4.0.1.121-universal.jar

Shoulder Surfing Reloaded
_ForgeUser21552638
ShoulderSurfing-1.16.5-2.2.1.jar

Small Ships
talhanation
smallships-1.16.5-1.10.1.jar

Spartan Shields
ObliviousSpartan
SpartanShields-1.16.5-2.1.2.jar

Spartan Weaponry
ObliviousSpartan
SpartanWeaponry-1.16.4-2.1.0-beta-4.jar

Starter Kit
Serilum
starterkit_1.16.5-2.5.jar

Structure Gel API
ModdingLegacy
structure_gel-1.16.5-1.7.7.jar

Subterranean Wilderness
Melonslise
subwild-1.3.0.jar

TenshiLib
flemmli97
TenshiLib-1.16.3-1.3.0.jar

Tetra
mickelus
tetra-1.16.5-3.14.1.jar

Tinkers Construct
mDiyo
TConstruct-1.16.5-3.1.2.265.jar

Traveler's Titles (Forge)
YUNGNICKYOUNG
TravelersTitles-1.16.4-1.5.jar

Upgrade Aquatic
TeamAbnormals
upgrade_aquatic-1.16.5-3.1.0.jar

Valhelsia Core
ValhelsiaTeam
valhelsia_core-16.0.10.jar

Valhelsia Structures
ValhelsiaTeam
valhelsia_structures-1.16.5-0.1.5.jar

Village Spawn Point
Serilum
villagespawnpoint_1.16.5-1.8.jar

Villager Names
Serilum
villagernames_1.16.5-3.3.jar

Wall-Jump! [FORGE]
genandnic
walljump-forge-1.16.4-1.3.7.jar

Waystones
BlayTheNinth
Waystones_1.16.5-7.6.3.jar

When Dungeons Arise - Forge!
Aureljz
DungeonsArise-1.16.5-2.1.47-release.jar

Xaero's Minimap
xaero96
Xaeros_Minimap_21.16.0_Forge_1.16.5.jar

YUNG's API (Forge)
YUNGNICKYOUNG
YungsApi-1.16.4-Forge-12.jar

YUNG's Better Caves (Forge)
YUNGNICKYOUNG
BetterCaves-Forge-1.16.4-1.1.2.jar

YUNG's Better Dungeons (Forge)
YUNGNICKYOUNG
BetterDungeons-1.16.4-1.2.jar

YUNG's Better Mineshafts (Forge)
YUNGNICKYOUNG
BetterMineshafts-Forge-1.16.4-2.0.4.jar

YUNG's Better Portals (Forge)
YUNGNICKYOUNG
BetterPortals-1.16.4-0.3.8.jar

YUNG's Better Strongholds (Forge)
YUNGNICKYOUNG
BetterStrongholds-1.16.4-1.2.1.jar

YUNG's Extras (Forge)
YUNGNICKYOUNG
YungsExtras-Forge-1.16.4-1.0.jar

**Comment by mickelus** [comment]
Can't do anything without a log.
