### ISSUE TITLE
[Bug] Forge Hammer not working.

### ISSUE THREAD

**Issue by toErIpNid** [mickelus/tetra#490]
### Observed behaviour

I put in my blackstone hammer and try to switch the head to obsidian on a minecraft server which doesn't work. It says I need a tier 5 hammer to do so even though it's placed directly under a forge hammer. 

### Expected behaviour

I expected it to work as intended. It has fuel cells and both upgrade slots filled. What am I doing wrong? 

### Steps to reproduce

1. Place hammer on forge workbench.
2. ?Select hammer head.
3. Try to put in obsidian block.
4. Cannot craft because it requires tier five hammer.

### Tetra version

1.16.5-3.14.1

### mGui version

3.2.0

### Forge version

1.16.5

**Comment by mickelus** [comment]
The forge hammer counts as a tier 4 hammer, combustion chamber upgrades increase its hammer tier.
