### ISSUE TITLE
Wrap Handle Holosphere Information

### ISSUE THREAD

**Issue by stephen-smith** [mickelus/tetra#494]
### Feature description

Want a way to see what materials are valid to use for the "Wrap Handle" honing from the holosphere, and how they might modify tool stats.

### How it improves the player experience

Currently, to see if a material can be be used as a wrap, you have to have the material in your inventory while you are applying the first level of Wrap Handle.  Of course materials without a holosphere entry are excluded (manaweave cloth); but, some fibers can be used (string), but not all of them (hemp, mana string).

Since wraps cannot be composed of multiple materials (applied at different levels of honing), a whole new tool (or at least handle) has to be made to determine is newly acquired materials will make for better wraps.

### Tetra synergies

The holosphere is the go-to for "planning" tools, so it is natural to include this information there.

**Comment by dannybgoo** [comment]
This would be extremely useful. Even better would be a new page in the holosphere for modifiers.

**Comment by mickelus** [comment]
This was added about a week ago.
