### ISSUE TITLE
Add enchantment compatibility for Better Default Biomes.

### ISSUE THREAD

**Issue by CyaniideDrive** [mickelus/tetra#497]
### Feature description

Enchantment compatibility with [Better Default Biomes.](https://www.curseforge.com/minecraft/mc-mods/better-default-biomes)

### The enchantment IDs are:
- betterdefaultbiomes:smelting_touch  for tools
- betterdefaultbiomes:hunting  for bows/crossbows
- betterdefaultbiomes:spikes  for shields

### How it improves the player experience

Better Default Biomes adds a few quite nice enchantments and Smelting Touch in particular would be nice on Tetra pickaxes.

### Tetra synergies

It gives the player more options for tool enchantments and makes the mod a bit more seamless with another mod.

**Comment by mickelus** [comment]
Fixed in 4.3.0.
