### ISSUE TITLE
[1.12.2] Can't Hot-Swap tools in Tool Belt.

### ISSUE THREAD

**Issue by Z-Tunic** [mickelus/tetra#50]
Minecraft: 1.12.2
Forge: 14.23.5.2808

Mods: 1
tetra-1.12.2-0.24.0

-----

I'm unable to hot-swap items in the tool belt. I hold down the 'key' and hover my mouse over the item to switch to it and it does nothing.

If I downgrade to 'tetra-1.12.2-0.23.0'... I'm able to swap between tools without any issue.

**Comment by mickelus** [comment]
Fixed in 0.24.1!
