### ISSUE TITLE
Holosphere include wrap handle materials

### ISSUE THREAD

**Issue by Jordan231111** [mickelus/tetra#500]
### Feature description

The Holosphere should include all the possible materials for wrap handle module

### How it improves the player experience

It will make players less confused as there is no guide on wrap handle module at all and no wiki or in game documentation about it.

### Tetra synergies

It synergizes with current feature because it make no sense to include everything in the holosphere except the wrap handle module..

**Comment by mickelus** [comment]
This was added about a week ago.
