### ISSUE TITLE
[Bug] Crash on Load Related to Font/Rendering

### ISSUE THREAD

**Issue by Liamdude** [mickelus/tetra#501]
### Observed behaviour

The game crashes before reaching the home screen when installed alongside the most recent version of Modern UI. I reported the issue to the Modern UI Github and was directed to file a report here. I did not experience the issue before updating Modern UI, but that update may have exposed an issue here. The original report can be found here: https://github.com/BloCamLimb/ModernUI/issues/77. This may also be an issue in Tetrapak rather than Tetra. The gist of the report is that there is a crash during the loading process. The game will load, get to the finalizing step, and then reload some assets. On my full pack, this causes a crash before the main menu loads, which has the side effect that all my resource packs are deselected. On a more compact load order, the crash produces an error screen with weird text rendering. I have a _somewhat_ limited mod list that _sometimes_ causes this crash. It is rather inconsistent, and more details can be found on the other report.
Apologies that this report is rather unhelpful. The short version is that the game crashes before the game fully loads. The developer of Modern UI says that Tetra is making a premature call on a font before the rendering system has loaded.

Side note, I will probably mention this on the Discord, somewhere, to make the Tetrapak developer aware.

### Expected behaviour

The game should load to the main menu without a crash.

### Steps to reproduce

1. Load the list of mods provided in the crash report.
2. Boot Minecraft
3. Experience crash before loading screen.*

*This may not happen every time. It was rather inconsistent when the error occurred. I can also try to further shorten the mod list, but I had issues reproducing it adequately. I can confirm that it always happens on my larger mod list, which is provided in the Modern UI issue report.

### Crashlog

https://pastebin.com/71CZWMv4

### Tetra version

3.15.0

### mGui version

3.3.0

### Forge version

1.16.5 - 36.2.2

### Other mods

On my most recent crash report, this is the mod list:
Jade-1.16.4-2.7.4
jei-1.16.5-7.7.1.121
flywheel-1.16-0.2.4
curios-forge-1.16.5-4.0.5.3
create-mc1.16.5_v0.3.2d
carrotslib-mc1.16.5-3.0.1
vanillafoodpantry-mc1.16.5-6.0.1
AutoRegLib-1.6-49
configured-1.2.0-1.16.3
forgery-1.16-1.3.5-rc2
tetranomicon-1.3
tetrapak-1.16.5-0.3.3
lazydfu-0.1.3
ferritecore-2.0.7-forge
ModernUI-1.16.5-2.6.1.89-universal
catalogue-1.3.0-1.16.5
ImmersivePetroleum-1.16.5-3.3.0-6
ImmersiveEngineering-1.16.5-5.0.3-138
Quark-r2.4-316
cofh_core-1.16.5-1.3.1
thermal_foundation-1.16.5-1.3.2
thermal_expansion-1.16.5-1.3.0
charm-forge-1.16.5-2.3.2
geckolib-forge-1.16.5-3.0.46
NekosEnchantedBooks-1.16-1.3.0
OpenLoader-1.16.5-9.0.3
Optifine G8 (I know Optifine is not liked in some circles, but I will say this issue did not occur on some load orders despite Optifine being present. I can remove it for further testing if necessary).

**Comment by mickelus** [comment]
From what I can see in your other issue this was closed on modern UIs side.
