### ISSUE TITLE
Contributing Process

### ISSUE THREAD

**Issue by Larandar** [mickelus/tetra#502]
### Feature description

Discussion on how to contribute to tetra, or if opening to contributions at least a closing the PRs that are waiting.

### How it improves the player experience

I guess I'm not the only tetra loving code monkey, and I would love to improve the mod because it has IMO a lot of potentials and with "the competition" released to 1.16 I would hate for tetra to become "just" an alternative because it's AWESOME!

### Tetra synergies

I would like to work on the enchanting side myself and I have a few ideas to try, workshop, propose and eventually implement for that.

**Comment by mickelus** [comment]
Would be a good thing to set up for hacktober, perhaps along with some easy-to-pick-up tasks on the projects page.

**Comment by Larandar** [comment]
It seems like you pushed the  `main` branch, could you set github to use it as the default?

**Comment by mickelus** [comment]
Oooof, added a contribution section to the readme a while back but I forgot to close this!
