### ISSUE TITLE
Two possible tool/weapon improvements

### ISSUE THREAD

**Issue by LucunJi** [mickelus/tetra#503]
## Conserved Momentum
Compatible with blades that can swing only.
If a swinging attack kills the targeted entity, the overflown damage will be passed onto a random entity also affect by the swing attack.
Maybe it can also be also to axes due to it huge damage.

## Thermal Conductor
Compatible with any tool head made with metals.
Items harvested with this improvement will have the immunity against all fire damage, until they are pick up by entities or blocks.

### How it improves the player experience

Both improvements are not over-powered. The first one is only effective when the player is dealing with a group of mobs, and the other just makes mining a bit more pleasant -- otherwise players have to manually put out fire or remove the lava before mining diamonds or glowstone.

### Tetra synergies

They gives player more option to improve their tools and weapons.

**Comment by mickelus** [comment]
I like your second suggestion, but unfortunately it's super hacky to change the fire immunity of an item :/.
