### ISSUE TITLE
More Intergration with other mods tools, weapons, shields, and armor.

### ISSUE THREAD

**Issue by ChronosForkyMason** [mickelus/tetra#506]
### Feature description

Hammers from other mods do not work with Tetra's tool stations.  For example, the hammers from Ex Nihlo for 1.16 don't work as hammers in the workbench/anvil.  Also, tools from other mods are not upgradable, changeable, and interchangeable with Tetra tools thru Tetra.  For example, I can not take a spartan weaponry tool, weapon, or shield and change its parts on a Tetra workbench or anvil.  Also, armor from other mods cannot be used to make armor in Tetra.  I would like to see an addon or feature in Tetra for making armor.
![2021-09-26_11 52 52](https://user-images.githubusercontent.com/6131437/134815980-8373b44b-6d51-4ed7-a712-13d1694dc02d.png)
![2021-09-26_11 53 02](https://user-images.githubusercontent.com/6131437/134815982-790d9e76-5cea-41f7-87a0-f67e94511ac2.png)
![2021-09-26_11 53 31](https://user-images.githubusercontent.com/6131437/134815984-a9d88bac-495c-44d0-bc41-7ae61dd48a92.png)
![2021-09-26_11 54 14](https://user-images.githubusercontent.com/6131437/134815987-67bc6db3-f1ae-44e4-b50b-6092abba8f14.png)
![2021-09-26_11 54 28](https://user-images.githubusercontent.com/6131437/134815991-7b3b1846-e70c-4f58-9e92-ff189e8174e8.png)
![2021-09-26_11 48 22](https://user-images.githubusercontent.com/6131437/134814858-5293668b-4743-4d3c-af23-1a859beecd96.png)
![2021-09-26_11 48 40](https://user-images.githubusercontent.com/6131437/134814860-d2b56d80-ebe3-47f8-ac70-4314f7a0fdd7.png)
![2021-09-26_11 49 59](https://user-images.githubusercontent.com/6131437/134814889-02e14ed8-caa6-48de-9105-9257a4121aab.png)
![2021-09-26_11 42 43](https://user-images.githubusercontent.com/6131437/134814724-2ca61f86-6fea-4e0f-b032-7a96d90da17a.png)

### How it improves the player experience

This would give the player more options when making tools, weapons, shields, and armor.  I think this would also encourage people to use Tetra moreover vanilla tools and maybe even replace Tinkers tools, weapons, shields, and armor.

### Tetra synergies

Having more integration would help other mods synergize with Tetra.  Plus, having Ex Nihlo hammers and other tools work with Tetra would make it easier to get Tetra tools and equipment.

**Comment by mickelus** [comment]
More compat would indeed be cool, but there's no generic solution that would add compat for all mods. Request compat for specific mods, preferably on the issue tracker for those mods, if you want something to get done. Closing.
