### ISSUE TITLE
More abblities for the hammer

### ISSUE THREAD

**Issue by PliskintheSaltyFork** [mickelus/tetra#507]
### Feature description

Would be nice if the hammer was able to be used like an Ex Nihlo hammer and with area upgrades.  And modes for the hammer and pickaxe for 3x3, 1x2, 1x1, bigger.  Also, would be nice if there was a lumber axe or a mode for axes to chop the whole tree much like the lumber axe from Tinkers.

Tinkers' Lumber Axe in action
https://www.youtube.com/watch?v=2tDV-3JQGXY
Tinkers' Hammer Example
https://www.youtube.com/watch?v=MpR1EmBrQBY
Example of area mode (Skip to [1:54](https://youtu.be/MgOwnqeOuk0?t=114))
https://www.youtube.com/watch?v=MgOwnqeOuk0

### How it improves the player experience

This would make it easier to mine and chop trees with Tetra tools.  Gathering wood, stone, and ores would be easier.

### Tetra synergies

This could make players want to use Tetra tools over other mods.

**Comment by mickelus** [comment]
There are several methods available for breaking multiple blocks at once. Tree felling is not available in vanilla tetra, but tetrapak adds functionality for that.
