### ISSUE TITLE
Not Enough Room on screen to show materials if you use a lot of material adding mods or mods with a lot materials. [Bug] 

### ISSUE THREAD

**Issue by PliskintheSaltyFork** [mickelus/tetra#508]
### Observed behaviour

![2021-09-27_06 44 43](https://user-images.githubusercontent.com/6131437/134894353-97e525e8-7d3d-41b4-8858-4fa97d4fa91d.png)
Too many materials to be able to show all of them.  I would recommend have word wrap for when there are too many things in the same row to show on the screen.  Also, a scroll bar could be used too if the list becomes too long with word wrap.  Also, more filter options and have filters that can be used to filter materials, so you only see the materials you want.

### Expected behaviour

More or Easier to find materials in the holostone.

### Steps to reproduce

Open the holosphere and go thru the menus until you find the materials list.
1. Open holosphere or craft a hammer if you don't have one
2. Click on CRFT
3. Click on either on any of the menus within CRFT
       a. If you click on anything other than Materials you will have to click on a part menu.
4. Observe the bug shown above.

### Tetra version

3.17.0

### mGui version

3.3.0

### Forge version

1.16.5 36.2.5

### Other mods

Tetra Pak 0.3.3
Tetranomicon 1.3

**Comment by mickelus** [comment]
Use the scroll, Luke.

**Comment by mickelus** [comment]
Also please stop spamming the issue tracker :)
