### ISSUE TITLE
Items dissapear if put into a slot to upgrade or repair and you take the tool of of the workbench before you hit craft

### ISSUE THREAD

**Issue by WolvzUnion** [mickelus/tetra#511]
### Observed behaviour

i accidentally put my pickaxe in a tool upgrade slot by shift clicking and took the tool out of the workbench to upgrade the pick and my pick just dissapeared

### Expected behaviour

the tool drops or the tool just doesnt shift click into the slot

### Steps to reproduce

you put a pickaxe or other tool in a workbench then select an upgrade (for instance to upgrade a pickaxe head) then put any item in the slot and take out the tool without hitting the craft button

### Tetra version

latest

### mGui version

?

### Forge version

1.16.5 36.2.0

### Other mods

all the mods are in a modpack called "Simply fun" on curseforge

**Comment by mickelus** [comment]
Pretty sure this is the long standing issue of materials not plopping out until you put something back in the target item slot. What happens if you do that?

**Comment by mickelus** [comment]
Closing this as it's been over a month without activity.
