### ISSUE TITLE
Add enchant compatability for Vein Mining Enchantment

### ISSUE THREAD

**Issue by CodexArchive** [mickelus/tetra#512]
### Feature description

Allows Tetra tools to receive the Vein Mining enchantment from the mod Vein Mining (Forge).

### How it improves the player experience

Would allow players to mine multiple blocks at once using the Tetra tools rather than having to carry a whole other set of vanilla tools specifically for gathering large quantities of resources.

### Tetra synergies

Grants another tool enchant option for Tetra from a mod that is becoming more and more widely used.

**Comment by mickelus** [comment]
Fixed in 4.3.0.
