### ISSUE TITLE
[Bug] Chthonic Extractor not extracting any minerals

### ISSUE THREAD

**Issue by afolk2** [mickelus/tetra#514]
### Observed behaviour

A few things that I think could be related to the issue.

1. Extractors can not be placed on Seeping Bedrock (assumed working based on item text)
2. Extractors can't be hammered into the same tile (assumed working based on item text)
3. After placing an extractor on fractured/bedrock and hammering with the hammer block and a Redstone signal the hammer locked up. After smacking the hammer with a handheld obsidian hammer it stopped hitting the extractor. <-- This is when all Extractors stopped functioning.
4. The auto extractor, hammer jam, and hammer unjam achievements did not complete.

I did try different locations, extractors, and hammers, but they still don't extract anything (the little particles don't show either)

### Expected behaviour

Extractors should get minerals as per the text and previous attempts

### Steps to reproduce

The third point in the observed behaviour is the reproduction steps, although I'm not sure if the issue is reproducible at this time.

### Tetra version

tetra-1.16.5-3.17.0.jar

### mGui version

mgui-1.16.5-3.3.0.jar

### Forge version

Forge - 36.2.4

### Other mods

This was done in an Enigmatica 6 - 0.5.16 server with 3 players.

**Comment by mickelus** [comment]
Not sure if I follow point 2, 3 and 4. Can you try to record this issue and post it here?

**Comment by afolk2** [comment]
Alright, I went to record it and it seems like they are working partially now.

"Several extractors can be hammered into the same fracture, increases the yield" <- This is what I mean by 2. Unless they are not meant to go into the same position, but adjacent to each other.

Point 3 was just trying to power a Forge hammer with redstone to automatically hammer the extractor into bedrock. After the forge hammer jammed I was unable to get any extractor to work.

"Increased yield when placed on top of seeping bedrock" <- I can place extractors on seeping bedrock, but they can't be hammered by a handheld hammer or the Forge hammer.

I can still record a short clip of the issue if you need.

**Comment by mickelus** [comment]
Yeah, I still don't follow :P

**Comment by mickelus** [comment]
Closing.

**Comment by WeebsGames** [comment]
I am having this same issue. After using up an entire extractor, I am unable to use another one on the same fractured bedrock.
