### ISSUE TITLE
chthonic extractor crashes server[Bug] 

### ISSUE THREAD

**Issue by coledracon** [mickelus/tetra#516]
### Observed behaviour

extractor crashes server when hit with hammer
[crash-2021-10-28_18.22.50-server.txt](https://github.com/mickelus/tetra/files/7436604/crash-2021-10-28_18.22.50-server.txt)

### Expected behaviour

not to crash

### Steps to reproduce

1. place extractor on bedrock
2. hit extractor with hammer until server crashes

### Tetra version

https://www.curseforge.com/minecraft/mc-mods/tetra/files/3468014

### mGui version

https://www.curseforge.com/minecraft/mc-mods/mgui/files/3456505

### Forge version

1.16.5-36.2.0

**Comment by mickelus** [comment]
This appears to be happening in a loot modifier introduced by CavesAndCliffsBackport. The mod has an All Rights Reserved license and I cannot look up what's causing the crash, you'll have to report the issue to them.
