### ISSUE TITLE
[Bug] Tetra tools do not fell trees when using Tree Felling

### ISSUE THREAD

**Issue by Coach-mdl** [mickelus/tetra#517]
### Observed behaviour

Trees won't snap back to reality and get affected by gravity. I'd imagine not much can be done due to the tool not being classed as an axe, but just having the functions of one. I'm putting this issue here, just in case some can be done. 
Mod Link: [](https://www.curseforge.com/minecraft/mc-mods/tree-felling-made-lightweight-and-with-mod)

### Expected behaviour

Oh, there goes gravity.

### Steps to reproduce

1. Disembowel the log
2. Profit

### Tetra version

1.16.5-3.18.0

### mGui version

3.3.0

### Forge version

1.16.5 36.2.8

### Other mods

Bookshelf (by DarkhaxDev)
Just Enough Items (JEI) (by mezz)
Default Options (by BlayTheNinth)
Plasmo Voice (by KPidS)
Legendary Tooltips (by Grend_G)
Enchantment Descriptions (by DarkhaxDev)
Create Crafts & Additions (by MRHminer)
Adorn (Forge) (by Juicebus)
Name Tag Tweaks (Forge) (by Serilum)
FTB Essentials (Forge) (by FTB)
ConnectedTexturesMod (by tterrag1098)
Kotlin for Forge (by thedarkcolour)
JEITweaker (by Jaredlll08)
Storage Drawers (by Texelsaur)
AppleSkin (by squeek502)
Cucumber Library (by BlakeBr0)
Architectury API (Forge) (by shedaniel)
FTB Library (Forge) (by FTB)
Two Players One Horse (by Beethoven92)
Skin Swapper (by cobrasrock_)
FTB Teams (Forge) (by FTB)
Economy Inc. (by FlorentLeBelge)
Dungeon Crawl (by xiroc_)
Waystones (by BlayTheNinth)
Name Pain (by naqaden)
Jade 🔍 (by Snownee_)
KleeSlabs (by BlayTheNinth)
Bedspreads (Forge) (by TheIllusiveC4)
Simple Storage Network (by Lothrazar)
Citadel (by alex_khaan)
FastFurnace (by Shadows_of_Fire)
Chisel (by tterrag1098)
Bountiful (Forge) (by ejektaflex)
Mystical Agriculture (by BlakeBr0)
Tinkers Construct (by mDiyo)
Create (by simibubi)
Dynamic Surroundings (by OreCruncher)
Advancement Plaques (by Grend_G)
TerraForged (by won_ton_)
mGui (by mickelus)
Patchouli (by Vazkii)
YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)
Mantle (by mDiyo)
Caelus API (Forge) (by TheIllusiveC4)
When Dungeons Arise - Forge! (by Aureljz)
Doggy Talents (by percivalalb)
Morpheus (by Quetzi)
CraftTweaker (by Jaredlll08)
Mekanism (by bradyaidanc)
YUNG's Better Caves (Forge) (by YUNGNICKYOUNG)
Sophisticated Backpacks (by P3pp3rF1y)
Mekanism Generators (by bradyaidanc)
Botania (by Vazkii)
Polymorph (Forge) (by TheIllusiveC4)
Artifacts (by ochotonida)
Callable Horses (by Tschipp)
Iceberg (by Grend_G)
Supplementaries (by MehVahdJukaar)
Music Maker Mod (by xerca0)
Cooking for Blockheads (by BlayTheNinth)
Simple Discord RPC [Forge/Fabric] (by hypherionsa)
Farmer's Delight (by vectorwing)
Cosmetic Armor Reworked (by LainMI)
Aquaculture 2 (by Shadowclaimer)
XP Tome (by bl4ckscor3)
Inventory HUD+ (by dmitrylovin)
Item Borders (by Grend_G)
Collective (Forge) (by Serilum)
Traveler's Titles (Forge) (by YUNGNICKYOUNG)
Clumps (by Jaredlll08)
YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)
Applied Energistics 2 Wireless Terminals Forge (by tfarecnim)
Corail Tombstone (by Corail_31)
Nature's Compass (by Chaosyr)
Better Advancements (by way2muchnoise)
FTB Quests (Forge) (by FTB)
Tree Felling [Forge] (by knightm3re)
Comforts (Forge) (by TheIllusiveC4)
Wildfire's Female Gender Mod (Forge) (by WildfireRomeo)
Mob Grinding Utils (by vadis365)
FTB Chunks (Forge) (by FTB)
Fast Leaf Decay (by olafskiii)
Curios API (Forge) (by TheIllusiveC4)
FPS Reducer (by bre2el)
Tetra (by mickelus)
Ice and Fire: Dragons (by alex_khaan)
Healing Campfire (Forge) (by Serilum)
FastWorkbench (by Shadows_of_Fire)
Charm Reforged (by svenhjol)
Applied Energistics 2 (by AlgorithmX2)
Immersive Cooking (by CrimsonDragonRider)
Alex's Mobs (by alex_khaan)
YUNG's API (Forge) (by YUNGNICKYOUNG)
Flywheel (by jozufozu)
Mouse Tweaks (by YaLTeR)
Spiders 2.0 (by TheCyberBrick)
ExpandAbility (by florensie)
Curio of Undying (Forge) (by TheIllusiveC4)
Item Filters (Forge) (by LatvianModder)
Controlling (by Jaredlll08)
Potion Descriptions (Forge) (by azmalent)
♪ Alex's Mobs Battle Music ♪ (by my_name_is_krossy)
Selene Lib (by MehVahdJukaar)
Placebo (by Shadows_of_Fire)
Curious Elytra (Forge) (by TheIllusiveC4)
Item Highlighter (by Grend_G)

**Comment by mickelus** [comment]
No idea what this is supposed to mean :P

**Comment by Coach-mdl** [comment]
Tetra axes do not make the tree fall down with Tree Felling.
