### ISSUE TITLE
Tools can be made with negative durability.

### ISSUE THREAD

**Issue by Roonas** [mickelus/tetra#52]
**Bug Report**

**Observed Behaviour**
Attempting to part swap a partially broken tool with low durability can cause it to end with a negative durability value. For example, switching from a double bronze pick head to a double iron pick head when the tool is nearly broken will result in the following.

https://cdn.discordapp.com/attachments/437844484810866688/559925432326029317/unknown.png

**Expected Behaviour**
Negative durability tools shouldn't be possible to craft; just a tool with maximum lower durability.

**Minimal setup needed to reproduce**
-Tetra 0.24.1
-A mod that adds bronze; Forestry, TE, Embers.
-Forge 14.23.5.2768, however, any recent version should function.

**Steps to reproduce**
Replace a partially broken pickaxe made of bronze pickaxe heads with iron pickaxe heads. Likely functions with other materials too.

**Feature description**
Tool parts should only be allowed to be swapped when at full durability, similar to the TiCon system, or implement a scaling with regards to damage values and total durability.

**How it improves the player experience**
Tools will either end up at full durability, albeit at a lower maximum, and still be usable, or will have a scaling attached to the maximum durability so that even though the durability is lower, it will not be possible for it to dip into the negatives and become unusable.

**Comment by mickelus** [comment]
Thank you for contributing, this is your second issue and there are two things I want you to consider. There are templates for both bug reports and feature requests, please use them. If you want your suggestions to be taken into consideration you need to explain the reasoning behind them.

**Comment by Roonas** [comment]
Apologies, report has been updated.
