### ISSUE TITLE
[Bug] Spike text missing

### ISSUE THREAD

**Issue by BaeyDesola** [mickelus/tetra#520]
### Observed behaviour

![2021-11-11_17 39 49](https://user-images.githubusercontent.com/49934846/141276406-df68566f-ac12-41ef-a762-ac3d0bb53381.png)

### Expected behaviour

No

### Steps to reproduce

No

### Crashlog

No

### Tetra version

3.19.0

### mGui version

3.3.0

### Forge version

1.16.5

**Comment by mickelus** [comment]
Unable to reproduce this. 

No
