### ISSUE TITLE
Compatibility with Project Spartan

### ISSUE THREAD

**Issue by Atlantispy** [mickelus/tetra#522]
### Feature description

A mod that provide extra weapons to game. Would be enhanced with compatibility with Tetra

### How it improves the player experience

This mod adds, greater depth into weapon types, and being able to enhance that with features from Tetra would be nice.

### Tetra synergies

It is a natural fit, with room for the unique system tetra has, just with new items.

**Comment by mickelus** [comment]
Closing, duplicate of #324
