### ISSUE TITLE
[Bug] Can't enchant hammers in workbench with books.

### ISSUE THREAD

**Issue by krokots** [mickelus/tetra#523]
### Observed behaviour

![2021-11-17_22 05 44](https://user-images.githubusercontent.com/25055882/142282567-c23ff9e7-2411-4970-8952-7835b2254dd2.png)

"Craft" button is locked in this case.

### Expected behaviour

I think that using books like knockback on hammers should work, but it's forebidden. But you can get this effect in enchanting table.

### Steps to reproduce

1. Craft hammer, workbench, create tetra workbench
2. Obtain enchanted book of knockback.
3. Try enchanting hammer with this book.

### Tetra version

tetra-1.16.5-3.19.0

### mGui version

mgui-1.16.5-3.3.0

### Forge version

1.16.5-forge-36.2.0

### Other mods

1.16.5-additionalbars-2.0.3.jar                                      
appleskin-forge-mc1.16.x-2.1.0.jar                                   
astikorcarts-1.16.5-1.1.1.jar                                        
AutoRegLib-1.6-49.jar                                                
BetterFoliage-2.6.5-Forge-1.16.5.jar                                 
Bookshelf-Forge-1.16.5-10.2.27.jar                                   
Ceramics-1.16.5-1.6.3.jar                                            
charm-forge-1.16.5-2.3.2.jar                                         
collective-1.16.5-2.58.jar                                           
Craftable+Saddles+[1.16+All]-1.3.jar                                 
create-mc1.16.5_v0.3.2f.jar                                          
createdeco-1.0.2-1.16.5.jar                                          
cryingghasts_1.16.5-1.4.jar                                          
DarkUtilities-1.16.5-8.0.10.jar                                      
decorative_blocks-1.16.4-1.7.2.jar                                   
DynamicSurroundings-1.16.5-4.0.5.0.jar                               
fairylights-4.0.5-1.16.5.jar                                         
flywheel-1.16-0.2.4.jar                                              
guardvillagers-1.16.5.1.2.6.jar                                      
Hwyla-forge-1.10.11-B78_1.16.2.jar                                   
jei-1.16.5-7.7.1.134.jar                                             
kotlinforforge-1.14.0-obf.jar                                        
list.txt                                                             
Mantle-1.16.5-1.6.115.jar                                            
mcw-bridges-1.0.6-mc1.16.5.jar                                       
mcw-doors-1.0.3-mc1.16.5.jar                                         
**mgui-1.16.5-3.3.0.jar**                                                
moreminecarts-1.3.11.jar                                             
OptiFine_1.16.5_HD_U_G8.jar                                          
Quark-r2.4-319.jar                                                   
repurposed_structures_forge-3.4.1+1.16.5.jar                         
Runelic-1.16.5-7.0.1.jar                                             
SaveMyStronghold-1.16.4-1.0.jar                                      
selene-1.16.5-1.9.0.jar                                              
supplementaries-1.16.5-0.17.9.jar                                    
TerraForged-1.16.5-0.2.16-BETA-2.jar                                 
**tetra-1.16.5-3.19.0.jar**                                              
**tetranomicon-1.3.jar**                                                 
thinpillars-1.0.jar                                                  
twuhastepotion-1.0.jar

**Comment by mickelus** [comment]
Knockback goes on the handle, the holosphere shows information about which enchantments different modules can accept.
