### ISSUE TITLE
[Bug]  Want to change textures

### ISSUE THREAD

**Issue by McFireWolf** [mickelus/tetra#524]
### Observed behaviour

Wanted to change the textures so when I messed with a weapon from my resource pack it would show up properly, but the only things I'm able to find are the ones for the overlays. Browsed the files and I found the new blades, but I'm not sure how to make them change with the color of the weapon, and also just change how the weapon appears in the workbench once it's been changed. like if you change the blade, the other parts remain the default Minecraft texture, but I couldn't find where that texture was in the files.

### Expected behaviour

I expected to be able to find the base sword texture that is used, but there isn't one in your file, and the only files are the overlays, which I'm oblivious as to how they change with the color of the sword

### Steps to reproduce

1. Place an iron sword in with Depixel 32x32 resource pack
2. Add a new blade or any mod
3. Sword changed to vanilla texture with an altered piece of choice
4. Nowhere to change these in files

### Tetra version

3.18.0

### mGui version

3.3.0

### Forge version

1.16.4 - 35.137

**Comment by mickelus** [comment]
I don't understand what you are asking for here. You can find all the module textures here https://github.com/mickelus/tetra/tree/main/src/main/resources/assets/tetra/textures/items/module, you can replace those with a resourcepack as with any other texture in the game. They're tinted at runtime, if you're worried about how things will look you'll have to test it out ingame.

Join discord if you need further help.
