### ISSUE TITLE
[Bug] ToolBelt Storage does not repect data predicate setting

### ISSUE THREAD

**Issue by khjxiaogu** [mickelus/tetra#525]
### Observed behaviour

Replaced toolbelt predicate data to avoid putting other item storage things inside toolbelt, but does not works.

### Expected behaviour

Toolbelt should check relavent predicates.

### Steps to reproduce

1. Set predicate to whitelist some tags
2. Put items not on whitelist into toolbelt storage slot
3. Reproduced

### Tetra version

3.18.0

### mGui version

3.3.0

### Forge version

1.16.5-36.2.4

### Other mods

ImmersiveEngineering-1.16.5-5.0.5-140

**Comment by mickelus** [comment]
Changed how toolbelt inventory predicates works in 4.0.0, which fixes this issue!
