### ISSUE TITLE
Arrows

### ISSUE THREAD

**Issue by CTH999** [mickelus/tetra#526]
### Feature description

The ability to produce custom arrows

### How it improves the player experience

It will allow people to make good ammo for their new bow! You could use feathers, and a few other things (Wool?) as the fletching, the tip effects damage and speed, the shaft effects the same stuff, the fletching effects accuracy, and perhaps the more? Maybe a special slot for adding in sockets? A way to add "packages", such as water-bottles which put out fires in a small area, potions to have their effect, gun-powder for a weak explosion, blaze powder for a fire (Or longer fire if combined with the flame enchantment), and more?

### Tetra synergies

We already have bows, this is the next logical step. That's how it goes with current features. It adds more weapons/ tools, adding in new potential customization. That's how it alings with the goals,

**Comment by CTH999** [comment]
And, arrows could also form another type that is stronger (Via a different tip? Rod?) The Crossbow Bolt! Stronger, but only works with crossbows. You could even go a step further, and have the part that allows it to connect to a bow as part of it

**Comment by mickelus** [comment]
I think there are lots of interesting choices that could be introduced with different types of arrows, arrows don't need to be modular for that and I think the choices would be more fun and interesting if they weren't. Closing :)

**Comment by CTH999** [comment]
okay!
