### ISSUE TITLE
Mild Incompatibility between Roots Classic and Tetra v4 [Bug] 

### ISSUE THREAD

**Issue by Drakoflame** [mickelus/tetra#528]
### Observed behaviour

For some reason, some how, Roots Classic causes Tetra Tools to register their mine level wrong(?). Specifically, a double-head diamond pickaxe from Tetra, ISN'T considered a diamond pickaxe, and thus unable to mind obsidian, but only if RootsClassic is installed. Remove RC fixes the issue.

### Expected behaviour

Double-headed diamond pickaxe mine obsidian

### Steps to reproduce

1. Use double-headed diamond pickaxe
2. mine obsidian
3. scream in futility

### Tetra version

4.0.0

### mGui version

4.0.0

### Forge version

1.18.1 39.0.7

### Other mods

RootsClassic-1.18-1.1.16

**Comment by mickelus** [comment]
Fixed in 4.1.0!
