### ISSUE TITLE
[Bug] tetra pickaxes (and possibly other tools for other purposes) fail to meet requirements for mining ore

### ISSUE THREAD

**Issue by esotericist** [mickelus/tetra#530]
### Observed behaviour

crafted a double headed tetra stone pickaxe. attempted to mine copper ore.
![image](https://user-images.githubusercontent.com/1569754/147040283-c6288adf-e15b-4996-aba3-58b596a5b027.png)
tested a vanilla stone pickaxe against the same ore.
![image](https://user-images.githubusercontent.com/1569754/147040303-2b028718-a992-491e-95e8-5986c02f6ca4.png)

this isn't just a cosmetic thing showing via jade, to be clear; it is both slow mining, and it deletes the ore instead of harvesting raw copper.

i notice that the tetra pickaxe doesn't show some of the tags the vanilla pickaxe does, and i wonder if that's pertinent.
![image](https://user-images.githubusercontent.com/1569754/147040843-2e8f0bc9-bd07-43d5-8b22-d6f27be4b93a.png)
![image](https://user-images.githubusercontent.com/1569754/147040860-8774ae7d-9dff-44c7-a64e-85f492ff9fb1.png)

### Expected behaviour

tetra pickaxes should be able to, you know. mine ores.

### Steps to reproduce

1. place a vanilla stone pickaxe in workbench
2. turn it into a tetra pickaxe
3. find some copper or iron ore
4. attempt to mine it
5. ???
6. not profit.

### Tetra version

4.1.0

### mGui version

no mgui present. mutil? 4.0.0

### Forge version

1.18.1-39.0.6

### Other mods

`SlabMachines-1.18.1-1.1.1.jar, supermartijn642configlib-1.0.9-mc1.18.jar, netherportalfix-forge-1.18-9.0.0.jar, curiousshulkerboxes-forge-1.18.1-4.2.0.0.jar, Uppers-0.4.0.jar, mcw-windows-2.0.2-mc1.18.1.jar, woodenhopper-1.18-1.2.0.1.jar, kleeslabs-forge-1.18-11.0.0.jar, villagernames_1.18.1-3.5.jar, cookingforblockheads-forge-1.18-11.0.0.jar, Controlling-forge-1.18-9.0.4.jar, Placebo-1.18.1-6.0.2.jar, citadel-1.10.5-1.18.jar, alexsmobs-1.15.1.jar, rangedpumps-0.9.0.jar, sophisticatedbackpacks-1.18.1-3.13.6.452.jar, guardvillagers-1.18.1.4.0.jar, buildinggadgets-3.10.1-build.3+mc1.18.jar, mcw-doors-1.0.5-mc1.18.1.jar, PickUpNotifier-v3.1.0-1.18.1-Forge.jar, balm-2.3.1+0.jar, WaterStrainer-1.18-12.1.0.jar, FpsReducer-forge-1.25-mc1.18.jar, JustEnoughResources-1.18.1-0.13.1.137.jar, cloth-config-6.1.48-forge.jar, MmmMmmMmmMmm-1.18-1.5.0.jar, absentbydesign-1.18-1.6.0.jar, supplementaries-1.18-1.0.7.jar, konkrete_forge_1.3.2_MC_1.18.jar, tis3d-1.18.1-forge-1.6.8+504189c.jar, mcw-bridges-2.0.1-mc1.18.1.jar, FarmersDelight-1.18.1-1.0.0.jar, torchmaster-18.0.2-beta.jar, signpost-1.18-2.00.3.jar, mcw-trapdoors-1.0.4-mc1.18.1.jar, mcw-fences-1.0.2-mc1.18.1.jar, supermartijn642corelib-1.0.15a-mc1.18.jar, simplylight-1.18.1-1.4.0-build.26.jar, curios-forge-1.18.1-5.0.3.1.jar, tetra-1.18.1-4.1.0.jar, Patchouli-1.18.1-61.jar, collective-1.18.1-3.8.jar, FramedBlocks-4.0.0.jar, DrawersTooltip-1.18-forge-4.0.0.jar, BetterThirdPerson-Forge-1.18-1.5.4.jar, NaturesAura-35.0.jar, constructionwand-1.18.1-2.6.jar, sapience-1.18.1-1.0.0-hotfix.jar, architectury-3.2.51.jar, productivebees-1.18.1-0.8.0.3.jar, light-overlay-6.0.4-forge.jar, chunkloaders-1.1.7b-mc1.18.jar, prettybeaches-forge-1.18-7.0.0.jar, veinmining-forge-1.18-0.14.jar, geckolib-1.18-forge-3.0.3.jar, TradingPost-v3.1.2-1.18.1-Forge.jar, mcw-lights-1.0.2-mc1.18.1.jar, BetterAdvancements-1.18.1-0.1.2.121.jar, QuarkOddities-1.18.jar, torchslabmod-1.18.1_v1.7.2.jar, enderbundle-1.08.jar, VanillaExcavators-1.18.1-4.0.0.jar, treeharvester_1.18.1-4.2.jar, jei-1.18.1-9.1.0.46.jar, VisualWorkbench-v3.1.0-1.18.1-Forge.jar, scannable-1.18.1-forge-1.7.6+da03abb.jar, goblintraders-1.7.0-1.18.1.jar, waystones-forge-1.18.1-9.0.1.jar, goldenhopper-1.2.5-1.18.1.jar, FastSuite-1.18.1-3.0.0.jar, shutupexperimentalsettings-1.0.4-1.18+.jar, journeymap-1.18.1-5.8.0beta4.jar, comforts-forge-1.18-5.0.0.1.jar, configured-1.5.1-1.18.1.jar, LibX-1.18.1-3.1.1.jar, copper-mod-1.9.jar, charginggadgets-1.5.0.jar, mahoutsukai-1.18.1-v1.33.6.jar, farsight-1.18-1.5.jar, catalogue-1.6.0-1.18.1.jar, ToastControl-1.18.1-6.0.0.jar, PackingTape-1.18-0.12.2.jar, mininggadgets-1.10.2.jar, selene-1.18-1.11.jar, drippyloadingscreen_forge_1.4.2_MC_1.18.jar, craftingtweaks-forge-1.18.1-14.0.1.jar, EnchantmentDescriptions-Forge-1.18.1-9.0.3.jar, MouseTweaks-forge-mc1.18-2.19.jar, ToolBelt-1.18-1.18.0.jar, ImmersiveEngineering-1.18.1-7.0.0-142.jar, BetterControls-Forge-1.18+v1.2.2.jar, MoreVanillaLib-1.18.1-3.0.0.jar, Jade-1.18-4.1.0.jar, forge-1.18.1-39.0.6-universal.jar, VanillaTweaks-1.18.1-1.5.52.jar, ShoulderSurfing-1.18-2.2.2.jar, Ding-1.18-1.3.0.jar, ceramicshears-1.18-1.5.0.1.jar, mutil-1.18.1-4.0.0.jar, gravestone-1.18.1-1.0.0.jar, FastWorkbench-1.18.1-6.0.0.jar, markdown_manual-1.18.1-forge-1.1.0+1299320.jar, JustEnoughProfessions-1.18-1.2.2.jar, AutoRegLib-1.7-52.jar, Quark-3.0-332.jar, StorageDrawers-1.18.1-10.0.0.jar, brickhopper-1.18-1.3.0.1.jar, VanillaHammers-1.18.1-4.0.0.jar, now-playing-1.2.0-forge-1.18.jar, IKnowWhatImDoing-5.0.0-forge.jar, effective_for_forge-1.001.jar, FastFurnace-1.18.1-6.0.1.jar, appleskin-forge-mc1.18-2.2.0.jar, ferritecore-4.0.0-forge.jar, occultism-1.18.1-1.23.6.jar, PuzzlesLib-v3.1.1-1.18.1-Forge.jar, modular-routers-1.18.1-9.0.1-79.jar, MineMenu-1.18-1.10.0.jar, extremeSoundMuffler-3.19_1.18.jar, Link to mindshaft-0.7.4-1.18.1.jar
 `

**Comment by esotericist** [comment]
i missed #528 in my previous scan of the issues, and now that i've looked over discord conversation history i can see that there is probably a connection.

i'm not in a position to try to do careful checks to see which of my mods might or might not be causing tetra to mishandle mining tiers, however.

**Comment by mickelus** [comment]
I need the minimal set of mods required to reproduce this.

**Comment by esotericist** [comment]
i'll get back to you on that when i can.

**Comment by cpw** [comment]
I'm getting the same issue - stone picks don't work to harvest ore. Quark, perhaps?

**Comment by cpw** [comment]
I removed cyclic, which fixed the weird hammer issue #531 but it did not fix this issue. A "tier 2" stone pickaxe cannot mine copper ore.

**Comment by ellbristow** [comment]
This is not a mod interaction/compatibility issue. I just ran a build with ONLY Tetra active and a wooden pick upgraded to have 2 stone pick head parts could not mine copper.

Forge 39.0.8 (1.18.1)
Tetra 4.1.0
mUtil 4.0.0

**Comment by aWhisper20** [comment]
Same issue as poster.
Forge 39.0.8 (1.18.1)
Tetra 4.1.0
mUtil 4.0.0
Mods are minimally invasive, but regardless:
Tetra (by mickelus)
Simple Voice Chat (by henkelmax)
Sound Physics Remastered (by henkelmax)
Valhelsia Structures (by ValhelsiaTeam)
mutil (by mickelus)
Just Enough Items (JEI) (by mezz)
Flywheel (by jozufozu)
Falling Leaves (Forge) (by Cheaterpaul)
Create (by simibubi)
Repurposed Structures (Forge) (by telepathicgrunt)
Valhelsia Core (by ValhelsiaTeam)
Stay True (by haimcyfly)
Xaero's World Map (by xaero96)
Most recent versions for 1.18.1 as of 24th december.

**Comment by bloodwishartz** [comment]
Same issue even at diamond pickaxe level with both heads being diamond and upgraded handle to bone. Woiuldnt mine diamond or iron ore, breaks at correct speed but cant harvest it. it states mining lvl 5 for pick as well.

**Comment by mickelus** [comment]
Fixed in 4.1.1.
