### ISSUE TITLE
Shovels & Hoe Not working after upgrade 

### ISSUE THREAD

**Issue by Rayskiz** [mickelus/tetra#533]
### Observed behaviour

When upgrading a hoe or shovel the activity of creating paths (shovel) or creating farmland (hoe) does not work.

### Expected behaviour

Creation of path blocks with shovel and farmland with hoe

### Steps to reproduce

1. Place hoe in workbench
2. Upgrade to next tier (stone, iron, etc.)
3. Create path or farmland

### Crashlog

none

### Tetra version

1.18.1-4.1.0

### mGui version

Multi v 1.18.1-4.0.0

### Forge version

1.18.1 - 39.0.8

### Other mods

None

**Comment by mickelus** [comment]
Fixed in 4.1.1.
