### ISSUE TITLE
[Bug] Pickaxe not being able to mine the correct ores bug persisting even after the update to 4.1.1 ON SERVERS

### ISSUE THREAD

**Issue by aWhisper20** [mickelus/tetra#534]
### Observed behaviour

After updating my server to the newly patched tetra mod, the infamous pickaxe not being able to mine the correct ore tier bug continues to persist. In singleplayer, it doesn't happen, only in the server. For details on the specifics, see the previous post mentioning this bug.

In addition to this, the bow crafting bug is still persisting (See my other post)

### Expected behaviour

Bug should have been in the 4.1.1 update, as happens in single player worlds, but for some reason servers are still affected.

### Steps to reproduce

1. Attempt to mine any ore of iron or higher with a tetra pickaxe on a server
2. Not profit

### Tetra version

4.1.1

### mGui version

4.0.0

### Forge version

39.0.9

### Other mods

Dramatic Skys (by thebaum64)
Tetra (by mickelus)
Simple Voice Chat (by henkelmax)
Sound Physics Remastered (by henkelmax)
Valhelsia Structures (by ValhelsiaTeam)
mutil (by mickelus)
Just Enough Items (JEI) (by mezz)
Flywheel (by jozufozu)
Falling Leaves (Forge) (by Cheaterpaul)
Create (by simibubi)
Valhelsia Core (by ValhelsiaTeam)
Repurposed Structures (Forge) (by telepathicgrunt)
Stay True (by haimcyfly)
Xaero's World Map (by xaero96)

All most recent version.

**Comment by aWhisper20** [comment]
Sorry if this bug report came off as too aggressive or something, I was just really hyped with the patch coming out, to be able to play with my friends, but unfortunately the universe has conspired against us today...

**Comment by mickelus** [comment]
Should be fixed in 4.1.2.
