### ISSUE TITLE
[Bug] Toolbelt slot acces via Curios doesent seem to work.

### ISSUE THREAD

**Issue by Altrenis** [mickelus/tetra#536]
### Observed behaviour

For few hours i was thinking it is a problem with other mods but after some time I've ended with few mods only to check things out:
-tetra - ver 1.18.1-4.2.0.jar
-mutil - ver 1.18.1-4.0.0.jar
-curious API - ver 1.18.1-5.0.4.2.jar
-Curio of Undying 1.18.1-5.3.0.0.jar
also i've check things out on version 1.16.5 and everythings work perfect.
But what's all about? well, with this simple pack of mods tetra belt work well but tetra itself doesn't create slot in curious for belt. Simple mod like curio of undying does it very well and i can use totem on curio slot. In 1.16.5 the same mods work perfectly, means - slot is added by tetra for curious.  I know it could be minor issue for you but still, lacking of feature in that amazing mod is a pain in the ... I hope it is understandable for any quiestions about this issue pls ask below I will check commenst often.

### Expected behaviour

I would like to see fix for belt slot for curious.

### Steps to reproduce

1. install tetra, mutil, curious and any other mod adding curious slot (my example Curio of undying) - all on version 1.18.1 forge
2. try to put belt item (any tier from tetra) on curio slot 
3. right now you see there is no slot - here is the problem (in 1.16.5 you could do it because there was slot)

### Tetra version

tetra-1.18.1-4.2.0

### mGui version

mutil-1.18.1-4.0.0

### Forge version

1.18.1-39.0.9

### Other mods

-tetra - ver 1.18.1-4.2.0.jar
-mutil - ver 1.18.1-4.0.0.jar
-curious API - ver 1.18.1-5.0.4.2.jar
-Curio of Undying 1.18.1-5.3.0.0.jar

**Comment by mickelus** [comment]
Fixed in 4.2.1.
