### ISSUE TITLE
netherite pickaxe drop no loot[Bug] 

### ISSUE THREAD

**Issue by Alonlystalker** [mickelus/tetra#537]
### Observed behaviour

netherite pickaxe after honing mine tier+1 have tier7 and drop no loot from any blocks like if you break it by hand.

### Expected behaviour

same pickaxe but a bit faster? dunno

### Steps to reproduce

1. craft netherite pickaxe to have mine  tier 6
2. upgrade it mine efficacy 5 times and then mine tier once
3. now you have tier 7 pickaxe that act like fast hand, any stone+ blocks dont have any loot
4. downgrade it's tier by changing one of parts to tool butt fixes that problem

### Tetra version

4.2.0

### mGui version

4.0.0

### Forge version

1.18.1-39.0.9

**Comment by mickelus** [comment]
Fixed in 4.2.1.
