### ISSUE TITLE
[Bug] Toolbelt dupe items

### ISSUE THREAD

**Issue by khjxiaogu** [mickelus/tetra#538]
### Observed behaviour

Open the toolbelt then swap and throw it out, take items from UI and pickup toolbelt can find duplicated items

### Expected behaviour

Toolbelt shouldn't be swapped and throw out. 

### Steps to reproduce

1. Place an toolbelt into hotbat slot 5 (other slots also works).
2. Switch to slot 5 and open toolbelt.
3. Place item inside and close it.
4. Open it again.
5. Mouse points at an empty slot in inventory, press keyboard key 5 to swap toolbelt into inventory.
6. Throw out the toolbelt, take away items in gui.
7. Pick up toolbelt and open, found item duplicated

### Tetra version

3.20.0

### mGui version

3.3.0

### Forge version

1.16.5-36.2.4

**Comment by mickelus** [comment]
Fixed in 4.4.0.
