### ISSUE TITLE
item tiers not working (multiplayer) [Bug] 

### ISSUE THREAD

**Issue by LORDdotD** [mickelus/tetra#539]
### Observed behaviour

im playing minecraft with a small modpack and in singleplayer everything works fine but when in a multiplayer world
the axes dont have any tier at all and every blade can only be tier 1 and iron is even tier 0
![Screenshot 2022-01-02 022612](https://user-images.githubusercontent.com/96963347/147863720-9cca2c67-5593-4709-b0ae-0b049b575f2c.png)
 

### Expected behaviour

they should have the correct tier
![Screenshot 2022-01-02 022724](https://user-images.githubusercontent.com/96963347/147863724-aea927a1-c12d-4c08-b04b-96168eb125b1.png)
 

### Steps to reproduce

1. be on a multiplayer server
2. try and replace the blade of a sword

### Tetra version

4.1.0

### mGui version

4.0.0

### Forge version

39.0.0

### Other mods

https://www.curseforge.com/minecraft/modpacks/it-just-fits
modlist but i dont think they are the problem as in singleplayer it works

**Comment by mickelus** [comment]
Update
