### ISSUE TITLE
Right-click empty workbench with hammer to convert to crafting table

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [mickelus/tetra#542]
### Feature description

It'd be nice if there was an option to have it so that you could just return a workbench to its normal status after you're done. I don't know if there's a specific reason you're not supposed to, but I end up just turning my main crafting bench into a workbench, and then breaking and replacing it when I'm done.

I dunno if this would be enabled by default, but perhaps have it so that right-clicking a workbench with a hammer returns it to crafting tableness.

Obviously, it should balk at you trying to do this with a workbench that has items in it. Or spit them out. ¯\\\_(ツ)_/¯

### How it improves the player experience

It'd improve my specific experience. I don't have any exciting reasoning, just "I already want to use the mod this way, but I have to do something inconvenient to make it so." I dunno if others do this, I may very well be the only one, but I get the crafting bench and the workbench confused anyway because of textures, so simply making it so that you only really need one and a hammer would ease things incredibly for me.

**Comment by mickelus** [comment]
Won't fix.
