### ISSUE TITLE
More material compatibility

### ISSUE THREAD

**Issue by wacaser2** [mickelus/tetra#543]
### Feature description

I would like compatibility for more rods to be able to be used as handles. Specifically Immersive Engineering(IE)'s Treated Stick (forge:rods/treated_wood) and Mekanism's PlaStick (forge:rods/plastic) would make good additions. But it would also be nice adding some of the other metal rods that IE and Create Additions add, and making them faster but less integrity / durability than their ingot counterparts similar to wood and sticks.

I also think using the wire that IE and Create Additions add as wraps for handles or bindings makes a lot of sense.

Much less useful, but I could also see using metal plates as scales.

Another enhancement, I might be in the minority on this, but it seems like steel should be workable like bronze

### How it improves the player experience

More choices for handles and their wraps/bindings would be nice, also improves the handle progression if you mostly care about speed as there would be something between sticks and blaze rods (or end rods if you don't like getting set on fire)

### Tetra synergies

Fills in some gaps in the handle progression, and adds more choices for customization.

**Comment by mickelus** [comment]
wontfix
