### ISSUE TITLE
cyclic enchantments 

### ISSUE THREAD

**Issue by suduko666** [mickelus/tetra#546]
### Feature description

name - auto smelt
description - smelts whatever you harvest with this tool.
id - cyclic:auto_smelt
max level - 1
applicable items - pickaxe, shovel, axe, hoe
enchantability function - i have no idea how to find this

name - disarm
description - chance to disarm opponent on hit.
id - cyclic:disarm
max level - 7
applicable items - sword
enchantability function

name - growth
description - grow nearby crops while held.
id - cyclic:growth
max level - 7
applicable items - hoe
enchantability function

name - ender
description - throws an ender pearl with your sword, consuming durability. cooldown decreases with level.
id - cyclic:ender
max level - 7
applicable items - sword
enchantability function

also i would love to know how to add these in myself for the future as im sure ill end up adding tetra to future modpacks i play with my friends as they really like it and being able to do on the fly temp fixes as needed would be helpful.

### How it improves the player experience

-

### Tetra synergies

-

**Comment by mickelus** [comment]
Closing, as of 4.3.0 tetra supports all enchantments.

**Comment by suduko666** [comment]
alright cool and thank you after being sick for a week this is good to hear.

**Comment by suduko666** [comment]
so i just relised 4.3.0 is for 1.18 isnt it
