### ISSUE TITLE
[Bug] crash when using holosphere

### ISSUE THREAD

**Issue by Kiryonn** [mickelus/tetra#548]
### Observed behaviour

I'm new to this mod, which is good... i think... well anyways i do some stupid stuff, clicking everywhere like a noob to see what's possible or not. At some point i crashed while performing a specific action that i was able to reproduce (this isn't hard at all)

### Expected behaviour

i was expecting to gain more informations about enchantments and the table thanks to the holosphere. i thought maybe it had some kind of tweak that makes enchantments behave differently.

### Steps to reproduce

1. Get there or anywhere with the enchantment tab
![image](https://user-images.githubusercontent.com/60699390/149006057-9f3d64c4-b261-4609-97ec-3e6c22827c97.png)
2. Click on an enchantment. I clicked on unbreaking III while testing. maybe not all of them makes you crash but i doubt it
3. there it is, the "saving world" screen followed by the game with exit -1
 

### Crashlog

https://gist.github.com/Kiryonn/a6f540e334efc1e13f52be8831a4fb94

### Tetra version

4.3.0

### mGui version

4.1.0

### Forge version

1.18.1 - 39.0.18

### Other mods

stated in the crash file

**Comment by jduni** [comment]
Ditto here, same situation, repeatable. And my modlist is distinct from op's. 

**Crashlog**
https://gist.github.com/jduni/3b860fa52cd27fc38c53a9f72d337d60

**Comment by mickelus** [comment]
Fixed in 4.4.0.
