### ISSUE TITLE
[Feature] Rack and holosphere

### ISSUE THREAD

**Issue by Kiryonn** [mickelus/tetra#549]
### Feature description

As hammers, axes, and other tools can be used by the workbench when on a nearby rack, i think it would make sense if the holoshpere could be detected that way too.

### How it improves the player experience

Players wouldn't need to exit the gui to pick up their holosphere that they could have lost in one of their billions chests.

Instead they just need to put the holosphere on a rack nearby the workbench as other tools, and when there is a section that needs the holoshpere to get more info, it is automatically detected and used.

### Tetra synergies

welp as i said, all other tools do that, it would just make sense, in my opinion, to add that feature for the holosphere.

**Comment by TheVillain-Inc** [comment]
I assumed this was a feature. +1. 

Be neat if it fitted into the Tetra Crafting Bench as its own slot.

**Comment by osirisgothra** [comment]
agreed, a pain to pick up the sphere off the rack every time I want to make stuff and need extra info, not sure if this is still a problem, though it is in atm:volcano block, skies, etc.  Maybe we need a holosphere pedestal or something.

**Comment by mickelus** [comment]
The holosphere can be placed on its own near the workbench and it'll become available from the workbench UI! That was added some time ago, should have closed this back then.
