### ISSUE TITLE
Belt quiver with quick latch does not work with item in offhand

### ISSUE THREAD

**Issue by Canada-LaVearn** [mickelus/tetra#552]
### Observed behaviour

When using a quiver with a quick latch, the bow will not draw back with an item in the offhand (eg. shield)

### Expected behaviour

Bow is expected to draw back as if arrows were in the inventory

### Steps to reproduce

1. Equip belt with quiver
2. Upgrade quiver with quick latch
3. Insert arrows into quiver
4. Place item in offhand (shield, torch, etc)
5. Attempt to pull bow back
6. Observe that no pullback occurs

### Tetra version

4.3.0

### mGui version

4.1.0

### Forge version

1.18.1 39.0.10

### Other mods

69 other mods present, mod is included in datapack.

**Comment by MsVella** [comment]
For some reason, my request showed up as by this other person, but I'm the one who submitted it if you need anything else.

**Comment by mickelus** [comment]
Unclear how this would work in practice. Afaik there has to be an itemstack whose item extends ArrowItem for a bow to be able to fire special ammunition (like a spectral arrow), as there's no hook for that.
