### ISSUE TITLE
[Bug] Cannot apply Bane of Illagers or Sea Infusion onto a tetra blade.

### ISSUE THREAD

**Issue by MemeLord32** [mickelus/tetra#553]
### Observed behaviour

When trying to enchant a tetra sword with bane of illagers or Sea infusion. 
![2022-01-13_15 53 37](https://user-images.githubusercontent.com/75860493/149407638-478d4646-8815-4d5d-87aa-28793f180ac1.png)
![2022-01-13_15 53 41](https://user-images.githubusercontent.com/75860493/149407643-678fb9c5-24ec-4700-9b9c-c3c7c7b65d34.png)

### Expected behaviour

Applying the bane of illagers and/or the sea infusion enchantment to the blade

### Steps to reproduce

1. Place Vanilla Sword in workbench
2. Select blade, and use whatever material you desire
3. Select enchant.
3. Place Bane of Illagers or Sea Infusion into material
4. Note that neither can be applied to the blade

### Tetra version

3.20.0

### mGui version

3.3.0

### Forge version

1.16.5 - 36.2.23

### Other mods

Apotheosis
Placebo (Requirement for Apotheosis)

**Comment by mickelus** [comment]
Closing, as of 4.3.0 tetra supports all enchantments.
