### ISSUE TITLE
[get some rest]

### ISSUE THREAD

**Issue by Kiryonn** [mickelus/tetra#554]
### Feature description

  It's all in the tittle. You need some rest. Don't oversleep tho, it's not healthy.

Eat well too. Food is yummi. Food is life.

Also if you have a day where you are on the edges, look up Karameru on youtube. They post some stupid stuff but it's funny and calming, and even tho it's japanese, it's in an universal language. Well i guess you'll see what i mean if you go there one day.
If you're into LoL then Polypuff videos have a funny and calming effect too.
Or you can watch cat videos. That works too.

### How it improves the player experience

A healthy content creator is more productive. Thus is able to come up with new high quality updates faster. Player is now happy :)

### Tetra synergies

Makes you synergies the updates even better.

Continue the good work, love you

**Comment by Kiryonn** [comment]
btw i say that for everyone that works on the project. Not just the owner of it :)

**Comment by mickelus** [comment]
❤️

**Comment by mickelus** [comment]
Food is life indeed, and cat videos.
