### ISSUE TITLE
[Bug] Spear Enchants

### ISSUE THREAD

**Issue by NJArquette** [mickelus/tetra#555]
### Observed behaviour

Spears are unable to hold weapon enchants, severely limiting spears in comparison to sword and axe weapons

### Expected behaviour

I expect to be able to add sharpness  or smite or flame aspect to my spears

### Steps to reproduce

Place spear on table
place sharp I book on enchant option

### Tetra version

4.3.0

### mGui version

4.1.0

### Forge version

1.18.1-39.0.17

### Other mods

https://i.imgur.com/YUGFAlf.png

**Comment by mickelus** [comment]
Won't fix. For now at least.

**Comment by sirius1242** [comment]
Sorry to comment for a closed issue, but I think it may be easier to add a scroll rolled for spear like Battle pickaxe?

**Comment by squimbo** [comment]
encountered this two years later. please fix. what's the point of spears if they aren't considered weapons by the game? :(
