### ISSUE TITLE
[Bug]Crash when hammering forged container

### ISSUE THREAD

**Issue by ins0mniacdrag0n** [mickelus/tetra#557]
### Observed behaviour

When using a hammer to unlock a forged containers latches game goes to a saving screen then crashes to launcher.

### Expected behaviour

Using a hammer on the container should unlock the latches and move the part where i need the claw

### Steps to reproduce

not sure how to replicate but this specific container always crashes

### Crashlog

https://gist.github.com/ins0mniacdrag0n/fce85e1ae0ff8fa4a6fdf9a05dbee0ee

### Tetra version

tetra-1.16.5-3.20.0

### mGui version

unknown 

### Forge version

1.16.5-36.2.20

**Comment by mickelus** [comment]
Closing, duplicate of #261.
