### ISSUE TITLE
[Bug] Blocks missing mineable tag (1.18)

### ISSUE THREAD

**Issue by inkvoiid** [mickelus/tetra#560]
### Observed behaviour

None of the blocks break any faster with an upgraded tool. This could be intended with the geode block, but the basic workbench doesn't break faster with an axe because it is missing the mineable/axe tag (1.18).

### Expected behaviour

Blocks require the mineable/"whatever tool" tag in 1.18 instead of code to decide what tool is efficient in breaking it.

### Steps to reproduce

1. Place a workbench
2. Try breaking it with an axe

### Tetra version

tetra-1.18.1-4.5.0

### mGui version

mutil-1.18.1-4.2.0

### Forge version

1.18.1 - 39.0.59

**Comment by mickelus** [comment]
Fixed in 4.8.0.
