### ISSUE TITLE
Travel Anchors Enchant

### ISSUE THREAD

**Issue by FooterManDev** [mickelus/tetra#561]
### Feature description

Came here from Enigmatica 6 to suggest adding support for the Teleportation enchantment from Travel Anchors to the Tetra tools.

### How it improves the player experience

Makes it so people using the Travel Anchors mod don't need a separate tool to use the enchant.

### Tetra synergies

Useful to those who like to make multi-tools, or use a certain tool quite often.

**Comment by mickelus** [comment]
The enchantment system was reworked in tetra for 1.18 so that mod compat works automatically, I won't add support for modded enchantments for earlier versions.
