### ISSUE TITLE
Tetra mod not working for 1.18.1 Alpha mod

### ISSUE THREAD

**Issue by PernDragon** [mickelus/tetra#562]
### Observed behaviour

I created a double hammer out of stone then later wood.  I created a work bench.
Then I put stone pickaxe on table and I can't click anything.  Not repair, Not Axe head sides, not handle not anything.  So I use the Orb thing.  Mind you I am new to this mod so I had to referance many video's to see if I was messing up.
Anyways I use the orb and am greated with at least nine symbols.  Not of them can I select or click on.  Arrow buttons wont move me around nor will the mouse.  I can't use the mod sadly.  I've waited a few days as it is after all an Alpha but I see no one has brought the issue up.  So I hope I am doing right to mention it.

### Expected behaviour

I expected to upgrade my pickaxe from wood to stone or stone to iron.

### Steps to reproduce

1.  Placed stone pickaxe on table
2. Clicked on surrounding menu for head, stick etc.
3. Got no Response.
4. Tried spear for menu use got over 9 icons that are non clickable
5. won't let me use menu
6. doesn't hint to wear the place is under ground.
7. nothing on my tetra mod works aside from showing me menu's

### Tetra version

4.5.0

### mGui version

?

### Forge version

Current 1.18.1

### Other mods

Optifine
Create
Ski Villages
amplified nether
alexs mobs

**Comment by PernDragon** [comment]
Hope I'm being helpful and not just missing something.

**Comment by mickelus** [comment]
Update to latest mutil.

**Comment by PernDragon** [comment]
Thanks, already did.  It fixed the issue.

**Comment by SlothIsKing** [comment]
I have got the most recent mutil version, and it still does not work, same issue as PernDragon
