### ISSUE TITLE
load fail 

### ISSUE THREAD

**Issue by PeskyBird2** [mickelus/tetra#563]
### Observed behaviour

![afbeelding](https://user-images.githubusercontent.com/98700216/151705412-0c2bd92d-f2d8-44dc-ac30-cdc169a4f43e.png)

### Expected behaviour

that minecraft wil start up and work

### Steps to reproduce

dont know how its happaning

### Tetra version

3.2

### mGui version

3.3

### Forge version

1.18.1-39.0.64

**Comment by mickelus** [comment]
You can't run the 1.16 version of tetra on 1.18.
