### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Kohlraeble** [mickelus/tetra#567]
### Observed behaviour

Mod File: Tetra-Mod-1.18.1.jar
	Failure message: Tetra (tetra) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 4.5.0
	Mod Issue URL: https://github.com/mickelus/tetra/issues/new?template=bug_report.md
	Exception message: java.lang.ClassNotFoundException: se.mickelus.mutil.data.deserializer.BlockPosDeserializer

### Expected behaviour

dont know i just wanna play with it and thats what im getting

### Steps to reproduce

start minecraft

### Tetra version

4.5.0

### mGui version

1.8.1

### Forge version

1.8.1 

### Other mods

alexmobs
autoreglib
biomesoplenty
blockui
citadel
create mc
domum ornamentum
dungeon crawl
effective
flywheel forge
jei
mgui
minecolonies
multipiston
mutil
optifine
quark
structurize
terrablender

**Comment by mickelus** [comment]
I'm just going to close this, those are not valid mutil & forge version and the crash log is missing.
