### ISSUE TITLE
Forged Structure entrace too short to walk through

### ISSUE THREAD

**Issue by Birgliss** [mickelus/tetra#57]
## Bug Report

**Observed Behaviour**

Exploring a forged structure underground, I found what appears to be a doorway and some stairs. But the stairs prevent the player from walking through, due to being unable to break forged blocks, and the player being 2 blocks tall, and not 1.5.
![image](https://user-images.githubusercontent.com/20749209/56843651-3c134600-6871-11e9-96c9-336fb208c7ca.png)

**Expected Behaviour**

The player should be able to walk through the doorway. I'm unaware if there's even another way to walk through that way. 

**Minimal setup needed to reproduce**

- Forge version: 1.12.2 - 14.23.5.2836
- Other mods: tetra-1.12.2-0.27.0.jar
- Tetra configuration: Unmodified from default

**Comment by mickelus** [comment]
I'm unable to reproduce this. I fixed a similar issue (possibly that one, it's difficult to see which turn it is in the screenshot) in 0.25.1. Is it possible that this generated in your world in a previous version?

**Comment by Birgliss** [comment]
Apologies for the delay in responding.

It is entirely possible the world was generated in an older version. However, I never wrote down the version, and I have only encountered it in this world.

As far as I know, this issue can be closed for now, until more information is found (if it is found).
