### ISSUE TITLE
Allow enchanted books to upgrade the level of an enchantment already on a modular tool/weapon.

### ISSUE THREAD

**Issue by LivingLandmine** [mickelus/tetra#570]
### Feature description

I am not sure if this is an oversight or an unintended bug, but modular tools with enchantments can't have their enchantments upgraded with an enchanted book of the same level.

Image: Modular longbow with power IV in workbench.  Attempting to enchant it to power V with another power IV book doesn't work. "The provided material cannot be used for this schematic"

![2022-02-07_16 38 13](https://user-images.githubusercontent.com/31289215/152876814-1b8374c2-423f-417a-8712-b173bf425823.png)

### How it improves the player experience

Allows the player to improve their enchantments on modular items on the workbench like an anvil would.

### Tetra synergies

Vanilla feature that logically would apply to Tetra enchanting as well.

**Comment by sirius1242** [comment]
In version 4.6.0 for 1.18.1, I can't even use an enchanted book with sharpness V to enchant the sword with sharpness IV. I don't know it's a bug or a feature, but this made my experience very bad. If I want to upgrade my enchant level, I need to remove all enchantments in grindstone.

![image](https://user-images.githubusercontent.com/32300858/153740881-ef086ff7-f847-4cac-8ea4-ad3447134552.png)

Forge version: 1.18.1-39.0.58
associated mod list:
AdFinders    6.0.0.1
AdHooks    7.0.0.1
AutoRegLib    1.7-53
BiomesOPlenty    15.0.0.82
CreativeCore v2.4.1
DungeonsArise    2.1.49c
ExplorersCompass    1.1.2
FarmersDelight    1.0.3
ForgeEndertech    8.0.0.0
JRFTL+    1.4.1
JustEnoughCharacters    4.3.3
JustEnoughResources    0.13.1.138
NaturesCompass    1.9.4
Paraglider    5.0.0
PlayerRevive    v2.0.0-pre04
Quark    3.0-334
QuarkOddities
StorageDrawers    10.1.1
TerraBlender    1.0.0.22
TravelersBackpack    7.0.1
TorchBowMod    v1.0-Beta
balm    2.4.2+0
corpse    1.0.4
create    v0.4d    
flywheel    0.6.0
jei    9.2.3.78
macawsbridgesbop    1.0
mcw-bridges    2.0.1    
mutil    4.4.0
selene     12.0
starlight    1.0.0+forge.4fd2e63
supplementaries    1.1.11
tetra    4.6.0
waystones    9.0.3

**Comment by mickelus** [comment]
Fixed in 4.7.0.
