### ISSUE TITLE
holosphere ui is not workinf

### ISSUE THREAD

**Issue by lokilost1** [mickelus/tetra#573]
### Observed behaviour

i can open it and it does the + line + line thing but i cannot click on any  icon in it 

### Expected behaviour

i feel like me clicking on it should do somthing

### Steps to reproduce

make hammer
get holosphere
open holosphere
click on an icon
nothing happens

### Tetra version

4.3.0

### mutil/mGui version

4.20

### Forge version

1.18 - 38.0.17

### Other mods

minecolonies
multi
sodium
betterthanmending
configurablecane
blockui
create
dungeoncrawl
domum_ornamentum
mcw-bridges, fences, trapdoors, windows
jei
flywheel
irisop-ores
multipiston
optifine
pocketmobfarms
sophisticadebackpacks
squatgrow
structurize
terralith
waystones
xaeros minimap and worldmap
balm
craftable emeralds
furniture
finally cc:tweaked but it dosent work

**Comment by mickelus** [comment]
Update both tetra and mutil to latest.

**Comment by lokilost1** [comment]
thanks so much now it works and it looks so cool
