### ISSUE TITLE
1.18.1?

### ISSUE THREAD

**Issue by shloakvatsyayan** [mickelus/tetra#578]
### Feature description

I noticed this mod was updated in 1.16.5 even after the 1.18 update and I wanted to ask if there is a 1.18 version in development. If not, that would be my request.

### How it improves the player experience

With the widely growing number of mods updating to 1.18, it would help players use their 1.18 mods with is amazing mod.

### Tetra synergies

This will overall, improve the player experience with this mod and remove the compatibility issues for the reason that this mod uses an older version.

**Comment by AzeznLadyofFloof** [comment]
Not to be rude, but there is a 1.18.1 version. it's an alpha but still
