### ISSUE TITLE
[Bug] No structures latest version (tetra-1.18.1-4.7.0)

### ISSUE THREAD

**Issue by FlitzerPS** [mickelus/tetra#581]
### Observed behaviour

structures not loaded. It makes impossible to have fun with amazing this mod.

### Expected behaviour

full experience? 

### Steps to reproduce

install latest ver.
searching hours and hours for the factory below mountains.
thats it.

### Crashlog

no crash

### Tetra version

4.7.0

### mutil/mGui version

4.4.0

### Forge version

39.0.66

**Comment by mickelus** [comment]
Closing, duplicate of #558.
