### ISSUE TITLE
[Bug] minecraft crashes when creating world

### ISSUE THREAD

**Issue by Comfyrain** [mickelus/tetra#583]
### Observed behaviour

minecraft crashes when creating a new world

### Expected behaviour

disable geodes from spawning

### Steps to reproduce

changing the geode density to 0 in  Tetra TOML file

### Crashlog

https://gist.github.com/Comfyrain/aebe90a310ce60652cca447b83d7d669

### Tetra version

1.18.1-4.8.0

### mutil/mGui version

1.18.1-4.4.0

### Forge version

39.0.88

**Comment by mickelus** [comment]
Please don't omit the crash log when reporting crashes...

**Comment by Comfyrain** [comment]
> Please don't omit the crash log when reporting crashes...

my bad , I uploaded the crashlog

**Comment by BaguaXingyiZhang** [comment]
I had the same problem with Minecraft 1.16.5 with forge-1.16.5-36.2.21 and tetra-1.16.5-3.20.0.jar. It crashed any time if a structure tries to generate. So if you are near it, it always crashes the server instantly after login.

**Comment by mickelus** [comment]
Fixed in 4.8.1.
