### ISSUE TITLE
[Feature] Config Option to change all of minecrafts menus to the tetra panel format

### ISSUE THREAD

**Issue by Merith-TK** [mickelus/tetra#588]
### Feature description

I want there to be a resource pack, or option in the mod, to change all of minecraft's base hud assets and textures, to look and function like Tetra's menus

### How it improves the player experience

immersion into the mod, also it looks freaking cool

### Tetra synergies

Design

**Comment by mickelus** [comment]
wontfix

**Comment by Merith-TK** [comment]
not a wontfix, there is no bug to be fixed here! lol
