### ISSUE TITLE
Curseforge missing newest version of Tetra

### ISSUE THREAD

**Issue by Zaldbathar** [mickelus/tetra#589]
### Feature description

Could you please add the 1.18.1 version to curseforge so people dont have to go to shady AF websites just to get it?

### How it improves the player experience

People will be able to download your mod without risk of malware

### Tetra synergies

Whats more synergistic then making the mod possible to get at all?

**Comment by mickelus** [comment]
Alpha releases aren't visible on curseforge by default.
