### ISSUE TITLE
Tools modified by Tetra do not show as enchanted when enchanted through Quark's Matrix enchanting[Bug] 

### ISSUE THREAD

**Issue by LapizGaming7751** [mickelus/tetra#591]
### Observed behaviour

Although enchanted effects are present, no glint nor effects are shown on sprite or on the item's lore. 

### Expected behaviour

Item is supposed to have enchanted glint along with enchanted effects shown in item lore/description

### Steps to reproduce

1: Have Quark's matrix enchant module open
2: Make a tool, anything through the Tetra workbench
3: Enchant the tool using an enchanting table (Which if Step 1 is followed should be Matrix)
4: Enjoy bugginess

### Tetra version

3.20.0

### mutil/mGui version

3.3.0

### Forge version

1.16.5 - 36.1.32

### Other mods

Quark r2.5-322
Quark Oddities 1.16.3

**Comment by mickelus** [comment]
Tetra doesn't work with matrix enchanting in 1.16, so it's good you enjoy the bugginess.
