### ISSUE TITLE
[Bug] Game crashes when right clicking basic_workbench.

### ISSUE THREAD

**Issue by Lemonmito** [mickelus/tetra#592]
### Observed behaviour

Game crashed.

### Expected behaviour

Open a workbench screen normally.

### Steps to reproduce

Right clicking basic_workbench.

### Tetra version

3.20.0

### mutil/mGui version

3.3.0

### Forge version

1.16.5-Forge_36.2.28

### Other mods

https://mclo.gs/Da0GxPU

**Comment by mickelus** [comment]
Is the modlist in the crashlog the smallest set required to reproduce this issue?
