### ISSUE TITLE
[Bug] when trying to launch comes up with error tetra has failed to load correctly

### ISSUE THREAD

**Issue by JRKE-dev** [mickelus/tetra#595]
### Observed behaviour

I launched Minecraft 1.18.2 with a few mods (I also tried without the other mods but I got the same error)  including tetra and it came up with the error Tetra (tetra) has failed to load correctly. 

### Expected behaviour

I expected it to launch and I would be able to play

### Steps to reproduce

1. I downloaded the latest version of 1.18.2 forge. 2. I put it in my mod folder. 3. I launched Minecraft. 4. the error showed up.

### Crashlog

java.lang.reflect.InvocationTargetExpansion: null

### Tetra version

4.5.0

### mutil/mGui version

4.4.0

### Forge version

1.18.2 40.0.21

### Other mods

I tried with and without the mods but here are them 
Incendium_v5.0.3 2.jar
jei-1.18.2-9.5.4.171.jar
MerchantMarkers-1.18.1-1.1.3.jar
NaturesCompass-1.18.2-1.9.5-forge.jar
ohmygoat-fabric-1.18.2-1.1.0 copy 2.jar
PuzzlesLib-v3.3.2-1.18.2-Forge.jar
StorageDrawers-1.18.1-10.1.1.jar
swingthroughgrass-1.18.1-1.8.0.jar
unusualfishmod-0.2.3.1 copy 2.jar
valhelsia_core-forge-1.18.2-0.3.0.jar
valhelsia_structures-forge-1.18.2-0.1.0.jar

**Comment by mickelus** [comment]
Most 1.18.1 mods are not compatible with 1.18.2.

**Comment by JRKE-dev** [comment]
I had no problem launching the mods 
I tried without tetra and it worked

**Comment by Joro1144** [comment]
Is it possible that we can get a minor update for 1.18.2? Just to have this mod for that version?
