### ISSUE TITLE
[Bug] Amethyst isn't recognized as a material due to having the wrong item name.

### ISSUE THREAD

**Issue by ambientNexus** [mickelus/tetra#596]
### Observed behaviour

materials/gem/amethyst.json has minecraft:amethyst as the item, and as that doesn't exist, the material doesn't show up.

### Expected behaviour

The correct name would be minecraft:amethyst_shard, rather than minecraft:amethyst.

### Steps to reproduce

1. Place tool in table.
2. Select any module.
3. Attempt to put amethyst shard in material slot.

### Tetra version

Any 1.18 Version

### mutil/mGui version

Any 1.18 Version

### Forge version

Any 1.18 Version

### Other mods

Bug happens regardless of mods installed.

**Comment by Xaidee** [comment]
#586
