### ISSUE TITLE
Amethyst isnt properly defined in the materials file

### ISSUE THREAD

**Issue by Archilyte** [mickelus/tetra#597]
### Observed behaviour

Amethyst is not a gemstone material (its minecraft:amethyst_shard not minecraft:amethyst lol)

### Expected behaviour

Amethyst is a gemstone material

### Steps to reproduce

Load game with latest tetra version, then try making anything out of amethyst

### Crashlog

N/A

### Tetra version

Latest

### mutil/mGui version

Latest

### Forge version

1.18.1 latest

### Other mods

None

**Comment by Archilyte** [comment]
#596 i guess someone beat me to it

**Comment by Xaidee** [comment]
#586
