### ISSUE TITLE
[Bug]  Tier Bug 1.18.1

### ISSUE THREAD

**Issue by Thyme2be** [mickelus/tetra#598]
### Observed behaviour

Even if you reach the requirement tier of your tool, it still can't be upgraded and keeps saying, "You have tier 0 available."

### Expected behaviour

It can be upgraded if the tool has reached the required tier. 

### Steps to reproduce

![2022-04-05_00 31 54](https://user-images.githubusercontent.com/102987816/161599699-166b9086-3fe8-4358-8ed6-64fdadbaa268.png)
![2022-04-05_00 33 22](https://user-images.githubusercontent.com/102987816/161599724-2952eb81-fdf4-455f-afc1-4fd977aa0dae.png)

### Tetra version

4.8.1

### mutil/mGui version

4.4.0

### Forge version

1.18.1

**Comment by mickelus** [comment]
You can't use the tool to upgrade itself.
