### ISSUE TITLE
Honing speed on hilt makes it slower [Bug] 

### ISSUE THREAD

**Issue by MemeLord32** [mickelus/tetra#599]
### Observed behaviour

When I try to hone my handle for speed, and the speed is already negative, the honing makes it slower, not faster.
![2022-04-06_11 36 43](https://user-images.githubusercontent.com/75860493/162013635-111dc091-588a-4b9a-b120-f9cd7abb0345.png)

### Expected behaviour

I expect it to improve the speed, not make it slower.

### Steps to reproduce

1) Obtain a tool/weapon with a negative speed.
2) Get it to honing level.
3) Try to hone the speed on the handle

### Tetra version

4.8.1

### mutil/mGui version

4.4.0

### Forge version

1.18.1 - 39.1.2

### Other mods

Gobber (The material used was from the gobber mod) - Gobber2-Forge-1.18.1-2.6.20.jar

**Comment by MemeLord32** [comment]
I also figured out that once the speed reaches 0, when you hone the speed on the handle, it does nothing...
![2022-04-06_11 46 47](https://user-images.githubusercontent.com/75860493/162015102-4dee361c-e2ad-46ba-8a57-e9f178883df5.png)

**Comment by MemeLord32** [comment]
I got it to 0 by honing the speed on the heads first, and then deciding to hone the speed on the handle

**Comment by mickelus** [comment]
> I expect it to improve the speed, not make it slower.
What do you really expect here though? What does a 5% attack speed bonus mean when the attack speed is a negative value?

**Comment by MemeLord32** [comment]
Ahh, I thought it would be a flat increase like when you hone the heads (I think the heads gives a flat increase for speed honing).

**Comment by MemeLord32** [comment]
If that's the case, then this isn't really an issue then. Thank you for responding.
