### ISSUE TITLE
[Question] Discord Server for Discussion

### ISSUE THREAD

**Issue by MasterEnderman** [mickelus/tetra#6]
Is there a discord Server of some kind for further discussion of stuff? I want to include this mod in my new pack and i really would like to have some compat between tetra and the other mods. :)

**Comment by mickelus** [comment]
I've got a channel set up in the MMD discord, here's an invite link: https://discord.gg/2gVdQWz

**Comment by MasterEnderman** [comment]
Thanks for letting me know :D
