### ISSUE TITLE
Questions about integrating Tetra.

### ISSUE THREAD

**Issue by chris-wjn** [mickelus/tetra#601]
### Feature description

Only writing this here because the modding section of the discord seems to be inactive.
I've added Tetra as a dependency to my project successfully, but am running into a few issues I'm hoping you can shed a bit of light on or let me know if what I'm attempting is not possible currently.
- My mod adds several attributes. I'd like to integrate them into Tetra by using the data system to add them to modules. Currently, adding attributes this way does not seem to work with non-vanilla attributes. I tested this by using identical code, one with my attribute and one with vanilla attack damage. Are these attributes hard coded?
- NBT tags and attributes don't carry over when crafting a modular item out of a vanilla tool at the workbench. Not sure if this is intended or not, but it would be really helpful to know.
- This isn't really an issue, per say, as I've not been able to get the attributes working to even test this. I planned to add gui bars to the workbench for each of my mod's attributes. I looked through your source code and tried to determine what to do, and I ended up essentially copying what you have in GuiStatBar and then registering it (I think?) to the workbench by calling WorkbenchGui.addbar() on it. Is this the correct way to do this?

Any advice would be appreciated greatly. Big fan of your work!

### How it improves the player experience

If I can get my mod to work it would add more depth to weapon crafting, which I think would be really cool.

### Tetra synergies

More variety in terms of tool crafting.

**Comment by mickelus** [comment]
If I understood you correctly on discord you've got this working. Feel free to poke me over there if you want to discuss anything else, I'll try to be faster to respond the next time :P
