### ISSUE TITLE
1.18.2

### ISSUE THREAD

**Issue by StormDragon-64** [mickelus/tetra#603]
### Observed behaviour

Tetra has no version for 1.18.2 on curseforge which means I can't update my modpack.

### Expected behaviour

Tetra would have a version marked as compatible with 1.18.2 or a separate version for 1.18.2 on curseforge.

### Steps to reproduce

Look at terta's curseforge page, you will see no 1.18.2 version.

### Crashlog

-

### Tetra version

-

### mutil/mGui version

-

### Forge version

-

**Comment by XionioXMaster** [comment]
need update)

**Comment by mickelus** [comment]
Don't abuse the issue tracker.
