### ISSUE TITLE
[Bug] Crash when some features on basic workbench are used

### ISSUE THREAD

**Issue by Nekogamer90** [mickelus/tetra#604]
### Observed behaviour

The game crashes when i temper, serrate, or curve a sword

### Expected behaviour

It adds the attributes with no issue

### Steps to reproduce

place a sword in the basic workbench
make it a heavy blade
temper, curve, or serrate it

### Crashlog

https://bytebin.lucko.me/KirQ07Ctp2

### Tetra version

tetra-1.16.5-3.20.0.jar

### mutil/mGui version

 mgui-1.16.5-3.3.0.jar

### Forge version

1.16.5 36.2.20

### Other mods

                notenoughcrashes-4.1.4+1.16.5-forge.jar      
		mowziesmobs-1.5.23.jar        
		BetterDungeons-1.16.4-1.2.1.jar     
		dusk-1.4.jar          
		oga-v1.0.jar          
		spiders-2.0-1.16.4-1.0.4.jar   
		bountifulbaubles-1.16.5-0.1.0-forge.jar   
		jei-1.16.5-7.7.1.152.jar     
		Druidcraft-1.16.5-0.4.54.jar        
		abnormals_core-1.16.5-3.3.1.jar     
		BetterCaves-Forge-1.16.4-1.1.2.jar   
		God_Slayer-1.16.4-v0.4.4.jar      
		EpicFightMod-16.5.13.jar       
		FastSuite-1.16.4-1.1.1.jar      
		mgui-1.16.5-3.3.0.jar          
		Placebo-1.16.4-4.4.2.jar           
		citadel-1.8.1-1.16.5.jar        
		alexsmobs-1.12.1.jar             
		untamedwilds-1.16.5-1.5.4.jar   
		YungsApi-1.16.4-Forge-13.jar     
		environmental-1.16.5-1.1.1.jar   
		champions-forge-1.16.5-2.0.1.13.jar  
		[1.16.5]-Epic-Knights-Armor-and-Weapons-5.9v.jar 
		MutantBeasts-1.16.4-1.1.3.jar     
		guardvillagers-1.16.5.1.2.6.jar     
		magnesium-1.5.jar          
		mahoutsukai-1.16.5-v1.34.11.jar        
		JustEnoughResources-1.16.5-0.12.1.128.jar   
		Paraglider-1.16.5-1.3.2.7.jar      
		forge-1.16.5-36.2.20-universal.jar    
		TravelersTitles-1.16.4-1.5.jar     
		corpse-1.16.5-1.0.6.jar        
		antiqueatlas-5.4.4-forge (1).jar   
		DungeonsArise-1.16.5-2.1.49-beta.jar  
		Ability_Powers_rework_1.2.1.jar     
		forge-1.16.5-36.2.20-client.jar     
		upgrade_aquatic-1.16.5-3.1.2.jar     
		TenshiLib-1.16.3-1.3.0.jar           
		FarmersDelight-1.16.5-0.5.5.jar     
		Alex's Delight 1.1.3 - Forge 1.16.5.jar   
		Leos_Mushrooms-1.16.4-v0.5.1.jar     
		YungsBridges-Forge-1.16.4-1.0.1.jar   
		Ksyxis-Forge1.14thru1.16-1.1.jar     
		darkerdepths-1.16.5-1.1.4.jar     
		wardance-0.8.7.0.jar        
		Bountiful-1.16.4-3.3.1.jar          
		farmersrespite-1.16.5-1.1.jar      
		curios-forge-1.16.5-4.0.5.3.jar     
		tetra-1.16.5-3.20.0.jar        
		eidolon-0.2.7.jar             
		tetranomicon-1.3.jar      
		SpartanShields-1.16.5-2.1.2.jar    
		savageandravage-1.16.5-3.2.0.jar  
		autumnity-1.16.5-2.1.2.jar             
		kryptonreforged-mc1.16.5_v1.0.0.jar    
		YungsExtras-Forge-1.16.4-1.0.jar      
		performant-1.16.2-5-3.93m.jar       
		entityculling-forge-mc1.16.5-1.4.0.jar    
		illagersweararmor-1.0.5.jar       
		Chunk Pregenerator V1.16-3.2.2.jar   
		BetterStrongholds-1.16.4-1.2.1.jar   
		cavebiomeapi-1.16.5-1.4.2.jar     
		SpartanWeaponry-1.16.5-2.2.0-rc-2.jar     
		mutantmore-1.16.5-1.0.0.jar          
		appleskin-forge-mc1.16.x-2.4.0.jar     
		[BETA]dannys_expansion1.16.5-1.0.9.1.jar    
		ferritecore-2.1.0-forge.jar    
		AI-Improvements-1.16.5-0.4.0.jar     
		cloth-config-4.14.54-forge.jar       
		byg-1.3.5.jar               
		Aquaculture-1.16.5-2.1.22.jar 
		improvedmobs-1.16.5-1.10.7.jar 
		CosmeticArmorReworked-1.16.5-v5.jar 
		BetterMineshafts-Forge-1.16.4-2.0.4.jar
		geckolib-forge-1.16.5-3.0.68.jar

**Comment by mickelus** [comment]
Try removing sodium.

**Comment by mickelus** [comment]
Ow, wrong button!

**Comment by bloodyeyesblackblood** [comment]
> Ow, wrong button!

Hey, mickelus.

Game Crash when Inserting a Netherrite Sword.
Easily Found out it's Magnesium (Sodium*) since I already had Problem with another Mod and (Sodium*)

Also how does the Mod work with Compatible mods like Powder Power? some tools work and some not?
I mainly play on 1.16.5, also tried on 1.18.2 and some tool still weren't compat. with Tetra? just the Obsidian Shovel and Pickaxe.

ps: The Mod is overwhelming and weird at first but somehow I got to Like it, thank u for the mod ❤️^^

Edit: rejoining into the world doesnt work anymore after inserting the sword, removed (Sodium*) again, worked.

I'm removing it for a while in Favor of Tetra and other mods that are not Compat. with it.
