### ISSUE TITLE
[Bug] Minecraft version 1.18.2

### ISSUE THREAD

**Issue by AppleMangoOrange** [mickelus/tetra#609]
### Observed behaviour

Minecraft is crashing at startup

### Expected behaviour

Minecraft runs (without crashing)

### Steps to reproduce

Run forge 1.18.2 with tetra, mutil

### Crashlog

https://gist.github.com/AppleMangoOrange/85bc19b1673dbb04ff8dde79417d3449

### Tetra version

4.8.1

### mutil/mGui version

4.4.0

### Forge version

1.18.2 - 40.1.0

### Other mods

none

**Comment by AppleMangoOrange** [comment]
All mods I have downloaded till now that are compatible with 1.18.1 are also compatible with 1.18.2. Is this not the case with Tetra?

**Comment by whatsubon** [comment]
> All mods I have downloaded till now that are compatible with 1.18.1 are also compatible with 1.18.2. Is this not the case with Tetra?

This generally can't be assumed -- although in some cases mods for 1.18.1 will work in 1.18.2 without modification, 1.18.2 has several wide-reaching changes which prevent full backwards compatibility. Working 1.18.1 mods are a lucky exception, rather than the expected behaviour.

**Comment by AppleMangoOrange** [comment]
Thanks for replying! I had made this assumption from previous minecraft versions (1.16.3 mods being compatible with 1.16.4 etc.). Now I know this is not the case here. Is the mod being updated to 1.18.2?
