### ISSUE TITLE
[Bug] java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by neocrypter** [mickelus/tetra#611]
### Observed behaviour

minecraft failed to load with current alpha of tetra for 1.18+

### Expected behaviour

expected minecraft to load

### Steps to reproduce

load minecraft

### Crashlog

https://gist.github.com/neocrypter/f657a5cb813c04d8b05a51d35dcd6215

### Tetra version

4.8.1

### mutil/mGui version

4.4.0

### Forge version

40.1.0

### Other mods

![image](https://user-images.githubusercontent.com/1081551/167198804-221f5788-f398-4651-b273-3d140ef1f719.png)
![image](https://user-images.githubusercontent.com/1081551/167198831-a7922913-dd2b-4638-8af8-a10c591e18d3.png)
![image](https://user-images.githubusercontent.com/1081551/167198864-9900f9f6-87a7-45d2-88dd-bdff12132272.png)
![image](https://user-images.githubusercontent.com/1081551/167198888-37a4a0b4-41e7-47fe-83c0-2844712face6.png)
![image](https://user-images.githubusercontent.com/1081551/167198926-f83d24cc-0ef2-4d9a-bf80-bc11d6400864.png)
![image](https://user-images.githubusercontent.com/1081551/167198956-24b023bf-5a9b-45bf-aed7-c49c63cb6280.png)
![image](https://user-images.githubusercontent.com/1081551/167198979-fe7570a6-fa4a-4b37-a9e2-99ef07b689e4.png)
![image](https://user-images.githubusercontent.com/1081551/167199005-56b14b6f-08f5-4285-863a-10157a312c89.png)
![image](https://user-images.githubusercontent.com/1081551/167199035-34fb8544-fd18-4235-9af4-32a6199e836f.png)
![image](https://user-images.githubusercontent.com/1081551/167199055-ece2f576-e631-4dc3-9056-543a7f7159a5.png)
![image](https://user-images.githubusercontent.com/1081551/167199076-78b75d9b-0712-4bb4-8d13-efdbd15db5f1.png)
![image](https://user-images.githubusercontent.com/1081551/167199090-e68bf4f2-82c9-44db-9f0a-cecaca6af2f9.png)
![image](https://user-images.githubusercontent.com/1081551/167199121-07a32381-eaa2-47cf-a1ae-3e1f36e7764b.png)
![image](https://user-images.githubusercontent.com/1081551/167199147-2da8ac6c-a302-4114-8c58-fdd7dbf8e018.png)
![image](https://user-images.githubusercontent.com/1081551/167199155-87164743-ad0a-4556-9dfe-bcebb4c85d2e.png)
![image](https://user-images.githubusercontent.com/1081551/167199184-33c6565f-076e-40d4-9e59-8a85e0489abf.png)

**Comment by neocrypter** [comment]
I just ran a completely separate test of a an instance of Minecraft with no other mods loaded just tetra and multi to make sure it wasn't a mod conflict since I do have several mods on the instance i initially tried it on and got the same result.

**Comment by mickelus** [comment]
Tetra is not available for 1.18.2 yet.

**Comment by neocrypter** [comment]
Yup i figured that out, though on forge it just says 1.18 hence why i tried  
![image](https://user-images.githubusercontent.com/1081551/167213416-de469975-96f9-417a-96aa-756d04be841d.png)

**Comment by mickelus** [comment]
It says 1.18.1 in the screenshot :P
