### ISSUE TITLE
[Bug] Throwable bucklers cover most of the screen

### ISSUE THREAD

**Issue by irkedIsaac** [mickelus/tetra#612]
### Observed behaviour

When "charging" the throw for a buckler with an aerodynamic trim (and possibly some of the other shields, I haven't thoroughly tested them), it renders very crooked across the screen, blocking _most_ vision.  Screenshot related.  This issue has been present across all versions of the mod I've played with, so I have no idea how far back it goes.

![unknown](https://user-images.githubusercontent.com/8321791/167457956-7d5bdcaf-309d-416d-8c89-e9d74baffd38.png)

### Expected behaviour

Ideally, the shield should render off to the side like every other thing that has a "charging" animation (such as the trident). 

### Steps to reproduce

1.  Place a shield into the workbench.
2.  Replace the shield plate with a buckler.
3.  Add the aerodynamic trim to the plate.
4.  Charge throw.

### Tetra version

4.8.1

### mutil/mGui version

4.4.0

### Forge version

1.18.1 - 39.1.2

**Comment by mickelus** [comment]
Thought you meant the issue with shields not accepting loyalty :P

**Comment by irkedIsaac** [comment]
It turns out I _am_ an idiot, but I've put one up for that as well, my bad

**Comment by mickelus** [comment]
Fixed :O
