### ISSUE TITLE
[Bug] Game won't load

### ISSUE THREAD

**Issue by Nytem** [mickelus/tetra#613]
### Observed behaviour

went to launch the game and was met with the error loading mods screen.

![image](https://user-images.githubusercontent.com/81455405/167484476-b50b3dd6-ffd1-4c1c-aeca-c2d820fe5fad.png)

Here is the log if this helps.
[latest.log](https://github.com/mickelus/tetra/files/8654823/latest.log)

### Expected behaviour

for the game to get to the main menu.

### Steps to reproduce

use the version of forge I'm running and try loading it?

### Tetra version

4.8.1

### mutil/mGui version

4.4.0

### Forge version

1.18.2 - 40.1.19

**Comment by mickelus** [comment]
Tetra for 1.18.1 doesn't run on 1.18.2, the same goes for lots of other mods.
