### ISSUE TITLE
Material details progression. Please, make holo-sphere show all resources you have "learnt"

### ISSUE THREAD

**Issue by Donny1995** [mickelus/tetra#614]
### Feature description

Please make holo-sphere **show all material choices** for selected component, when you **at least once touched** this material

At the moment, you must have all the resources in your inventory to see all possible craft options for a component.
It is a pain, and you can always miss something cool. Missing cool stuff is not cool.

### How it improves the player experience

This will greatly improve (imho) the rewarding feeling of the obtaining new materials, but won't spoiler you all the possible options, so you wont hunt the exact materials.

### Tetra synergies

Viewing extra (rare) resources and it's params may be locked behind upgrading a holo-sphere casing, which is not used at the moment (if casing is not an option, there may be something called "materials scanner")

Viewing exact numbers may be locked behind another holo-sphere upgrade, before having it you may see only some ↑↓ indication of what is better than what in in what criteria?

**Comment by mickelus** [comment]
> At the moment, you must have all the resources in your inventory to see all possible craft options for a component

At the moment it shows all material choices for selected module.
