### ISSUE TITLE
[Bug] "Tetra (tetra) has failed to load correctly" Crash on startup

### ISSUE THREAD

**Issue by ghost** [mickelus/tetra#615]
### Observed behaviour

Using the latest version of Tetra for 1.18, an error occurs when you try to launch the mod.

### Expected behaviour

The game launches and takes you to the title screen like normal.

### Steps to reproduce

1. Install the latest version of Tetra for 1.18 as well as the multi dependency
2. Put them in your mods folder and try to run the game
![image_2022-05-15_211910450](https://user-images.githubusercontent.com/105619424/168514311-af0cae11-324f-4043-a387-ea71932d3946.png)

3. Note how the game goes to the error screen instead of launching normally.

### Crashlog

https://gist.github.com/bunnynerd/4aec5a0e1acdc5930ffb85b20bdc72d3

### Tetra version

4.8.1

### mutil/mGui version

4.5.0

### Forge version

40.1.10

**Comment by mickelus** [comment]
Tetra for 1.18.1 does not work with minecraft 1.18.2.
