### ISSUE TITLE
0.29.0 Crashes serverside on startup (calling client GUI classes)

### ISSUE THREAD

**Issue by al132mc** [mickelus/tetra#62]
## Bug Report

**Observed Behaviour**
Crash on server startup

**Expected Behaviour**
No crash on server startup

**Minimal setup needed to reproduce**

- Forge version: 1.12.2-14.23.5.2838
- Other mods: Shouldn't matter
- Tetra configuration: v0.29.0

**Steps to reproduce**
1. Start up a server with Tetra on 0.29.0
2. ???
3. Crash

[log here](https://pastebin.com/H2nKv7Xv) 
Indeed, the log does not have Tetra in the stack trace, but this bug was introduced after I updated to Tetra 0.29.0 and fixed when I reverted to 0.28.0

**Comment by mickelus** [comment]
That's embarrassing, fixed in 0.29.1 https://minecraft.curseforge.com/projects/tetra/files/2725050
