### ISSUE TITLE
[Bug] Erratic Booster Module (Belt) behavior when Jump key is rebound

### ISSUE THREAD

**Issue by Ballisticannon** [mickelus/tetra#620]
### Observed behaviour

After modifying and equipping a belt with any number of booster modules and an inventory slot to hold gunpowder, the belt's booster functionalities (hover, boosted jump, and elytra boost) all behave erratically with regards to detecting jump inputs. 

During testing, the following was observed when attempting to trigger each booster behavior:

Hover: Jump+Release+Jump-and-hold trigger works **correctly** in approx. 50% of attempts. **Of failures**, approx. 90% simply never activated the hover behavior; approx. 5% resulted in a delayed hover, which began noticeably after the second press of the jump button; and approx. 5% began their hover behavior properly, but would not stop hovering when the button was released, and continued to hover regardless of jump inputs until the booster fuel gauge was empty. In addition, simply holding the jump button will occasionally interrupt the standard behavior of repeatedly jumping with an unstoppable hover, behaving similarly to this last failure case.

Boosted Jump: Crouch+Jump trigger works **correctly** in approx. 50% of attempts. **Of failures**, approx. 30% resulted in an ostensibly normal jump; approx. 60% resulted in a normal jump with a split-second of hovering behavior; and approx. 10% resulted in a strange, _very_ short directional jump, that seems as though it may have been a result of the boosted jump being almost immediately cut short by the split-second hover.

Elytra Boost: Mid-flight Jump-and-hold trigger works **correctly** approx. 50% of the time. **Of failures**, all instances simply had no boosting behavior at all, and resembled standard Elytra flight.

Note that time very clearly seems to be a factor on the Elytra Boost - it appears that the ability to use the elytra boost effectively switches on or off at irregular intervals, such that any attempt to boost will _always_ work normally for a period of around 5-60 seconds, then will _never_ work at all for another 5-60 seconds, and so on. The other triggers also _appear_ to trend towards extended streaks of properly functioning or repeatedly failing, but a handful of trials which focused on repeatedly setting off all three triggers round-robin seemed to show no correlations between the working/failing streaks of each booster function. 

### Expected behaviour

Standard booster module behavior:

Hover: Hitting the jump key in mid-air causes the wearer to begin hovering at their current height until the jump key is released (or until they run out of fuel).

Boosted Jump: Holding the crouch key and hitting the jump key catapults the wearer in the direction they are aiming.

Elytra Boost: Pressing the jump key while in Elytra flight gradually boosts the wearer in the direction they are aiming, for as long as they hold the jump key (or until they run out of fuel).

### Steps to reproduce

1. In Minecraft's "Controls..." option menu, rebind the Jump input to _any_ key or button other than Space.
2. Make a Belt with one or two Booster Modules, and at least one storage module for holding Gunpowder.
3. Store some Gunpowder in the Belt, and equip it.
4. Attempt to use any of the Belt's Booster-Module-related functions.

Be aware that _when_ you rebind the Jump key does not affect the outcome. At any time before or during play, both on networked servers and in singleplayer, setting the Jump key to Space (manually, or via the Reset button) will promptly restore your Belt to its full functionality, and setting it to any other button will put your jump detection right into the more erratic state described above.

_Note: Although the Boosted Jump function relies on both the Crouch button and the Jump button, rebinding Crouch does not appear to interfere with the player's ability to use it. The Jump key seems to be the only one which causes problems when rebound._

### Tetra version

Various; Focused testing performed on Tetra 3.20.0

### mutil/mGui version

Focused testing performed on mGui 3.3.0

### Forge version

Focused testing performed on Forge 36.2.31

### Other mods

Focused testing was performed in the most recent version of Valhelsia 3 (Version 3.5.1), but this behavior has occurred with varying levels of severity in all of my experiences with Tetra's booster modules, which include various versions of other modpacks such as Better Minecraft [PLUS], Medieval Minecraft, and a handful of homebrew modpacks including Tetra which were put together by myself and others. (I've been rebinding Jump to a thumb button on my mouse for years as a result of a somewhat dodgy spacebar, but I was unaware of the cause for this troublesome jump detection on the Belt until I did some more rigorous testing just earlier today.)

**Comment by mickelus** [comment]
This was fixed quite some time ago in 1.18, but I forgot to close the issue. No plans to backport to 1.16.
