### ISSUE TITLE
[Bug] [1.18.2] Cannot wrap tool handle with string

### ISSUE THREAD

**Issue by Lernni** [mickelus/tetra#621]
### Observed behaviour

I have Tetra Mod installed on my multiplayer Forge server. The mod works just fine, except when I try to wrap the handle of my tool out of string. In this case the string won't be applied and moves back to my inventory. For a brief moment you can see the tool with the string handle applied in the Tetra slot, but then it returns to the previous state of the tool.

I can, on the other hand, wrap the tool handle with leather.

This bug only appears when I'm playing on the server. In singleplayer, I can wrap the tool handle with string normally. I have also noticed some error messages appearing in the server log, when starting with Tetra installed. I uploaded the server log as a gist.

### Expected behaviour

The string should be applied to the tool handle in multiplayer, just like it does in singleplayer.

### Steps to reproduce

1. Enter a server world
2. Place a vanilla tool with handle in a workbench.
    (I tried it with an iron axe and a wooden sword)
3. Wrap the tool handle with two strings

### Crashlog

https://gist.github.com/Lernni/995ab807a771f027b5ffa430ed954488

### Tetra version

4.9.1

### mutil/mGui version

4.5.0

### Forge version

1.18.2 - 40.1.0 (Recommended)

### Other mods

None

**Comment by mickelus** [comment]
This should've been fixed in 4.9.3.
