### ISSUE TITLE
[Bug]  Missing Effect Textures

### ISSUE THREAD

**Issue by zachsai** [mickelus/tetra#623]
### Observed behaviour

![image](https://user-images.githubusercontent.com/63996164/171298463-a2f716ec-5601-44c0-86d2-f9a9cddd14b9.png)
Could you add the missing textures please?

### Expected behaviour

Not missing

### Steps to reproduce

Download mod + just enough effect descriptions + jei

### Tetra version

4.9.1

### mutil/mGui version

4.5.0

### Forge version

40.1.25

**Comment by mickelus** [comment]
Which textures are those supposed to be?

**Comment by zachsai** [comment]
bleeding,
stun,
suspended,
mining_speed

**Comment by mickelus** [comment]
Those effects don't render in the UI, so they shouldn't have textures.

**Comment by Lucky-56** [comment]
suggestion:
make them invisible or hide them from JEED entirely
