### ISSUE TITLE
[Bug] Schematics and Racks not working

### ISSUE THREAD

**Issue by squimbo** [mickelus/tetra#626]
### Observed behaviour

Regardless of placed racks' tools, and placed schematics within range, workbenches act as if there is nothing around them.

### Expected behaviour

Tools placed on racks should be accessible to workbenches within range, and schematics placed nearby should allow for workbenches to be used to apply the schematic's modification.

### Steps to reproduce

1. Place workbench
2. Place schematic / rack nearby
2.5. Place tools on rack (if rack was placed)
3. Access workbench and insert a tool or weapon
4. Attempt to modify the tool or weapon in a way that requires a tool or schematic you have placed

### Tetra version

tetra 1.18.2-4.9.1

### mutil/mGui version

mutil 1.18.2-4.5.0

### Forge version

1.18.2 - 40.1.31

**Comment by mickelus** [comment]
It's much easier to resolve an issue if you're more specific on how to reproduce the issue :). This should have been solved in 4.9.**2**.
