### ISSUE TITLE
Changing the mechanics of netherite

### ISSUE THREAD

**Issue by CoolDemon96** [mickelus/tetra#628]
### Feature description

Allows you to use netherite as a shell for tetra-tools as on vanilla instruments.

### How it improves the player experience
Makes netherite the way the developers intended it to be.

### Tetra synergies
Makes tetra closer to vanilla minecraft.

**Comment by mickelus** [comment]
No idea what this is supposed to mean, you need to put in some more effort.

**Comment by CoolDemon96** [comment]
> Понятия не имею, что это должно означать, вам нужно приложить еще немного усилий.

updated everything
