### ISSUE TITLE
Default Compatability with Thermal Foundation materials

### ISSUE THREAD

**Issue by trpg1** [mickelus/tetra#63]
## Feature Request

**Feature description**
Add default support for the metals within Thermal Foundation which are: Aluminum, Platinum, Mana Infused Metal, Iriduim, Constatan, Signalum, Enderium, and Lumium. Some of these metals are also used it other mods to.

**How it improves the player experience**
This improves player experience because it means they wouldn't need to add tool materials for such a commonly used mod

**Tetra synergies**
It synergizes with tetra because it simply adds default support for Thermal Foundation.

**Comment by mickelus** [comment]
I need the following for each tool/weapon:

name
damage
swing speed
durability
harvest capabilities (type, level, speed)
effects (e.g. autosmelt or uses mana to restore durability, sweeping)
usages (e.g. can till dirt or strip logs)

**Comment by mickelus** [comment]
Closing this as it still has not been refined, feel free to reopen if you manage to provided the requested information.
