### ISSUE TITLE
[Bug] Toolbelt booster bar showing for all players in LAN multiplayer

### ISSUE THREAD

**Issue by miner-sd** [mickelus/tetra#630]
### Observed behaviour

when a player uses the booster module on a toolbelt, the cooldown/fuel bar is shown to all players

### Expected behaviour

only the player wearing and using the toolbelt should see the cooldown/fuel bar

### Steps to reproduce

1. set up a LAN server over a virtual network (LogMeIn Hamachi in my case)
2. join the server in survival with a friend
3. craft a toolbelt (belt buckle, 1 iron loop, 2 iron loops, and a booster in my case)
4. hover around with the booster

### Crashlog

no crash

### Tetra version

tetra-1.18.1-4.8.1

### mutil/mGui version

mutil-1.18.1-4.4.0

### Forge version

Forge - 39.1.2

### Other mods

- AppleSkin
- AutoRegLib
- Balm (Forge Edition)
- Better Third Person
- Caelus API (Forge)
- Clumps
- Configured
- Controlling
- Cooking for Blockheads
- Cosmetic Armor Reworked
- Cosmetic Netherite
- Crafting Tweaks
- Create
- Create Chunkloading
- Create Deco
- Create: Alloyed
- Create: Steam Powered
- CreateFoodAdditions
- Curios API (Forge)
- Curious Elytra (Forge)
- Dynamic Lights
- Fast Leaf Decay
- Flywheel
- Food Enhancements
- Just Enough Items (JEI)
- Just Enough Resources (JER)
- Mouse Tweaks
- mutil
- Quark
- Skin Layers 3D (Fabric/Forge)

**Comment by mickelus** [comment]
Fixed this a while back afaik.
