### ISSUE TITLE
[Bug] Tools Do Not Hold Onto Their Improvements

### ISSUE THREAD

**Issue by vivvyinks** [mickelus/tetra#632]
### Observed behaviour

Several different types of improvement simply refuse to remain on a tool. The improvement will briefly appear on the tool then immediately pop back off and reappear in your inventory, with the tool reverting to the state it was in before it had the improvement. This has happened with:

- My friend's diamond pickaxe (could not put hide binding on it)
- My spruce bow (could not install a linear stabilizer)
- a pair of netherite hammers my friend made (could not upgrade the rear head, only allowed the front head to be converted to netherite)
- My iron shovel (could not install a string binding)

In one case (the string binding) the bug went away and I was able to put the binding on after a time. I don't remember WHY it allowed it in that one case, but I'm pretty sure it had something to do with switching to singleplayer. 

### Expected behaviour

The item remains on the tool as expected.

### Steps to reproduce

1. Start a forge multiplayer server (or LAN world).
2. create a Tetra tool (you may have to make several tools before the bug occurs)
3. Attempt to change out one of the modules for a different type of module
4. Bug occurs

### Tetra version

4.9.2

### mutil/mGui version

4.5.0

### Forge version

1.18.2 - 40.1.14

### Other mods

Apotheosis - 5.3.5
AppleSkin - 2.4.0
AutoRegLib - 1.7-53
Balm (Forge) - 3.1.0+0
Bookshelf - 13.2.21
Clumps - 8.0.0+10
Comforts (Forge) - 5.0.0.4
Crafting Tweaks - 14.0.3
Creeper Confetti - 3.11
Curios API (Forge) - 5.0.7.0
Distant Horizons - 1.6.3a
Enchantment Descriptions - 10.0.4
Farmer's Delight - 1.1.2
JEI - 9.7.0.196
JER - 0.14.1.171
Mouse Tweaks - 2.21
Patchouli - 70
Placebo - 6.4.0
Quark - 3.2-358
Selene Lib - 1.17.7
Simple Voice Chat - 2.2.45
Supplementaries - 1.4.6
TimeoutFixes - 1.0.0
Waystones - 10.1.0
YUNG's API - Forge-2.0.8
YUNG's Better Desert Temples - Forge-1.1.0
YUNG's Better Dungeons - Forge-2.1.0
YUNG's Better Mineshafts - Forge-2.1.3
YUNG's Better Strongholds - Forge-2.1.1
YUNG's Extras - Forge-2.1.0

**Comment by vivvyinks** [comment]
BUG UPDATE:

It's not a whole lot but it looks like tools are using up one more item than they should.

**Comment by mickelus** [comment]
This should've been fixed in 4.9.3.
