### ISSUE TITLE
[Suggestion] Adding compatibility for aluminum as a tool material

### ISSUE THREAD

**Issue by Corvus20** [mickelus/tetra#634]
### Feature description

Add the ability to use modded aluminum (such as from Immersive Engineering) in tool construction.

### How it improves the player experience

Yet another material ready to work with right out of the box.

### Tetra synergies

Being that Tetra as a lot of the common modded metals already built in as compatibility, aluminum is the only one I imagine being left to integrate. Being that several popular tech mods use it (Immersive Engineering, Thermal Foundation, etc.) it certainly wouldn't go unused, I reckon.

**Comment by mickelus** [comment]
wontfix
