### ISSUE TITLE
[Bug] Tetra Axes do not trigger Falling Tree mod.

### ISSUE THREAD

**Issue by Angular-Angel** [mickelus/tetra#636]
### Observed behaviour

The [Falling Tree Mod](https://www.curseforge.com/minecraft/mc-mods/falling-tree) allows using an axe to chop down an entire tree at once, or shifting the furthest away log block into the position being chopped, or a number of other behaviors. Unfortunately, it does not recognize Tetra axes as axes, and thus it's behavior does not trigger. This bug has come up [before](https://github.com/mickelus/tetra/issues/517), but the person who reported it did so poorly, and was not given time to explain further before the report was closed.

### Expected behaviour

When using a Tetra axe on a tree with the Falling Tree mod installed, the mods behavior should be triggered on the tree.

### Steps to reproduce

Use Tetra and Falling Tree mod together, then use a Tetra axe to break a log on a tree so that it should trigger Falling Tree.

### Tetra version

4.9.2

### mutil/mGui version

4.5.0

### Forge version

40.1.22

### Other mods

Falling Tree: 3.5.1

**Comment by Angular-Angel** [comment]
Added an issue for Tetra as well: https://github.com/RakSrinaNa/FallingTree/issues/373

**Comment by mickelus** [comment]
Seems like this was resolved on their side! <3
