### ISSUE TITLE
[Bug] Structures not spawning

### ISSUE THREAD

**Issue by GeminiMarshdevil** [mickelus/tetra#637]
### Observed behaviour

i have searched my game world over for an entire 12 hour period in creative and spectator, hunting for any structure built by tetra,  forges of any kind, literally anything at all.  they do not spawn. 

### Expected behaviour

structures to spawn, like the forge hammer or ancient ruins of any kind.

### Steps to reproduce

https://www.curseforge.com/minecraft/modpacks/shaped-aion-cubes/files/3850373

import this modpack (of my design) via any launcher of your choosing (i use AT launcher) and load a singleplayer or server world with any seed.

try and find a structure of any kind.

### Tetra version

4.9.3

### mutil/mGui version

4.5.0

### Forge version

1.18.2 - 40.1.52

### Other mods

over 189 mods present in the Shaped Aion Cubes modpack
found here: https://www.curseforge.com/minecraft/modpacks/s
![Tetra not spawning 2022-06-29_23-33](https://user-images.githubusercontent.com/35816347/176593438-d821f6ad-0e88-48fe-8c79-5bf58d6317b4.png)
haped-aion-cubes/files/3850373

**Comment by mickelus** [comment]
Structures are not available in the 1.18 verions.
