### ISSUE TITLE
Holding tetra tools while near sheep drastically increases MSPT

### ISSUE THREAD

**Issue by BlackStone5677** [mickelus/tetra#639]
### Observed behaviour

If quark and apotheosis are in the pack along with tetra, when you are close to an animal pen with sheep the server TPS drops by a large magnitude, MSPT gets multiplied by around 30.
Basically quark tempts sheep and checks what you are holding for every sheep, apotheosis makes the check more expensive and when it has to check a tetra tool's enchants the check becomes alot more expensive

### Expected behaviour

not produce that much lag

### Steps to reproduce

1. Have apotheosis and quark with tetra in the same pack
2. Put around 10 sheep encased in an animal pen
3. Approach the sheep while holding any tetra item
4. Check tps via /spark tps or /forge tps

### Crashlog

https://spark.lucko.me/Ux001mvJjF here's a spark report to show more insight on what is happening

### Tetra version

3.20.0

### mutil/mGui version

3.3.0

### Forge version

1.16.5 - 36.2.34

### Other mods

Quark: r2.4-322
Apotheosis: 4.8.99F
Spark(just for testing): 1.9.1

Alternatively can try Enigmatica 6 Expert modpack: 1.3.0

**Comment by mickelus** [comment]
This is a mod compat issue that was fixed with the enchanting rework in 1.18, no plans to backport to 1.16.
