### ISSUE TITLE
Standard Blade Knightmetal Has no Armor Pen. Skill

### ISSUE THREAD

**Issue by Shiarbme** [mickelus/tetra#64]
**Observed Behaviour**
Knightmetal Simple Blade has no armor related skill

**Expected Behaviour**
The main knightmetal tools/weapons have an armor related skill

**Minimal setup needed to reproduce**

- Forge version: 1.12.2 - 14.23.5.2838
- Mods: Tetra, Twilight Forest

**Steps to reproduce**
Create a Simple Blade made out of Knightmetal.  Create a Heavy Blade made out of knightmetal, an Axe out of Knightmetal, and a Pickaxe out of knightmetal.  All have armor related abilities related to their Twilight Forest counterparts.  A Knightmetal Simple Blade should have Penetrating 1 to keep in line with being a weaker version of the Heavy Blade.

**Comment by mickelus** [comment]
Closing this since tf has not yet updated from 1.12.
