### ISSUE TITLE
[Bug] Incompatability between Dense Ores Reborn and Tetra pickaxes

### ISSUE THREAD

**Issue by Vaerys-Dawn** [mickelus/tetra#641]
### Observed behaviour

Breaking dense ore blocks drops nothing

### Expected behaviour

the ore block should drop something

### Steps to reproduce

1. make a pickaxe using tetra (i.e. iron pickaxe)
2. attempt to mine a dense ore (i.e. dense copper ore)
3. recieve no drops

### Tetra version

4.9.3

### mutil/mGui version

4.5.0

### Forge version

1.18.2.40.1.68

### Other mods

[Forge 1.18.2] Dense Ores Reborn v3.2

**Comment by Vaerys-Dawn** [comment]
p.s. i am playing on a server

**Comment by Vaerys-Dawn** [comment]
not an issue with tetra, seems to be a bug with the dense ores mod, mod dev doesn't seem to be able to be contacted easily

**Comment by mickelus** [comment]
Thanks for looking into it!
