### ISSUE TITLE
Finding Tetra structures (/locate, structure compass)

### ISSUE THREAD

**Issue by LilJagty** [mickelus/tetra#642]
### Feature description

Hi, I love this mod but its underground structures can be difficult to find, especially when other worldgen mods are in the mix. Having the ability to use the "/locate" command to find Tetra structures would be a big help- and by extension, having the ability to use structure compasses (from other mods). Without these tools, finding the underground forges is nigh impossible.

### How it improves the player experience

It's important that the player can access the more advanced Tetra features only accessible behind finding underground structures, even in modpacks with worldgen changes. This small feature would be a big help. 

### Tetra synergies

It aligns with the goals of Tetra because it makes Tetra a viable tool mod option even in bigger modpacks. Without the ability to find the underground structures, Tetra loses a lot of its unique charm.

**Comment by diceLibrarian** [comment]
judging based on what I've seen from the curseforge/website; I don't think that's going to happen any time soon.

**Comment by mickelus** [comment]
Ruins register as proper structures as of 1.18.
