### ISSUE TITLE
[Compat] with oretweaker

### ISSUE THREAD

**Issue by MikeTheBuddy** [mickelus/tetra#644]
### Feature description

I'm hoping that a combability between oretweaker and tetra could be made where tetra's rules regarding geodes is disabled if oretweaker is detected, as trying to custom modify the geodes to spawn in specific ways completely fails when reaching the deepslate level of the world, where it just completely refuses to generate them leaving these holes instead where deepslate was, instead of the geode blocks.

### How it improves the player experience

It allows for pack developers to better control the ore distribution of geodes as it seems to glitch out when reaching the deepslate level, leaving holes wherever it was supposed to generate.

### Tetra synergies

It doesn't really synergize with tetra features, just it's more of a compatibility thing

**Comment by mickelus** [comment]
Pack developers can already tweak that with a datapack.
