### ISSUE TITLE
[Bug] Unable to craft Shortblade from vanilla sword if Throwing Knife schematic is active

### ISSUE THREAD

**Issue by SuperStormer** [mickelus/tetra#646]
### Observed behaviour

Placing down a Throwing Knife schematic prevents you from changing the blade of a vanilla sword to a Shortblade as there are no more slots in the UI for the Shortblade option. The eight UI slots are taken up by "Throwing Knife", "Enchant", "Carve hook", "Serrate", "Temper", "Basic blade", "Heavy Blade", "Machete". Changing the GUI scale has no effect.

### Expected behaviour

Scrolling is allowed in the UI in order to access the Shortblade option.

### Steps to reproduce

1. Place vanilla sword in workbench
2. Click blade module
3. Attempt to craft shortblade and observe that option is not present.

### Tetra version

4.9.3

### mutil/mGui version

4.5.0

### Forge version

1.18.2 - 40.1.68

**Comment by mickelus** [comment]
There are next/previous buttons which you can use when there are more schematics available than what fits on a page.
