### ISSUE TITLE
[Bug] [1.16.5] Pick is seen as a sword by the vanilla enchanting table.

### ISSUE THREAD

**Issue by ProsperCraft** [mickelus/tetra#649]
### Observed behaviour

![image](https://user-images.githubusercontent.com/4427684/182401579-0a1b8b8d-fb6e-42a3-861d-a9da48c0270a.png)

### Expected behaviour

Enchantments that are valid to a pick show up.

### Steps to reproduce

1. Install TownCraft release candidate refactored 0.3
2. Make an iron pick, and convert it to Tetra
3. Try to enchant it.

The only mod I can think of that may be involved is Lapis Reserve that just keeps the lapis in the enchanting table.  Apotheosis is not installed.

### Tetra version

tetra-1.16.5-3.20.0

### mutil/mGui version

mgui-1.16.5-3.3.0

### Forge version

mohist-1.16.5-1073-server  which is forge-1.16.5-36.2.39

### Other mods

Tool Belt (by gigaherz)
Player Plates (Obsidian Plates) [Forge] (by Gaz_)
Lighting Wand 🌟 (Forge) (by Snownee_)
Iron Age Furniture (by SkyBlade1978)
OAuth (by Sintinium)
Ding (by ohaiiChun)
mutil (by mickelus)
Chocobo Knights of the Crafting Table (by bladeandfeather)
JEI Integration (by SnowShock35)
Sophisticated Backpacks (by P3pp3rF1y)
Obfuscate (by MrCrayfish)
Enigmatic Graves (by Quarris)
Polymorph (Forge) (by TheIllusiveC4)
MmmMmmMmmMmm (Target Dummy) (by MehVahdJukaar)
FTB Quests (Forge) (by FTB)
FTB Library (Forge) (by FTB)
Custom FoV (Forge) (by TheIllusiveC4)
FTB Teams (Forge) (by FTB)
Let Sleeping Dogs Lie (by ohaiiChun)
Passthrough Signs (by Girafi)
Unbreakable Spawner (by Lothrazar)
Hand Over Your Items (Forge) (by Serilum)
CleanView (by LainMI)
More Dragon Eggs (by Darkere)
Clickable advancements[Forge/Fabric] (by someaddon)
TellMe (by masady)
Awesome Dungeon The End edition - Forge (by jtl_elisa)
KubeJS (by LatvianModder)
Immersive Petroleum (by Flaxbeard)
MrCrayfish's Gun Mod (by MrCrayfish)
Drippy Loading Screen [Forge] (by Keksuccino)
Macaw's Roofs (by sketch_macaw)
Emotecraft (Forge) (by KosmX)
Citadel (by sbom_xela)
Controlling (by Jaredlll08)
Crafting Station (by tfarecnim)
Enchantment Descriptions (by DarkhaxDev)
FancyMenu [Forge] (by Keksuccino)
Observable (by tasgon)
Awesome Dungeon Ocean edition - Forge (by jtl_elisa)
Trash Cans (by SuperMartijn642)
MultiBeds (by ShetiPhian)
Many Ideas Core (by GeheimagentNr1)
Many Ideas Doors (by GeheimagentNr1)
ShetiPhianCore (by ShetiPhian)
Open Loader (by DarkhaxDev)
Server Tab Info (by black_dog20)
Macaw's Paintings (by sketch_macaw)
Spawner Bug Fix (by MacTso)
Engineer's Tools (by wilechaote)
Item Filters (by LatvianModder)
Cooking for Blockheads (by BlayTheNinth)
Titanium (by Buuz135)
Macaw's Paths and Pavings (by sketch_macaw)
Yuushya Townscape [Forge/Fabric] (by coco_fish)
Traveller's Boots (by DenisMasterHerobrine)
Just Enough Items (JEI) (by mezz)
The Lord of the Rings Mod: Renewed (by ChildWalrus)
FerriteCore (Forge) (by malte0811)
Decocraft (by RazzleberryFox)
Speedy Ladders (by Dark_Arcana)
Entity Culling Fabric/Forge (by tr9zw)
Colt's Cosmetic Armor Mod (by Colt_Senpai)
Awesome Dungeon Nether edition - Forge (by jtl_elisa)
Comics Bubbles Chat (by Thomas7520)
Extreme sound muffler (Forge) (by LeoBeliik)
Konkrete [Forge] (by Keksuccino)
HeIium (by someoneelsewastaken)
Krate (by owmii)
Autojoin (by Resetium)
Applied Energistics 2 (by AlgorithmX2)
Nature's Compass (by Chaosyr)
Tetra (by mickelus)
EnderTanks (by ShetiPhian)
Macaw's Fences and Walls (by sketch_macaw)
Friendly Fire (by DarkhaxDev)
More Overlays Updated (by RiDGo8)
Inventory Profiles Next (by mirinimi)
In Control! (by McJty)
Storage Drawers (by Texelsaur)
Terracart Reloaded (by Kreezxil)
SuperMartijn642's Config Lib (by SuperMartijn642)
Long Fall Boots (by Nano_Heart)
Just Enough Resources (JER) (by way2muchnoise)
Energy Meter (by DamnRelentless)
Mekanism (by bradyaidanc)
Lootr (Forge) (by Noobanidus)
Mekanism Generators (by bradyaidanc)
Mekanism Tools (by bradyaidanc)
Elytra Slot (Forge) (by TheIllusiveC4)
Tips (by DarkhaxDev)
Just Enough Vehicles (by Ozelot5836)
Sound Device Options (by ichttt)
Re-chiseled (by SuperMartijn642)
Cosmetic Armor Reworked (by LainMI)
Structurize (by H3lay)
Small Ships (by talhanation)
EnderChests (by ShetiPhian)
Overloaded Compressed Blocks (by cjm721)
CC: Tweaked (by SquidDev)
Curios API (Forge) (by TheIllusiveC4)
Effortless Building (by Requioss)
Kotlin for Forge (by thedarkcolour)
Futurepack Mod - Now with flyable Spaceships! (by Mcenderdragon)
Kaleido - Yuushya Townscape Data (by Snownee_)
Macaw's Windows (by sketch_macaw)
Forestry (by mezz)
World Pre Generator (by GeheimagentNr1)
The Mighty Architect (by simibubi)
Lollipop (by owmii)
GeckoLib (by ThanosGecko)
Dank Storage (by tfarecnim)
Load My Resources [Forge] (by Keksuccino)
Shutup Experimental Settings! (by Corgi_Taco)
Spice of Life: Carrot Edition (by lordcazsius)
Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)
Kaleido 🎨 (by Snownee_)
OpenBlocks Elevator (by vsngarcia)
DEUF - Duplicate Entity UUID Fix (by CAS_ual_TY)
Bookshelf (by DarkhaxDev)
KubeJS Immersive Engineering (by LatvianModder)
Industrial Foregoing (by Buuz135)
Tool Stats (by DarkhaxDev)
Gauges and Switches (by wilechaote)
GoProne (by Alpvax)
Caelus API (Forge) (by TheIllusiveC4)
Recipes Library (by GeheimagentNr1)
FTB Industrial Contraptions (Forge) (by FTB)
MrCrayfish's Furniture Mod (by MrCrayfish)
MrCrayfish's Vehicle Mod (by MrCrayfish)
Torchmaster (by xalcon)
Patchouli (by Vazkii)
Friendermite (by CreativeMD)
Kaleido - Yuushya Townscape Resources (by Snownee_)
ChineseWorkshop (by cityofskytcd)
AntiGhost (by Giselbaer)
Immersive Engineering (by BluSunrize)
Crafting Tweaks (by BlayTheNinth)
Awesome Dungeon - Forge (by jtl_elisa)
Auudio [Forge] (by Keksuccino)
Reap Mod (by henkelmax)
Charm of Undying (Forge) (by TheIllusiveC4)
McJtyLib (by McJty)
Rhino (by LatvianModder)
Collective (Forge) (by Serilum)
Clockout (by Commoble)
Jade 🔍 (by Snownee_)
spark (by Iucko)
Construction Wand (by ThetaDev)
Memory Settings[Forge/Fabric] (by someaddon)
Prefab (by wuestman)
Vanilla Expanded - Orcz (by duke2die4)
AppleSkin (by squeek502)
Industrial Renewal Port (by starspath)
Tetranomicon (by syrikalis)
Architectury API (Fabric/Forge) (by shedaniel)
Mod Name Tooltip (by mezz)
Pro Placer (by Fuzs_)
Dramatic Doors (by FizzWare)
Macaw's Lights and Lamps (by sketch_macaw)
Chimes (by BlewberryPie)
Glassential (by Lykrast)
Farsight [Forge] (by someaddon)
Login Protection[Forge/Fabric] (by someaddon)
SuperMartijn642's Core Lib (by SuperMartijn642)
Dynamic View[Forge] (by someaddon)
Fix Experience Bug (now with FABRIC and FORGE versions) (by MacTso)
MineColonies (by H3lay)
Starter Kit (Forge) (by Serilum)
Mouse Tweaks (by YaLTeR)
The Twilight Forest (by Benimatic)
Mana and Artifice (by AWildCanadianEh)
KubeJS Mekanism (by LatvianModder)
Lapis Reserve (by sfort__)
Default Options (by BlayTheNinth)
Can't Sleep Clowns Will Eat Me (by Commoble)
Smooth Boot (Forge) (by UltimateBoomer)
Extra Tags (by tfarecnim)
Clumps (by Jaredlll08)
Beenfo (by Giselbaer)
Nef's Medieval decoration (by neoelfe0)
The Lost Cities (by McJty)
End Remastered (by jack_bagel)
Bigger Sponge Absorption Radius (Forge) (by Serilum)
Kiwi 🥝 (Forge) (by Snownee_)
Audio Extension for FancyMenu [Forge] (by Keksuccino)
Crash Utilities (by Darkere)
Simply Light (by Flanks255)
Builders Crafts & Additions (Forge) (by MRHminer)
Morpheus (by Quetzi)
Alex's Mobs (by sbom_xela)
Macaw's Furniture (by sketch_macaw)
Macaw's Bridges (by sketch_macaw)
Bad Wither No Cookie - Reloaded (by Kreezxil)
Chisels & Bits - For Forge (by AlgorithmX2)
JourneyMap (by techbrew)
Fairy Lights (by pau101)
TrashSlot (by BlayTheNinth)
Neko's Enchanted Books (by Nekomaster1000)
Build Guide (Forge+Fabric) (by brentmaas)
Trample Stopper (by UnRealDinnerbone)
Croptopia (by thethonk)
Library Ferret - Forge (by jtl_elisa)
Macaw's Trapdoors (by sketch_macaw)
Connectivity[Forge/Fabric] (by someaddon)
Myrtrees (by Jake_Evans)
Inventory Tweaks Renewed (by godemperordoge)
SignTastic (by McJty)
Road Stuff (by Mapper)
Building Gadgets (by Direwolf20)
BetterEnd (Forge) (by Beethoven92)
Mapper Base (by Mapper)
Angel Block (by tfarecnim)
Champions (by TheIllusiveC4)
My Server Is Compatible (by Focamacho)
Macaw's Doors (by sketch_macaw)
Engineer's Decor (by wilechaote)
Connected Glass (by SuperMartijn642)

**Comment by mickelus** [comment]
The enchanting system was reworked in 1.18, in part to deal with this issue. No plans to backport that as of now, closing.
