### ISSUE TITLE
[Bug] botania's mana regeneration not working. Mana rep not working.

### ISSUE THREAD

**Issue by kemofu** [mickelus/tetra#652]
### Observed behaviour

When I put tetra and botania in mods folder

### Expected behaviour

Restores the durability of tools with Mana rip functionality.

### Steps to reproduce

1.We will create a tool with the functionality of Mana rep.
2.Consumes tool durability.
3.Have an item that holds mana.
4.Tool durability is not restored.

### Tetra version

4.9.3.jar

### mutil/mGui version

4.5.0.jar

### Forge version

1.18.2-440.1.68

### Other mods

botania-1.18.2-434.jar
Patchouli-1.18.2-71.1.jar
curios-forge-1.18.2-5.0.7.1.jar

**Comment by DerekSSWong** [comment]
Addendum to the Steps to Produce section:

- Throwing the tool into the mana pool does not repair the tool either.

**Comment by Vane79** [comment]
Still doesn't work in tetra-1.19.2-5.2.1

**Comment by berneymark** [comment]
Still seeing the same issue on the Valhelsia 5 modpack (Tetra 5.2.1). Very disappointing to find this out after making the tools.

**Comment by erathia65** [comment]
Reproduced in tetra-1.19.2-5.2.1, botania-1.19.2-440
no mana repair, manasteel tools consume durability.
![image](https://github.com/mickelus/tetra/assets/3441742/549db03f-a93b-4483-a176-0ad98f5ce588)

**Comment by MattmonGaming** [comment]
Can confirm that it is still an issue. Mana repair does not appear to trigger no matter. In the Valhelsia 5 modpack.

**Comment by mickelus** [comment]
Forgot to mark this as closed, fixed in 5.3.1.

(valhelsia 5 isn't running 5.3.1 yet)
