### ISSUE TITLE
[Bug] Item Rendering makes game lag

### ISSUE THREAD

**Issue by Floatttttt** [mickelus/tetra#655]
### Observed behaviour

If the tool/weapon that has been edited by tetra is rendered, the fps will be much lower. For example, I hold the tool just like normal, and the fps will keep 10 even less

### Expected behaviour

Fix up the rendering bug

### Steps to reproduce

1.Place a vanilla tool/weapon in the workbench and edit it
2.Pick up the tool/weapon that has been edited
3.when it is rendered, the fps becomes much lower

### Tetra version

4.9.3

### mutil/mGui version

4.5.0

### Forge version

1.18.2-40.1.69

**Comment by SeanChengN** [comment]
#624

**Comment by Floatttttt** [comment]
OK, thx

**Comment by mickelus** [comment]
Closing, duplicate of #624
