### ISSUE TITLE
Specific Modded Ores Won't Drop Items Broken By Tetra Tools[Bug] 

### ISSUE THREAD

**Issue by TomerZack** [mickelus/tetra#656]
### Observed behaviour

Breaking ores that require a pickaxe to break from other mods won't drop items if broken by a Tetra pickaxe. Even if the tool has high enough mining level.

### Expected behaviour

written above

### Steps to reproduce

only an example:
1. take a vanilla iron pickaxe and change  its handle to something else to turn in to tetra pickaxe.
2.  try breaking modded ores from mods like Enlightened End.
3. The block should break without dropping anything.

### Crashlog

none

### Tetra version

4.9.3

### mutil/mGui version

4.5.0

### Forge version

1.18.2 - 40.1.73

### Other mods

Gobber [2.6.31] - not strictly necessary
Global Block Hardness [1.0.0] - not strictly necessary
Tetra Pak [0.5.2] - not strictly necessary
Potassium & Sulfur's Gunpowder Mod [3.3.4.5] - mod affected
Nurished Nether [13.2] - mod affected
Enlightened End [1.5] - mod affected
Obscuria's Essensials [3.2.0] - mod affected
Plus The end [1.1.9] - mod affected

**Comment by mickelus** [comment]
Wontfix.
All affected mods are released under ARR making debugging impossible.

**Comment by screret** [comment]
oh how the tables have turned...
