### ISSUE TITLE
[1.18.2 - Bug] Binding Texture Not Being Colored Properly with Rubidium.

### ISSUE THREAD

**Issue by SaltSouls** [mickelus/tetra#658]
### Observed behaviour

The color of tool bindings seem to all be grayscale when using tetra with rubidium.
How it looks currently:
![image](https://user-images.githubusercontent.com/36361103/185773397-934f4a06-171e-41c7-9934-d6b4527e1ea1.png)
How it should look:
![image](https://user-images.githubusercontent.com/36361103/185773456-cbaac9cc-7bec-41f7-98f9-ccacb82d6c27.png)

### Expected behaviour

Bindings should reflect their material color.

### Steps to reproduce

1. make a tool using tetra
2. add leather binding(this might also be a problem with other bindings as well)
3. watch binding not reflect color of material

### Log

[latest.log](https://gist.github.com/SaltSouls/86de78b71a0acb2181aaa6e829d9a86e)

### Tetra version

4.3.9

### mutil/mGui version

4.5.0

### Forge version

1.18.2-40.1.73

### Other mods

Check log file for all listed mods.

**Comment by mickelus** [comment]
wontfix

**Comment by SaltSouls** [comment]
> wontfix

Is there a reason?
