### ISSUE TITLE
More On-Hit Effects

### ISSUE THREAD

**Issue by Derpford** [mickelus/tetra#659]
### Feature description

Right now, there's only two on-hit effects available via Tetra modules: Backstab and Bleed. Backstab is incredibly situational, and difficult to use in vanilla (and there are few mods that add enough stealth mechanics to make Backstab useful outside of multiplayer), and Bleed is similarly situational because it doesn't work on undead mobs.

I think there needs to be a few more options for on-hit effects, to give players interesting options if they go for a dual-wield or heavy blade build.

### How it improves the player experience

At the moment, the Heavy Blade and Shortblade both feel a little underwhelming. The Heavy Blade's improved damage and True Sweeping effects aren't enough to make up for its low attack speed, and the Shortblade's reduced damage isn't enough to make it very useful (especially because of the way that i-frames cap damage output!). By giving both of these weapons more interesting options in the form of on-hit effects, the Heavy Blade and Shortblade will hopefully appeal more to players, creating more build variety.

### Tetra synergies

If done correctly, new on-hit effects would make existing content in Tetra feel fresh and new.

**Comment by Derpford** [comment]
Some suggestions:

## Armor Crush
This effect would apply a debuff to the target, causing attacks to ignore a percentage of their armor. This would stack with Tempered, giving players a powerful anti-armor option. 

I would put this on a unique upgrade for the Heavy Blade. This would make Heavy Blade users especially powerful in team-vs-team fights, as a well-placed sweep can apply Armor Crush to a large group. It would also prevent Shortblades from being all-powerful armor-shredding machines.

## Primed
The three-hit bonus damage passive, as popularized by League of Legends. On-hit, applies a single stack; upon applying 3 stacks, the target takes additional damage. 

I would make this one part of a Guard module, such as a spiked guard--or perhaps it could be a hilt module instead, like a special hilt designed to let you switch to a backhanded grip more easily. Damage and stack duration should be determined by material stats--harder materials do more damage, but also have a smaller stacking window.

## Disarm
On-hit, the target suffers a stacking debuff to their damage output. This would be a Guard module, probably something akin to a sai's tines or a sword-catcher guard--and it could also work as a Binding module for spears. The maximum stack count could scale with material hardness.

IMO, there's not enough useful options for shortblade guards when building for an offhand weapon--wide guards don't work in the offhand, bindings aren't really interesting, and finger ring has no effect on jab cooldown, so you generally either pick a gem to socket or remove the module.

## Potion Reservoir
That's right, I'm at it again with the potions thing. This would be a new guard module that applies a couple seconds of a selected potion effect on-hit. Obviously this means poisoned daggers would be a thing, but it'd *also* allow Heavy Blades to apply Slowness or Weakness on-hit. Takes any potion as material.

## Momentum
On-hit, gain a small amount of movespeed that lasts for a couple seconds. I think I'd put this on a pommel module--specifically because that means it'd conflict with counterweight, the main attack speed upgrade for swords. "Unbalanced Pommel", maybe?

This would let Heavy Blade users steal movespeed from a large group, or let Shortblade users play cat-and-mouse. Material density could increase movespeed and decrease duration, letting you tune for either a long-term speed advantage or a short-term dash to safety.

## Uppercut
This one would be an alternate Guard--maybe a knuckle guard? On-hit, the target receives additional vertical knockback. Material density decreases swing speed--and lighter materials *also* apply some additional horizontal knockback, making lighter knuckle guards better as defensive "get off me" tools, while heavier ones give combo potential at the cost of longer cooldowns.

**Comment by mickelus** [comment]
There's so much weird stuff going on in this feature request that I'm just gonna close it.
