### ISSUE TITLE
Honing progress doesn't reset after honing tool

### ISSUE THREAD

**Issue by jesmores** [mickelus/tetra#66]
## Bug Report

**Observed Behaviour**
After using the tool for some time (thank you for fixing the thing with honing progress reset after repair), I get a notification saying "honing available", so I go to the workbench and select one of the honing options for my tool. After doing so, I notice it still says Honing Progress: 100% on the tooltip, but I figured maybe I can only hone the tool once. I proceed to use the tool some more, when I immediately get another "honing available" notification, and can add another honing option to the tool. It seems that the honing progress was supposed to reset after selecting an option, but it currently doesn't so any time you use the tool after picking a honing option, you immediately get a new one, since the progress remains at 100%.

**Expected Behaviour**
Honing progress seems like it should reset after picking a honing option.

**Minimal setup needed to reproduce**

1.12.2 - 14.23.5.2844
- Other mods: Various other mods in custom modpack, but the tool in questiuon had all vanilla modules.
- Tetra configuration: Latest 0.38.0

**Steps to reproduce**
See observed behavior.
1. Use tool until honing progress at 100%
2. Add honing to tool
3. Note tooltip says honing progress still at 100%
4. Use tool again, immediately get another honing option available
5. This repeats.

**Comment by mickelus** [comment]
Fixed in 0.38.1!

**Comment by jesmores** [comment]
It works now, thanks!
