### ISSUE TITLE
[Bug] Clicking on Repair button does nothing and produces error in Enigmatica 6

### ISSUE THREAD

**Issue by Elliona** [mickelus/tetra#660]
### Observed behaviour

Modpack is Enigmatica 6 v. 1.4.1
Tetra v. 3.20.0
server environment
After opening the Workbench and inserting any Tetra tool, clicking on the Repair button does not open the repair menu. Attached is the Logpart with the error. 
I was playing Enigmatica 6 Expert earlier, repair works as intended there.

### Expected behaviour

Clicking on the Repair button should open the repair menu

### Steps to reproduce

1. Place damaged Tetra Tool in Workbench
2. Click on Repair button
3. Nothing happens

### Crashlog

https://gist.github.com/Elliona/5a8aa4528ca225acd5f828e8ccf5e36f

### Tetra version

3.20.0

### mutil/mGui version

3.3.0

### Forge version

1.16.5 - 36.2.34

### Other mods

Enigmatica 6 v. 1.4.1

**Comment by mickelus** [comment]
That issue typically occurs when a mod or a datapack adds faulty materials or schematic outcomes, if the entire e6 modpack is required to reproduce this issue you should probably report this on their issue tracker instead.
