### ISSUE TITLE
Seperate tool/weapon variant item ids

### ISSUE THREAD

**Issue by Corvus20** [mickelus/tetra#661]
### Feature description

This is probably a bit of a longshot but just hear me out. A lot of combat mods often rely on tool ids to change their behavior accordingly (such as attack animations) and Tetra's current names for tools are very limited.  "tetra:modular_double", for example, encompasses ALL non sword tools. Axes, shovels, and all their variants are bundled under this singular id, making compatibility for any variations under them, such as spears, great axes, and others extremely difficult. The same can be said for "tetra:modular_sword", as the very different machete and heavy blades are forced to share the same tag and behavior.

I am suggesting that more tags be added to indicate these variations so other mods can more easily work with them. "tetra:modular_machete" or "tetra:modular_spear" for example. This functionality likely could uses outside of combat mod compatibility, too.

I am not sure how difficult this would be to implement but I figured it was worth a mention.

### How it improves the player experience

Even though this is more of a backend change that would likely not effect a player only playing with a handful of mods, the implementation of this change would open a ton of doors for mod compatibility and perhaps future addons or updates to tetra itself. Moreover, the ability for more in-depth combat mods (Such as [Better Combat](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus), which is why I got the idea to make this request from in the first place) to hook into Tetra would likely be a welcome addition to many RPG modpacks. Immersive tool and weapon modification combined with immersive combat is a dream come true for a lot people.

### Tetra synergies

When only considering tetra itself, this changes relatively little of the content in the mod, but taking into account how other mods can make use of this feature to integrate tetra's tools and weapons, there would be a massive benefit. It doesn't really "synergize" in a direct manner being it doesn't directly effect gameplay without other mods making use of these changes.  But it definitely adds to the ability to create a more immersive and cohesive experience when mods that take advantage of this are installed.

**Comment by mickelus** [comment]
Unfortunately that's not worth the tradeoff 😢
