### ISSUE TITLE
Better Combat Compat

### ISSUE THREAD

**Issue by Smartin-b** [mickelus/tetra#662]
### Feature description

Compat with Better Combat

### How it improves the player experience

Allow Custom animations based on the Blade used

### Tetra synergies

Animations are awesome

**Comment by Smartin-b** [comment]
https://github.com/ZsoltMolnarrr/BetterCombat/pull/73
progress on NBT detection by Better combat

**Comment by mickelus** [comment]
No idea what this is supposed to mean, you need to elaborate on what this would entail if something is to be done.

**Comment by Smartin-b** [comment]
BetterCombat needs to support Weapon Detection by NBT tags first to allow Tetra Weapons to be classiefied correctly.
Once that is supported by BetterCombat Tetra should add identifiers for BetterCombat what animations map on what Weapon.

**Comment by Smartin-b** [comment]
This probably would mean just adding a file like this for every major modul similar to this
![grafik](https://user-images.githubusercontent.com/67115074/186777886-b1ccb009-cba4-4a8e-b9c6-e33a17f0d699.png)
but like i said, Better Combat first needs to support NBT detection

**Comment by Corvus20** [comment]
Has a similar post to this been made on Better Combat's github already?

Edit: Heck you've already made a commit for it on their page. Lets hope they add it to the main build.

**Comment by Smartin-b** [comment]
https://github.com/AceTheEldritchKing/art_of_forging/pull/8
So, compat would be fully achieved by this PR and by including Tetra:AoF as well.
