### ISSUE TITLE
[Bug] Missing material for 'Flowered wrap'

### ISSUE THREAD

**Issue by whiteknight9547** [mickelus/tetra#666]
### Observed behaviour

Currently the only material to fully negate the effects of 'Reverb' from using an End Rod handle/hilt is by wrapping it with 'Flowered' material, but it is currently unknown what material this is. Using the holosphere doesnt show what item this is as it is missing.

### Expected behaviour

Using the holosphere in materials menu should present what material this is

### Steps to reproduce

1. Right-click the holoshpere
2. Select any double-headed, single headed or blade schematic
3. Select End Rod hilt/handle
4. Select improvements under the material stats
Currently shows 'Flowered wrap' as the only material to fully negate 'Reverb'

5. Materials menu does not show any valid options for this material

### Tetra version

4.9.3

### mutil/mGui version

4.5.0

### Forge version

1.18.2 - 40.1.60

**Comment by mickelus** [comment]
There's no such material in vanilla tetra.
