### ISSUE TITLE
[Bug] Honing is not working when using Falling Tree mod

### ISSUE THREAD

**Issue by Morasiu** [mickelus/tetra#667]
### Observed behaviour

When I am sneaking and I have [Falling Tree mod](https://www.curseforge.com/minecraft/mc-mods/falling-tree) installed and set to Sneak enable and chopping to Shift Down, I am chopping logs and my tetra axe is using durability, but it's not honing at all.

### Expected behaviour

Tetra axe is honing with every log chopped.

### Steps to reproduce

1. Install Tetra and Falling Tree mod
2. Set Falling Tree to Shift Down
3. Chop wood using a tetra axe by pressing the left button
4. See honing progress and durability

### Tetra version

4.9.3

### mutil/mGui version

4.5.0

### Forge version

1.18.2 - 40.1.73

### Other mods

Falling Tree - 1.18.2-3.5.3

For more mods see [my modpack](https://www.curseforge.com/minecraft/modpacks/village-challenge-forge/relations/dependencies)

**Comment by mickelus** [comment]
The falling tree mod needs to call the mineBlock on the used itemstack for honing to be applied for each block broken. That would also cause damage to the item for each block broken though. I can't do much on the tetra side :/
