### ISSUE TITLE
Modular fishing rod

### ISSUE THREAD

**Issue by Morasiu** [mickelus/tetra#669]
### Feature description

It would be cool to have a modular fishing rod which we can repair and hone! Maybe we can change some parts and add emerald for luck bonus or something.

### How it improves the player experience

Just another awesome Tetra tool to play with :)

### Tetra synergies

Utilize another basic Minecraft tool to make it awesome!

**Comment by mickelus** [comment]
I also find that to be an appealing fantasy. This request is too vague though, closing.
