### ISSUE TITLE
[Bug] Modules lose tint when certain things are applied

### ISSUE THREAD

**Issue by RedPxnda** [mickelus/tetra#670]
### Observed behaviour

Occasionally when adding dragon sinew, warforging, etc. item modules lose their tint. 

### Expected behaviour

The item shouldn't lose its tint.

### Steps to reproduce

1. Use the workbench to modify a modular double
2. Grab a warforge scroll and warforge one of the heads
3. The item MAY lose its tint (doesn't always work first time)

### Tetra version

4.9.3

### mutil/mGui version

4.5.0

### Forge version

40.1.79

### Other mods

Works with tetra and mutil only

**Comment by mickelus** [comment]
> doesn't always work first time

Difficult to fix issues you can't even reproduce yourself my dude
