### ISSUE TITLE
[Bug] Lapis+ does not give additional benefit over lapis for tools

### ISSUE THREAD

**Issue by peanubnutter** [mickelus/tetra#672]
### Observed behaviour

Lapis+ should give 2x intuit, but actually only gives 1x xp-based honing progress which is no different from regular lapis. 

### Expected behaviour

Lapis+ should give twice the xp-based honing progress as regular lapis.

### Steps to reproduce

1) Create 2 diamond pickaxes, one with lapis+, one with lapis. 
2) Break some coal (enough to be statistically signficant, say 30 with each pickaxe)
3) Observe that both pickaxes give roughly the same honing progress.

I looked at the code and there seems to be a bug: 
 
The honing progression for tools should be updated to be "xp * intuitLevel": https://github.com/mickelus/tetra/blob/1a6710e93b306367211f553a63d43286f502a890/src/main/java/se/mickelus/tetra/items/modular/ItemModularHandheld.java#L190

just like the honing progression for weapons does:
https://github.com/mickelus/tetra/blob/1e058d250dfd1c18796f6f44c69ca1e21127d057/src/main/java/se/mickelus/tetra/effect/ItemEffectHandler.java#L119

### Tetra version

1.18 branch

### mutil/mGui version

Idk

### Forge version

Idk

**Comment by mickelus** [comment]
Ow, fixed this a while back!

**Comment by esparano** [comment]
Oh, weird. I don't see the fix although I checked what I think are the most recent branches. Is it supposed to be in the 1.18 branch?
