### ISSUE TITLE
[Bug] Apotheosis tools lose their affixes when edited with Tetra.

### ISSUE THREAD

**Issue by LoSilopante** [mickelus/tetra#673]
### Observed behaviour

After update (5.7.2) of Apotheosis, the compatibility for two headed tools, bows, and shields broke; when an item has its main component changed to another type (e.g. axe to claw/base bow to recurved) it loses its affixes, this doesn't happen when changingonly the material or other components.

Base item:
![immagine1](https://user-images.githubusercontent.com/24480520/197522702-9f3306b9-ae1c-4cb3-9c6c-2bb65b4832aa.png)

Left head changed with Tetra:
![immagine2](https://user-images.githubusercontent.com/24480520/197522809-fa85327d-4ff0-4ca4-9f96-0e7a9df0273d.png)

### Expected behaviour

The item should retain its affixes.

![immagine3](https://user-images.githubusercontent.com/24480520/197522890-43c5d8ce-7799-42de-b2e7-718738ea1a3c.png)

### Steps to reproduce

1. Obtain any two headed tool with an affix;
2. Edit its left head with Tetra;
3. Notice that the original affixes are gone.

### Tetra version

4.10.1

### mutil/mGui version

4.5.0

### Forge version

1.18.2 - 40.1.84

### Other mods

Apotheosis - 5.7.4 (the bug happens with every version after 5.7.0)

**Comment by mickelus** [comment]
Having the NBT value for the item before and after the conversion would be really helpful!

**Comment by LoSilopante** [comment]
Oh, so sorry, I forgot to update this issue, whilst I was doing more tests, Apotheosis received another update that fixed the issue, have a good one!

**Comment by Lokilotus** [comment]
This issue is still present in Minecraft 1.20.1, Neoforge 47.1.100, Tetra version 6.2.0 from Curseforge, and Apotheosis 7.3.0 from Curseforge.  I can provide more details of our server setup if required - just mention me in Github!

EDIT: I have referenced this issue in an Apotheosis bug report: https://github.com/Shadows-of-Fire/Apotheosis/issues/1173#issue-2140685931

**Comment by Lokilotus** [comment]
Update: Shadows-of-Fire has confirmed that this is a Tetra-only issue and has closed the issue on their end. As such I shall open a new issue on this bug tracker as a copy of that issue.
