### ISSUE TITLE
[Bug] Game crashes out when right-clicking with holosphere/basic workbench

### ISSUE THREAD

**Issue by ghost** [mickelus/tetra#674]
### Observed behaviour

For some reason, my client crashes when I attempt to access the tetra weapon menu through a basic workbench or the holosphere.
I encountered this issue in multiplayer, where my friend was still able to modify weapons through the workbench (and the functionalities of the weapons replicated without any issue), but the moment I tried to interact with any workbench, it would crash me. This also occurs in singleplayer.

### Expected behaviour

I expect the tetra menu to show up without any problem and not crash the client.

### Steps to reproduce

1. Place down a basic workbench/have a holosphere equipped in your main hand
2. Right click the bench/holosphere, then the game will freeze, before showing up with the "Saving World" text and abruptly closing out of the minecraft client.
I don't know if this is a result of my hardware or not, because my friend has a low-end pc yet can still run the mod with no problem.
[Edit]: Okay, so it turns out that it's starting to crash my friend too, so my assumptions were right. I don't know why the mod is crashing at all as I have everything installed correctly on my client and server.
### Crashlog

https://gist.github.com/aynows/9f7ab38dcabf4e55ad2103063962a32c

### Tetra version

4.10.1

### mutil/mGui version

4.5.0

### Forge version

40.1.0

### Other mods

		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		tetra-1.18.2-4.10.1.jar                           |Tetra                         |tetra                         |4.10.1              |DONE      |Manifest: NOSIGNATURE
		BetterThirdPerson-Forge-1.18.2-1.8.1.jar          |Better Third Person           |betterthirdperson             |1.8.1               |DONE      |Manifest: NOSIGNATURE
		preciseblockplacing-1.1.0+1.18.2-forge.jar        |PreciseBlockPlacing           |preciseblockplacing           |1.1.0               |DONE      |Manifest: NOSIGNATURE
		Origins-1.18.2-1.4.1.4-unified.jar                |Additional Entity Attributes  |additionalentityattributes    |1.18.2-1.4.1.4      |DONE      |Manifest: NOSIGNATURE
		Pehkui-3.5.0+1.18.2-forge.jar                     |Pehkui                        |pehkui                        |3.5.0+1.18.2-forge  |DONE      |Manifest: NOSIGNATURE
		mmoparties-2.3.0.1.18.jar                         |MMOParties                    |mmoparties                    |2.3.0               |DONE      |Manifest: NOSIGNATURE
		FallingTree-1.18.2-3.5.4.jar                      |FallingTree                   |fallingtree                   |3.5.4               |DONE      |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		cloth-config-6.4.90-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.4.90              |DONE      |Manifest: NOSIGNATURE
		caelus-forge-1.18.1-3.0.0.2.jar                   |Caelus API                    |caelus                        |1.18.1-3.0.0.2      |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.0-universal.jar                 |Forge                         |forge                         |40.1.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		appleskin-forge-mc1.18.2-2.4.1.jar                |AppleSkin                     |appleskin                     |2.4.1+mc1.18.2      |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.18.2-2.3.8.jar                      |Aquaculture 2                 |aquaculture                   |1.18.2-2.3.8        |DONE      |Manifest: NOSIGNATURE
		rubidium-0.5.4.jar                                |Rubidium                      |rubidium                      |0.5.4               |DONE      |Manifest: NOSIGNATURE
		mutil-1.18.2-4.5.0.jar                            |mutil                         |mutil                         |4.5.0               |DONE      |Manifest: NOSIGNATURE
		origins-classes-forge-1.1.6.jar                   |Origins: Classes              |origins_classes               |1.1.6               |DONE      |Manifest: NOSIGNATURE

**Comment by mickelus** [comment]
Update to the latest forge version, or downgrade tetra to 4.9.5.
