### ISSUE TITLE
[Bug] [Compat] Tetra Bows can't use Arrows in Thermal Innovation's Arrow Bag

### ISSUE THREAD

**Issue by shanoaice** [mickelus/tetra#676]
### Observed behaviour

When I have a Thermal Innovation arrow bag in my inventory with some arrow, the bow won't recognize it and cannot shoot.
(Devs from Team CoFH told me that mods need to make some changes in order to be able to use the arrow bag so I sent an issue here)

### Expected behaviour

The bow picks up arrows from the Arrow Bag and shoots.

### Steps to reproduce

1. Obtain a Tetra bow.
2. Put an filled Arrow Bag in the inventory. Make sure no vanilla arrow is present in the inventory.
3. Try to shoot.

### Crashlog

_Not A Crash_

### Tetra version

4.10.1

### mutil/mGui version

4.5.0

### Forge version

1.18.2 - 40.1.84

### Other mods

Thermal Series 9.0.0.32
Thermal Innovation 9.0.0.14

**Comment by mickelus** [comment]
> Devs from Team CoFH told me that mods need to make some changes in order to be able to use the arrow bag

Which changes were those?

It's likely that resolving this issue is not worth the tradeoff. There are quivers in tetra which I assume fill the same function as the bags from thermal innovation.
