### ISSUE TITLE
Sorting Compat

### ISSUE THREAD

**Issue by Lucky-56** [mickelus/tetra#677]
### Feature description

The ability to sort scrolls using E.g. Quark's sorting API

### How it improves the player experience

easier to read duplicate scrolls in chests at a glance

### Tetra synergies

um.. nuffin?
well most likely, a better experience

**Comment by mickelus** [comment]
No idea what this entails.

**Comment by Lucky-56** [comment]
Unsorted chest:
![image](https://user-images.githubusercontent.com/55949451/201332114-1dc514dd-47f7-4c21-a30f-88580be4a1fe.png)

"Sorted" chest:
![image](https://user-images.githubusercontent.com/55949451/201332174-c74b2473-7b46-4484-af5b-fde2e482f69c.png)

What I expect sorting to do:
![image](https://user-images.githubusercontent.com/55949451/201471528-1cef7ef1-2d34-4d2c-b3b2-9683c2283f44.png)

Edit: ok fixed now

**Comment by Lucky-56** [comment]
oh fuck I'm apparently color blind xD
