### ISSUE TITLE
tetra interfering with loot generation in chests [1.18.2 Forge][Bug] 

### ISSUE THREAD

**Issue by ghost** [mickelus/tetra#678]
### Observed behaviour

Hello, hope you are well,

I noticed when exploring that some chests would end up completely empty. Not all would be however, but noticing mainly certain dungeon structures and nether fortresses would have zero loot in the chests generated inside. 

When I took at the log file, it said this:

```
[Render thread/ERROR]: Couldn't parse loot table minecraft:chests/simple_dungeon
java.lang.RuntimeException: Attempted to add a duplicate pool to loot table: tetra:chests/simple_dungeon_extended
```

any way how I can work around this? I already deleted/re-installed the mod itself within curseforge.
[latest.log](https://github.com/mickelus/tetra/files/9986917/latest.log)

### Expected behaviour

It would normally just generate the loot pool as fine; its not as though its deleting the tetra items in the loot but the entirety of the chests content doesnt exist

### Steps to reproduce

Generated new world
Looked around overworld for immediate structures, otherwise went into nether.
Find a fortress, and find the chests.

*to note, other structures like villages and other mods like Artifacts' structures do not have this issue. 

### Tetra version

 tetra-1.18.2-4.10.1.jar

### mutil/mGui version

mutil-1.18.2-4.5.0.jar

### Forge version

40.1.84

**Comment by mickelus** [comment]
Make sure to include all mods you've got installed in the 'Other mods' field, and reducing that list to the minimal set required to reproduce the issue will greatly speed up how fast the issue can be resolved.

Uninstall art of forging.

**Comment by ghost** [comment]
Thanks! The issue was actually not Art of Forging but Tetra Pak. Everything works like a charm now!

This mod is really fun, thank you for all that you’re doing; I am excited for the new stuff whenever it comes around. Take care!
