### ISSUE TITLE
[Bug] Tool with no durability is considered broken

### ISSUE THREAD

**Issue by ChrisHei** [mickelus/tetra#685]
### Observed behaviour

The staff from the arsomega mod has no durability and tetra thinks because of this, that the item is broken and needs repair. Becauseof that the staff is not:
- Visible when held
- Leveling with the Weapon Leveling mod
- able to break blocks
 But the staff itself is still usable and works as expected

### Expected behaviour

Because the staff has no durability I would expect it shouldn't be able to be broken at all. Or the tetra mod could add durability for such items and a way to repair them.

### Steps to reproduce

1. Mods needed: arsomega (an additional mod to ars nouveau), Weapon Leveling and of cours tetra
2. Craft the arsomega staff item

### Tetra version

tetra-1.18.2-4.10.1

### mutil/mGui version

mutil-1.18.2-4.5.0

### Forge version

1.18.2 - 40.2.0

### Other mods

- ars_nouveau-1.18.2-2.8.0 -> arsomega-2.7.1
- weaponleveling-1.18.2-1.4.3

**Comment by mickelus** [comment]
Unrelated to tetra, closing.
