### ISSUE TITLE
[Bug] "overpowereffect" is causing an instant crash

### ISSUE THREAD

**Issue by Nenebotto** [mickelus/tetra#686]
### Observed behaviour

Attempting to charge the Guisarmes with the combat upgrade causing a crash on use, 

### Expected behaviour

I expected to just kill the enemy (a Zombie Brute in this case) but ended up crashing instead.

### Steps to reproduce

1. Place a diamond hoe in the tetra workbench
2. Add the Guisarmes upgrade to it
3. Charge attack at enemy/tile
4. Crash should occur, worked the three times I've tried.

### Crashlog

https://gist.github.com/Nenebotto/c1f72f53b54aecaafe89168054251c90

### Tetra version

3.20.0

### mutil/mGui version

3.3.0

### Forge version

1.16.5

### Other mods

https://www.modpackindex.com/modpack/43352/enigmatica-6-expert-e6e

**Comment by mickelus** [comment]
Fixed in 5.2.0!
