### ISSUE TITLE
[Bug]  [1.19.2] Crash with REI

### ISSUE THREAD

**Issue by hipsterjazzbo** [mickelus/tetra#688]
### Observed behaviour

When REI tries to display Tetra items, the game crashes

### Expected behaviour

REI should be able to display Tetra items

### Steps to reproduce

1. Have Tetra 1.19.2-5.0.0 and REI 9.1.587 installed together
2. search REI for `@tetra`

### Crashlog

https://gist.github.com/hipsterjazzbo/18a1a8302b196ff78298229d88ec4602

### Tetra version

5.0.0

### mutil/mGui version

5.1.0

### Forge version

1.19.2 - 43.2.0

### Other mods

RoughlyEnoughItems-9.1.587.jar

**Comment by Excederus** [comment]
Getting the exact same crash when simply scrolling through REI pages.
MC: 1.19.2
Forge: 43.2.4
REI: 9.1.587
REI Plugin Compatibilities: 9.0.44
Tetra: 5.0.1

**Comment by mickelus** [comment]
Should be fixed in 5.0.2!
