### ISSUE TITLE
Suggested Materials for Hilt Wrap

### ISSUE THREAD

**Issue by SirChamomile** [mickelus/tetra#69]
Suggested Hilt Wrap materials from other mods:

Twilight Forest - Yeti Fur
Botania - Spellbinding Cloth, Manaweave Cloth
Thaumcraft - Enchanted Fabric
Embers - Ashen Fabric
_Harvestcraft - Hardened Leather?_

I'm sure that materials exist other than leather that could be used to wrap the hilt of the weapons, but to me these all seemed like obvious fits for your mod.

This is like a perfect synergy with the mod, and would be easy to add. Adding one of these to a weapon would be a rewarding option for the player to imbue a little more enchantability into their weapons, while doing what the hilt wrap normally does. These are almost all middle-tier items within their given mods and it would allow players to integrate an element of their favorite mod more thoroughly with their weapons, which is my favorite part of this mod.

**Comment by Sunconure11** [comment]
Ice and Fire’s Troll Leather might be good as well.

**Comment by mickelus** [comment]
Closing this as it's really old. Feel free to re-open if you update it to adhere to the feature request template.
