### ISSUE TITLE
Item incompatibility between similar items with different dirrectory

### ISSUE THREAD

**Issue by bobBobingtonBobinsky** [mickelus/tetra#690]
### Feature description

i've encountered a couple mods that use the items mentioned by Tetra compatibility, however they are not actually compatible.
Zombie extreme, features rubies and copper, however is incompatible with Tetra crafting. i've had a look at the code, but im completelt clueless. I have never really worked with code before. Is there something I could do to fix it myself?

### How it improves the player experience

it would allow the material to have more uses as the original mod use of the material is very bare bones

### Tetra synergies

it's a Zombie survival mod. many items facilitate survival, however tetra integration would give the mod additional life and the creatures features in ZE are great sponges for the powerful end game gear of tetra

**Comment by mickelus** [comment]
Can't do anything about that in tetra, mods need to tag their materials properly for tetra to be able to pick them up. Closing.
