### ISSUE TITLE
[Bug] [1.19.2] CTD when moving potion in belt inventory

### ISSUE THREAD

**Issue by Eario** [mickelus/tetra#691]
### Observed behaviour

When moving a potion around in the belt inventory screen (accessed in this instance by holding the belt and right-clicking), crashes to desktop are very common.

### Expected behaviour

No crash to desktop.

### Steps to reproduce

1. Place rope belt in workbench, use rabbit hide to add a small potion bag.
2. Take several potions, have them in your inventory.
3. Open rope belt inventory via right-clicking while holding it.
4. Pick up a potion by left-clicking it and wave it around in the inventory for a moment.

### Crashlog

https://gist.github.com/Eario/20e41236053eba373586c056b168e7f4

### Tetra version

5.0.0

### mutil/mGui version

5.1.0

### Forge version

1.19.2 - 43.2.4

**Comment by mickelus** [comment]
Ow forgot to close this, fixed this in 5.0.1!
