### ISSUE TITLE
Honing and durability loss on canes

### ISSUE THREAD

**Issue by wqferr** [mickelus/tetra#692]
### Feature description

Canes currently have no durability limit and no reason to be repaired, and no useful hones. I would like to suggest a (low) durability cost of using a cane to walk, which would also progress towards honing.

With respect to honing, I only have two suggestions: speed boost and step assist.

### How it improves the player experience

This makes canes more fun, adds some progression to them, and gives us reason to make canes out of anything other than wood.

### Tetra synergies

Canes seem a bit underwhelming, even if very useful. Adding this would make them more in line with the rest of the Tetra tools.

**Comment by mickelus** [comment]
No idea what a cane is, closing.

**Comment by wqferr** [comment]
My bad, must be an add-on I didn't realize was installed. Will forward appropriately.
