### ISSUE TITLE
[Bug] ArrayIndexOutOfBoundsException when rendering tetra:modular_crossbow 

### ISSUE THREAD

**Issue by aaronhowser1** [mickelus/tetra#693]
### Observed behaviour

When the `tetra:modular_crossbow` is rendered, either through `/give` or through REI (see shedaniel/RoughlyEnoughItems/issues/1353, as well as #688), the game crashes.

### Expected behaviour

For it to not crash

### Steps to reproduce

Get the item to render

### Crashlog

https://gist.github.com/aaronhowser1/539b41156658766880f84681ac71214d

### Tetra version

tetra-1.19.2-5.0.1

### mutil/mGui version

mutil-1.19.2-5.1.0

### Forge version

1.19.2 - 43.2.4

**Comment by mickelus** [comment]
Ah, forgot to close this. Was fixed in 5.0.2.
