### ISSUE TITLE
[Bug] [1.19.2] Forged blocks not breaking

### ISSUE THREAD

**Issue by DragonKiller952** [mickelus/tetra#695]
### Observed behaviour

when using a tier 6, tier 7 or tier 8 netherite hammer with silk touch, the forged block break very slow. after fully breaking, the blocks drop nothing. even after breaking without silk touch the blocks drop nothing

### Expected behaviour

expected the blocks to break at average speed, and to drop scrap/ the block when using tier 6+ netherite hammer

### Steps to reproduce

1. get netherite hammer tier 6+
2. break any forged block (incl. forge hammer and forged workbench)

### Tetra version

tetra-1.19.2-5.0.1

### mutil/mGui version

mutil-1.19.2-5.1.0

### Forge version

1.19.2 - 43.2.0

**Comment by mickelus** [comment]
Should be fixed in 5.0.2!
