### ISSUE TITLE
[Bug] Crash rendering modular tools with no modular item tags

### ISSUE THREAD

**Issue by LegoMaster3650** [mickelus/tetra#696]
### Observed behaviour

Items with nbt but no modular item tags crashing the game (also appears related to #694 and #693, with both having a similar error and stack trace, although the crossbow one requires no NBT data to be set, so it may be slightly different unless crossbows add their own nbt instantly)

### Expected behaviour

Items with nbt but no modular item tags not showing at worst, certainly not crashing

### Steps to reproduce

1. Launch the game with tetra
2. `/give @s tetra:modular_double{garbagejson:"among us"}` (or any non-tetra tags)
3. Observe the game as it crashes (It appears to expect items with NBT to have at least 1 tetra material or something)

### Crashlog

https://gist.github.com/LegoMaster3650/d054cc764542e4e8e83aa796256821eb

### Tetra version

5.0.1

### mutil/mGui version

5.1.0

### Forge version

1.19.2-43.2.0

### Other mods

None.

**Comment by mickelus** [comment]
Should be fixed in 5.0.2!
