### ISSUE TITLE
[Bug] [1.19.2] Ruins spawning very infrequently and not generating in modded biomes terralith/tectonic

### ISSUE THREAD

**Issue by ianwilliamson5** [mickelus/tetra#699]
### Observed behaviour

I have spawned in bunches of times and did /locate only to find that the structures where generating over 2k from spawn even in cold worlds this issue has somewhat persisted but only got cut in half or so with the closest to spawn one i found being 458 blocks yet still.

### Expected behaviour

Ruins should spawn regularly within cold and mountainous biomes 

### Steps to reproduce

spawn in world /locate 
repeat till find min/medium/range
notice that its far apart over many worlds and usually are atleast 500 blocks from eachother

### Tetra version

5.1.0

### mutil/mGui version

5.1.0

### Forge version

1.19.2 43.2.0

### Other mods

Terralith/Tectonic

**Comment by mickelus** [comment]
Reduced spacing and separation by 30% in 5.0.2. Additional tools are planned to make it easier to find ruins, so the distance should be come less of a problem.
