### ISSUE TITLE
Rendering issues with Tetra Block/Entities

### ISSUE THREAD

**Issue by SirChamomile** [mickelus/tetra#70]
## Bug Report

**Observed Behaviour**
No texture for the Transfer unit, and no breaking texture for some items in the ruins such as the forged container.

**Expected Behaviour**
Self-evident.

**Minimal setup needed to reproduce**

- Forge version: 1.12.2 - 14.23.5.2847
- Other mods: Many
- Tetra configuration: Default

**Steps to reproduce**
Delete much of the world with Worldstripper, fly around until you find some ancient ruins, be impressed by the cool structures, and then notice some bits are missing textures, and are missing textures when you break them.

![2019-10-14_21 27 58](https://user-images.githubusercontent.com/23204608/66795628-cc4e5180-eeca-11e9-9e3a-ccb9955e67cc.png)

**Comment by mickelus** [comment]
I've noticed this as well, I think it happens when Connected Textures is
installed but I have not figured out why and why it only happens for this
block.

**Comment by mickelus** [comment]
Fixed in 0.39.1!
