### ISSUE TITLE
Custom Item: Item Materializer

### ISSUE THREAD

**Issue by MaximusXgamer** [mickelus/tetra#700]
### Feature description

It can only be obtained in creative mode. With this, it looks and acts like a holosphere except it can create items.

First, you select the tool type like the normal Holosphere.

Then a GUI would open like the one that appears whenever you try to modify a tool, however it will initially all be Oak tool parts.

Also, if you click a section (like clicking Head on a shovel), first you can either choose a new toolpart or modify the existing tool part, once you do that it will open the GUI similar to a holosphere, but once you click the material you want you can click "Confirm" to go back to item creator GUi, or you can also choose to add an enchant and/or add a certain level of Hone stat before going back to click "Confirm". Once you click "Create" in the tool creator GUI, the tool you created will be granted no matter what, no tools or resources needed.

### How it improves the player experience

I just think it's just a fun thing to add because now if you're in creative mode and want a custom tool you don't have to go through the hassle of pulling random materials out of your inventory, only to realize you have to get tools of a specific type to make tools as well, which is a frustrating experience, especially because you don't really need to make anything else because you can just pull a vanilla iron sword out of the Combat tab of the Creative menu.

### Tetra synergies

I feel like it kinda aligns with what Tetra was going for, tool creation and modification, but it's more fun for creative mode players as they do not have to go through the same hassle and frustration as survival minecraft players.

**Comment by Archilyte** [comment]
I will add on to this by saying that this will tremendously help people that are creating addons/datapacks for Tetra

**Comment by mickelus** [comment]
Closing as this overlaps with already planned functionality. But thank you for the thought out suggestion! ☺️
