### ISSUE TITLE
[Bug] 1.19.3 Crash on load with only this mod - org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

### ISSUE THREAD

**Issue by ProsperCraft** [mickelus/tetra#702]
### Observed behaviour

Crash on load with Minecraft 1.19.3 

### Expected behaviour

Load.

### Steps to reproduce

Install Forge profile, add Tetra, Multi manually from website.

### Crashlog

https://gist.github.com/ProsperCraft/e4b66a408a8200210d26ccdb9cc03e39

### Tetra version

tetra-1.19.2-5.0.1.jar

### mutil/mGui version

mutil-1.19.2-5.1.0

### Forge version

44.1.17

**Comment by mickelus** [comment]
As with most mods tetra for 1.19.2 does not run on 1.19.3, closing.
