### ISSUE TITLE
(1.19.2) Latest Tetra version crashes on servers.

### ISSUE THREAD

**Issue by IronlegacyXVII** [mickelus/tetra#703]
### Observed behaviour

I made a little personal pack for my friends and I with Tetra within it and whenever we engage in pvp with tetra weapons the server has a tick error and crashes.

### Expected behaviour

(idk what to put here)

### Steps to reproduce

1. launch a server with tetra.
2. make a tetra weapon/tool
3. attack a player
4. crash

### Tetra version

5.0.1

### mutil/mGui version

5.1.0

### Forge version

1.19.2-43.2.0

### Other mods

![image](https://user-images.githubusercontent.com/82254712/221453235-4c3e3c00-d247-4771-8f0e-2e108ff8a4b8.png)
![image](https://user-images.githubusercontent.com/82254712/221453259-a002dcdb-8807-403d-945c-1aa3270c766b.png)

**Comment by mickelus** [comment]
Can fix crashes without the crashlog, closing.
