### ISSUE TITLE
[Bug] Incompatibility with modded right click events/left click events

### ISSUE THREAD

**Issue by JAWredstoneguy** [mickelus/tetra#704]
### Observed behaviour

When I have Tetra and Immersive Weathering/Decorative Blocks/Daves Building Extended/Quark, certain right click events do not trigger with Tetra tools. Some examples are; Stripping logs with a tetra axe will not drop an immersive_weathering:bark item, immersive_weathering:crackable blocks are unable to be cracked with a tetra pickaxe, right clicking a decorative_blocks:support with a tetra axe will not cause the support to change state, breaking a Daves Building Extended steel block with a tetra tool will not drop the steel block item, a tetra hoe does not break a three by three area of foliage when quark is installed.

### Expected behaviour

Using a tetra tool on blocks should trigger the associated modded event. For example; Logs should drop bark when stripped and immersive weathering is installed, immersive_weathering:crackable blocks should be crackable with tetra tools, supports from decorative blocks should change state when right clicked/shift + right clicked with a tetra axe or adze, Steel blocks from Daves building Extended should drop the corresponding steel block, hoes should trigger quarks 3x3 breaking when enabled.

### Steps to reproduce

1. Install Tetra and Immersive Weathering/Decorative blocks/Dave's Building Extended/quark
2. Place down a log, crackable block, support, or steel block
3. strip the log with the associated tetra tool, right click the crackable block with a tetra pickaxe, right click the support with a tetra axe, break the steel block in survival with a tetra pickaxe, or break grass that is next to other grass / foliage with a tetra:hoe
4. The log should not drop a bark item, the crackable block should not be cracked, the support shouldn't do anything, the steel block should not drop, and only the grass you hit with the hoe should be broken.

### Tetra version

5.0.2

### mutil/mGui version

5.1.0

### Forge version

43.2.4

### Other mods

Dave's Building Extended ver. 5.0.5
Decorative Blocks ver. 3.0.0
Immersive Weathering ver. 1.2.8
Quark-3.4-389

**Comment by mickelus** [comment]
Forge provides `IForgeBlockState.getToolModifiedState` for mods to handle compat around tool right click behaviour. Tetra calls that properly, if other mods have not implemented that you'll have to report that on their issue trackers as that cannot be fixed in tetra.
