### ISSUE TITLE
[Bug] 1.12.2 Enchanted Books Not Applying to Already Enchanted Modules

### ISSUE THREAD

**Issue by LivingLandmine** [mickelus/tetra#705]
### Observed behaviour

Trying to enchant a Tetra item on an already enchanted module consumes the book and exp, but doesn't apply the new enchantment.

### Expected behaviour

Like on an anvil, you should be able to apply new enchantments and upgrade existing enchants on the module.

### Steps to reproduce

1. Enchant any tetra module with something like sharpness or smite
2. Use another compatible enchantment book on the module.
3. The book and exp will be consumed, but the module will not receive the enchantment.

### Tetra version

1.12.2-0.39.1

### mutil/mGui version

N/A

### Forge version

1.12.2-14.23.5.2860

### Other mods

![image](https://user-images.githubusercontent.com/31289215/224525736-43902487-356f-4b4f-8a98-dc638c467d9d.png)

**Comment by mickelus** [comment]
Anvil enchanting is not supported in 1.12.
