### ISSUE TITLE
Machete doesn't get honing progress on breaking cobwebs and leaves

### ISSUE THREAD

**Issue by CaveAnon** [mickelus/tetra#71]
## Bug Report

**Observed Behaviour**
When cutting cobweb and leaves, the machete doesnt get honing progress.

**Expected Behaviour**
Expecting the machete to gain honing progress

**Minimal setup needed to reproduce**
Reproduced on client with only Tetra and JEI installed using an iron machete. 

- Forge version: 1.12.2 - 14.23.5.2847 --->
- Other mods:
Tetra
Jei
 
- Tetra configuration: 
Default

**Steps to reproduce**
Cut a cobwebor leaf block

**Comment by mickelus** [comment]
Fix will be introduced in 1.14.5
