### ISSUE TITLE
Suggestion: Alter text for current repair material needed

### ISSUE THREAD

**Issue by Shibva** [mickelus/tetra#711]
### Feature description

![image](https://user-images.githubusercontent.com/38770780/227696037-d4e51a23-f8b2-4963-94aa-8e9150fe7aec.png)
you see the text on where the extractor is the next up to be repaired?

the suggestion is to use a different color 

### How it improves the player experience

This would make it stand out more and easier to understand what is material you need to use to repair. The color could be yellow but any color would work as long as its not similar to any shade like the other text in the description.

### Tetra synergies

It should be more or less the same as its just a small alteration to make it stand out more on what material you need to use (espeshaly in cases where the item overlay blends into the background of the UI [Ie; Extractor and other related colors])

**Comment by mickelus** [comment]
wontfix
