### ISSUE TITLE
null=se.mickelus.tetra.items.modular.ThrownModularItemRenderer

### ISSUE THREAD

**Issue by Shadesknight** [mickelus/tetra#713]
[crash-2023-04-13_17.50.34-client.txt](https://github.com/mickelus/tetra/files/11226747/crash-2023-04-13_17.50.34-client.txt)
Says the Cause was Tetra

**Comment by mickelus** [comment]
Please follow the template and link the crashlog instead of inlining it.

**Comment by Shadesknight** [comment]
> Please follow the template and link the crashlog instead of inlining it.

Apologizes I couldn't figure it out.
