### ISSUE TITLE
[1.19.2 - Bug] Latest version of Tetra causes server to crash on startup

### ISSUE THREAD

**Issue by DelviousCrafts** [mickelus/tetra#715]
### Observed behaviour

Server will not load producing a crash report on startup. Client does not appear to be affected. 

### Expected behaviour

Server not to crash.

### Steps to reproduce

1. Attempt to load tetra on a server
2. Crash

### Crashlog

https://gist.github.com/DelviousCrafts/b56e06f9a5c71ea740202cdb8fb567ff

### Tetra version

5.2.0

### mutil/mGui version

5.1.0

### Forge version

43.2.8

### Other mods

I verified this occurs with no other mods installed. My original mod list is extensive.

**Comment by Enderteck** [comment]
Same here.
[latest.log](https://github.com/mickelus/tetra/files/11212914/latest.log)
[crash-2023-04-12_16.55.24-fml.txt](https://github.com/mickelus/tetra/files/11212920/crash-2023-04-12_16.55.24-fml.txt)

**Comment by mickelus** [comment]
Fixed in 5.2.1.
