### ISSUE TITLE
minor rephrasing for cutting implement description

### ISSUE THREAD

**Issue by CaveAnon** [mickelus/tetra#72]
## Bug Report

**Observed Behaviour**
The sentence describing the shortblade reads a bit clunkily. 
See attached image

![2019-10-30_12 21 14](https://user-images.githubusercontent.com/53201084/67855914-bae48680-fb13-11e9-89fd-05085428dc17.png)

Could be: 
"This item can be used for cutting, crafting and for breaking webs and plants"

**Comment by mickelus** [comment]
It is usable for cutting in the context of crafting and for breaking webs and plants. Your suggestion says otherwise :P
