### ISSUE TITLE
[Bug] Compatibility w/ Ars nouveau (Crash)

### ISSUE THREAD

**Issue by ghost** [mickelus/tetra#721]
### Observed behaviour

While using a mine block spell in Ars nouveau in the off-hand and holding an enchanted tetra pick in the main hand, the server crashed giving the error message found at this Reddit post: https://www.reddit.com/r/CurseForge/comments/13rrtm6/so_i_created_a_mod_pack_for_mc_w_tetra_arsnouveau/

### Expected behaviour

For the server to not crash while holding a spell book and a tetra pickTetra

### Steps to reproduce

enchant a tetra pick w/ a silk touch
have a spell book w/ a spell w/ projectile > break > amplify

hold the spellbook in the off-hand and the tetra pick in the main hand
use the spell from the book on a block, the server should crash

### Tetra version

tetra-1.16.5-3.20.0.

### mutil/mGui version

mutil-1.19.2-5.1.0

### Forge version

1.19.2-43.2.11

### Other mods

ars nouveau - ars_nouveau-1.19.2-3.13.4

**Comment by mickelus** [comment]
This should have been resolved in 5.3.0, if the issue persists please include a full backlog rather than a picture.
