### ISSUE TITLE
[Bug] Performance issues while not in use

### ISSUE THREAD

**Issue by Nishh** [mickelus/tetra#725]
### Observed behaviour

Tetra uses 16% of CPU time while not being used (no active gui)

https://spark.lucko.me/WSFXdgHtaB

### Expected behaviour

Minimal (1%?) CPU use while not in use.

### Steps to reproduce

1. Install ATM-8
2. do /sparkc profiler start
3. wait 10 sec
4. do /sparkc profiler stop
5. examine the results

### Tetra version

1.19.2 - 5.2.1

### mutil/mGui version

1.19.2 - 5.1.0

### Forge version

1.19.2 - 43.2.14

### Other mods

ATM - 8 mods + 29 different:
https://gist.github.com/Nishh/81cb16dfc6a5f95ae241230d6edb6f67

**Comment by mickelus** [comment]
Fixed in 5.3.1.
