### ISSUE TITLE
Project MMO (and likely a few other mods) Support For Tools

### ISSUE THREAD

**Issue by SomewhatDamaged** [mickelus/tetra#727]
### Feature description

[Project MMO](https://github.com/Caltinor/Project-MMO-2.0) has a vein-mining system that, at present, doesn't work with Tetra.

Talking to the developer of PMMO, Caltinor, he said that there are some Forge overrides that would need to be set that would let the tools have wider compatibility with mods.

> They need to override `IForgeItem#isCorrectToolForDrops` which is an expanded version of `Item#isCorrectToolForDrops` (either works).  this is how modular items like Ticon/Tetra/SilentGear can get around the `minecraft:mineable/tool` tag limitation which doesn't factor in their variability.

### How it improves the player experience

It would make things "just work" between the two mods in particular, and likely any other mod that reacts to tools being used on the environment.

### Tetra synergies

By allowing a deeper and more seamless integration between Tetra and other Forge mods.

**Comment by mickelus** [comment]
Tetra items implement IForgeItem#isCorrectToolForDrops 👍
