### ISSUE TITLE
[Bug] the "long gone" advancement is granted upon joining a world

### ISSUE THREAD

**Issue by kuba26038** [mickelus/tetra#729]
### Observed behaviour

the "long gone" advancement, the one which is granted to the player when it finds a forged structure, is granted to it the moment it joins a new world

### Expected behaviour

the advancement should only be granted when the player finds a forged structure

### Steps to reproduce

-create and join a new world
-observe the advancement being granted to you for no apparent reason

### Tetra version

tetra-1.19.2-5.3.0

### mutil/mGui version

mutil-1.19.2-5.1.0

### Forge version

1.19.2 - 43.2.14

**Comment by mickelus** [comment]
Fixed in 5.3.1.

**Comment by kuba26038** [comment]
just tested and it wasn't actually fixed
