### ISSUE TITLE
Crushing Hammers

### ISSUE THREAD

**Issue by PliskintheSaltyFork** [mickelus/tetra#730]
### Feature description

Would like it if the hammers worked like Ex Nihilo Hammers and do crushing damage to mobs.  Plus, it would be interesting to see upgrades for tools that are AOE to allow things like tools to mine more then one block or do a for weapons to do an AOE.

### How it improves the player experience

1. Makes it easier for players to get gravel for flint.
2. More sand would be easily gotten.
3. More types of attacks for players to use to help kill mobs.
4. Profit

### Tetra synergies

This would make it more compatible with Ex Nihilo mods and would give players easier time when dealing with large "zombie" hordes.

**Comment by mickelus** [comment]
It's a bit unclear what you're asking for but based on the description everything you've requested is already in the mod. Closing.
