### ISSUE TITLE
General gameplay and new feature requests

### ISSUE THREAD

**Issue by JMANIUS6300** [mickelus/tetra#731]
### Feature description

I think that removing the underground structures you can find is a bad thing because it makes it too easy to just go along with the vanilla sort of line instead of having to go out of your way to find a structure to get the forge, although be sort of a modder myself i know that structures between version are difficuilt but to fix this i think you should make the forge craftable using netherite and other rare materials aswell as you should probably take this mod more towards machinery instead of just tools

### How it improves the player experience

balancing the gameplay experience

### Tetra synergies

i personally dont know the goals of tetra

**Comment by mickelus** [comment]
The structures have been re-added.
