### ISSUE TITLE
[Bug] Geode blocks unobtainable in creative, don't show in REI and RER

### ISSUE THREAD

**Issue by T3sT3ro** [mickelus/tetra#737]
### Observed behaviour

Geode blocks are unobtainable in the creative mode without `setblock x y z tetra:block_geode` and they don't show in Roughly Enough Resources. This makes it unclear how one obtains geodes and where do geode blocks spawn.

### Expected behaviour

geode blocks should be visible in REI, RER and creative tab.

### Steps to reproduce

1. Search for geode in REI
2. click `r` over it
3. in the menu visible there is no geode block, just a tag below the loot window saying `tetra:block_geode`

### Tetra version

tetra-1.19.2-5.3.1

### mutil/mGui version

mutil-1.19.2-5.1.0

### Forge version

43.2.4

### Other mods

relevant:
- Roughly Enough Items
- Roughly Enough Resources

**Comment by mickelus** [comment]
> This makes it unclear how one obtains geodes and where do geode blocks spawn.
What?

Closing, observed behavior is intended.
