### ISSUE TITLE
[Bug] Void Bug

### ISSUE THREAD

**Issue by DinnerBeef** [mickelus/tetra#738]
### Observed behaviour

If you have items in the repair slot of the tool, and you take the tool out of the table, it voids the items in the repair slow.

### Expected behaviour

Not to void items

### Steps to reproduce

1. Place tool in workbench
2.  Put Items in repair slot
3.  Take tool out of repair slot
4.  Items Missing "Even if you put the tool back in"

### Tetra version

 tetra-1.19.2-5.3.1.jar

### mutil/mGui version

 mutil-1.19.2-5.1.0.jar

### Forge version

43.2.14

### Other mods

Video https://s.dinnerbeef.com/gOXe5/daJedeme56.mp4

**Comment by mickelus** [comment]
Do you have any other mods present? Attempting to reproduce that causes the itemstack to plop out into the world for me.

**Comment by DinnerBeef** [comment]
Lol, I found out where they were going. They were going behind the table because I have a furnace on top of it
