### ISSUE TITLE
[1.14] Crash when Creating Handle from Material

### ISSUE THREAD

**Issue by oitsjustjose** [mickelus/tetra#74]
## Bug Report

**Observed Behaviour**
In trying to give my pickaxe a handle out of leather, the GUI for creating it popped up, highlighting the leather in my inventory. On hovering over the leather, the game crashes with [this report](https://pastebin.com/mJn0KTud).

**Expected Behaviour**
Less crashing ideally

**Minimal setup needed to reproduce**
- Forge version: 1.12.2-28.1.90
- Other mods: None
- Tetra configuration:  Completely Default

**Steps to reproduce**
Place a pickaxe (I used Diamond) in the workbench, select Handle -> Craft -> Handle -> Hover over Leather highlighted in inventory

**Comment by mickelus** [comment]
I've not been able to reproduce this issue, but I noticed a bunch of data that did not load properly while attempting to reproduce it. Also found a spot that might have been causing this which I patched up, although I've not been able to verify if it did as cannot get it to crash to begin with.

Feel free to reopen if this issue persists

**Comment by oitsjustjose** [comment]
I was about to come back and update that in a larger modpack (with OptiFine even, of all things!) I couldn't reproduce it either. I'll test to see if it ever happens again, but it very well could've been a loading error causing something else down the line to break ¯\_(ツ)_/¯
