### ISSUE TITLE
[Bug] Server console spamming warnings

### ISSUE THREAD

**Issue by wowaoaw** [mickelus/tetra#749]
### Observed behaviour

Server console is constantly spewing out the following:
 [Server] Server thread/[WARN] [minecraft/V99]: Unable to resolve BlockEntity for ItemStack: tetra:scroll_rolled

This is happening on a ATM8 server version 1.0.2.5
 This started recently, (perhaps a day or two before writing this report), and we believe someone might've placed down a scroll from the this mod and now the server doesn't know what to do with it. We haven't been able to find the scroll yet.
 This report doesn't really affect the server thankfully, as it can boot and function without crashing, therefore I have no crash log to provide. However I can only imagine that whatever it does affect is something I am unaware of and could lead to worst case scenarios.
 
 Not to mention the constant spam is really annoying when trying to read the console. It reports the same line each time roughly twice every second, and then stops for a random amount of time (less than 10 minutes), only to then happen again. I have also posted this issue on the ATM8 github.

### Expected behaviour

Not that.

### Steps to reproduce

We haven't found it yet, but we believe that it happens when you place down a scroll.

### Tetra version

5.4.0

### mutil/mGui version

5.1.0

### Forge version

1.19.2

### Other mods

Only ATM8 modpack and Luckperms was also added to the server to change user permissions.

**Comment by mickelus** [comment]
This is too vague to do anything about. Closing, please leave a comment if you figure out how to reproduce the issue.
