### ISSUE TITLE
Support for arrows from mods

### ISSUE THREAD

**Issue by chillcat222** [mickelus/tetra#75]
## Feature Request
The quiver belt upgrade really falls short in modded games as the only accept vanilla arrows, perhaps add a config option to allow you to add supported items? 
**Feature description**

Any compatibility for arrows/bolts from other mods as its a big shortcoming of the current quiver
**How it improves the player experience**

Just makes it way more useful when used with other mods
**Tetra synergies**

**Comment by mickelus** [comment]
There is a config file which you can override to allow the quiver to hold additional types of arrows. It contains an array of item predicates, i.e. the same as what's used in advancements and crafting jsons.

It's `/data/tetra/predicates/toolbelt/quiver.json` in a datapack for 1.14 
and `/data/toolbelt/quiver_predicates.json` in using the config override system described in the wiki for 1.12

I don't quite know how datapacks work to be honest (I just know that I'm using minecrafts resource manager and that should fix that), poke me on discord if you try that out!
