### ISSUE TITLE
[Bug][1.19.2] Issues with Numismatic Overhaul: Reforged

### ISSUE THREAD

**Issue by DoctorMage** [mickelus/tetra#751]
### Observed behaviour

https://github.com/dr3ams/Life-in-the-village-3/issues/76

Get villager of certain type to max level and no tetra scrolls will be offered

Not an expert with code but this seems to be the handler for what villagers give no idea to tell wether its guranteed or not
https://github.com/mickelus/tetra/blob/1.18/src/main/java/se/mickelus/tetra/trades/TradeHandler.java

Mods Involved

mutil-1.19.2-5.1.0.jar
numismaticoverhaul-1.19.2-1.0.4.jar
tetra-1.19.2-5.5.1.jar

Forge 43.2.6

(copied report from numismatic discord)

Was told to report it here on Numismatic Overhaul: Reforged discord

### Expected behaviour

Villagers offer scrolls for trade

### Steps to reproduce

1. Get a villager that can offer scrolls for trades
2. Max them out
3. No scrolls being offered

### Tetra version

tetra-1.19.2-5.5.1.jar

### mutil/mGui version

mutil-1.19.2-5.1.0.jar

### Forge version

Forge 1.19.2 43.2.6

### Other mods

numismaticoverhaul-1.19.2-1.0.4.jar - https://github.com/Nyfaria/numismatic-overhaul-reforged
(appears to be closed source)

**Comment by mickelus** [comment]
Don't think there's anything that can be done on the tetra side
