### ISSUE TITLE
Saber's in off hand enchanted with fire aspect don't drop cooked food on mob kill [Bug] 

### ISSUE THREAD

**Issue by MoonwaIk** [mickelus/tetra#753]
### Observed behaviour

As mentioned in the title, sabers used in the off hand slot enchanted with fire aspect do not drop cooked food from mobs (i.e raw beef is dropped from cows instead of steak), this does not occur when the saber is used in a mainhand slot, and the cooked product is dropped as expected.

### Expected behaviour

a cooked version of the raw food is expected to be dropped when killed by fire aspect.

### Steps to reproduce

1. Create a saber and enchant it with fire aspect
2. Place saber into offhand slot
3. Kill a mob that would drop a raw food item (i.e rabbit, chicken, cow, pig, sheep, etc.) using the saber (right click since its in offhand slot) 
4. Note that raw food items are dropped instead of cooked food items. Note this does not occur when using the saber in a mainhand slot.
5. Additionally note that this behaviour was tested with a sword that killed the entity in one attack.

### Tetra version

1.19.2-5.5.0

### mutil/mGui version

1.19.2-5.1.0

### Forge version

1.19.2-43.2.6

### Other mods

latest version of life in the village 3 modpack,

notably: tetradic combat, quark, and art of forging.
Behaviour was only tested using forged steel from the art of forging mod with fire aspect 3 (quark addition) enchanted on the weapon.

**Comment by mickelus** [comment]
There's no saber in tetra, closing.
