### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by SharkoxPrime974** [mickelus/tetra#754]
### Observed behaviour

The Tooltips of the tools i craft with tetra is way too big and it's an issue that appeared recently in my game.  I was playing normally and honing my tools normally but recently all the honing i have done just shows itself in the tooltip and create a new line for every honing i put on my tools here's an example  : 

![issue tetra](https://github.com/mickelus/tetra/assets/146974830/7c02b678-e501-4fd6-8ec7-e163f594dcb0)

**Please note** that i already done a lot of research about these issue and i couldn't find any help or any similarities on my own and that the version of tetra that i am using right now is the only one **working** for my modpack including origin classes

### Expected behaviour

the tooltip to be normal or having all these information about the honing grouped in one single line to reduce the size of the tooltip

### Steps to reproduce

1. craft a tetra tool
2. hone it to a certain level
3. having your tooltip overflowed 

### Tetra version

5.2.1

### mutil/mGui version

5.1.0

### Forge version

1.19.2 - 43.2.23

### Other mods

AdvancementPlaques-1.19.2-1.4.7.jar
alexsdelight-1.4.1.jar
alexsmobs-1.21.1.jar
another_furniture-forge-1.19.2-2.1.4.jar
appleskin-forge-mc1.19-2.4.2.jar
architectury-6.5.85-forge.jar
art_of_forging-1.6.7-1.19.2.jar
async-locator-forge-1.19.2-1.3.0.jar
AttributeFix-Forge-1.19.2-17.2.7.jar
balm-forge-1.19.2-4.6.0.jar
betterchunkloading-1.19.2-2.1.jar
bettercombat-forge-1.7.1+1.19.jar
betterstats-2.2.2+1.19.2.jar
BetterThirdPerson-Forge-1.19-1.9.0.jar
Bookshelf-Forge-1.19.2-16.3.20.jar
botarium-forge-1.19.2-1.8.2.jar
caelus-forge-1.19.2-3.0.0.6.jar
camera-1.19.2-1.0.4.jar
catalogue-1.7.0-1.19.2.jar
cc-tweaked-1.19.2-1.101.3.jar
cccbridge-mc1.19.2-forge-v1.5.1.jar
chat_heads-0.10.20-forge-1.19.2.jar
citadel-2.1.4-1.19.jar
clienttweaks-forge-1.19.2-8.3.0.jar
cloth-config-8.3.103-forge.jar
Clumps-forge-1.19.2-9.0.0+14.jar
CoffeeDelight-Forge-1.19.2-1.4.jar
collective-1.19.2-6.65.jar
configured-2.1.1-1.19.2.jar
connectivity-1.19.2-4.5.jar
Controlling-forge-1.19.2-10.0+7.jar
CorgiLib-forge-1.19.2-1.0.0.34.jar
corpse-1.19.2-1.0.0.jar
CosmeticArmorReworked-1.19.2-v1a.jar
CraftTweaker-forge-1.19.2-10.1.49.jar
create-1.19.2-0.5.1.c.jar
create-new-age-forge-1.19.2-1.0.1.jar
create-structures-0.1.0.jar
create-stuff-additions1.19.2_v2.0.4a.jar
createaddition-1.19.2-1.0.0.jar
createdeco-1.3.3-1.19.2.jar
createdieselgenerators-1.19.2-1.1d.jar
creategoggles-1.19.2-0.5.5.c-[FORGE].jar
create_enchantment_industry-1.19.2-for-create-0.5.1.c-1.2.6.b.jar
create_jetpack-forge-3.2.2.jar
create_misc_and_things_ 1.19.2_4.0A.jar
create_sabers-1.19.2-1.3.0.jar
ctov-3.2.5.jar
culturaldelights-1.19.2-0.15.4.jar
cupboard-1.19.2-2.0.jar
curios-forge-1.19.2-5.1.4.1.jar
DecorationDelightRefurbished-1.19.2.jar
deeperdarker-forge-1.1.6-forge.jar
dragonfight-1.19.2-4.1.jar
DungeonsArise-1.19.2-2.1.54-release.jar
dungeons_gear-1.19.2-5.0.5-beta.jar
dungeons_libraries-1.19.2-3.0.10-beta.jar
dungeons_mobs-1.19.2-4.0.8-beta.jar
dynamiclightsreforged-1.19.2_v1.4.0.jar
EasyAnvils-v4.0.11-1.19.2-Forge.jar
EasyMagic-v4.3.3-1.19.2-Forge.jar
eatinganimation-1.19-3.2.0.jar
emotecraft-for-MC1.19.2-2.2.5-forge.jar
endsdelight-1.19.2-1.2.1.jar
entityculling-forge-1.6.1-mc1.19.2.jar
Entity_Collision_FPS_Fix-forge-1.19-2.0.0.0.jar
epicfight-19.5.0.19-beta.2.jar
fantasyfurniture-1.19.2-6.7.0.jar
FarmersDelight-1.19.2-1.2.3.jar
FarmersRespite-1.19-2.0.jar
fastfooddelight-1.19-1.2.3.jar
FastFurnace-1.19.2-7.0.0.jar
FastLeafDecay-30.jar
FastSuite-1.19.2-4.1.1.jar
FastWorkbench-1.19.2-7.1.4.jar
ferritecore-5.0.3-forge.jar
forge-1.19.2-43.2.23-installer.jar
FPS-Monitor-1.19.2-1.3.0.jar
ftb-chunks-forge-1902.4.2-build.302.jar
ftb-essentials-1902.1.10-build.47.jar
ftb-library-forge-1902.4.1-build.236.jar
ftb-quests-forge-1902.5.4-build.275.jar
ftb-teams-forge-1902.2.14-build.123.jar
ftb-xmod-compat-forge-1.2.2.jar
FTBQuestsOptimizer-forge-1.1.1-1.19.2.jar
fusion-1.0.5-forge-mc1.19.2.jar
gamemenumodoption-mc1.19.2-1.18.1.jar
geckolib-forge-1.19-3.1.40.jar
getittogetherdrops-forge-1.19.2-1.3.jar
habitat-1.2.4.jar
handcrafted-forge-1.19.2-2.0.6.jar
hourglass-1.19.1-1.2.1.1.jar
Iceberg-1.19.2-forge-1.1.4.jar
ImmediatelyFast-1.2.4+1.19.2.jar
ImmersiveEngineering-1.19.2-9.2.2-165.jar
Incendium_1.19.3_v5.1.6.jar
InventoryProfilesNext-forge-1.19-1.10.7.jar
ironchest-1.19.2-14.2.7.jar
item-filters-forge-1902.2.9-build.51.jar
ItShallNotTick-1.0.11-build.35.jar
Jade-1.19.1-forge-8.9.0.jar
JadeAddons-1.19.2-forge-3.5.0.jar
jei-1.19.2-forge-11.6.0.1018.jar
JetAndEliasArmors1.4.1-1.19.2.jar
kotlinforforge-3.12.0-all.jar
kubejs-forge-1902.6.2-build.3.jar
lazydfu-1.19-1.0.2.jar
LegendaryTooltips-1.19.2-forge-1.4.0.jar
letmedespawn-1.18.x-1.19.x-forge-1.0.3.jar
libIPN-forge-1.19-4.0.0.jar
lootintegrations-1.19.2-3.2.jar
lootr-1.19-0.4.24.64.jar
macawsroofsbyg-1.19.2-1.3.jar
mcw-doors-1.1.0forge-mc1.19.2.jar
mcw-fences-1.0.7-mc1.19.2forge.jar
mcw-furniture-3.2.0-mc1.19.2forge.jar
mcw-lights-1.0.6-mc1.19.2forge.jar
mcw-paintings-1.0.4-mc1.19.2.jar
mcw-paths-1.0.3forge-mc1.19.2.jar
mcw-roofs-2.2.4-mc1.19.2forge.jar
mcw-trapdoors-1.1.1-mc1.19.2forge.jar
mcw-windows-2.2.0-mc1.19.2forge.jar
mcwfencesbyg-1.19.2-1.0.jar
mcwfurnituresbyg-1.19.2-1.2.jar
memoryleakfix-forge-1.17+-1.0.0.jar
modernfix-forge-5.7.2mc1.19.2.jar
moonlight-1.19.2-2.2.46-forge.jar
moremobvariants-forge+1.19.2-1.2.0.jar
MouseTweaks-forge-mc1.19-2.23.jar
MutantMonsters-v4.0.6-1.19.2-Forge.jar
mutil-1.19.2-5.1.0.jar
netherportalfix-forge-1.19-10.0.1.jar
NethersDelight-1.19-3.1.jar
notenoughanimations-forge-1.6.2-mc1.19.2.jar
observable-3.3.1.jar
Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.4.jar
open-parties-and-claims-forge-1.19.2-0.19.3.jar
origins-classes-forge-1.2.0.jar
origins-forge-1.19.2-1.7.1.3-all.jar
origins-plus-plus-2.1.2-forge.jar
OverflowingBars-v4.0.1-1.19.2-Forge.jar
paladin-furniture-mod-1.1.1-forge-mc1.19.jar
Paraglider-1.19.2-1.7.0.5.jar
Patchouli-1.19.2-77.jar
Pehkui-3.7.8+1.19.2-forge.jar
Placebo-1.19.2-7.3.2.jar
player-animation-lib-forge-1.0.2.jar
Prism-1.19.1-1.0.2.jar
productivebees-1.19.2-0.10.7.2.jar
PuzzlesLib-v4.4.3-1.19.2-Forge.jar
rechiseled-1.1.4-forge-mc1.19.2.jar
rechiseledcreate-1.0.0-forge-mc1.19.jar
repurposed_structures_forge-6.3.26+1.19.2.jar
resourcefullib-forge-1.19.2-1.1.24.jar
rhino-forge-1902.2.2-build.272.jar
rottencreatures-forge-1.19.2-1.0.1.jar
rubidium-0.6.2b.jar
rubidium-extra-0.4.17+mc1.19.2-build.71.jar
rubidium_extras-1.19.2_v1.4.3.jar
saturn-mc1.19.2-0.0.4.jar
seasonhud-forge-1.19.2-1.5.6.jar
SereneSeasons-1.19.2-8.1.0.24.jar
servercore-forge-1.3.5+1.19.2.jar
simplyswords-forge-1.47.0-1.19.2.jar
sliceanddice-forge-2.3.2.jar
smallships-forge-1.19.2-2.0.0-a2.3.jar
smoothboot(reloaded)-mc1.19.2-0.0.2.jar
smoothchunk-1.19.2-3.2.jar
sophisticatedbackpacks-1.19.2-3.18.58.907.jar
sophisticatedcore-1.19.2-0.5.87.417.jar
soundphysics-forge-1.19.2-1.2.1.jar
spark-1.10.37-forge.jar
Steam_Rails-1.5.1+forge-mc1.19.2.jar
StorageDrawers-1.19-11.1.2.jar
Structory_1.19.3_v1.3.1a.jar
supermartijn642configlib-1.1.8-forge-mc1.19.jar
supermartijn642corelib-1.1.12-forge-mc1.19.2.jar
supplementaries-1.19.2-2.3.24.jar
TerraBlender-forge-1.19.2-2.0.1.136.jar
tetra-1.19.2-5.2.1.jar
toofast-1.19-0.2.2.4.jar
ToolStats-Forge-1.19.2-12.1.4.jar
treeharvester-1.19.2-8.2.jar
untamedwilds-1.19.2-3.0.3.jar
upgradedcore-1.19.2-4.1.0.1-release.jar
upgradednetherite-1.19.2-5.1.0.9-release.jar
VisualWorkbench-v4.2.4-1.19.2-Forge.jar
waystones-forge-1.19.2-11.4.1.jar
XaerosWorldMap_1.34.1_Forge_1.19.1.jar
Xaeros_Minimap_23.8.0_Forge_1.19.1.jar
xercamusic-1.19.2-1.1.0.jar
xlpackets-1.18.2-2.1.jar
YungsApi-1.19.2-Forge-3.8.9.jar
YungsBetterDesertTemples-1.19.2-Forge-2.2.2.jar
YungsBetterDungeons-1.19.2-Forge-3.2.2.jar
YungsBetterJungleTemples-1.19.2-Forge-1.0.1.jar
YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar
YungsBetterNetherFortresses-1.19.2-Forge-1.0.6.jar
YungsBetterOceanMonuments-1.19.2-Forge-2.1.0.jar
YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar
[1.19.2-forge]-Epic-Knights-8.2.jar

**Comment by mickelus** [comment]
I'm not booting up that modlist :P. Please provide a minimal set of mods required to reproduce this or I'll have to close it.

**Comment by SharkoxPrime974** [comment]
Hello it's okay you don't need to look up at my issue anymore I found out
that it was the origin classes mod and specifically the blacksmith classes
that messed with the tooltips

The blacksmith classes adds bonus to each item you craft but since tetra
consist into "re-crafting" your tools over and over again by honing or
changing the module's material it creates this bug

I will write down the solution in the report and then close it as solved
since it's more like an origin classes issue

Le mer. 18 oct. 2023 à 23:05, Mikael E. Wikner ***@***.***> a
écrit :
