### ISSUE TITLE
1.14.4 "PlayerExpEvent" Crash on startup

### ISSUE THREAD

**Issue by DeviantTeal** [mickelus/tetra#76]
## Bug Report

**Observed Behaviour**
When the game goes to launch, it said there was an Error Loading mods. Crashes from the following exception:
```java.lang.ClassNotFoundException: net.minecraftforge.event.entity.player.PlayerXpEvent$PickupXp```

**Expected Behaviour**
I expected the game to Launch.

**Minimal setup needed to reproduce**
- Forge version:  14.23.5.2807 
- Other mods: mgui
- Tetra configuration: 

Crashlog: [latest.log](https://github.com/mickelus/tetra/files/3923523/latest.log)

**Steps to reproduce**
Install the two mods needed for 1.14.4 and then launch the game

**Comment by mickelus** [comment]
Did updating forge resolve this issue?

**Comment by DeviantTeal** [comment]
**Updating Forge Did Resolve the Issue**

**Comment by RuneMercy** [comment]
im having issues with mine aswell? PlayerXpEvent$PickupXp i also have the latest vesion of forge, but im also new too modding

**Comment by RuneMercy** [comment]
[help.txt](https://github.com/mickelus/tetra/files/3925119/help.txt)

**Comment by mickelus** [comment]
Judging by your log you're running forge 28.1.0, the latest forge is 28.1.108. I'm closing this btw, but feel free to keep commenting.
