### ISSUE TITLE
[Bug] Game crash while

### ISSUE THREAD

**Issue by M1hono** [mickelus/tetra#760]
### Observed behaviour

I encountered a crash while using a diamond to create a "sword blade." After this crash, I attempted to "temper" my iron sword, and this function worked correctly. The issue seems to be related to the rendering of achievements.

### Expected behaviour

expect to be able to create a "sword blade" using a diamond without any crashes or issues related to achievement rendering.

### Steps to reproduce

Open the crafting interface.
Insert a diamond to create a "sword blade."
Observe if the game crashes at this point.
If the crash occurs, restart the game and attempt to "temper" an iron sword.
Observe if the "tempering" function works correctly without issues.
the problem may be related to achievement rendering due to the crash file.

### Crashlog

https://gist.github.com/Guda-nemo/69474d67dd0f6d887458e82bf72f3299

### Tetra version

6.0.0

### mutil/mGui version

6.1.1

### Forge version

1.20.1-47.2.1

### Other mods

can be founded in crash report.

**Comment by digitalseraphim** [comment]
@Guda-nemo, I have the same issue in 1.19.2, turns out it's actually a Tetra Extras bug, and they are aware of it (I see people commenting on the curseforge page saying they have submitted bug reports on discord).

**Comment by mickelus** [comment]
Closing, from what I've heard this has been fixed in Tetra extras!
