### ISSUE TITLE
compatibility with soul fire'd mod for tetra bows

### ISSUE THREAD

**Issue by clashyboi805** [mickelus/tetra#761]
### Feature description

from Nyphet (soul fired's maker):
So, from what I can see, it's an issue with Tetra.
Basically its bow item does not extend Vanilla bow item and it just has its own method for firing arrows.
The solution is for Tetra to add Soul Fire'd as an optional dependency and use its API to add the proper fire behavior.

### How it improves the player experience

Using soul fire'd, it adds a very minor yet cool effect of simply making things burn with soul fire and not normal fire only.

since tetra's bows arent vanilla bows, the enchantment from soul fire'd that's called "soul flame" only shoots normal fire arrows and not soul flame arrows, meanwhile "soul fire aspect" works just fine on swords.

### Tetra synergies

blue fire is cool.

**Comment by Crystal-Spider** [comment]
Just a quick comment to also link the related issue (https://github.com/Nyphet/soul-fire-d/issues/31).  
I'd also like to add that, with Soul Fire'd, burning from soul fire doesn't only produce a visual effect, but also the damage is increased (double the usual burning damage, as standing on soul fire gives double the damage of standing on plain fire).

**Comment by clashyboi805** [comment]
more importantly, blue fire is cool.

**Comment by CatAndPaste** [comment]
Would love to see this compat <3

**Comment by mickelus** [comment]
Done!
