### ISSUE TITLE
[Bug] Tetracelium incompatible with apotheosis

### ISSUE THREAD

**Issue by DankestO** [mickelus/tetra#762]
### Observed behaviour

Good afternoon, It seems that Tetracelium does not get along with Apoth.
When you start Minecraft with Tetracelium and Apotheosis the game crashes, I have been hearing that Apotheosis in version 1.20.1 changed something in its code and several mods compatible with it have stopped working well.

On dedicated servers it directly crashes.

### Expected behaviour

Start a world normally?

### Steps to reproduce

1.Start minecraft.
2.Broken menu.
![image](https://github.com/mickelus/tetra/assets/126206944/775ec1e2-8364-4eb9-acb5-c967d2735044)
3.Minecraft dies when starting a world :(

### Crashlog

https://gist.github.com/DankestO/a9dc919aa89089f0afb1e52d2741ba78

### Tetra version

6.0.0

### mutil/mGui version

6.1.1

### Forge version

1.20.1-47.2.0

**Comment by CatAndPaste** [comment]
I have Apotheosis v. 7.0.5 and Tetra along with Tetracelium, and this doesn't happen to me. Although, I use NeoForge 47.1.79 instead of Forge, so may be give NeoForge a try? ~I believe, NeoForge is recommended on Apotheosis page anyway.~

EDIT: factcheck

**Comment by DankestO** [comment]
I took your word, installed NeoForge, deleted all mods except tetra, mutil and Tetracelium.
I tried starting it together with Iron's Spells 'n Spellbooks and everything was fine.
After trying several combinations without problems, I tried tetra and apoth again but with the minimum required.
-Apoth
-Patchouli
-ApothicAttributes
-Placebo
And in fact now it won't let me advance beyond the loading screen, am I doing something wrong? :(
![image](https://github.com/mickelus/tetra/assets/126206944/ef672989-5b37-4fcd-a777-888af30f402d)

I even removed Embeddium because I saw it causing graphical errors for other people, but I still couldn't fix it.

**Comment by CatAndPaste** [comment]
That's strange. I currently have over 230 mods installed with all the mods you mentioned (versions):
Placebo 8.3.7
Patchouli 1.20.1-81-FORGE
ApothicAttributes 1.1.4
Apotheosis 7.0.5
mutil 6.1.1
tetra 6.0.0
tetracelium 1.0.0
Embeddium 0.2.5

(you can see my whole list of mods (w/o oculus and different rubidium tweaks as I was looking for visual bug candidate meantime) in bug report here, https://github.com/mickelus/tetra/issues/764 )

NeoForge 47.1.79 (Java 17.0.8)

EDIT: I decided to rename my current mods folder and try it with setup you have, it didn't load for me with the same error :/ You're not alone! (crash report: https://pastebin.com/PSP8xYw7 )

**Comment by DankestO** [comment]
wow, that fix was quick, thanks! :D
