### ISSUE TITLE
[Bug-1.20.1] Random crash when /reloading game.

### ISSUE THREAD

**Issue by Gbergz** [mickelus/tetra#763]
### Observed behaviour

I reloaded the game using / reload then suddenly game froze and it crashed.
Log points to tetra so I might aswell report it just because.

### Expected behaviour

No crashes while reloading etc.

### Steps to reproduce

For me it was.
1. Go ingame.
2. Do /reload
3. Game froze for 1 minute.
4. Crash.

### Crashlog

https://gist.githubusercontent.com/Gbergz/23b8ed1246fdfb552333b872f968b873/raw/d8df1b4b9471f866dc7eb311f0005c2615503103/gistfile1.txt

### Tetra version

6.0.0

### mutil/mGui version

6.1.1

### Forge version

47.1.3

### Other mods

Modlist is here, scroll down:
https://legacy.curseforge.com/minecraft/modpacks/tnp-limitless-7/files/4819624

**Comment by mickelus** [comment]
Should have been fixed alongside the other similar crash, in 6.2.0.
