### ISSUE TITLE
Add compatibility for Stargate Journey mod

### ISSUE THREAD

**Issue by AngellusMortis** [mickelus/tetra#765]
### Feature description

Add compat for [Stargate Journey mod](https://www.curseforge.com/minecraft/mc-mods/sgjourney) to [Tetracelium](https://www.curseforge.com/minecraft/mc-mods/tetracelium). Posting in this repo since I do not see a repo for Tetracelium.

Stargate Journey is an upcoming mod that adds the popular Sci-fi Universe of Stargate to Minecraft. The mod really only adds a single resource, Naquadah. Specifcially "Weapons Grade Naquadah" is what is used for crafting. There is a full set of tools/weapons, armor + special armors that match the "Jaffa" from the show. There is a special Staff Weapon that might be cool to integrate, but it is its own thing and probably extra.

Naquadah is a post Netherite item (you can upgrade Netherite tools to Naquadah ones). The properties for the resource in the show is that it is kind of a combination of amazing fuel source and superconductor. It is the main resource in a lot of space age type tech in the show, including spaceships, shields, hyperspace engines, etc. 

If you want any technical specifics about the mod to integrate, just let me know and I can try to help out in any way I can. I imagine is it pretty easy to install the mod and poke around in it, but I do not want to assume.

### How it improves the player experience

Compatibility for mods is always great for players. Stargate Journey has decent popularity, and it is included in ATM 9, which is a rather large mod pack. 

### Tetra synergies

It can be added as a usable Tetra resource and synergize with all of the existing features the mod. The Sword, Pickaxe, Shovel, and Hoes can also all be integrated to allow being converted to Tetra tools/weapons. Optionally, it might be really cool to find a way to integrate the Staff Weapon.

**Comment by mickelus** [comment]
I'm not interested in adding compat for that mod to tetracelium, but if someone would like to make a dedicated compat mod I'll gladly help out!
