### ISSUE TITLE
[Bug] Random Button Click Event Crash

### ISSUE THREAD

**Issue by ReeCodes** [mickelus/tetra#766]
### Observed behaviour

Clicking any button in the world select menu causes it to crash.

### Expected behaviour

Work flawlessly.

### Steps to reproduce

Use tetra version

### Crashlog

https://gist.github.com/ReeCodes/81a32762bc301461d2042fca64f23a81

### Tetra version

tetra-1.20.1-6.0.0.jar

### mutil/mGui version

mutil-1.20.1-6.1.1

### Forge version

1.20.1 - forge-47.2.4

**Comment by mickelus** [comment]
This should have been fixed in 6.2.0.
