### ISSUE TITLE
Ars Elemental Enchantment support

### ISSUE THREAD

**Issue by anna-s-h** [mickelus/tetra#767]
### Feature description

The soulbound enchantment should be supported by tetra tools and belts.

### How it improves the player experience

enchantments should be compatible even if they are not vanilla

### Tetra synergies

soulbound is a very good enchantment for tools which you invest so much into

**Comment by mickelus** [comment]
Was going to ask for a more elaborate description of how compat with that mod would look like, but I don't think this is the correct issue for that. I'm happy to help out with ars nouveau compat, or add ars compat in tetracelium if someone puts in the work on how to do that in a meaningful way. There's also https://www.curseforge.com/minecraft/mc-mods/ars-armiger, it might be a better fit to ask them for compat for one-off features.
