### ISSUE TITLE
Repair and text display not working as intended.

### ISSUE THREAD

**Issue by SaltSouls** [mickelus/tetra#77]
## Bug Report

**The Problem at Hand**
The text is something that is easy to show in an image so I won't bother to explain it other than I think it is an issue with the color codes/invalid character when programming in the descriptions. As far as the repair function goes though, I have a feeling that it is pulling items in alphabetical order to use as repair materials, and in some cases it isn't allowing you to use the material used to make the tool to repair it. For example, my pack has **BoP** and **EmbellishCraft**. When I go to repair the log hammer it shows "Stripped Jacaranda Wood" as the material(a wood from **BoP**). In this case it allows me to use other wood types though to repair it. It should just say logs though and check for all logs using the oredict. Now for the situation where it doesn't work as intended(or at least not in my mind). I upgraded a wooden pickaxe using the table and turned it into a cobblestone one. When I went to go repair it, the listed material was "Jade"(a stone type from **EmbellishCraft**). Again, should just show something like stone as the repair material. All would be good though if it let me use cobblestone to repair it, but it sadly doesn't. I don't know if cobblestone and stone are classified differently in the oredict, but it doesn't feel right having to go and smelt the cobblestone that was used to make the cobblestone pickaxe just to be able to repair it. It should allow the use of both cobblestone and stone variants, maybe using stone would result in a higher repair amount, who knows? All I know is that something doesn't seem right there, and I'm not sure if it is a bug or a feature, but I'm assuming it is a bug.

- Forge version: 28.1.102
- Tetra configuration: Default, I think? I made no changes or additions after installing the mod.

**Images:**
![2019-12-04-1](https://user-images.githubusercontent.com/36361103/70186285-73b45d00-16a0-11ea-82c4-4e6d7ce6305a.png)
![2019-12-04-2](https://user-images.githubusercontent.com/36361103/70186292-7911a780-16a0-11ea-97b9-00d824a0b44d.png)

**Comment by mickelus** [comment]
I've been fighting the the first issue for a while, I'm only able to reproduce it when I download tetra as part of a mod pack. I think I've managed to fix it in 1.0.6.

It picks the first item that has the item tag that that module needs for repairs, I'm working on this!

**Comment by mickelus** [comment]
Tag/oredict material display was fixed in 1.16.0.
