### ISSUE TITLE
[Bug] Blocks from some mods are unminable even with the correct tool, and correct level of tool.

### ISSUE THREAD

**Issue by MsVella** [mickelus/tetra#776]
### Observed behaviour

In tetra 1.19.2 blocks from some mods such as enlightend and endlessbiomes don't drop even if you have the correct tool type, and level of tool to break them. Vanilla equivalents of the same tool break these blocks just fine.

### Expected behaviour

The block should break and drop itself.
Note: this does happen with vanilla tool equivalents.

### Steps to reproduce

1. Locate effected block suck as Arkan from endlessbiomes, or Malachite ore from Elightend
2. Break with a vanilla diamond pickaxe and observe that the block drops correctly.
2. Break with a Tetra diamond pickaxe and observe that the block does not drop. 

### Tetra version

5.5.1

### mutil/mGui version

5.1.0

### Forge version

1.19.2 Latest stable version

### Other mods

Ruincraft & Create modpack
https://legacy.curseforge.com/minecraft/modpacks/ruincraft-create/files

**Comment by mickelus** [comment]
From what I've gathered the "correct" way to handle tool requirements is for blocks that require a pickaxe to break to be tagged with "minecraft:mineable/pickaxe", and tetra tools relies on that. Both of the mods you've references appear to be made with mccreator, I don't know how that works. Closing.
