### ISSUE TITLE
[Bug] Screen render error

### ISSUE THREAD

**Issue by Happysquid69** [mickelus/tetra#778]
### Observed behaviour

if i click on any of the modifiable Parts the game freezes and then crashes immeadiately 

### Expected behaviour

no crash when choosing parts to modify 

### Steps to reproduce

1. Place tetra tool in workbench
2. click on any modifiable tool part 
3. game freeze and crash . 

### Crashlog

https://gist.github.com/Happysquid69/405647466758eb1f3149e2999e21aefc

### Tetra version

tetra-1.19.2-5.5.1

### mutil/mGui version

5.1.0

### Forge version

43.3.5

**Comment by mickelus** [comment]
You've listed no other mods but the crash log contains a long list of mods. Closing, we can look into reopening this if you can provide a minimal list of mods required to reproduce the issue.
