### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by bobodoustaud** [mickelus/tetra#78]
## Bug Report

My RAM usage goes up and up when i have an modified item from tetra

i think that the models are always added to the ram

- Forge version: 1.12.2-LiteLoader1.12.2-1.12.2-forge1.12.2-14.23.5.2847
- Tetra version: 0.39.1

- Tetra configuration: stock config
![Capture](https://user-images.githubusercontent.com/49878442/70373546-0f380e80-18e9-11ea-96dd-a94b44e242c9.JPG)
![Czefapture](https://user-images.githubusercontent.com/49878442/70373549-12cb9580-18e9-11ea-8a16-5a5a57a797ec.JPG)
![Captergure](https://user-images.githubusercontent.com/49878442/70373550-13fcc280-18e9-11ea-81c3-a8d2b7e0f188.JPG)

have an item from tetra loaded in your world

**Comment by mickelus** [comment]
What do you mean with up and up? "Baking" the item models is expensive so when you craft a new permutation of an item its model is cached for five minutes.
Does the memory usage appear to go up as you make frequent changes to items in a short period of time, or does it slowly increase over a longer span of time?

Is that the minimum set of mods you need to reproduce this issue?

**Comment by bobodoustaud** [comment]
i go from 45% to 80% in 10 minutes when i have a modified weapon in my inventory

**Comment by bobodoustaud** [comment]
i'm not totally sure that is the modified weapons but removing tetra fixes the RAM issue

**Comment by mickelus** [comment]
This is too unclear for me to act on and It's been almost five months since I asked for clarification, feel free to reopen if you manage to provided the requested information.
