### ISSUE TITLE
[Bug-1.20.1] Can't re-enter the world after creating one. (datapack error).

### ISSUE THREAD

**Issue by Gbergz** [mickelus/tetra#781]
### Observed behaviour

Any world created cannot be re-entered after quitting it. Results in datapack errors.

### Expected behaviour

No datapack errors and worlds can be re-entered without issues.

### Steps to reproduce

1. Install mod. (?) (might be caused by other stuff)
2. Create world.
3. Quit world
4. try to re-enter.
5. datapack error.
profit.

### Crashlog

https://gist.githubusercontent.com/Gbergz/896044d8bc7a98c3d41a47c86abc4040/raw/ea0b6d6f7131db8830a2bd06a05a83957de446a2/gistfile1.txt

### Tetra version

6.1.0

### mutil/mGui version

6.1.1

### Forge version

47.2.17

### Other mods

# Modlist: https://gist.github.com/Gbergz/3d8db6fc98ca2ab1224ae017433e4323

### Other: 
Modpack is [TNP Limitless 7](https://legacy.curseforge.com/minecraft/modpacks/tnp-limitless-7), by me. on an indev version.

I can send you the indev version that this is happening on if you wanna investigate further.
Write a reply with that if needed.

Also, this doesn't happen on Forge 47.2.0, but any version above that it happens. Not sure what changed in newer forge versions.
But it's worth mentioning.

### Edit:
Also seems to happen even on forge 47.2.0 but only sometimes when using `/reload` in-game.

**Comment by mickelus** [comment]
It looks like a concurrency issue, but it's difficult for me to test with a modlist of that size. I think I have a fix, ping me on discord and I can send you a prerelease!

**Comment by Gbergz** [comment]
Pinged you there.

**Comment by Plaer1** [comment]
any chance I could help test this out? I'm also running the latest TNP and would love to be using Tetra ;a;

**Comment by mickelus** [comment]
Pretty sure the fix I rolled out back then managed to solve this issue, let me know if that wasn't the case! Closing!
