### ISSUE TITLE
[Bug] tetra netherite pickaxe extractor not mining 3x3

### ISSUE THREAD

**Issue by drakosoldier298** [mickelus/tetra#787]
### Observed behaviour

when mining itf you break one block it breaks in a corner 3 blocks forward.

### Expected behaviour

At potency level 5 a extractor pickaxe to mine the 3x3x3 

### Steps to reproduce

1. upgrade a netherite pickaxe with an extractor
2. use alot of mods.
3. watch it fail

### Tetra version

6.1.0

### mutil/mGui version

6.1.1

### Forge version

1.20.1 47.2.17

### Other mods

Mods:
  [✔] additionaladditions-6.0.1
  [✔] AdvancedPeripherals-1.20.1-0.7.35b
  [✔] aeroblender-1.20.1-1.0.1-neoforge
  [✔] aether-1.20.1-1.0.0-beta.2.2-neoforge
  [✔] alltheores-1.20.1-47.1.3-2.2.3
  [✔] almostunified-forge-1.20.1-0.7.2
  [✔] alternate_current-mc1.20-1.7.0
  [✔] appleskin-forge-mc1.20.1-2.5.1
  [✔] architectury-9.1.12-forge
  [✔] ars_creo-1.20.1-4.0.1
  [✔] ars_nouveau-1.20.1-4.8.1-all
  [✔] athena-forge-1.20.1-3.1.1
  [✔] balm-forge-1.20.1-7.2.1
  [✔] beautify-2.0.2
  [✔] bedspreads-forge-6.2.0+1.20.1
  [✔] bellsandwhistles-0.4.3-1.20.x
  [✔] BetterFurnaces-1.20.1-1.1.1-forge
  [✔] blockui-1.20.1-1.0.128-BETA
  [✔] bloodmagic-1.20.1-3.3.2-44
  [✔] born_in_chaos_[Forge]1.20.1_1.1
  [✔] Bountiful-6.0.3+1.20.1-forge
  [✔] caelus-forge-3.1.0+1.20
  [✔] carpeted-1.20-1.4
  [✔] casualness_delight-1.20.1-0.2n
  [✔] cc-tweaked-1.20.1-forge-1.109.2
  [✔] chat_heads-0.10.27-forge-1.20
  [✔] chefs-delight-1.0.3-forge-1.20.1
  [✔] chipped-forge-1.20.1-3.0.1
  [✔] Chunky-1.3.92
  [✔] ClearDespawn-forge-1.20.2-1.1.15
  [✔] cloth-config-12.0.109-forge
  [✔] cluttered-2.1-1.20.1
  [✔] collective-1.20.1-7.22
  [✔] Controlling-forge-1.20.1-12.0.2
  [✔] cookingforblockheads-forge-1.20-16.0.1
  [✔] CorgiLib-forge-1.20.1-4.0.0.4
  [✔] corn_delight-1.0.3-1.20.1
  [✔] craftingtweaks-forge-1.20-18.2.2
  [✔] CraterLib-forge-1.20-1.0.2
  [✔] create_tweaked_controllers-1.20.1-1.2.2
  [✔] create-1.20.1-0.5.1.f
  [✔] createaddition-1.20.1-1.1.1
  [✔] CreateCasing-1.20.1-1.5.0-ht3
  [✔] createendertransmission-2.0.6-1.20.1
  [✔] create-structures-0.1.1-1.20.1-FORGE
  [✔] CreativeCore_FORGE_v2.11.16_mc1.20.1
  [✔] creeperoverhaul-3.0.1-forge
  [✔] ctov-3.3.6
  [✔] ctov-advanced-peripheral-compat-2.0
  [✔] ctov-farmers-delight-compat-2.1
  [✔] ctov-immersive-engineering-compat-2.0
  [✔] ctov-irons-spells-n-spellbooks-compat-1.2
  [✔] curios-forge-5.4.6+1.20.1
  [✔] CyclopsCore-1.20.1-1.18.14
  [✔] dicemcdeathgen-1.20.1-0.0.1
  [✔] dimdoors-5.3.0-forge-beta2
  [✔] domum_ornamentum-1.20-1.0.147-BETA-universal
  [✔] doubledoors-1.20.1-5.2
  [✔] duckyperiphs-1.20.1-1.3.1-forge
  [✔] dummmmmmy-1.20-1.8.13
  [✔] eidolon_repraised-1.20.1-0.3.7.5
  [✔] embeddium-0.2.13+mc1.20.1
  [✔] embeddiumplus-1.20.1-v1.1.0
  [✔] embersrekindled-1.20.1-1.0.3
  [✔] emi-1.0.28+1.20.1+forge
  [✔] emiffect-forge-1.1.2+mc1.20.1
  [✔] enchantedbookredesign-1.20.1-1
  [✔] Enhanced_Celestials-forge-1.20.1-5.0.0.2
  [✔] entangled-1.3.16-forge-mc1.20
  [✔] entityculling-forge-1.6.2-mc1.20.1
  [✔] EverlastingAbilities-1.20.1-2.0.10
  [✔] expandingtechnologies-1.0.2
  [✔] ExplorersCompass-1.20.1-1.3.3-forge
  [✔] ExtraDisks-1.20.1-3.0.1
  [✔] ExtremeReactors2-1.20.1-2.0.75
  [✔] FactoryAPI-1.20.1-2.0.2-forge
  [✔] FarmersDelight-1.20.1-1.2.3
  [✔] ferritecore-6.0.1-forge
  [✔] Festive_Delight_1.3_Forge_1.20.1
  [✔] findme-3.1.1-forge
  [✔] FramedBlocks-9.1.6
  [✔] fusion-1.1.0b-forge-mc1.20.1
  [✔] geckolib-forge-1.20.1-4.3.1
  [✔] geodeplus-forge-1.2.4-1.20.1
  [✔] geophilic-v2.1.0-mc1.20u1.20.2
  [✔] handcrafted-forge-1.20.1-3.0.5
  [✔] immersive_aircraft-0.6.2+1.20.1-forge
  [✔] immersive_armors-1.6.1+1.20.1-forge
  [✔] immersive_melodies-0.1.0+1.20.1-forge
  [✔] immersive_paintings-0.6.7+1.20.1-forge
  [✔] ImmersiveEngineering-1.20.1-10.0.0-169
  [✔] interiors-0.5.2+mc1.20.1-FORGE
  [✔] irons_spellbooks-1.20.1-2.1.2
  [✔] Jade-1.20.1-forge-11.6.4
  [✔] jei-1.20.1-forge-15.2.0.27
  [✔] Kambrik-6.1.1+1.20.1-forge
  [✔] kotlinforforge-4.9.0-all
  [✔] LetSleepingDogsLie-1.20.1-Forge-1.2.0
  [✔] liquidburner-1.20.1-0.5
  [✔] Mekanism-1.20.1-10.4.5.19
  [✔] MekanismGenerators-1.20.1-10.4.5.19
  [✔] minecolonies-1.20.1-1.1.373-BETA
  [✔] miners_delight-1.20.1-1.2.1
  [✔] missions-forge-0.2
  [✔] moonlight-1.20-2.8.67-forge
  [✔] morebeautifultorches-2.5.2-1.20.1_forge
  [✔] moremobvariants-forge+1.20-1.2.2
  [✔] MorePeripherals_1.20.1-1.12.2
  [✔] MouseTweaks-forge-mc1.20-2.25
  [✔] multipiston-1.20-1.2.31-ALPHA
  [✔] mutil-1.20.1-6.1.1
  [✔] mysterious_mountain_lib-1.4.2-1.20.1
  [✔] NaturesCompass-1.20.1-1.11.2-forge
  [✔] neruina-1.3.0-forge+1.18.2-1.20.1
  [✔] netherportalfix-forge-1.20-13.0.1
  [✔] nethersdelight-1.20.1-4.0
  [✔] NoChatReports-FORGE-1.20.1-v2.2.2
  [✔] oceansdelight-1.0.2-1.20
  [✔] oculus-mc1.20.1-1.6.13
  [✔] open-parties-and-claims-forge-1.20.1-0.20.1
  [✔] PacketFixer-forge-1.2.1-1.20.1
  [✔] Patchouli-1.20.1-84-FORGE
  [✔] Paxi-1.20-Forge-4.0
  [✔] peripheralium-forge-1.20.1-0.6.14
  [✔] peripheralworks-forge-1.20.1-1.4.2
  [✔] pipez-1.20.1-1.2.5
  [✔] player-animation-lib-forge-1.0.2-rc1+1.20
  [✔] polymorph-forge-0.49.2+1.20.1
  [✔] Powah-5.0.4
  [✔] rechiseled-1.1.5c-forge-mc1.20
  [✔] refinedcooking-4.0.0
  [✔] refinedstorage-1.12.4
  [✔] refinedstorageaddons-0.10.0
  [✔] RegionsUnexploredForge-0.5.3+1.20.1
  [✔] repurposed_structures-7.1.11+1.20.1-forge
  [✔] resourcefulconfig-forge-1.20.1-2.1.0
  [✔] resourcefullib-forge-1.20.1-2.1.19
  [✔] riverredux-0.3.1
  [✔] rubidium-extra-0.5.3.1+mc1.20.1-build.110
  [✔] saturn-mc1.20.1-0.1.0
  [✔] Searchables-forge-1.20.1-1.0.2
  [✔] sebastrnlib-4.0.0
  [✔] sfcr-1.7.6-mc1.20
  [✘] SimpleDiscordLink-Combo-1.20-3.0.0.jar (disabled)
  [✔] sophisticatedbackpacks-1.20.1-3.19.4.978
  [✔] sophisticatedcore-1.20.1-0.5.111.517
  [✔] sophisticatedstorage-1.20.1-0.8.62.671
  [✔] spark-1.10.53-forge
  [✔] starbunclemania-1.20.1-1.2.0.4
  [✔] Steam_Rails-1.5.3+forge-mc1.20.1
  [✔] structurize-1.20.1-1.0.664-BETA
  [✔] supermartijn642configlib-1.1.8-forge-mc1.20
  [✔] supermartijn642corelib-1.1.16-forge-mc1.20.1
  [✔] supplementaries-1.20-2.7.12
  [✔] tarotcards-1.20-1.5.5
  [✔] tectonic-mod-mc1.19.3+-v2.1.1
  [✔] tempad-forge-1.20.1-2.3.0
  [✔] TerraBlender-forge-1.20.1-3.0.0.169
  [✔] tetra-1.20.1-6.1.0
  [✔] tetracelium-1.20.1-1.0.1
  [✔] textrues_embeddium_options-0.1.3+mc1.20.1
  [✔] tomeofblood-1.20.1-0.4.3-all
  [✔] toms-peripherals-1.20.1-1.1.1
  [✔] toomanyglyphs-1.20.1-2.3.2.12345
  [✔] torchmaster-20.1.5
  [✔] towntalk-1.20.1-1.0.1
  [✔] TreeChop-1.20.1-forge-0.18.3
  [✔] Twilight Flavors & Delight-2.0.1
  [✔] twilightforest-1.20.1-4.3.1893-universal
  [✔] village-nullifier-2.0.0
  [✔] voicechat-forge-1.20.1-2.4.32
  [✔] waveycapes-forge-1.4.0-mc1.20
  [✔] waystones-forge-1.20-14.1.3
  [✔] WaystonesTeleportPets-1.20-1.20.1--1.2
  [✔] wirelesschargers-1.0.9-forge-mc1.20
  [✔] XaeroPlus-Forge-1.20.1-59-WM1.37.2-MM23.9.3
  [✔] Xaeros_Minimap_23.9.3_Forge_1.20
  [✔] xaeros_waystones_compability-1.19.2-1.20.1--1.0
  [✔] XaerosWorldMap_1.37.2_Forge_1.20
  [✔] YungsApi-1.20-Forge-4.0.2
  [✔] YungsBetterDesertTemples-1.20-Forge-3.0.3
  [✔] YungsBetterDungeons-1.20-Forge-4.0.3
  [✔] YungsBetterEndIsland-1.20-Forge-2.0.4
  [✔] YungsBetterJungleTemples-1.20-Forge-2.0.4
  [✔] YungsBetterMineshafts-1.20-Forge-4.0.4
  [✔] YungsBetterNetherFortresses-1.20-Forge-2.0.5
  [✔] YungsBetterOceanMonuments-1.20-Forge-3.0.4
  [✔] YungsBetterStrongholds-1.20-Forge-4.0.3
  [✔] YungsBetterWitchHuts-1.20-Forge-3.0.3
  [✔] YungsBridges-1.20-Forge-4.0.3
  [✔] YungsExtras-1.20-Forge-4.0.3
  [✔] ZeroCore2-1.20.1-2.1.39

**Comment by mickelus** [comment]
Closing this as the description doesn't make any sense. Feel free to reply if this issue still persists.
