### ISSUE TITLE
Modded Enchantment Compatability

### ISSUE THREAD

**Issue by Axelph237** [mickelus/tetra#79]
Added compatibility allowing the use of modded enchantments on tools modded with Tetra

Tetra currently lacks the functionality of taking a weapon that has been changed and using it in either an anvil or enchantment table. I love the idea of enchanting parts of the weapon and also believe it gives the mod a further sense of balance. This all works fine in vanilla Minecraft. However, when using a mod that adds additional enchantments, they are impossible to acquire on weapons that have been changed using the workbench.

I really love this mod but am also very interested in additional, unique, enchantment books and believe that the compatibility of this mod with other enchantment books would make the entire mod feel more cohesive when playing on a modded world. Currently, I am playing the 1.12 edition and believe this would be a great fix to both the 1.12 and 1.14 versions of the mod.

The features are already in Tetra. The only issue is the incompatibility of outside enchantment books in the current version. I think that adding this would in no way change the goals of the modpack but would instead create a better user experience.

**Comment by mickelus** [comment]
Please update this to adhere to the template for feature requests.

I also see great value in allowing/integrating enchantments from other mods. It may seem like it but this features is not in tetra, I am working on it though.
I've looked into making tetra items enchantable in the enchanting table but I've not found a way to hook into how it applies enchantments to items, I'll request it from forge but I have no control over how that goes.

**Comment by Axelph237** [comment]
Thank you for the quick reply. I am sorry for not directly staying to the template provided and will note to do so in future requests. I greatly appreciate your willingness to be apart of the requests given by your fan base. I would love to see the integration of other enchantments but I feel like you could likely get away with the tools being unenchantable in an enchantment table. I realize that nonetheless it is an important feature to add and highly respect your aptitude in taking action on these subjects.

**Comment by mickelus** [comment]
Supporting modded enchantments became significantly easier in 1.1.0, but they still need to be added manually. 

Closing this ticket as I can take no further actions. Feel free to create a new issue if you want support for a specific mod (perferrably including a list of the enchantments in the mod).

**Comment by raijeen** [comment]
Sir honestly im a big fan of your mod but please make tetra compatible with unique enchantments
