### ISSUE TITLE
[Issue] Log messages from cutting recipes

### ISSUE THREAD

**Issue by moonfather1** [mickelus/tetra#790]
### Observed behaviour

With tetra present but FD not present, recipes of type `farmersdelight:cutting` output a lot of mess into the log.

### Details

section 
   "forge:conditions": [
    {
      "modid": "farmersdelight",
      "type": "forge:mod_loaded"
    }
  ]
needs to be added to all recipes of FD cutting type. then if FD isn't present, no errors in log.

notice (from fellow dev):
in forge 1.20.2, this section is changed. it is from that point onwards a single condition, not an array. delete brackets and call it condition (not conditions).
in neoforge, it is still an array in 1.20.4, just replace the two namespaces with neoforge.

### Steps to reproduce

tetra present, farmer's delight not present. look at log window.

### Crashlog

not a crash

### Tetra version

tetracelium-1.20.1-1.0.1

### mutil/mGui version

mutil-1.20.1-6.1.1.jar

### Forge version

1.20.1 - 47.1.3

**Comment by mickelus** [comment]
Fixed in 1.1.0.
