### ISSUE TITLE
[BUG]The game crashed whilst unexpected error Error: net.minecraftforge.fml.ModLoadingException: tetra (tetra) encountered an error during the done event phase

### ISSUE THREAD

**Issue by Jangoism** [mickelus/tetra#793]
### Observed behaviour

I join into the server and everything sits there as if it's loading me in, then I get booted and kicked with a "timeout" the game eventually crashes and gives me the error above. Crashlog is included.

### Expected behaviour

To not be booted from the server

### Steps to reproduce

1. I join my server, people are actively playing on it however I get this error when I join.

### Crashlog

https://gist.github.com/Jangoism/57f04cad4376944bab19b3068623fe6f

### Tetra version

6.10

### mutil/mGui version

N/A

### Forge version

47.2.0

### Other mods

Mods included in crashlog

**Comment by mickelus** [comment]
How did you solve it?

**Comment by Jangoism** [comment]
> How did you solve it?

My apologies, I went to bed immediately after fixing it so I forgot to put my fix actions.

1. Export zip of modpack from curseforge
2. Delete modpack from curseforge
3. Import zip file to curseforge
4. Launch
5. Change ram settings
6. Done

I'm not really sure what caused it in the end but these steps got me back into my server.

**Comment by Jangoism** [comment]
Update on this. I think this was just giving me a false positive. My internet isn't handling packages and I think the tetra mod error just displayed whenever it closed. Swapped to different internet and it's not happening so I don't believe this error has anything to do with this mod or mods at all.
