### ISSUE TITLE
[1.0.5] Fortune enchant not working on Tetra Pickaxes

### ISSUE THREAD

**Issue by PokeMaserJ** [mickelus/tetra#80]
## Bug Report

**Observed Behaviour**

Tetra Pickaxes enchanted with the Fortune enchant through the Tetra Crafting Table don't "fortune" ores. 

**Expected Behaviour**

Tetra Pickaxes that have Fortune on them to "fortune" ores. 
**Minimal setup needed to reproduce**

- Forge version: 
- Tetra version: 
- Tetra configuration: 
- Other mods:
N/A
**Steps to reproduce**

Make a Tetra Pickaxe
Use the Tetra Crafting Table to enchant it with Fortune
Mine Ores that can be Fortuned
Notice no additional drops

**Comment by mickelus** [comment]
This has been fixed in 1.1.0
