### ISSUE TITLE
[Bug] Material Lost when switching between items

### ISSUE THREAD

**Issue by Gleiphnir** [mickelus/tetra#804]
### Observed behaviour

When modifying any item in the workbench, and selecting a module to upgrade, you can insert any appropriate material to the material slot to preview the effects.  However if you leave the material slotted in the material window and then swap out the main Tetra item, then the material you were using will be lost forever.  Doesn't matter what the material, all material will be lost if you don't craft the upgrade and simply leave it in the slot, and then swap to a different item.

### Expected behaviour

The expected behaviour, is as with most other functions where if you cancel an action, then any materials should simply return to your inventory, or dropped on the floor if there is no more room.  If you are viewing an upgrade on an item with a material slotted, and then decide to swap to a different item, without first removing the slotted upgrade material, then the material should be sent back to the player if the main item is swapped out.

### Steps to reproduce

1. Place any Valid item in the workbench
2. Select any upgrade module and schematic
3. Place any material in the material slot
4. Replace the Worbench item with any other Valid Item and observe that the previous material in the material slot will be missing from your inventory, and will also be missing from the material slot.

### Tetra version

5.6.0

### mutil/mGui version

5.2.0

### Forge version

43.3.2

### Other mods

Latest Modlist available for "Life in the Village 3"  version 2.6

**Comment by mickelus** [comment]
The player that did the swap is not available in that context, so when you switch the upgraded item like that any materials will plop out into the world (above the workbench) instead of going in the player inventory. If you've placed a block above the workbench the itemstack probably plops out in the nearest available space.
