### ISSUE TITLE
[FR] (minimal) Apotheosis Support

### ISSUE THREAD

**Issue by MaxWasUnavailable** [mickelus/tetra#807]
### Feature description

Editing tools/weapons that have apotheosis modifiers, sockets, etc... removes all Apotheosis data. It would be nice if the item retained this data.

### How it improves the player experience

Allows users to combine features of Apotheosis and Tetra, hence significantly increasing variation in tools/weapons, as well as removing frustration of accidentally wiping a high-end Apotheosis modified object.

### Tetra synergies

It increases variation in tools/weapons, makes tools even more "personalised", and adds content both-ways: one could find a good base item with apotheosis modifiers to turn into a tetra build they like, or tetra build around an apotheosis modified item they really like.

**Comment by mickelus** [comment]
This is already supported in tetracelium 😊
