### ISSUE TITLE
[Bug/Mod Compat] Blocks from other mods that require a tool level to be mined do not drop blocks

### ISSUE THREAD

**Issue by sauphle** [mickelus/tetra#813]
### Observed behaviour

From what I found there's incompatibility with **The Luminous Mod**, **Easter Island (Moai Mod)**, **Create : Misc & Things**, and probably more. When mining a Moai block for example with a tier 4 tetra iron pickaxe it does not drop the block, but mines at the correct speed. This probably has something to do with the tool's mining level.

This has happened with stone types from **Deeper Caves**, stone types from **The Luminous Mod**, the sails from **Create : Misc & Things**, and the Moai blocks from **Easter Island (Moai Mod)**.

### Expected behaviour

Stone and above pickaxes are able to break and drop the Moai block, but fists and wooden pickaxes cannot. Vanilla iron pickaxes are able to break the block

### Steps to reproduce

1. Start the game with **Tetra** + one of the listed mods installed
2. Place a vanilla pickaxe in a workbench and use leather on the binding to turn it into a tetra pick
3. try and break one of the listed blocks with it.

### Tetra version

6.3.0

### mutil/mGui version

6.1.1

### Forge version

1.20.1 - 47.2.23

### Other mods

**The Luminous Mod** - 1.3.45
**Easter Island (Moai Mod)** - 4.0
**Create : Misc & Things** - 4.0A
**Deeper Caves** - 1,2,7

**Comment by mickelus** [comment]
MCreator mods don't check for tool actions the right way, I guess you could try reporting that on the MCreator issue tracker!

**Comment by sauphle** [comment]
Good to know thanks
