### ISSUE TITLE
[Bug] Pickaxes break some blocks without drops

### ISSUE THREAD

**Issue by moonfather1** [mickelus/tetra#818]
### Observed behaviour

Tetra pickaxe breaks a block with no drops; 
vanilla pickaxe of the same tier breaks it with drops.

### Expected behaviour

item dropped.

### Steps to reproduce

1) make a datapack overriding any block's loot table with this: https://pastebin.com/BtgScWtL
(replace names)
2) make a vanilla wooden pickaxe and a vanilla iron pickaxe.
3) take a wooden pickaxe and replace both heads with iron.
4) break offending block with both pickaxes. one drops loot, one does not.

it's a block from some mcreator mod that i can't find on the net so no link.
my friend came across this issue and sent me the mod to check out.

it is not caused by a 3rd mod, i tried in an empty instance.

### Tetra version

6.3.0

### mutil/mGui version

6.1.1

### Forge version

1.20.1 - 47.1.3

### Other mods

mutil-1.20.1-6.1.1.jar
OpenLoader-Forge-1.20.1-19.0.3.jar
tetra-1.20.1-6.3.0.jar

yes, that is all.

**Comment by mickelus** [comment]
I wouldn't expect that to work as you've not tagged the block but you're running a match tool predicate in the loot table?

**Comment by moonfather1** [comment]
it has a mineable/pickaxe tag.
it originally didn't have a tier tag, i tried adding needs_stone_tool but that didn't change anything.

**Comment by mickelus** [comment]
I've tested the provided loot table (using different items) and it works for me 🤔

**Comment by moonfather1** [comment]
then we have two options left. one, stupid mcreator mods add loot tables differently; two, it's an openloader issue.

to test option 1, try the original mod: https://file.io/Ybuf6UceoVaG      
warning, i can't find it on curse or modrinth, it likely wasn't scanned with anything.

for option 2 (the way i recreated the issue) you need another mcreator mod: https://modrinth.com/mod/smithing-steel plus a datapack that adds loot tables (the mod linked has none): https://ufile.io/a0ltppqc plus the openloader https://www.curseforge.com/minecraft/mc-mods/open-loader
put the datapack in config/openloader/data
put some limestone ore on the ground (there are two variants, should work the same); try vanilla pickaxe; try corresponding tetra pickaxe.

**Comment by mickelus** [comment]
Yeah, mccreator does its own thing instead of using the system provided by forge for determining correct tool types. And that doesn't work with tetra :(
