### ISSUE TITLE
Compatibility with Mine and Slash Mod by mcrobertx22

### ISSUE THREAD

**Issue by Novatruepower** [mickelus/tetra#819]
### Feature description

All features from weapons from Mine and Slash should work on tetra item weapons when a soul is apply to the tetra weapon. By that I mean, like be able to use a "soul" on a tetra weapon and it will add the stats and the rarity on the weapon. Also, being able to not lose the stats and the rarity when you pass from Mine and Slash to tetra weapon. As for last wish, it would be nice if the items to power up gear from Mine and Slash can be use on tetra weapon when they have a "soul" on it.

### How it improves the player experience

The player will enjoy even more because the tools will be more customizable and it will look nice for doing an rpg with more flexibility because Mine and Slash is mostly a rpg mod that is missing the customization of being able to change the material parts of the item. So the rpg player, will be able to fully enjoy to play the way he wants like attacking faster or doing more damage.

### Tetra synergies

The goal of tetra is like to cutomize the tools. Mine and Slash goal is to be use in a rpg and let the player make their own choices by playing how they feel like. Adding compatibility with Mine and Slash will allow to make it event more customizable by adding stats and rarity to the item such in this picture (come from https://www.curseforge.com/minecraft/mc-mods/mine-and-slash-reloaded).
![rare_items](https://github.com/mickelus/tetra/assets/123615683/46306764-b5f4-4042-8cf5-247b93231697)

**Comment by mickelus** [comment]
I'm leaning towards apotheosis compat with tetracelium and I feel that fills the same niche as this mod. If someone wants to do a dedicated mine and slash compat mod I'd happily help out though!

**Comment by Netrinil** [comment]
I know this is an old post, but I'm interested in doing a compat mod between MNS and Tetra (at least for 1.20.1, we'll see how it goes). I have a good amount of programming experience but 0 minecraft modding experience.
