### ISSUE TITLE
[Bug] Reaching damage is double it's tooltip value

### ISSUE THREAD

**Issue by SomeFellaUnknown** [mickelus/tetra#822]
### Observed behaviour

the Reaching property seems to be adding (aproximately) double the percentage multiplier listed in the tooltip for reaching, for instance if the reaching property tooltip claims that the property is going to add a +33% bonus to the damage, the damage is actiually being multiplied by +66%.

See tables / examples below:

(in all of these examples we have an entity with 0 armor and 300 health with an block position of (18.5, -58.5, 14.5) we teleport to a certain location, hit the entity and extract it's health after being hitl)

![image](https://github.com/mickelus/tetra/assets/100487467/6f952607-a9bc-4929-b4a4-5ca6577468c8)

![image](https://github.com/mickelus/tetra/assets/100487467/89bfa361-a50c-4b83-bc02-fd03dfee60ff)

![image](https://github.com/mickelus/tetra/assets/100487467/855f48a9-cf5c-4543-97a2-8acd04b34686)

target lost 14.39444 health when 3 blocks away, as well as 17.16705 damage when we were 6 blocks away. Our expected damage is 12.2 and 13.6 respectively

![image](https://github.com/mickelus/tetra/assets/100487467/59852f6e-7117-476d-b460-b164403bff84)

![image](https://github.com/mickelus/tetra/assets/100487467/26181c19-c40f-41bd-862d-03025a3c0e26)

![image](https://github.com/mickelus/tetra/assets/100487467/bc368892-3779-4094-91b3-0eb0a8851a81)

target took 11.61417 damage when 3 blocks away and 12.82245 damage when 4 blocks away compared to the expected 9.31 and 9.94 damage respectively

![image](https://github.com/mickelus/tetra/assets/100487467/2b89948b-e2a1-4892-85d7-ae90ca0475cb)

![image](https://github.com/mickelus/tetra/assets/100487467/601cb078-72c8-42ca-966c-4ee1c45da361)

![image](https://github.com/mickelus/tetra/assets/100487467/20f26738-bd65-4442-b0bb-30a4264c0f61)

target took 16.59167 damage when 3 blocks away and 20.75055 damage when 6 blocks away compared to the expected 13.3 and 15.4 damage respectively

### Expected behaviour

for the tooltip to accurately describe the damage bonus of the Reaching property for the listed distances

### Steps to reproduce

1.  get an NoAI entity at a known set of coordinates and known maximum health
2. get an item with the Reaching property, note the damage percentages in the tooltip
3. use commands to teleport yourself so that you are exactly a distance away from the target based on the distances mentioned in the tooltip for reaching (3 and the weapon's maximum reach)
4. attack the entity in question
5. gain the entity's current health using /data get or similar commands
6. compare to expected damage
7. heal target and repeat

### Tetra version

6.3.0

### mutil/mGui version

6.1.1

### Forge version

1.20.1 - 47.2.0

### Other mods

none, i have a specific instance for testing just Tetra alone with only it's required dependencies

**Comment by mickelus** [comment]
Fixed in 6.4.0, thanks for the detailed issue!
