### ISSUE TITLE
[Bug] Cannot see Full UI inside Holosphere

### ISSUE THREAD

**Issue by Veesquared232** [mickelus/tetra#823]
### Observed behaviour

Instead of being able to see past the wood options, i can only see them.  This is happening on a mildly large modpack so that could also be part of the issue

### Expected behaviour

Hopefully be able to scroll through the different options

### Steps to reproduce

1. install a few compatibility mods (If that's what's causing it my bad)
2. Open Holosphere and look through materials
3. see that some things are cut off

### Tetra version

6.3.0

### mutil/mGui version

6.1.1

### Forge version

1.20.1-forge-47.2.0

### Other mods

"Zeta-1.0-16" "waystones-forge-1.20-14.1.3" "umbral_skies-1.3" "twilightforest-1.20.1-4.3.1893-universal" "TrueDarkness-1.20.1_2.2.4_MonarchUpdate" "Towns-and-Towers-1.11-Fabric+Forge" "totw_modded-forge-1.20.1-1.0.5" "tetranomicon-1.5.3-1.20.1" "tetra-1.20.1-6.3.0" "Terralith_1.20.4_v2.4.11" "TerraBlender-forge-1.20.1-3.0.1.6" "structure_gel-1.20.1-2.16.2" "Steam_Rails-1.6.4+forge-mc1.20.1" "sophisticatedcore-1.20.1-0.5.113.524" "sophisticatedbackpacks-1.20.1-3.19.5.988" "sliceanddice-forge-3.2.0" "relics-1.20.1-0.6.5.1" "RegionsUnexploredForge-0.5.5+1.20.1" "Quark-4.0-441" "PuzzlesLib-v8.1.18-1.20.1-Forge" "player-animation-lib-forge-1.0.2-rc1+1.20" "oreexcavation-1.13.170" "octolib-1.20.1-0.3" "nethersdelight-1.20.1-4.0" "netherportalfix-forge-1.20-13.0.1" "NaturesCompass-1.20.1-1.11.2-forge" "MysticalAgriculture-1.20.1-7.0.8" "mutil-1.20.1-6.1.1" "modernfix-forge-5.17.0+mc1.20.1" "modernfix-forge-5.17.0+mc1.20.1 (1)" "mobcompack-0.0.3.9-1.20.1" "lootr-forge-1.20-0.7.33.83" "kotlinforforge-4.10.0-all" "journeymap-1.20.1-5.9.21-forge" "jei-1.20.1-forge-15.2.0.27" "irons_spellbooks-1.20.1-3.1.5" "inspirationvibes-1.0.0-forge-1.20.1" "Incendium_1.20.4_v5.3.4" "iceandfire-2.1.13-1.20.1-beta-4" "HangGlider-v8.0.1-1.20.1-Forge" "goblintraders-forge-1.20.1-1.9.3" "geckolib-neoforge-1.20.1-4.4.4" "framework-forge-1.20.1-0.6.27" "FPS_Increaser_Forge" "ferritecore-6.0.1-forge" "FarmersDelight-1.20.1-1.2.3" "explorify-v1.3.0-mc1.20u1.20.1" "embeddium-0.3.19+mc1.20.1-all" "DungeonsArise-1.20.x-2.1.58-release" "dungeons-and-taverns-3.0.3.f" "dimdoors-5.3.3-forge" "curios-forge-5.9.0+1.20.1" "Cucumber-1.20.1-7.0.7" "cristellib-1.1.5-forge" "createutilities-0.1.4+1.20.1 (1)" "createaddition-1.20.1-1.2.2" "create-1.20.1-0.5.1.f" "create_misc_and_things_ 1.20.1_4.0A" "configured-forge-1.20.1-2.2.3" "Clumps-forge-1.20.1-12.0.0.4" "cloth-config-11.1.118-forge" "citadel-2.5.4-1.20.1" "cc-tweaked-1.20.1-forge-1.110.3" "caelus-forge-3.2.0+1.20.1" "born_in_chaos_[Forge]1.20.1_1.2" "blue_skies-1.20.1-1.3.31" "BiomesOPlenty-1.20.1-18.0.0.592" "bettercombat-forge-1.8.5+1.20.1" "balm-forge-1.20.1-7.2.1" "artifacts-forge-9.5.9" "architectury-9.2.14-forge" "appleskin-forge-mc1.20.1-2.5.1" "almostunified-forge-1.20.1-0.9.3" "alexsmobs-1.22.8" "alexscaves-1.1.4" "aetheric_tetranomicon-1.1.2-1.20.1" "aether-1.20.1-1.4.2-neoforge (1)"

**Comment by mickelus** [comment]
Would have been nice with a screenshot, but I'm guessing you need to use the scroll wheel! Closing!
