### ISSUE TITLE
Remove need for offhand to be empty to properly use a quick latch quiver.

### ISSUE THREAD

**Issue by Daggerdoc** [mickelus/tetra#826]
### Feature description

Currently, from what I can tell, the quiver places an arrow into a player's offhand, and only into the player's offhand, to allow them to shoot the bow. What I think would work better is system to place the arrow into their inventory by either maintains a stack or just 1 arrow. You could maintain the current functionality as well with the suggested system only occurring when the arrow can't fit in the offhand. If it can't fit in the inventory it then be dropped or the arrow could just not be transferred.

### How it improves the player experience

With the way it works right now players must have an empty offhand which given the dependence of modern minecraft combat on shields is a rare occurrence. Almost all players will have a shield equipped most of the time they are fighting. With the new system it wouldn't punish players for playing how they normally would and make the tetra quiver more viable when compared to other mod's quivers. 

### Tetra synergies

The tool belt is kinda pointless right now unless it's your only option. Most backpacks mod will outclass the storage options and most mods that add a quiver outclass tetra's version as well. A simple improvement to make the quiver more viable would go a long way to improving the tool belt's usability when compared to other options in a modpack.

**Comment by mickelus** [comment]
In vanilla minecraft special arrows have to be held in the offhand for it to be used with the bow. Closing, if you would like to propose for tetra to change that vanilla mechanic then update your issue and we can look into it again.
