### ISSUE TITLE
Make bows be able to critical strike

### ISSUE THREAD

**Issue by XenoHoe** [mickelus/tetra#828]
### Feature description

As title says, instead of melee attacking with the bow being able to crit, instead make it possible for bow projectiles to strike critically with the criticalStrike or another itemEffect, dealing a certain amount of bonus damage based on effect efficiency. This effect can come natively at a low percentage for basic bows and from sights in vanilla tetra. 

### How it improves the player experience

This would benefit the creation of datapacks that add custom bow parts, as item effects and attributes applicable to bows are quite lacking in quantity and variety. In addition, allowing the bow to crit would also incentivize the player to use the bow more for more thrilling gameplay as a simulation to "Hitting the weak spot of the target", which also explains why having sights would provide such a bonus as that would make aiming for the weak spot easier.

### Tetra synergies

Modular bows would be a more thrilling and interesting experience, enhancing the playability of mods and potentially benefitting the creation of modpackt that include tetra.

**Comment by mickelus** [comment]
In vanilla bows always "critical strike" when fully drawn, and the intent for tetra items is for them to work the same way as their vanilla counterpart. It will be possible to mimic how the chance based critical strikes for bows with a datapack, although you should probably call that something else. But there's no intent to add an explicit chance based critical strike effect for bows, closing!
