### ISSUE TITLE
crashes with Traverse 

### ISSUE THREAD

**Issue by duntwave** [mickelus/tetra#83]
## Bug Report

**Observed Behaviour**
So, I don't have any other mods installed but this and Traverse. I start it up things look ok but then it crashes mid-load.

Crash log: (this is all I have)
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Initializing game

**Expected Behaviour**
expected it to play the game lol 

**Minimal setup needed to reproduce**

- Forge version: 28.1.102
- Tetra version: 1.14.4-1.0.7
- Tetra configuration: stock
- Other mods: Traverse

**Steps to reproduce**
install mods, play game, crash

**Comment by mickelus** [comment]
I'm unable to reproduce this, if you can provide me with a log I can help you further.
Incase you need help I found this guide on how to get the log: https://imgur.com/a/N7sQD

Closing this issue, feel free to reopen if you manage to get some logs.
