### ISSUE TITLE
White tools

### ISSUE THREAD

**Issue by Wolf2307** [mickelus/tetra#830]
### Observed behaviour

So ,my tools (not the swords) are just pure white and shows no texture

### Expected behaviour

I think they should have textures

### Steps to reproduce

Just moded a normal pickaxe

### Tetra version

6.3.0

### mutil/mGui version

6.1.1

### Forge version

1.20.1-47.3.5

### Other mods

Create 
Farmers delight
Copycat+
Jei
Rechisled
Rechisled create
Sophisticated backpack
Storage drawers
Teralihth
Terrablender
Xareos minimap
And all of the suport mods ,i also have some optimization mods but i dont think those mess with tetra

**Comment by Wolf2307** [comment]
Also ,all my particlies are turned off

**Comment by mickelus** [comment]
Switch to embeddium

**Comment by SSalvadoRR-official** [comment]
Thank you! Switching to embeddium really helped! 

Mod versions that don't crash: 
Embeddium [0.3.31](https://modrinth.com/mod/embeddium/version/0.3.31+mc1.20.1)
Oculus [1.7.0](https://modrinth.com/mod/oculus/version/1.20.1-1.7.0)
Tetra [6.8.0](https://modrinth.com/mod/tetra/version/6.8.0) (Can be newer)
Mutil [6.1.1](https://modrinth.com/mod/mutil/version/5.2.0) (Can be newer)

Shaders work just fine
