### ISSUE TITLE
Some tools come out as grey

### ISSUE THREAD

**Issue by Jasseanwriting** [mickelus/tetra#832]
### Observed behaviour

When I make anything with diamond or nephrite in it, like a pickaxe for example, it comes out with no colour/ grey.
I am not using any resource packs or shaders, so not sure why this is happening.

### Expected behaviour

Normal textures

### Steps to reproduce

Make a diamond pick

### Crashlog

none

### Tetra version

6.2.0

### mutil/mGui version

unsure

### Forge version

1.20.1

**Comment by mickelus** [comment]
Switch to embeddium
