### ISSUE TITLE
[Bug] Bow Sights + Sneak = Drown

### ISSUE THREAD

**Issue by naqaden** [mickelus/tetra#837]
### Observed behaviour

Sneaking while holding a tetra bow with sights causes the player to drown.

[drowning_sights.webm](https://github.com/user-attachments/assets/28e1c84f-c780-4006-8eeb-e8900da6a435)

### Expected behaviour

I expect snorkel-free archery.

### Steps to reproduce

1. Place a vanilla bow in a workbench
2. Add a sights module
3. Hold the bow
4. Sneak

### Tetra version

6.4.0

### mutil/mGui version

6.1.1

### Forge version

1.20.1 - 47.3.0

### Other mods

none

**Comment by mickelus** [comment]
Good, then it's working as intended!

**Comment by naqaden** [comment]
I couldn't tell if you were kidding, since there is no current source to track, but at this point I'll wager not.

I can see the air meter being borrowed as a measure of stamina, like we're straining to focus to get that extra zoom, and straining for too long causes injury. Maybe. I mean vanilla spyglasses let us zoom without hurting ourselves, so why would attaching one to a bow hurt? But I especially don't see why the strain would happen during _crouch_.

Crouching is the Minecraft stance that prevents the player from falling off blocks. It's common for me in the Nether so I don't fall into lava, but as I kept taking surprise-damage from my inactive bow instead, after taking a while to ID the culprit, I ditched the sights for a stabilizer. I suggest applying the extra zoom only while _using_ the bow.
