### ISSUE TITLE
Question: is a NeoForge Port planned?

### ISSUE THREAD

**Issue by TheGrinchOnMath** [mickelus/tetra#851]
### Feature description
Neoforge support - port to 1.21

### How it improves the player experience

Porting Tetra to neoforge 1.21 allows modpack devs to include tetra in their modpacks.
I have no Idea what the state of developement is in, and do not have the funds to become a Patreon supporter

**Comment by mickelus** [comment]
It's already running on neoforge.

**Comment by TheGrinchOnMath** [comment]
Yup, saw that on the curseforge page. Is neoforge support for future versions (1.21 and future) planned?
By the way, amazing mod.

**Comment by Fundryi** [comment]
Any news on the 1.21 update :o ?

**Comment by TheGrinchOnMath** [comment]
I have not worked on this, no idea if anyone else has.
