### ISSUE TITLE
copies of the same enchantment with the same tier present on multiple tool parts sum up

### ISSUE THREAD

**Issue by kuba26038** [mickelus/tetra#857]
### Feature description

a feature that allows the player to have the same name and tier enchant on two or more tool heads, which would make the enchantment combine into a higher tier (a pickaxe with fortune 2 on both of it's heads would have the effect of fortune 3 for an instance)

### How it improves the player experience

it's currently impossible to apply an enchantment to a tool that already has the enchantment applied, even if one is trying to apply the enchantment to a tool part that doesn't have this enchantment. this is un-intuitive, since one would assume that only the tool part that has the enchant applied would benefit from it, but that's not how it works, instead if one has an enchant, all parts have it. but that isn't true, because it's still only that part that has the nbt, in most cases. this would be fixed by either scrapping the idea of having an enchantment be bound only to a specific part of the tool instead of the entire item, or by having the feature described above. of course if said feature were to be included, enchants such as fortune 4 or looting 4 would be possible, but as the mod quark with it's ancient tomes demonstrated, this isn't a cause for concern in about 95% of the cases.

### Tetra synergies

this would add another fun and engaging dimension to tool improvement, and would lightly but firmly improve the enchanting system already present in the mod.

**Comment by mickelus** [comment]
Enchantment stacking was removed in ~1.16 and there's no plan to re-add that behavior.
