### ISSUE TITLE
Datapack or config for adding innate crafting ability for certain mod tools

### ISSUE THREAD

**Issue by YuliaS11** [mickelus/tetra#858]
### Feature description

There are certain mods that add tools not limited to hammers and daggers, which should function as viable smithing tools. In particular, the hammer from Cataclysm dropped by the Netherite Monstrosity was a literally smithing hammer, yet there is no way to add it as a functional netherite tiered hammer for crafting's sake. The various knives from farmers' delight and aquaculture should be viable as carving tools yet cannot be configured as such.

### How it improves the player experience

There are a considerable number of mods that adds various tool considered less than favorable due to more limited combat utilities. They are perfectly functional on their own, but might be lackluster when considering swords or spears/tridents. This would give the player more incentive to keep one in their inventory for general usage.

### Tetra synergies

The goal of this request is to reward exploration from other mods, and provide alternatives to tetra's hammering progression which is currently limited to finding the ruins, which can be difficult to locate without other mods or commands.

**Comment by mickelus** [comment]
As long as an item can be converted into a tetra item it counts as a tool for crafting, which in part is already available for some of the listed examples. Closing!
