### ISSUE TITLE
Progress Blocked Without Ruins

### ISSUE THREAD

**Issue by ShamusYoung** [mickelus/tetra#88]
## Bug Report

**Observed Behaviour**

Ruins do not spawn. More importantly, it is impossible to acquire the needed upgrades without the ruins - not even obtainable with cheats or in creative mode! This blocks all progress in the mod. :(

**Expected Behaviour**

Obviously it would be ideal if the ruins spawned, but more importantly I'd suggest an alternate fallback system to acquire needed items, particularly the hammer. Perhaps add the items to loot tables in abandoned mineshafts. Or make it a drop in the Nether. Or add the hammer as an item that can be acquired through cheats. Or a recipe so the player can construct the hammer via other means. Or a console command workaround.  

**Minimal setup needed to reproduce**

- Forge version: 
1.14.4-forge-28.1.102

- Tetra version: 
tetra-1.14.4-1.0.7

- Tetra configuration: 
https://pastebin.com/6JifmAq2

- Other mods:
Many mods, but the two relevant ones are:
bunchofbiomes-1.14.2-1.0.3
BetterCaves-1.14.4-1.1.0

**Steps to reproduce**

Run 1.14 with the listed mods, go into spectator mode, and look around underground. You'll never see a single ruin.

**Comment by mickelus** [comment]
Those who want can config a fallback system on their own. Tetra for 1.14 is release as alpha for a reason,  and porting is done when it's done :).
