### ISSUE TITLE
[Suggestion] Advancements should be more specific

### ISSUE THREAD

**Issue by Dragnier** [mickelus/tetra#9]
For example:

Bench mk II - should probably mention right clicking with a mallet... 
Smashing - should probably mention you'll need a second mallet to work on the first...

**Comment by mickelus** [comment]
They could be more clear, do you have additional advancements in mind?

Advancement descriptions are not yet described in localization files and those two would be located here:
https://github.com/mickelus/tetra/blob/master/src/main/resources/assets/tetra/advancements/upgrades/hammer_2.json
https://github.com/mickelus/tetra/blob/master/src/main/resources/assets/tetra/advancements/upgrades/workbench.json
Feel free to create a PR for new descriptions.

**Comment by mickelus** [comment]
The benchmark advancement description has been changed. Closing this issue is as it's too generic and it's unclear how it is to be resolved. Feel free to provide specific suggestions and re-open the issue.
