### ISSUE TITLE
Feature Request: Keep enchants after modification

### ISSUE THREAD

**Issue by Saellys** [mickelus/tetra#90]
This is all of a complaint, a request, and possibly a bug report (if what happened to me was not intentional):
Forge server on Version 1.12.2. Having an enchanted wooden sword (Living enchant, it was level 24 crycry), I wanted the sword to last longer so I tried upgrading the blade to iron, but once I had the wood-handle-iron-blade sword (now Iron Sword) the enchantment got removed from it. That's pretty much a tragedy, ngl, but anyway I'd like to request that enchantments stay on a weapon after modification, or at least, enchantments stay on a weapon if only certain parts are modified. (I think I remember reading somewhere that the hilt/handle is where the "magic" is stored and, thus, enchantments) In that case, there's still some "balancing" in the way weapons can be reforged with enchants, but they're at least somewhat modifiable.

Also, if this is actually an issue on Living Enchantment's side, let me know and I'll post a report about it to them, but I also tried upgrading a vanilla wooden sword with vanilla Sharpness enchant to iron blade and that also nuked its enchantment, so I'm sure that's not just a mod compatibility issue.

**Comment by Saellys** [comment]
Also sorry but I don't know how to add the different tags to the post. :T

**Comment by mickelus** [comment]
I'm sorry, tetra does not support the living enchant mod. Please see these issues: https://github.com/mickelus/tetra/issues/48
https://github.com/Clownvin/Living-Enchantment/issues/4

Tetra items do not accept enchantments in an enchantment table, but enchantments from a book can be applied to specific slots in a tetra workbench. Those enchantments are persisted.
