### ISSUE TITLE
Bootstrap Problem with Hammer Upgrades

### ISSUE THREAD

**Issue by zauberparacelsus** [mickelus/tetra#91]
## Bug Report

**Observed Behaviour**
When upgrading the hammers, or at least when upgrading a stone hammer to an iron hammer, it requires a tier-2 hammer to be in my inventory... but it acts like I have no tier-2 hammers because its in the modification interface, with it saying that I only have tier-0 hammer.  And yet, upgrading the handle works just fine.

**Expected Behaviour**
Should be able to upgrade the stone hammer to an iron hammer without issue.

**Minimal setup needed to reproduce**
- Forge version: 1.12.2 14.23.5.2847
- Tetra version: 0.39.1

**Steps to reproduce**
1. Put a stone hammer into the modification interface
2. Attempt to upgrade the left or right head to iron

**Comment by mickelus** [comment]
This is intended behaviour, wouldn't it be rather strange if you craft a tool using the tool itself?
You'll need two hammers :)

**Comment by zauberparacelsus** [comment]
Okay then, I assumed otherwise because I was able to upgrade the log hammer to a stone hammer without having a second hammer.
