### ISSUE TITLE
Support for Metallurgy 4 Reforged

### ISSUE THREAD

**Issue by zauberparacelsus** [mickelus/tetra#92]
## Feature Request

**Feature description**
Add support for the additional metals which are added by Metallurgy 4 Reforged.  At present, it only implicitly supports some of the generic ones like bronze.

**How it improves the player experience**
Greater variety of materials to construct equipment from.

**Comment by mickelus** [comment]
Detailing what this support would entail will greatly increase the likelyhood for it to be implemented.

**Comment by mickelus** [comment]
Closing this as it has been marked with "needs refinement" for over 6 months.
