### ISSUE TITLE
Seem to be missing crafting material options

### ISSUE THREAD

**Issue by oChitWalltap** [mickelus/tetra#93]
In [this video](https://youtu.be/QRwvwrXZv2I?t=100), using the hammer option for example, I can clearly see that there are about 15 different material options available. In my game, however, there are only four (wood, stone, iron, and obsidian). This also prevents me from crafting a Tier 4 hammer, among other things. I thought this might've been a problem with the 1.12.2 version, but it's the same thing in the 1.14.4 version. 

I'm gonna guess that I may have overlooked something in installation like the numpty I am, but I figured I'd ask for help here anyway.

**Comment by mickelus** [comment]
Tetra only adds a few materials on its own, so if you only have tetra installed you'd only be able to use materials from vanilla minecraft for crafting items. If you want to use additional materials like steel, copper or ironwood you should install mods that add those materials, there are some mods that only add ores if you're not interested in tetra.

This is not what prevents you from crafting a tier 4 hammer, or other things. Check the advancements window for hints on how to progress.
