### ISSUE TITLE
won't work with modded enchants

### ISSUE THREAD

**Issue by wandomfwend** [mickelus/tetra#95]
mods like randomenchant's won't work with tetra. If i have a enchant from randomenchant's mod the enchant will disappear

**Comment by mickelus** [comment]
Support for modded enchantments has to be configured. I'll look into it if you rewrite your issue using the feature request template and detail what the support would entail, i.e the following for each enchantment:
- enchantment id
- allowed items
- enchantability function (e.g. 5 + 3 * level)
- name
- description

**Comment by phyne** [comment]
For the record, Ma Enchants, FlashFyre's Enchantments, and Ensorcellation are the 3 enchantment mods I'm using that I'm slowly configuring for tetra. I'll share those once I'm done.

**Comment by mickelus** [comment]
I've added support for the larger enchantment mods, closing this.
