### ISSUE TITLE
[SUGGESTION] Support for my mod, Bewitchment

### ISSUE THREAD

**Issue by Sunconure11** [mickelus/tetra#97]
## Feature Request

**Feature description**
My mod has a few tools, and at least one unique material, cold iron.

Materials
- [ ] Cold Steel
    - modules: blades, pommels, guards, tool heads
    - iron mining tier
    - 850 durability for all tools (divided between heads & handle)
    - ? efficiency
    - ? damage
    - ? enchantability / magic capacity
- [ ] Wool of bat (wrappings, bindings)
    - modules: bindings & handle wrappings
    - stats: slightly better than string?
- [ ] Amethyst
    - modules: sockets
    - Currently sockets in tetra provide some unique effect, we should come up with something fun!
- [ ] Garnet
    - modules: sockets
    - Currently sockets in tetra provide some unique effect, we should come up with something fun!
- [ ] Opal
    - modules: sockets
    - Currently sockets in tetra provide some unique effect, we should come up with something fun!

Replacements (converts tools/weapons from other mods into their tetra counterpart)
- [ ] cold iron tools (pickaxe, axe, hoe)
- [ ] silver tools (pickaxe, axe, hoe)

**How it improves the player experience**
Allowing these to be supported by this mod would allow greater customization of these tools, and in general expand my own goals of making it compatible with more content.

**Tetra synergies**
So far, this mod is not supported, but it would be a good idea to add support IMO.

**Comment by mickelus** [comment]
Oh, I'd love to. Witchery was amzing and I'm excited for bewitchment. How far away are you guys from a 1.14 release?

I'll edit your post with a checklist so that we can expand on it together.

**Comment by Sunconure11** [comment]
I'd say most of the compat you just wrote down is mostly applicable to 1.12.2. Gems are gone on 1.14+, and cold iron is being moved to an addon since we will go a somewhat modular route.

**Comment by Sunconure11** [comment]
Wool of bat also hasn't been in for a while, it got pulled.

**Comment by Sunconure11** [comment]
Cold iron should be less enchantable than iron, but it takes advantage of BW's API for usage in targeting specific mobs.

Gemstones should apply a slight enchantment bonus and durability bonus.

**Comment by Sunconure11** [comment]
Allow the athame and boline to be customizable, too, if possible.

**Comment by Sunconure11** [comment]
There's also several fiber-type materials you could use for wrappings and bindings.

Yeah I should've done this in an edit.

**Comment by mickelus** [comment]
>  it takes advantage of BW's API for usage in targeting specific mobs
What does that mean?

Can the athame and boline be used for something? Or are they just weapons?

**Comment by Sunconure11** [comment]
Athame and Boline are both used in rituals.

The boline can be used to scrape resin from dragon's blood trees

The athame can be used to get special drops from mobs

Cold iron targets mobs tagged under some new creature attributes added + a few mobs given this weakness through said mod

**Comment by mickelus** [comment]
Closing this as you seem to have moved over to fabric. Feel free to reopen if you return :)
