### ISSUE TITLE
Allow waterlogging of blocks

### ISSUE THREAD

**Issue by WenXin20** [mickelus/tetra#98]
## Feature Request

**Feature description**

 - Allow blocks to be waterloggable if placed underwater.
- (The workbench also renders incorrectly underwater, with water flowing down it's sides.)

**How it improves the player experience**

- If they are used underwater, they won't look odd. Also could be good for decorations.

**Tetra synergies**

- It will allow better immersion for the game.

**Comment by WenXin20** [comment]
The hammer head can be waterlogged, but the hammer base was missed.

**Comment by mickelus** [comment]
The hammer base is a full block and those typically don't waterlog, water flows down the side because of how minecraft handles transparent textures :/. But I can look into it :p
