### ISSUE TITLE
Feature request: Make the toolbelt place tools in the hand slot when using the quick swaps.

### ISSUE THREAD

**Issue by Edulml** [mickelus/tetra#99]
## Feature Request

**Feature description**
Currently as of version 1.4.0, when using the quick swap the toolbelt it places everything in the offhand slot, making swaps between tools quite cumbersome when tools only work when on the main hand slot.

**How it improves the player experience**
It makes the toolbelt much more quick and fluid to use.

**Comment by mickelus** [comment]
Something similar to what you describe is intended to be an upgrade that the player can apply to toolbelt straps, which would allow the player to choose which hand the tool goes into depending on which side of the UI box they drop the key.

The quick latch upgrade (which is implemented) for straps also puts the item into the players mainhand, have you had the chance to try that out?

**Comment by Edulml** [comment]
I didn't have the chance of trying it, so after using it in a creative world the quick latch does work as intended, however it requires a better explanation. 

When seeing it in JEI it seemed like it was an item required to see more upgrades for all tools, not an upgrade specific for the tool belt. Also, when trying to use it I was confused thinking it didn't work properly, but the case was simply that the timing to use it's quick equip function is way too short.

**Comment by Edulml** [comment]
> Something similar to what you describe is intended to be an upgrade that the player can apply to toolbelt straps, which would allow the player to choose which hand the tool goes into depending on which side of the UI box they drop the key.

Another good upgrade could be done to the quiver too, allowing players to select whether the arrows are placed in the off-hand or the inventory, if using arrows directly from the quiver isn't already a planned feature.

**Comment by mickelus** [comment]
There's already an upgrade available that lets the player nock an arrow directly from the quiver.
